/**
 * The full requirement catalogue: every ISO/IEC 27001:2022 Annex A control and
 * every auditable ISO 9001:2015 clause.
 *
 * Only the reference and its short title are held here — the standards' own
 * text is copyrighted and is not reproduced. A row from this catalogue is a
 * placeholder for a requirement that exists whether or not this organisation
 * has started on it; the ones the ISMS actually tracks come from the mockup
 * dataset and carry a criticality weight. See ADR-0011.
 */
export type CatalogEntry = { id: string; title: string; standard: '27001' | '9001' }

const A5: [string, string][] = [
  ['A.5.1', 'Policies for information security'],
  ['A.5.2', 'Information security roles and responsibilities'],
  ['A.5.3', 'Segregation of duties'],
  ['A.5.4', 'Management responsibilities'],
  ['A.5.5', 'Contact with authorities'],
  ['A.5.6', 'Contact with special interest groups'],
  ['A.5.7', 'Threat intelligence'],
  ['A.5.8', 'Information security in project management'],
  ['A.5.9', 'Inventory of information and other associated assets'],
  ['A.5.10', 'Acceptable use of information and other associated assets'],
  ['A.5.11', 'Return of assets'],
  ['A.5.12', 'Classification of information'],
  ['A.5.13', 'Labelling of information'],
  ['A.5.14', 'Information transfer'],
  ['A.5.15', 'Access control'],
  ['A.5.16', 'Identity management'],
  ['A.5.17', 'Authentication information'],
  ['A.5.18', 'Access rights'],
  ['A.5.19', 'Information security in supplier relationships'],
  ['A.5.20', 'Addressing information security within supplier agreements'],
  ['A.5.21', 'Managing information security in the ICT supply chain'],
  ['A.5.22', 'Monitoring, review and change management of supplier services'],
  ['A.5.23', 'Information security for use of cloud services'],
  ['A.5.24', 'Information security incident management planning and preparation'],
  ['A.5.25', 'Assessment and decision on information security events'],
  ['A.5.26', 'Response to information security incidents'],
  ['A.5.27', 'Learning from information security incidents'],
  ['A.5.28', 'Collection of evidence'],
  ['A.5.29', 'Information security during disruption'],
  ['A.5.30', 'ICT readiness for business continuity'],
  ['A.5.31', 'Legal, statutory, regulatory and contractual requirements'],
  ['A.5.32', 'Intellectual property rights'],
  ['A.5.33', 'Protection of records'],
  ['A.5.34', 'Privacy and protection of PII'],
  ['A.5.35', 'Independent review of information security'],
  ['A.5.36', 'Compliance with policies, rules and standards for information security'],
  ['A.5.37', 'Documented operating procedures'],
]

const A6: [string, string][] = [
  ['A.6.1', 'Screening'],
  ['A.6.2', 'Terms and conditions of employment'],
  ['A.6.3', 'Information security awareness, education and training'],
  ['A.6.4', 'Disciplinary process'],
  ['A.6.5', 'Responsibilities after termination or change of employment'],
  ['A.6.6', 'Confidentiality or non-disclosure agreements'],
  ['A.6.7', 'Remote working'],
  ['A.6.8', 'Information security event reporting'],
]

const A7: [string, string][] = [
  ['A.7.1', 'Physical security perimeters'],
  ['A.7.2', 'Physical entry'],
  ['A.7.3', 'Securing offices, rooms and facilities'],
  ['A.7.4', 'Physical security monitoring'],
  ['A.7.5', 'Protecting against physical and environmental threats'],
  ['A.7.6', 'Working in secure areas'],
  ['A.7.7', 'Clear desk and clear screen'],
  ['A.7.8', 'Equipment siting and protection'],
  ['A.7.9', 'Security of assets off-premises'],
  ['A.7.10', 'Storage media'],
  ['A.7.11', 'Supporting utilities'],
  ['A.7.12', 'Cabling security'],
  ['A.7.13', 'Equipment maintenance'],
  ['A.7.14', 'Secure disposal or re-use of equipment'],
]

const A8: [string, string][] = [
  ['A.8.1', 'User end point devices'],
  ['A.8.2', 'Privileged access rights'],
  ['A.8.3', 'Information access restriction'],
  ['A.8.4', 'Access to source code'],
  ['A.8.5', 'Secure authentication'],
  ['A.8.6', 'Capacity management'],
  ['A.8.7', 'Protection against malware'],
  ['A.8.8', 'Management of technical vulnerabilities'],
  ['A.8.9', 'Configuration management'],
  ['A.8.10', 'Information deletion'],
  ['A.8.11', 'Data masking'],
  ['A.8.12', 'Data leakage prevention'],
  ['A.8.13', 'Information backup'],
  ['A.8.14', 'Redundancy of information processing facilities'],
  ['A.8.15', 'Logging'],
  ['A.8.16', 'Monitoring activities'],
  ['A.8.17', 'Clock synchronization'],
  ['A.8.18', 'Use of privileged utility programs'],
  ['A.8.19', 'Installation of software on operational systems'],
  ['A.8.20', 'Networks security'],
  ['A.8.21', 'Security of network services'],
  ['A.8.22', 'Segregation of networks'],
  ['A.8.23', 'Web filtering'],
  ['A.8.24', 'Use of cryptography'],
  ['A.8.25', 'Secure development life cycle'],
  ['A.8.26', 'Application security requirements'],
  ['A.8.27', 'Secure system architecture and engineering principles'],
  ['A.8.28', 'Secure coding'],
  ['A.8.29', 'Security testing in development and acceptance'],
  ['A.8.30', 'Outsourced development'],
  ['A.8.31', 'Separation of development, test and production environments'],
  ['A.8.32', 'Change management'],
  ['A.8.33', 'Test information'],
  ['A.8.34', 'Protection of information systems during audit testing'],
]

/** ISO 9001:2015 clauses 4 to 10 — the auditable ones; 1 to 3 are scope, refs and terms. */
const Q: [string, string][] = [
  ['4.1', 'Understanding the organization and its context'],
  ['4.2', 'Understanding the needs and expectations of interested parties'],
  ['4.3', 'Determining the scope of the quality management system'],
  ['4.4', 'Quality management system and its processes'],
  ['5.1', 'Leadership and commitment'],
  ['5.2', 'Policy'],
  ['5.3', 'Organizational roles, responsibilities and authorities'],
  ['6.1', 'Actions to address risks and opportunities'],
  ['6.2', 'Quality objectives and planning to achieve them'],
  ['6.3', 'Planning of changes'],
  ['7.1', 'Resources'],
  ['7.1.5', 'Monitoring and measuring resources'],
  ['7.1.6', 'Organizational knowledge'],
  ['7.2', 'Competence'],
  ['7.3', 'Awareness'],
  ['7.4', 'Communication'],
  ['7.5', 'Documented information'],
  ['7.5.1', 'Documented information — general'],
  ['7.5.2', 'Creating and updating documented information'],
  ['7.5.3', 'Control of documented information'],
  ['8.1', 'Operational planning and control'],
  ['8.2', 'Requirements for products and services'],
  ['8.3', 'Design and development of products and services'],
  ['8.4', 'Control of externally provided processes, products and services'],
  ['8.4.1', 'External providers — general'],
  ['8.4.2', 'Type and extent of control of external provision'],
  ['8.4.3', 'Information for external providers'],
  ['8.5', 'Production and service provision'],
  ['8.5.1', 'Control of production and service provision'],
  ['8.5.2', 'Identification and traceability'],
  ['8.5.3', 'Property belonging to customers or external providers'],
  ['8.5.4', 'Preservation'],
  ['8.5.5', 'Post-delivery activities'],
  ['8.5.6', 'Control of changes'],
  ['8.6', 'Release of products and services'],
  ['8.7', 'Control of nonconforming outputs'],
  ['9.1', 'Monitoring, measurement, analysis and evaluation'],
  ['9.1.1', 'Monitoring and measurement — general'],
  ['9.1.2', 'Customer satisfaction'],
  ['9.1.3', 'Analysis and evaluation'],
  ['9.2', 'Internal audit'],
  ['9.2.1', 'Internal audit — requirements'],
  ['9.2.2', 'Internal audit programme'],
  ['9.3', 'Management review'],
  ['9.3.1', 'Management review — general'],
  ['9.3.2', 'Management review inputs'],
  ['9.3.3', 'Management review outputs'],
  ['10.1', 'Improvement — general'],
  ['10.2', 'Nonconformity and corrective action'],
  ['10.3', 'Continual improvement'],
]

export const CATALOG: CatalogEntry[] = [
  ...[...A5, ...A6, ...A7, ...A8].map(([id, title]) => ({
    id,
    title,
    standard: '27001' as const,
  })),
  ...Q.map(([id, title]) => ({ id, title, standard: '9001' as const })),
]
