import type { SeedDocument } from './types'

/** Annex A.7 physical controls, part 2: equipment and media (A.7.8–A.7.14). */
export const ANNEX_A7_PHYSICAL_2: SeedDocument[] = [
  {
    code: 'ISMS-POL-A-7-8',
    title: 'Equipment Siting and Protection',
    clause: 'A.7.8',
    crossRefs: ['A.7.5', 'A.7.12', 'A.5.9'],
    version: 'v1.3',
    owner: 'Agil',
    form: { code: 'FRM-A-7-8-01', name: 'Sited equipment register' },
    revisions: [
      {
        version: 'v1.2',
        date: '2024-10-02',
        author: 'Agil',
        approval: 'Reviewed by Andreas',
        status: 'Superseded',
        note: 'Covered HQ equipment only; branch kit was tracked in a spreadsheet outside the ISMS.',
      },
      {
        version: 'v1.3',
        date: '2026-03-10',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Branch comms cabinets folded into the register, and the ceiling-mount rule added after the Bandung cabinet was found on the floor of a wet corridor.',
      },
    ],
    evidence: [
      {
        name: 'sited-equipment-register-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-03-10',
        expiryDate: '2027-03-10',
        uploader: 'Agil',
        note: 'All fixed equipment by site, with mounting, protection and the next maintenance date.',
        body: [
          'Site | Equipment | Mounting | Environmental protection | Owner | Next maintenance',
          'Jakarta HQ | Core switch, 24-port | Wall cabinet, 4th floor | UPS 1500VA, split AC | Agil | 2026-09-14',
          'Jakarta HQ | NAS (build artefacts only) | Same cabinet | UPS, no patient data held | Randy | 2026-09-14',
          'Kemang | Branch switch + router | Wall cabinet, 1.8m | UPS 650VA | Agil | 2026-08-20',
          'PIK | Branch switch + router | Wall cabinet, 1.8m | UPS 650VA | Agil | 2026-08-21',
          'Bandung Dago | Branch switch + router | Wall cabinet, relocated Mar 2026 | UPS 650VA, new | Agil | 2026-09-02',
          'Cakung | Label printer, stock terminal | Bench, raised 30cm | Surge strip only | Pak Chen | 2026-10-06',
          '',
          'The Cakung terminal is the only device without UPS cover; its loss stops label printing but',
          'no data is held locally, so the gap is accepted and reviewed with the 2027 racking budget.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-A-7-8 · Equipment Siting and Protection',
      '',
      '**Owner** Agil · **Approver** Aris Ihwan · **Version** v1.3 · **Review** annually, each March',
      '**Requirement** A.7.8 · **Also satisfies** A.7.5, A.7.12, A.5.9',
      '',
      '## Purpose',
      '',
      'Since the platform moved to AWS ap-southeast-1, the equipment left on our own floors is',
      'modest — switches, routers, a build NAS, reception workstations and label printers. That',
      'makes it easy to site badly. This policy sets where such equipment may be installed and what',
      'must protect it once it is there.',
      '',
      '## Scope',
      '',
      'Fixed and semi-fixed equipment owned or leased by the group at any site: network equipment,',
      'the HQ NAS, workstations, printers, UPS units and stock terminals. Laptops and phones are',
      'covered by the end-point control; equipment taken off site is covered by ISMS-SOP-A-7-9.',
      '',
      '## Roles and responsibilities',
      '',
      'Agil maintains the sited equipment register and approves every installation. Pak Andre must',
      'be consulted before any equipment is fixed in a clinical space, because a cabinet on a',
      'treatment corridor is a clinical problem before it is a security one. Randy owns the HQ NAS.',
      '',
      '## Policy',
      '',
      '1. **Every fixed device is on the register** before it is powered on, with its site, mounting,',
      '   protection and owner. A device not on the register is removed or registered within 5',
      '   working days of discovery.',
      '2. **Network equipment is wall- or rack-mounted at 1.5 m or higher**, inside a lockable',
      '   cabinet. Equipment on the floor, on a shelf in an open corridor or on top of a cabinet is',
      '   not acceptable, whatever the temporary reason.',
      '3. **Away from water and heat.** No device is installed beneath a pipe, an AC unit or a',
      '   sprinkler head, or within a metre of a sterilising or heating appliance.',
      '4. **Power protection.** Every switch, router and the HQ NAS is on a UPS sized for at least 15',
      '   minutes, enough for a clean shutdown and for a short mall outage. Printers and stock',
      '   terminals need surge protection only.',
      '5. **Nothing patient-identifying is stored on site equipment.** The HQ NAS holds build',
      '   artefacts and installers. Reception workstations hold nothing locally; they are clients of',
      '   the platform. This is the reason the branch protection standard can be as light as it is.',
      '6. **Eating, drinking and cleaning.** No liquids on or above a cabinet; cleaning of a cabinet',
      '   interior is done by Agil, not by the cleaning contractor.',
      '7. **Relocation is a change.** Moving a device between rooms requires the register to be',
      '   updated and, where the new room is a different zone, the site custodian’s agreement.',
      '',
      '## Records',
      '',
      'The sited equipment register (FRM-A-7-8-01) is filed against A.7.8 and kept current rather',
      'than versioned; the annual snapshot is retained for three years as evidence of the review.',
      '',
      '## Review',
      '',
      'Annually each March by Agil, and at every branch opening, relocation or refit.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-7-9',
    title: 'Security of Assets Off-Premises',
    clause: 'A.7.9',
    crossRefs: ['A.6.7', 'A.8.1', 'A.5.11'],
    version: 'v2.0',
    owner: 'Agil',
    form: { code: 'FRM-A-7-9-01', name: 'Off-premises asset movement log' },
    revisions: [
      {
        version: 'v1.4',
        date: '2025-01-29',
        author: 'Randy',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Assumed laptops normally live in the office and leave by exception — the opposite of how engineering actually works.',
      },
      {
        version: 'v2.0',
        date: '2026-05-05',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Rewritten for a laptop-first engineering group; disk encryption and remote wipe made the primary controls, and the loss-reporting clock set at 4 hours.',
      },
    ],
    evidence: [
      {
        name: 'off-premises-asset-log-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-07-01',
        expiryDate: '2027-07-01',
        uploader: 'Agil',
        note: 'Movements of equipment other than routinely mobile laptops, plus the one loss event of the year.',
        body: [
          'Ref | Date out | Asset | Taken by | Destination | Encrypted | Returned | Note',
          'OFF-2026-04 | 2026-02-03 | Demo laptop DL-07 | Wiwin | Surabaya trade show | Yes | 2026-02-06 | Clean',
          'OFF-2026-07 | 2026-03-18 | Spare branch switch | Agil | Bandung Dago | n/a | 2026-03-18 | Installed, register updated',
          'OFF-2026-11 | 2026-04-27 | Laptop DL-14 | Randy | Home, on-call rotation | Yes | standing | Standing assignment',
          'OFF-2026-15 | 2026-06-09 | Laptop DL-09 | Tika | Airport, Jakarta–Denpasar | Yes | lost | See incident INC-2026-031',
          '',
          'DL-09 was reported 90 minutes after loss, wiped remotely the same evening and confirmed',
          'encrypted at rest. No data exposure was identified; the device was not recovered.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-7-9 · Security of Assets Off-Premises',
      '',
      '**Owner** Agil · **Approver** Aris Ihwan · **Version** v2.0 · **Review** annually, each May',
      '**Requirement** A.7.9 · **Also satisfies** A.6.7, A.8.1, A.5.11',
      '',
      '## Purpose',
      '',
      'Engineering here is laptop-first and partly remote, and commercial staff carry demo machines',
      'to trade shows and clinic openings. Pretending that equipment normally sits in an office would',
      'produce a procedure nobody follows. This one starts from the fact that the asset is usually',
      'out, and protects it accordingly.',
      '',
      '## Scope',
      '',
      'Company laptops, phones, demo devices, spare network equipment and any paper record taken off',
      'a site. Personal devices are not in scope and are not permitted to hold company data.',
      'Patient records leaving a clinic in paper form are prohibited outright by step 6.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Agil** issues equipment, holds the asset register and performs remote wipes.',
      '- **Dhiaz Fathra** decides whether a loss is a reportable personal data incident, with **Rica**.',
      '- The **holder** of the asset is responsible for it while it is out, including in a car, a hotel',
      '  and an airport.',
      '',
      '## Procedure',
      '',
      '1. **Issue.** Every laptop and phone is issued against the asset register, encrypted at rest',
      '   before handover, enrolled for remote wipe, and acknowledged in writing by the holder.',
      '2. **Standing assignment, not a permit per trip.** A laptop assigned to a person may leave any',
      '   site at any time. Only non-standard movements — demo kit, spare hardware, a device issued to',
      '   a contractor — are logged in FRM-A-7-9-01.',
      '3. **In transit.** Equipment is carried, not checked into hold luggage, and is never left',
      '   visible in a parked vehicle. In a public space the device stays within reach or is locked.',
      '4. **On a network you do not control.** Use the company VPN for anything beyond public web',
      '   browsing. Do not connect to an unencrypted hotspot to reach the admin console.',
      '5. **Screen exposure.** Do not open patient, financial or credential material on a screen',
      '   visible to strangers — an aircraft seat and a café bench both count.',
      '6. **Paper stays on site.** Original patient records, personnel files and signed contracts do',
      '   not leave the site that holds them. A copy needed elsewhere is produced digitally from the',
      '   platform, never carried as paper.',
      '7. **Loss or theft.** Tell Agil and the on-call engineer within 4 hours of noticing, by phone,',
      '   not email. Agil wipes remotely and revokes the device’s sessions in Zitadel. The event is',
      '   raised as a security incident the same day, and Rica assesses the personal data position.',
      '8. **Return.** Equipment comes back to Agil on the last working day of an assignment or of',
      '   employment, is wiped, and the register updated within 2 working days.',
      '',
      '## Records',
      '',
      'The movement log (FRM-A-7-9-01) and the signed issue acknowledgements are filed against A.7.9',
      'and retained for three years after the asset is retired. Loss incidents are cross-filed with',
      'the incident record.',
      '',
      '## Review',
      '',
      'Annually each May by Agil, and after every loss or theft of a company device.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-7-10',
    title: 'Storage Media Handling',
    clause: 'A.7.10',
    crossRefs: ['A.7.14', 'A.8.10', 'A.5.33'],
    version: 'v1.5',
    owner: 'Agil',
    form: { code: 'FRM-A-7-10-01', name: 'Removable media register' },
    revisions: [
      {
        version: 'v1.4',
        date: '2025-06-24',
        author: 'Agil',
        approval: 'Reviewed by Rica',
        status: 'Superseded',
        note: 'Allowed encrypted USB drives for clinic photo transfer, which is how three unregistered drives entered circulation.',
      },
      {
        version: 'v1.5',
        date: '2026-04-14',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Removable media prohibited by default; clinical photography routed through the platform upload path instead.',
      },
    ],
    evidence: [
      {
        name: 'removable-media-register-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-04-14',
        expiryDate: '2027-04-14',
        uploader: 'Agil',
        note: 'The complete set of permitted media, each with its exception approval and expiry.',
        body: [
          'Media ID | Type | Encrypted | Holder | Permitted use | Exception expires | Status',
          'MED-01 | 64GB USB | Yes, hardware | Agil | Switch firmware at branches | 2027-04-14 | In use',
          'MED-02 | 64GB USB | Yes, hardware | Randy | Bare-metal recovery, HQ NAS | 2027-04-14 | In use',
          'MED-03 | 1TB external SSD | Yes | Tika | Measurement ETL cold extract | 2026-12-31 | In use',
          'MED-04 | 32GB USB | Yes | — | Withdrawn from clinic photo transfer | — | Destroyed 2026-04-30',
          'MED-05 | 32GB USB | Yes | — | Withdrawn from clinic photo transfer | — | Destroyed 2026-04-30',
          '',
          'Two further drives found at Kemang and PIK during the April sweep were unregistered, were',
          'not encrypted, and were destroyed on 30 April 2026 with the two withdrawn ones.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-7-10 · Storage Media Handling',
      '',
      '**Owner** Agil · **Approver** Aris Ihwan · **Version** v1.5 · **Review** annually, each April',
      '**Requirement** A.7.10 · **Also satisfies** A.7.14, A.8.10, A.5.33',
      '',
      '## Purpose',
      '',
      'Removable media used to be how a treatment photograph got from a clinic camera to a patient',
      'file. That path produced unregistered drives in reception drawers with clinical images on',
      'them. This procedure closes it and defines the narrow set of cases where media is still used.',
      '',
      '## Scope',
      '',
      'USB drives, external disks, SD cards, optical media and backup tapes, in any hand at any site.',
      'Paper records are media in the broad sense but are governed by the records protection control.',
      'Cloud object storage is not media and is covered by the cloud services control.',
      '',
      '## Roles and responsibilities',
      '',
      'Agil holds the register and is the only person who may approve a new item onto it. Rica must',
      'agree any use involving personal data. Pak Andre sweeps branch drawers during his site visits',
      'and hands anything he finds to Agil rather than reusing it.',
      '',
      '## Procedure',
      '',
      '1. **Default is no.** Removable media is not used to move company information. Files move',
      '   through the platform, the object store or the approved file transfer path.',
      '2. **Exceptions are registered and dated.** Each permitted item has an ID, a named holder, a',
      '   stated purpose and an expiry no more than 12 months out. Renewal is a fresh approval.',
      '3. **Hardware encryption for anything leaving a site.** Software encryption is acceptable only',
      '   for media that never crosses a site boundary.',
      '4. **Never personal data on removable media.** Clinical photography goes from the clinic camera',
      '   to the patient record through the platform upload, over the branch network. If that path is',
      '   down, the photograph waits.',
      '5. **Marking.** Registered media carries its MED-nn label physically. Unlabelled media found on',
      '   any site is treated as untrusted, is not plugged into a company machine, and goes to Agil.',
      '6. **In transit** registered media is carried by its holder under the off-premises procedure and',
      '   is never posted or couriered.',
      '7. **End of life.** Media is wiped and then physically destroyed under the disposal procedure',
      '   ISMS-SOP-A-7-14; it is not reused between purposes or handed to another holder.',
      '8. **Quarterly sweep.** Agil reconciles the register against holders once a quarter and asks',
      '   each branch to confirm no unregistered media is on site.',
      '',
      '## Records',
      '',
      'The media register (FRM-A-7-10-01), exception approvals and destruction certificates are filed',
      'against A.7.10 and retained for three years after the item is destroyed.',
      '',
      '## Review',
      '',
      'Annually each April by Agil with Rica, and whenever a new exception is requested.',
    ].join('\n'),
  },
  {
    code: 'ISMS-POL-A-7-11',
    title: 'Supporting Utilities',
    clause: 'A.7.11',
    crossRefs: ['A.7.5', 'A.8.14', 'A.5.30'],
    version: 'v1.2',
    owner: 'Agil',
    form: { code: 'FRM-A-7-11-01', name: 'UPS and utility test record' },
    revisions: [
      {
        version: 'v1.1',
        date: '2024-08-13',
        author: 'Agil',
        approval: 'Reviewed by Randy',
        status: 'Superseded',
        note: 'Written when HQ still held production servers and generator cover was in scope.',
      },
      {
        version: 'v1.2',
        date: '2026-01-27',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Generator requirement dropped as disproportionate post-migration; UPS runtime target set at 15 minutes and battery replacement put on a three-year cycle.',
      },
    ],
    evidence: [
      {
        name: 'ups-test-record-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-25',
        expiryDate: '2027-06-25',
        uploader: 'Agil',
        note: 'Half-yearly load tests with measured runtime against the 15-minute target.',
        body: [
          'Date | Site | UPS | Battery age | Measured runtime | Target met | Action',
          '2026-01-14 | HQ | 1500VA | 2y 3m | 24 min | Yes | None',
          '2026-01-15 | Kemang | 650VA | 3y 1m | 9 min | No | Battery replaced 2026-01-28',
          '2026-01-16 | PIK | 650VA | 1y 7m | 19 min | Yes | None',
          '2026-06-22 | HQ | 1500VA | 2y 8m | 22 min | Yes | None',
          '2026-06-23 | Kemang | 650VA | 0y 5m | 21 min | Yes | None',
          '2026-06-24 | Bandung | 650VA | 0y 3m | 20 min | Yes | None',
          '',
          'Kemang failing in January is what set the three-year battery cycle; every unit older than',
          'three years at the January test is now replaced whether or not it passes.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-A-7-11 · Supporting Utilities',
      '',
      '**Owner** Agil · **Approver** Aris Ihwan · **Version** v1.2 · **Review** annually, each January',
      '**Requirement** A.7.11 · **Also satisfies** A.7.5, A.8.14, A.5.30',
      '',
      '## Purpose',
      '',
      'A branch loses power when the mall does. What matters is not keeping the clinic running — the',
      'clinical team can handle a dark hour — but that network equipment shuts down cleanly, that the',
      'booking terminal comes back without corruption, and that nobody is left unable to reach the',
      'platform for the whole afternoon. This policy states the utility protection each site needs.',
      '',
      '## Scope',
      '',
      'Electrical supply, internet connectivity, air conditioning serving equipment, and water where',
      'its failure would affect a Zone 2 or Zone 3 space. Clinical gas and medical device power are',
      'governed by clinical engineering, not by this document. Utility resilience for the production',
      'platform is AWS’s responsibility in ap-southeast-1.',
      '',
      '## Roles and responsibilities',
      '',
      'Agil specifies, tests and replaces UPS units and manages the connectivity contracts. Pak Andre',
      'reports branch outages and holds the landlord contact. Pak Rila approves the replacement',
      'budget on the three-year battery cycle so it does not have to be argued each time.',
      '',
      '## Policy',
      '',
      '1. **UPS on all network equipment,** sized for a minimum of 15 minutes at measured load. The',
      '   target is a clean shutdown and a short outage ride-through, not continuity of service.',
      '2. **No generator, deliberately.** With production in AWS and no site holding primary data, the',
      '   cost of generator cover buys nothing the mall supply does not already provide. This is a',
      '   stated acceptance, revisited if any site takes back a production role.',
      '3. **Batteries are replaced on age, not on failure** — every three years, or immediately when a',
      '   half-yearly test measures under 15 minutes.',
      '4. **Test twice a year.** Agil runs a load test at each site in January and June, records the',
      '   measured runtime and acts on any shortfall within 15 working days.',
      '5. **Two internet paths at HQ** — Telkom fibre as primary with a 4G failover router. Branches',
      '   run a single fibre path with a 4G dongle held by the branch as a manual fallback, because a',
      '   branch offline for two hours is an operational nuisance, not a security failure.',
      '6. **AC serving the HQ cabinet** is on the landlord’s maintenance schedule; Agil confirms the',
      '   service has happened rather than assuming it.',
      '7. **Outage reporting.** Any power or connectivity loss over 30 minutes is reported by the',
      '   branch to Agil the same day and recorded, so repeated failures at one site become visible.',
      '',
      '## Records',
      '',
      'The UPS and utility test record (FRM-A-7-11-01), battery replacement invoices and outage',
      'reports are filed against A.7.11 and retained for three years.',
      '',
      '## Review',
      '',
      'Annually each January by Agil, and after any outage that stopped a branch trading.',
    ].join('\n'),
  },
  {
    code: 'ISMS-POL-A-7-12',
    title: 'Cabling Security',
    clause: 'A.7.12',
    crossRefs: ['A.7.8', 'A.8.20', 'A.8.22'],
    version: 'v1.1',
    owner: 'Agil',
    form: { code: 'FRM-A-7-12-01', name: 'Cabling and patching record' },
    revisions: [
      {
        version: 'v1.0',
        date: '2024-12-05',
        author: 'Agil',
        approval: 'Drafted',
        status: 'Superseded',
        note: 'First statement of the labelling scheme, written during the PIK fit-out.',
      },
      {
        version: 'v1.1',
        date: '2026-02-10',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Guest and clinical VLAN separation made a cabling requirement rather than only a network one, after a guest port was found patched into the clinical VLAN at Surabaya.',
      },
    ],
    evidence: [
      {
        name: 'patching-record-pik-2026.md',
        fileType: 'MD',
        uploadedAt: '2026-02-28',
        expiryDate: '2027-02-28',
        uploader: 'Agil',
        note: 'Port-by-port patching record for the PIK branch cabinet, produced at the annual audit of the labelling scheme.',
        body: [
          '# PIK branch — cabinet patching record',
          '',
          'Audited 28 February 2026 by Agil, witnessed by the PIK duty nurse (Zone 3 two-person rule).',
          '',
          '| Port | Label | Outlet | VLAN | In use |',
          '| --- | --- | --- | --- | --- |',
          '| 1–2 | PIK-REC-01/02 | Reception counter | Clinical | Yes |',
          '| 3–6 | PIK-TRT-01..04 | Treatment rooms 1–4 | Clinical | Yes |',
          '| 7–8 | PIK-ADM-01/02 | Records room | Clinical | Yes |',
          '| 9–12 | PIK-GST-01..04 | Waiting area AP, spare | Guest | 1 of 4 |',
          '| 13–22 | unlabelled | — | — | No, disabled |',
          '| 23 | PIK-UPL-01 | Uplink, Telkom ONT | — | Yes |',
          '| 24 | PIK-MGT-01 | Management | Management | Yes |',
          '',
          'Ports 13–22 were live and unlabelled at the previous audit. They are now administratively',
          'disabled and will be enabled only against a labelled outlet.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-A-7-12 · Cabling Security',
      '',
      '**Owner** Agil · **Approver** Aris Ihwan · **Version** v1.1 · **Review** annually, each February',
      '**Requirement** A.7.12 · **Also satisfies** A.7.8, A.8.20, A.8.22',
      '',
      '## Purpose',
      '',
      'A live network port in a public waiting area is the cheapest way into a clinical network, and',
      'an unlabelled patch panel is how such a port survives three audits. This policy sets the',
      'standard for how cabling is run, labelled and patched at every site.',
      '',
      '## Scope',
      '',
      'Data and power cabling from the incoming service to the outlet at every site, including the',
      'patch panels in branch comms cabinets. Cabling inside the landlord’s risers is not ours; where',
      'our cable passes through one, this policy applies to the segments we can reach.',
      '',
      '## Roles and responsibilities',
      '',
      'Agil specifies and audits cabling and is the only person who may patch a port. Contractors',
      'installing cable work to this document under a secure area permit. Andreas reviews the VLAN',
      'design that the patching enforces, so the physical and logical plans do not drift apart.',
      '',
      '## Policy',
      '',
      '1. **Every outlet and every port is labelled** to the scheme `SITE-FUNC-nn`, at both ends. An',
      '   unlabelled port is disabled, not investigated later.',
      '2. **Unused ports are administratively disabled** at the switch, not simply left unpatched.',
      '3. **Guest and clinical are physically distinct at the panel.** Guest outlets are grouped in a',
      '   contiguous block, labelled GST, and patched only to guest VLAN ports. No outlet is ever',
      '   moved between the two groups without Agil re-labelling the outlet itself.',
      '4. **No outlet in a public space** unless it is a guest outlet or feeds a fixed device such as a',
      '   wireless access point mounted out of reach.',
      '5. **Cable routes are concealed and protected.** Cables run in trunking or above the ceiling —',
      '   never across a floor, through a doorway, or where a trolley crosses.',
      '6. **Power and data separated** in trunking, with data crossing power at right angles where a',
      '   crossing is unavoidable.',
      '7. **Cabinets are dressed and documented.** Every change to a patch is recorded in the patching',
      '   record before the cabinet is closed, as part of the secure area permit close-out.',
      '8. **Annual audit.** Agil audits one cabinet per branch per year, port by port, against the',
      '   patching record, and disables anything that does not reconcile.',
      '',
      '## Records',
      '',
      'The cabling and patching record (FRM-A-7-12-01) is held per site, updated at each change, and',
      'the annual audited version retained for three years against A.7.12.',
      '',
      '## Review',
      '',
      'Annually each February by Agil with Andreas, and at every fit-out or cabinet change.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-7-13',
    title: 'Equipment Maintenance',
    clause: 'A.7.13',
    crossRefs: ['A.7.8', 'A.5.22', 'A.8.32'],
    version: 'v1.2',
    owner: 'Agil',
    form: { code: 'FRM-A-7-13-01', name: 'Equipment maintenance record' },
    revisions: [
      {
        version: 'v1.1',
        date: '2025-04-16',
        author: 'Agil',
        approval: 'Reviewed by Pak Chen',
        status: 'Superseded',
        note: 'Maintenance was tracked per contract rather than per device, so a device could be serviced twice and another not at all.',
      },
      {
        version: 'v1.2',
        date: '2026-06-01',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Per-device schedule adopted; supplier engineers brought under the secure area permit and a data-bearing device rule added before any off-site repair.',
      },
    ],
    evidence: [
      {
        name: 'maintenance-record-2026-h1.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-30',
        expiryDate: '2027-06-30',
        uploader: 'Agil',
        note: 'Maintenance performed in the first half of 2026, per device, with the engineer and the permit reference.',
        body: [
          'Date | Asset | Type | Provider | Engineer | Permit | Data-bearing | Outcome',
          '2026-01-28 | Kemang UPS | Battery replacement | PT Daya Prima | Suwandi | PRM-2026-004 | No | Passed retest',
          '2026-03-02 | Bandung switch | Firmware + relocation | In-house | Agil | PRM-2026-011 | No | Cabinet remounted',
          '2026-04-09 | HQ NAS | Disk replacement | In-house | Randy | PRM-2026-019 | Yes | Old disk destroyed on site',
          '2026-05-27 | PIK switch | Replacement, faulty PSU | In-house | Randy | PRM-2026-024 | No | Old unit returned to HQ',
          '2026-06-18 | HQ AC (cabinet) | Landlord service | Mall FM | Hendrawan | escorted | No | Confirmed by Agil',
          '',
          'The April NAS disk is the only data-bearing item serviced this half. It was not released to',
          'the supplier: the disk was destroyed on site and the certificate filed under A.7.14.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-7-13 · Equipment Maintenance',
      '',
      '**Owner** Agil · **Approver** Aris Ihwan · **Version** v1.2 · **Review** annually, each June',
      '**Requirement** A.7.13 · **Also satisfies** A.7.8, A.5.22, A.8.32',
      '',
      '## Purpose',
      '',
      'Maintenance is the moment when an outsider stands inside a cabinet with a laptop, and when a',
      'disk that held data leaves the building in a service engineer’s bag. This procedure keeps',
      'equipment serviceable and makes sure neither of those things happens unrecorded.',
      '',
      '## Scope',
      '',
      'Preventive and corrective maintenance of every asset on the sited equipment register, plus',
      'issued laptops. Medical devices are maintained under clinical engineering and are outside this',
      'procedure, although the escort and permit rules still apply to the engineer who visits.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Agil** owns the schedule, raises the permits and signs off completion.',
      '- **Randy** performs in-house work and covers out-of-hours corrective maintenance.',
      '- **Pak Chen** holds the supplier contracts and their confidentiality terms.',
      '- **Pak Andre** provides the escort and the second person at branch cabinets.',
      '',
      '## Procedure',
      '',
      '1. **Schedule per device.** Each registered device carries its own next-maintenance date on the',
      '   sited equipment register, taken from the manufacturer interval or, for UPS batteries, from',
      '   the three-year cycle in ISMS-POL-A-7-11.',
      '2. **Only approved providers.** Maintenance is performed in-house or by a provider on Pak Chen’s',
      '   approved list, whose agreement carries a confidentiality clause.',
      '3. **Permit and escort.** Every visit is covered by a secure area work permit and a continuous',
      '   escort. The engineer’s name goes on the permit before arrival.',
      '4. **Data-bearing devices never leave for repair.** If a device holds or held data — the NAS, a',
      '   laptop, any disk — the storage is removed and destroyed on site before the chassis goes',
      '   anywhere, or the repair is refused and the device replaced.',
      '5. **Changes follow change management.** Firmware, configuration and replacement of a network',
      '   device are changes and are raised as such, including for corrective work; an emergency fix',
      '   is recorded retrospectively within one working day.',
      '6. **Retest before close-out.** A UPS is load-tested after a battery change; a switch is checked',
      '   port by port against the patching record before the cabinet is closed.',
      '7. **Record the outcome.** Date, asset, provider, engineer, permit reference, whether the device',
      '   was data-bearing, and the result go into FRM-A-7-13-01 the same day.',
      '8. **Overdue chase.** Anything more than 30 days past its scheduled date is escalated by Agil to',
      '   Dhiaz Fathra with a date for the work.',
      '',
      '## Records',
      '',
      'Maintenance records (FRM-A-7-13-01), supplier service reports and any destruction certificates',
      'arising from step 4 are filed against A.7.13 and retained for three years.',
      '',
      '## Review',
      '',
      'Annually each June by Agil with Pak Chen, and whenever a maintenance provider changes.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-7-14',
    title: 'Secure Disposal and Re-use of Equipment',
    clause: 'A.7.14',
    crossRefs: ['A.7.10', 'A.8.10', 'A.5.11'],
    version: 'v2.1',
    owner: 'Agil',
    form: { code: 'FRM-A-7-14-01', name: 'Asset disposal and sanitisation certificate' },
    revisions: [
      {
        version: 'v2.0',
        date: '2025-10-08',
        author: 'Agil',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Sanitisation standard set, but disposal of clinic reception machines was still handled locally by branches.',
      },
      {
        version: 'v2.1',
        date: '2026-05-19',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'All disposal centralised at HQ after a branch sold two workstations to a staff member without sanitisation; SSDs now destroyed rather than wiped.',
      },
    ],
    evidence: [
      {
        name: 'disposal-certificate-2026-05-batch.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-05-30',
        uploader: 'Agil',
        note: 'Signed certificate for the May 2026 disposal batch, including the two recovered branch workstations.',
      },
      {
        name: 'asset-disposal-register-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-30',
        expiryDate: '2027-06-30',
        uploader: 'Agil',
        note: 'Every asset disposed of or re-issued this year, with the method and the witness.',
        body: [
          'Asset | Type | Data-bearing | Method | Witness | Date | Certificate',
          'WS-KMG-03 | Reception PC | Yes, HDD | HDD shredded, chassis recycled | Randy | 2026-05-28 | DIS-2026-05',
          'WS-KMG-04 | Reception PC | Yes, HDD | HDD shredded, chassis recycled | Randy | 2026-05-28 | DIS-2026-05',
          'DL-05 | Laptop | Yes, SSD | SSD destroyed, chassis to e-waste | Agil | 2026-05-28 | DIS-2026-05',
          'MED-04, MED-05 | USB drives | Yes | Physically destroyed | Tika | 2026-04-30 | DIS-2026-04',
          'SW-HQ-02 | Switch | No | Config erased, re-issued to Bandung | Randy | 2026-03-02 | n/a, re-use',
          '',
          'WS-KMG-03 and 04 were the branch-sold machines. Both were recovered intact from the buyer,',
          'confirmed never to have been powered on since, and destroyed in the May batch.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-7-14 · Secure Disposal and Re-use of Equipment',
      '',
      '**Owner** Agil · **Approver** Aris Ihwan · **Version** v2.1 · **Review** annually, each May',
      '**Requirement** A.7.14 · **Also satisfies** A.7.10, A.8.10, A.5.11',
      '',
      '## Purpose',
      '',
      'In March 2026 a branch sold two retired reception machines to a member of staff with their',
      'disks in place. Nothing was exposed, but only because the buyer never switched them on. This',
      'procedure takes disposal out of branch hands entirely and states how equipment is sanitised',
      'before it is destroyed, sold or re-used.',
      '',
      '## Scope',
      '',
      'Every asset leaving service: workstations, laptops, phones, network equipment, printers with',
      'internal storage, and all removable media. It also covers re-use — a device moving to a',
      'different purpose or a different holder inside the group.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Agil** performs or supervises all sanitisation and signs the certificate.',
      '- **Randy** witnesses destruction; no asset is destroyed by one person alone.',
      '- **Pak Andre** ensures branches send retired equipment to HQ rather than disposing locally.',
      '- **Pak Rila** may not release an asset from the fixed asset ledger without a certificate',
      '  reference, which is the control that makes this procedure hard to skip.',
      '',
      '## Procedure',
      '',
      '1. **Nothing is disposed of at a branch.** Retired equipment is returned to HQ, logged into the',
      '   disposal register on arrival, and held in the Zone 2 store until the batch is processed.',
      '2. **Classify the asset.** Data-bearing or not. Printers, routers and stock terminals are',
      '   assumed data-bearing until Agil confirms otherwise.',
      '3. **Spinning disks are shredded.** A three-pass wipe is not accepted as the final state for a',
      '   disk leaving the group; the drive is removed and physically shredded.',
      '4. **SSDs and flash are destroyed, not wiped,** because wear levelling makes erasure unverifiable',
      '   on the hardware we own. This replaced the wipe-and-sell practice in v2.1.',
      '5. **Network equipment is factory reset and its configuration erased,** then verified by console',
      '   before it is re-used or released.',
      '6. **Re-use inside the group** requires the same sanitisation as disposal where the device moves',
      '   between purposes or people, and the asset register is updated with the new holder.',
      '7. **Two people, one certificate.** Destruction is performed with a witness, and the certificate',
      '   (FRM-A-7-14-01) records each asset, its method, both names and the date.',
      '8. **Ledger closure.** Agil sends the certificate to Pak Rila, who closes the assets in the',
      '   fixed asset ledger within 10 working days.',
      '9. **Batch cadence.** Disposal runs quarterly, or sooner when the holding store is full or an',
      '   asset is known to have held personal data.',
      '',
      '## Records',
      '',
      'Disposal certificates and the asset disposal register are filed against A.7.14 and retained for',
      'five years — longer than the other physical records, because a disposal certificate is the only',
      'evidence that data no longer exists on hardware we no longer hold.',
      '',
      '## Review',
      '',
      'Annually each May by Agil with Pak Rila, and immediately after any uncertified disposal.',
    ].join('\n'),
  },
]
