import type { SeedDocument } from './types'

/**
 * Annex A.5 batch C — incident handling, continuity, compliance and documented
 * procedures (A.5.26 through A.5.37).
 */
export const ANNEX_A5_C: SeedDocument[] = [
  {
    code: 'ISMS-SOP-A-5-26',
    title: 'Information Security Incident Response Procedure',
    clause: 'A.5.26',
    crossRefs: ['A.5.24', 'A.5.25', 'A.5.27', 'A.6.8'],
    version: 'v2.2',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-5-26-01', name: 'Incident response log (per incident)' },
    revisions: [
      {
        version: 'v2.1',
        date: '2025-09-08',
        author: 'Randy',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Severity ladder rewritten after the March NATS backlog was triaged as SEV-3 for eleven hours before anyone noticed patient bookings were failing.',
      },
      {
        version: 'v2.2',
        date: '2026-05-19',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Added the 3×24-hour PDP notification clock and the rule that the incident commander is never the person fixing the system.',
      },
    ],
    evidence: [
      {
        name: 'incident-log-2026-h1.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-30',
        expiryDate: '2027-06-30',
        uploader: 'Randy',
        note: 'Every declared incident in the first half of 2026, with severity, commander and time to containment.',
        body: [
          '# Incident log — 2026 H1',
          '',
          'Ref | Opened | Severity | Summary | Commander | Contained | Personal data',
          'INC-2026-004 | 2026-01-22 08:41 | SEV-2 | Zitadel session tokens not rotating after password reset | Dhiaz Fathra | 4h 10m | No',
          'INC-2026-007 | 2026-02-14 21:03 | SEV-3 | Object storage bucket for marketing assets readable without auth | Agil | 51m | No',
          'INC-2026-011 | 2026-03-30 06:12 | SEV-1 | Booking writes failing group-wide, NATS consumer wedged | Randy | 2h 35m | No',
          'INC-2026-018 | 2026-05-06 13:27 | SEV-2 | Clinic tablet lost in transit between Kelapa Gading and Bintaro | Agil | 3h 02m | Yes — device wiped, no access recorded',
          'INC-2026-023 | 2026-06-17 09:55 | SEV-3 | Phishing mail to three staff impersonating Pak Rila, one credential entered | Dhiaz Fathra | 1h 18m | No',
          '',
          'Five incidents, one SEV-1. Two produced corrective actions still open at the June review',
          '(INC-2026-011 consumer alerting, INC-2026-018 device enrolment gap).',
        ].join('\n'),
      },
      {
        name: 'inc-2026-011-timeline.md',
        fileType: 'MD',
        uploadedAt: '2026-04-02',
        uploader: 'Randy',
        note: 'Working timeline for the only SEV-1 of the period, written during the incident.',
      },
    ],
    body: [
      '# ISMS-SOP-A-5-26 · Information Security Incident Response Procedure',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v2.2 · **Review** every six months',
      '**Requirement** A.5.26 · **Also satisfies** A.5.24, A.5.25, A.5.27, A.6.8',
      '',
      '## Purpose',
      '',
      'When something goes wrong at 02:00 nobody reads a policy. This procedure exists so the',
      'first person awake knows three things without deciding them: who to wake, what to write',
      'down, and what they are allowed to break to stop the bleeding. It turns the assessment',
      'made under A.5.25 into an actual response.',
      '',
      '## Scope',
      '',
      'Every confirmed information security incident affecting the Eternesia ERP, the Super App,',
      'the marketplace services, clinic devices at all 13 locations, or any supplier holding the',
      'group’s data. It excludes ordinary service faults with no security dimension — a slow',
      'query is an operations problem and is handled by the on-call runbook, not this procedure.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Incident commander** — Dhiaz Fathra, or Randy out of hours. Owns the decision log and',
      '  the clock. The commander never has hands on the keyboard; if the only responder',
      '  available is also the fixer, they hand command to Andreas before touching anything.',
      '- **Responder** — the on-call engineer. Executes containment, narrates in the incident',
      '  channel, changes nothing without saying so first.',
      '- **Rica** — decides whether personal data is in scope and owns any notification.',
      '- **Pak Andre** — decides what clinics are told and when, so that reception is not',
      '  improvising an explanation to patients.',
      '- **Aris Ihwan** — informed for SEV-1 within 30 minutes; authorises any external statement.',
      '',
      '## Procedure',
      '',
      '1. **Declare.** Anyone may declare. Open `#inc-<yyyy>-<nnn>` in Slack and state severity,',
      '   what is observed, and who is commander. Under-declaring is the expensive mistake; a',
      '   SEV-1 that turns out to be SEV-3 costs an hour of sleep and nothing else.',
      '2. **Severity.** SEV-1 — patient data exposed, or a group-wide service is unusable.',
      '   SEV-2 — a control has failed but no exposure is confirmed, or one clinic is down.',
      '   SEV-3 — contained, single-user or single-asset, no data at risk.',
      '3. **Contain before you understand.** The commander may authorise revoking Zitadel',
      '   sessions, disabling a service account, blocking an IP range, or taking a service out',
      '   of the load balancer without further approval. Preserve first where it is free to do',
      '   so — snapshot the volume before you rebuild the host (see ISMS-SOP-A-5-28).',
      '4. **Assess personal data within 60 minutes.** Rica answers one question in writing: is',
      '   personal data of patients, staff or applicants involved, and whose? If yes, the',
      '   3×24-hour written notification clock under the PDP Law starts at the moment of',
      '   confirmation, not at the end of the incident.',
      '5. **Communicate on a fixed cadence.** SEV-1: written update every 30 minutes to Aris',
      '   Ihwan and Pak Andre even when the update is "no change". SEV-2: hourly. SEV-3: on',
      '   close only.',
      '6. **Eradicate and recover.** Restore from a verified backup rather than repairing in',
      '   place where the integrity of a host is in doubt. Recovery is declared by the commander,',
      '   not by the responder who did the work.',
      '7. **Close.** The commander closes the channel with a one-paragraph statement of what',
      '   happened and what is still open. Every incident above SEV-3 is handed to',
      '   ISMS-SOP-A-5-27 for review within 10 working days.',
      '',
      '## Records',
      '',
      'The incident channel transcript, the timeline file, and one row in the incident log',
      '(`FRM-A-5-26-01`) held in the compliance repository. Retained seven years — long enough',
      'to outlive the retention of the patient records an incident may have touched.',
      '',
      '## Review',
      '',
      'Every six months by Dhiaz Fathra, and immediately after any SEV-1 where the procedure',
      'itself got in the way.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-5-27',
    title: 'Post-Incident Review and Corrective Action',
    clause: 'A.5.27',
    crossRefs: ['A.5.26', 'A.5.7', '10.2', 'A.5.24'],
    version: 'v1.3',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-5-27-01', name: 'Post-incident review record and action list' },
    revisions: [
      {
        version: 'v1.2',
        date: '2025-06-11',
        author: 'Tika',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Review template shortened; the twelve-section version was being skipped for anything below SEV-1.',
      },
      {
        version: 'v1.3',
        date: '2026-04-09',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Blameless rule written down explicitly, and actions now carry a named owner and a date or they are not accepted.',
      },
    ],
    evidence: [
      {
        name: 'pir-inc-2026-011-nats-consumer.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-04-14',
        uploader: 'Dhiaz Fathra',
        note: 'Signed review of the group-wide booking outage, the only SEV-1 of 2026 H1.',
        body: [
          '# Post-incident review — INC-2026-011',
          '',
          '**Incident** Booking writes failing group-wide · **Severity** SEV-1 · **Date** 30 March 2026',
          '**Commander** Randy · **Review chaired by** Dhiaz Fathra · **Attending** Andreas, Agil, Pak Andre',
          '',
          '## What happened',
          '',
          'A durable NATS consumer in the `booking` service stopped acknowledging after a broker',
          'restart. The service stayed healthy on its liveness probe, so no alert fired. Reception',
          'at four clinics took bookings on paper for 2h 35m before the queue was drained.',
          '',
          '## Why it was not caught',
          '',
          'The liveness probe answers "is the process up", which was true throughout. Nothing',
          'watched consumer lag. This is a monitoring design gap, not an operator error — the',
          'on-call engineer had no signal to act on.',
          '',
          '## Contributing factors',
          '',
          '- Broker restart was routine patching, performed inside the change window, correctly.',
          '- The paper fallback at reception worked, but no one told Pak Andre for 40 minutes.',
          '',
          '## Actions',
          '',
          'A1 — Alert on consumer lag > 500 messages for every durable consumer · Agil · 2026-04-30 · Closed',
          'A2 — Readiness probe asserts consumer health, not just process health · Randy · 2026-05-15 · Closed',
          'A3 — Clinic notification added as step 5 of ISMS-SOP-A-5-26 · Dhiaz Fathra · 2026-05-19 · Closed',
          'A4 — Chaos test: restart the broker in staging each release · Tika · 2026-07-31 · Open',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-5-27 · Post-Incident Review and Corrective Action',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v1.3 · **Review** annually',
      '**Requirement** A.5.27 · **Also satisfies** A.5.26, A.5.7, ISO 9001 10.2, A.5.24',
      '',
      '## Purpose',
      '',
      'An incident that teaches nothing has only cost money. This procedure converts what was',
      'learned during a response into a change someone owns, and feeds the recurring patterns',
      'back into threat intelligence and into the annual risk assessment.',
      '',
      '## Scope',
      '',
      'Every incident of SEV-2 or above, every SEV-3 that is the third of its kind in a quarter,',
      'and every near miss reported voluntarily. Reviews are not held for incidents caused',
      'entirely by a supplier outage where the group has no control to change — those are logged',
      'and raised at the supplier review with Pak Chen instead.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Dhiaz Fathra** chairs. The chair is never the incident commander, so that the',
      '  decisions made under pressure can be questioned by someone who did not make them.',
      '- **The incident commander** presents the timeline as it was, including what was believed',
      '  at the time and turned out to be wrong.',
      '- **Tika** tracks the resulting actions in the corrective action register.',
      '- **Andreas** decides whether the finding changes an architectural decision record.',
      '',
      '## Procedure',
      '',
      '1. Book the review within 10 working days of close. Later than that and the detail is',
      '   already reconstruction rather than memory.',
      '2. Circulate the raw timeline beforehand. The meeting is for the "why", not for reading.',
      '3. Run it blameless, and mean it. The question is what made the mistake reasonable at the',
      '   time — a misleading dashboard, a missing alert, an ambiguous runbook. Naming a person',
      '   as a root cause ends the analysis one step early and guarantees a repeat.',
      '4. Stop at the first cause the organisation can actually change. "The engineer did not',
      '   see it" is not that cause; "nothing was watching consumer lag" is.',
      '5. Write actions with an owner from the list of people in the room and a date. An action',
      '   with neither is a wish and is not recorded as an action.',
      '6. Classify the incident against the threat categories used for A.5.7 so the intelligence',
      '   picture is built from real events rather than vendor bulletins alone.',
      '7. Where the same cause appears twice in four quarters, raise a nonconformity under',
      '   ISO 9001 10.2 rather than another action; the fix is evidently not working.',
      '',
      '## Records',
      '',
      'A signed review record per incident (`FRM-A-5-27-01`), the action rows in the corrective',
      'action register, and a quarterly summary presented to the management review. Retained',
      'five years.',
      '',
      '## Review',
      '',
      'Annually by Dhiaz Fathra, using one number as the test: the proportion of review actions',
      'closed by their due date. Below 70% the procedure is producing paper, not change.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-5-28',
    title: 'Collection and Handling of Digital Evidence',
    clause: 'A.5.28',
    crossRefs: ['A.5.26', 'A.5.33', 'A.8.15'],
    version: 'v1.1',
    owner: 'Agil',
    form: { code: 'FRM-A-5-28-01', name: 'Evidence chain of custody record' },
    revisions: [
      {
        version: 'v1.0',
        date: '2025-03-17',
        author: 'Agil',
        approval: 'Drafted',
        status: 'Superseded',
        note: 'First version, written after a rebuilt EC2 host destroyed the only copy of the logs that would have explained INC-2025-002.',
      },
      {
        version: 'v1.1',
        date: '2026-02-26',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Hashing made mandatory at capture rather than at hand-over; clinic tablet imaging steps added.',
      },
    ],
    evidence: [
      {
        name: 'chain-of-custody-register-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-30',
        expiryDate: '2027-06-30',
        uploader: 'Agil',
        note: 'Every evidence item captured in 2026, with hash, custodian and current location.',
        body: [
          '# Chain of custody register — 2026',
          '',
          'Item | Incident | Captured | Type | SHA-256 (first 12) | Captured by | Held in | Released',
          'EV-2026-01 | INC-2026-007 | 2026-02-14 21:40 | S3 access log export | 4c9a1f0b73de | Agil | evidence bucket, Object Lock 1y | —',
          'EV-2026-02 | INC-2026-011 | 2026-03-30 07:05 | EBS snapshot, booking-2 | 8b21ce55a0f7 | Randy | ap-southeast-1, tagged legal-hold | —',
          'EV-2026-03 | INC-2026-018 | 2026-05-06 15:12 | MDM wipe confirmation + device record | 1de77a34cc90 | Agil | evidence bucket | —',
          'EV-2026-04 | INC-2026-023 | 2026-06-17 10:30 | Mail headers, 3 messages | 90fa2b1d6e45 | Dhiaz Fathra | evidence bucket | —',
          '',
          'No item has been released to a third party in 2026. Two items (EV-2026-01, EV-2026-02)',
          'carry a legal hold and are exempt from the normal 12-month expiry until Rica lifts it.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-5-28 · Collection and Handling of Digital Evidence',
      '',
      '**Owner** Agil · **Approver** Aris Ihwan · **Version** v1.1 · **Review** annually',
      '**Requirement** A.5.28 · **Also satisfies** A.5.26, A.5.33, A.8.15',
      '',
      '## Purpose',
      '',
      'Most evidence is lost in the first twenty minutes of an incident, by someone helpfully',
      'rebuilding a host. This procedure states what to capture, in what order, and how to keep',
      'it in a state that would survive being questioned — by a regulator under the PDP Law, by',
      'an insurer, or by the group’s own counsel.',
      '',
      '## Scope',
      '',
      'Digital evidence from AWS ap-southeast-1 workloads, Zitadel, the NATS estate, clinic',
      'tablets and staff laptops. Physical evidence — a recovered device, a visitor book page —',
      'is bagged, labelled and held by Agil under the same custody rules. Nothing here authorises',
      'reading an individual’s personal mailbox or messages; that requires Rica’s written',
      'agreement and Aris Ihwan’s approval, recorded before the access happens.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Agil** is evidence custodian and the only person who grants access to the evidence',
      '  bucket.',
      '- **The incident commander** decides that evidence is to be preserved, and records that',
      '  decision with a timestamp.',
      '- **Rica** places and lifts legal holds where personal data or a regulatory notification',
      '  is involved.',
      '- **Randy and Andreas** may capture, but capture is always witnessed by a second engineer.',
      '',
      '## Procedure',
      '',
      '1. **Preserve before you remediate.** Snapshot the EBS volume, export the CloudWatch log',
      '   group and pull the Zitadel audit events for the window before restarting, rebuilding',
      '   or rotating anything. Capture is measured in minutes; a lost log is lost forever.',
      '2. **Capture in volatility order** — in-memory state and open connections first, then',
      '   disk, then logs already shipped off the host, which are the least likely to disappear.',
      '3. **Hash at the moment of capture.** Compute SHA-256 and write it into the custody record',
      '   before the item moves anywhere. A hash produced later proves only that nothing changed',
      '   since later.',
      '4. **Write once.** Evidence goes to the dedicated S3 bucket with Object Lock in compliance',
      '   mode for 12 months. No one, including Agil, can delete inside that window.',
      '5. **Record every touch.** Who took it, from what, when, witnessed by whom, and every',
      '   subsequent access — one row per event in `FRM-A-5-28-01`. A gap in the row sequence is',
      '   treated as a broken chain and the item is marked unreliable rather than quietly used.',
      '6. **Clinic devices** are imaged before wipe where the device is in hand. Where it is lost,',
      '   the MDM wipe confirmation and the enrolment record are the evidence and are captured',
      '   the same way.',
      '7. **Release to a third party** — police, insurer, regulator, external counsel — only on',
      '   Aris Ihwan’s written instruction, with the release logged and a hash re-verified in',
      '   front of the recipient.',
      '',
      '## Records',
      '',
      'The custody register (`FRM-A-5-28-01`) and the evidence items themselves. Register retained',
      'seven years; items expire at 12 months unless a legal hold is in force.',
      '',
      '## Review',
      '',
      'Annually by Agil with Dhiaz Fathra, and after any incident where a needed record turned',
      'out not to have been captured.',
    ].join('\n'),
  },
  {
    code: 'ISMS-POL-A-5-29',
    title: 'Maintaining Information Security During Disruption',
    clause: 'A.5.29',
    crossRefs: ['A.5.30', 'A.5.26', 'A.8.13'],
    version: 'v1.2',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-5-29-01', name: 'Degraded-mode authorisation record' },
    revisions: [
      {
        version: 'v1.1',
        date: '2025-08-05',
        author: 'Pak Andre',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Paper fallback for clinic reception documented after the March 2025 connectivity loss at Kelapa Gading.',
      },
      {
        version: 'v1.2',
        date: '2026-05-12',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Explicit list of controls that must never be relaxed, and a 24-hour cap on any degraded-mode authorisation.',
      },
    ],
    evidence: [
      {
        name: 'degraded-mode-drill-report-2026.docx',
        fileType: 'DOCX',
        uploadedAt: '2026-03-21',
        expiryDate: '2027-03-21',
        uploader: 'Pak Andre',
        note: 'Report of the annual clinic drill running two locations on paper for a full session.',
      },
    ],
    body: [
      '# ISMS-POL-A-5-29 · Maintaining Information Security During Disruption',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v1.2 · **Review** annually',
      '**Requirement** A.5.29 · **Also satisfies** A.5.30, A.5.26, A.8.13',
      '',
      '## Purpose',
      '',
      'Under pressure the tempting move is to turn a control off — share one login so reception',
      'can keep working, e-mail a patient list to a personal address, put the spreadsheet on a',
      'USB stick. This policy states in advance which of those are permitted, for how long, and',
      'who may say yes, so the decision is not made by whoever is most stressed.',
      '',
      '## Scope',
      '',
      'Any disruption lasting more than 30 minutes: platform outage, clinic connectivity loss,',
      'supplier failure, building evacuation, or the recovery period after a security incident.',
      'It covers all 13 clinic locations and the engineering group. Financial continuity and',
      'insurance are Pak Rila’s and sit outside this document.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Pak Andre** decides when a clinic moves to degraded mode and when it returns.',
      '- **Dhiaz Fathra** is the only person who may authorise relaxing a security control, and',
      '  records it on `FRM-A-5-29-01` before it takes effect.',
      '- **Agil** runs the technical recovery under ISMS-SOP-A-5-30.',
      '- **Rica** is told within the hour whenever degraded mode involves personal data leaving',
      '  its normal system.',
      '',
      '## Policy',
      '',
      '1. **Security requirements survive the disruption.** The obligations under the PDP Law do',
      '   not pause because a system is down. Degraded mode changes how work is done, never',
      '   whether patient data is protected.',
      '2. **Controls that are never relaxed**, whatever the pressure: individual accounts (no',
      '   shared logins, ever), encryption of data at rest, the prohibition on removable media',
      '   for patient data, and the logging of access to treatment records. If continuing work',
      '   requires breaking one of these, work stops instead.',
      '3. **Controls that may be relaxed with written authorisation**: the four-eyes rule on',
      '   production changes, the change window, and the requirement that patient contact happen',
      '   through the Super App rather than a phone call from a clinic line.',
      '4. **Every authorisation is time-boxed to 24 hours.** It expires automatically. Extending',
      '   it requires a fresh record and Aris Ihwan’s counter-signature, which is deliberately',
      '   inconvenient — a relaxation running for a week has become the normal way of working.',
      '5. **Paper fallback is the designed answer for clinics.** Reception uses the numbered',
      '   fallback forms held at each location: booking, consent and treatment note. Forms are',
      '   locked in the reception cabinet during the session, entered into the ERP within 24',
      '   hours of recovery, and then shredded with the destruction logged.',
      '6. **What was done in the dark is reconstructed in the light.** Every degraded-mode period',
      '   ends with a reconciliation: which records were created on paper, which access happened',
      '   outside the normal audit trail, and what is now in the system that was not before.',
      '',
      '## Records',
      '',
      'Degraded-mode authorisations, reconciliation notes and fallback-form destruction logs,',
      'held with the incident record. Retained three years, or seven where personal data was',
      'handled outside its normal system.',
      '',
      '## Review',
      '',
      'Annually by Dhiaz Fathra with Pak Andre, informed by the yearly clinic drill and by any',
      'real disruption in the period.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-5-30',
    title: 'ICT Continuity and Recovery Procedure',
    clause: 'A.5.30',
    crossRefs: ['A.5.29', 'A.8.13', 'A.8.14', 'A.8.6'],
    version: 'v2.0',
    owner: 'Agil',
    form: { code: 'FRM-A-5-30-01', name: 'Recovery test result record' },
    revisions: [
      {
        version: 'v1.4',
        date: '2025-10-02',
        author: 'Agil',
        approval: 'Reviewed by Andreas',
        status: 'Superseded',
        note: 'RTO and RPO set per service tier rather than one figure for the whole platform.',
      },
      {
        version: 'v2.0',
        date: '2026-06-03',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Restore rehearsal made quarterly and evidence-bearing; a backup that has not been restored is now formally treated as no backup.',
      },
    ],
    evidence: [
      {
        name: 'restore-rehearsal-2026-q2.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-08',
        expiryDate: '2026-09-08',
        uploader: 'Agil',
        note: 'Q2 restore rehearsal: every tier-1 service restored into an isolated account and verified.',
        body: [
          '# Restore rehearsal — 2026 Q2',
          '',
          'Service | Tier | RTO target | Restored in | RPO target | Data loss | Verified by | Result',
          'patient | 1 | 2h | 1h 12m | 15m | 4m | Randy | Pass',
          'booking | 1 | 2h | 1h 41m | 15m | 9m | Randy | Pass',
          'billing | 1 | 2h | 2h 26m | 15m | 6m | Tika | Fail — RTO missed, index rebuild',
          'catalogue | 2 | 8h | 46m | 4h | 0m | Tika | Pass',
          'Super App API | 1 | 2h | 58m | 15m | 2m | Agil | Pass',
          'marketing site | 3 | 48h | not tested | 24h | — | — | Deferred by design',
          '',
          'One failure. The billing restore missed RTO on index rebuild time; action B-14 (pre-built',
          'index snapshot) is owned by Agil for the Q3 rehearsal.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-5-30 · ICT Continuity and Recovery Procedure',
      '',
      '**Owner** Agil · **Approver** Aris Ihwan · **Version** v2.0 · **Review** quarterly',
      '**Requirement** A.5.30 · **Also satisfies** A.5.29, A.8.13, A.8.14, A.8.6',
      '',
      '## Purpose',
      '',
      'To state what the engineering group has to be able to bring back, how fast, and how that',
      'claim is proved. The organisation does not claim a recovery time it has not measured in',
      'the current quarter.',
      '',
      '## Scope',
      '',
      'All production workloads in AWS ap-southeast-1: the Eternesia ERP services, the Super App',
      'API, the marketplace services and their PostgreSQL, NATS and object storage dependencies.',
      'Clinic hardware and the paper fallback are covered by ISMS-POL-A-5-29. There is no second',
      'region and no warm standby — see the limits below.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Agil** owns the recovery capability, runs the rehearsals and holds the runbooks.',
      '- **Randy** is the on-call executor out of hours.',
      '- **Tika** independently verifies a sample of restored data against production values; the',
      '  person who ran the restore never signs it off.',
      '- **Andreas** sets the service tier when a new service is designed, not after it ships.',
      '',
      '## Procedure',
      '',
      '1. **Tiers and targets.** Tier 1 (patient, booking, billing, Super App API): RTO 2 hours,',
      '   RPO 15 minutes. Tier 2 (catalogue, pricing, internal tooling): RTO 8 hours, RPO 4 hours.',
      '   Tier 3 (marketing site, analytics): RTO 48 hours, RPO 24 hours.',
      '2. **Backups.** PostgreSQL: continuous WAL archiving plus a nightly base backup, 35-day',
      '   retention. Object storage: versioning with cross-account replication. Infrastructure:',
      '   Terraform state and manifests in Git — a host is rebuilt, never repaired, so its',
      '   configuration is recovered from source.',
      '3. **Quarterly rehearsal.** Restore every tier-1 service into an isolated AWS account from',
      '   backup alone, with no access to production. Record wall-clock restore time and actual',
      '   data loss on `FRM-A-5-30-01`. A backup that has not been restored this quarter is not',
      '   counted as a backup in the management review.',
      '4. **Verification is independent.** Tika runs a fixed query set against the restored',
      '   database and compares row counts and checksums for five reference records.',
      '5. **A missed target is a finding.** It goes into the corrective action register with an',
      '   owner and a date, and is retested at the next rehearsal rather than closed on argument.',
      '6. **Invoking recovery** in a real event follows the runbook in `ops/runbooks/`, under the',
      '   incident commander appointed by ISMS-SOP-A-5-26. Recovery is declared complete only',
      '   after the verification step, not when the service answers.',
      '',
      '## Deliberate limits',
      '',
      'No multi-region failover and no hot standby. At the group’s size the cost is real and the',
      'benefit is a reduction from a two-hour to a ten-minute outage in a scenario that has not',
      'occurred. This is revisited annually and would change if a tier-1 RTO were contractually',
      'committed to a partner.',
      '',
      '## Records',
      '',
      'Rehearsal results (`FRM-A-5-30-01`) and runbook revisions, kept in the compliance',
      'repository for three years and reported quarterly to the management review.',
      '',
      '## Review',
      '',
      'Quarterly, immediately after each rehearsal, by Agil with Andreas.',
    ].join('\n'),
  },
  {
    code: 'ISMS-POL-A-5-31',
    title: 'Legal, Regulatory and Contractual Obligations Register Policy',
    clause: 'A.5.31',
    crossRefs: ['A.5.34', 'A.5.32', 'A.5.33', 'A.5.20'],
    version: 'v1.4',
    owner: 'Rica',
    form: { code: 'FRM-A-5-31-01', name: 'Legal and regulatory obligations register' },
    revisions: [
      {
        version: 'v1.3',
        date: '2025-05-20',
        author: 'Rica',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Health-facility licensing obligations added alongside the data protection entries.',
      },
      {
        version: 'v1.4',
        date: '2026-01-27',
        author: 'Rica',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Each obligation now names the control that satisfies it, so an unmapped obligation is visible rather than assumed covered.',
      },
    ],
    evidence: [
      {
        name: 'legal-obligations-register-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-01-27',
        expiryDate: '2027-01-27',
        uploader: 'Rica',
        note: 'The register itself: obligation, source, owner, satisfying control, last checked.',
        body: [
          '# Legal and regulatory obligations register — 2026',
          '',
          'Obligation | Source | Owner | Satisfied by | Last checked',
          'Protect personal data as a controller | UU No. 27/2022 (PDP) | Rica | TRD-SEC-002, A.5.34 controls | 2026-01-20',
          'Notify data subjects and authority within 3×24h | UU No. 27/2022 Art. 46 | Rica | ISMS-SOP-A-5-26 step 4 | 2026-01-20',
          'Medical record retention and confidentiality | Permenkes on medical records | Pak Andre | Clinic records SOP, ISMS-POL-A-5-33 | 2026-01-22',
          'Clinic operating licence per location | Health office, per regency | Pak Andre | Licence file, renewal calendar | 2026-01-22',
          'Electronic system operator registration | UU ITE / PSE registration | Dhiaz Fathra | PSE certificate, renewed 2025-11 | 2025-11-14',
          'Tax records retention (10 years) | Indonesian tax law | Pak Rila | Finance archive, ISMS-POL-A-5-33 | 2026-01-15',
          'Licensed software used within terms | Contract, per vendor | Pak Chen | ISMS-POL-A-5-32 | 2026-01-26',
          'Supplier data processing instructions in writing | UU No. 27/2022 Art. 51 | Pak Chen | Supplier agreements, A.5.20 | 2026-01-26',
          '',
          'Eight obligations, all mapped to a control. One gap closed in this revision: supplier',
          'processing instructions previously relied on a verbal understanding with two vendors.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-A-5-31 · Legal, Regulatory and Contractual Obligations Register Policy',
      '',
      '**Owner** Rica · **Approver** Aris Ihwan · **Version** v1.4 · **Review** twice yearly',
      '**Requirement** A.5.31 · **Also satisfies** A.5.34, A.5.32, A.5.33, A.5.20',
      '',
      '## Purpose',
      '',
      'The group operates clinics and a software platform, so it sits under health-facility',
      'regulation, data protection law and ordinary commercial contract at the same time. This',
      'policy keeps a single list of what the organisation is actually obliged to do, who owns',
      'each obligation, and which control discharges it — so that "we assumed someone had that"',
      'is not an answer available to anyone.',
      '',
      '## Scope',
      '',
      'Obligations arising from Indonesian statute and regulation, from licences held by the 13',
      'clinic locations, and from contracts with patients, partners, suppliers and employees,',
      'where they bear on information security or on the handling of records. Clinical practice',
      'standards and employment law generally are tracked by Pak Andre outside this register.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Rica** maintains the register and is the controller representative for personal data.',
      '- **Pak Andre** owns clinic licensing and medical record obligations.',
      '- **Pak Chen** owns supplier contractual obligations and licence terms.',
      '- **Pak Rila** owns financial and tax retention obligations.',
      '- **Dhiaz Fathra** owns the mapping from obligation to ISMS control and reports coverage',
      '  to the management review.',
      '',
      '## Policy',
      '',
      '1. Every obligation is recorded with five fields and is not accepted without them: the',
      '   obligation in plain words, its source, a named owner, the control or document that',
      '   satisfies it, and the date it was last checked as still current.',
      '2. An obligation with no satisfying control is a gap, is reported as such at the next',
      '   management review, and is not closed by adding a note that says "handled by policy".',
      '3. Owners confirm their entries every six months — January and July. Confirmation means',
      '   the person went and looked, including whether the source instrument has changed.',
      '4. New or amended legislation reaching the group through counsel, an industry body or the',
      '   health office is assessed within 20 working days and either added or explicitly',
      '   recorded as not applicable, with the reason.',
      '5. Contractual security commitments made to a partner are entered here before the contract',
      '   is signed, not after. Pak Chen does not sign a clause the engineering group has not',
      '   confirmed it can meet.',
      '6. Cryptographic and export-related constraints are checked here whenever a new component',
      '   is introduced into the platform.',
      '',
      '## Records',
      '',
      'The register (`FRM-A-5-31-01`), the licence and certificate files behind it, and the',
      'half-yearly confirmation notes. Retained ten years to match the longest statutory',
      'retention the group carries.',
      '',
      '## Review',
      '',
      'Twice yearly by Rica with the named owners, and reported annually to Aris Ihwan as part of',
      'the compliance obligations input to the management review.',
    ].join('\n'),
  },
  {
    code: 'ISMS-POL-A-5-32',
    title: 'Intellectual Property and Software Licensing Policy',
    clause: 'A.5.32',
    crossRefs: ['A.5.31', 'A.8.19', 'A.5.9'],
    version: 'v1.2',
    owner: 'Pak Chen',
    form: { code: 'FRM-A-5-32-01', name: 'Software licence and open-source inventory' },
    revisions: [
      {
        version: 'v1.1',
        date: '2025-04-14',
        author: 'Pak Chen',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Seat-count reconciliation added after an audit of design tooling found four unused paid seats and two shared ones.',
      },
      {
        version: 'v1.2',
        date: '2026-03-11',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Open-source licence classes defined and enforced in CI; copyleft dependencies now blocked at merge rather than found later.',
      },
    ],
    evidence: [
      {
        name: 'oss-licence-scan-2026-06.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-24',
        expiryDate: '2026-09-24',
        uploader: 'Andreas',
        note: 'Monthly dependency licence scan across the Go, Flutter and Node repositories.',
        body: [
          '# Open-source licence scan — June 2026',
          '',
          'Repository group | Dependencies | Permissive | Weak copyleft | Strong copyleft | Unknown | Action',
          'Go services (21) | 613 | 601 | 12 | 0 | 0 | None',
          'Flutter Super App | 288 | 279 | 6 | 0 | 3 | 3 unknown licences raised to Andreas',
          'Node/Express marketplace | 741 | 726 | 15 | 0 | 0 | None',
          'Internal tooling | 154 | 150 | 4 | 0 | 0 | None',
          '',
          'No strong-copyleft dependency reached a distributed artefact. The three unknown licences',
          'in the Flutter tree were resolved within the week: two MIT with a missing SPDX header,',
          'one abandoned package replaced.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-A-5-32 · Intellectual Property and Software Licensing Policy',
      '',
      '**Owner** Pak Chen · **Approver** Aris Ihwan · **Version** v1.2 · **Review** annually',
      '**Requirement** A.5.32 · **Also satisfies** A.5.31, A.8.19, A.5.9',
      '',
      '## Purpose',
      '',
      'The group both consumes other people’s intellectual property — commercial software, open',
      'source, stock imagery, clinical content — and creates its own in the Eternesia platform.',
      'This policy sets out how the first is used within its terms and how the second stays the',
      'group’s.',
      '',
      '## Scope',
      '',
      'All software, media and written material used on group systems or in group marketing, and',
      'all code, designs and documentation produced by staff and contractors. Patient records are',
      'not intellectual property and are governed by TRD-SEC-002.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Pak Chen** owns commercial licence procurement, renewal and seat reconciliation.',
      '- **Andreas** owns the open-source position: which licence classes are acceptable and what',
      '  the CI gate blocks.',
      '- **Wiwin** owns rights clearance for marketing imagery and treatment copy.',
      '- **Dhiaz Fathra** ensures contractor agreements assign IP to the group before work starts.',
      '',
      '## Policy',
      '',
      '1. **Licences are bought, not borrowed.** No paid tool is used beyond its purchased seat',
      '   count, and no personal or educational licence is used for group work. Sharing a login',
      '   to avoid buying a seat is treated as a policy breach under ISMS-SOP-A-5-36.',
      '2. **Installation is controlled.** Staff cannot install software outside the approved',
      '   catalogue on managed devices; requests go to Agil and are approved against a licence.',
      '3. **Open source is classified.** Permissive (MIT, Apache-2.0, BSD, ISC) is allowed',
      '   freely. Weak copyleft (MPL-2.0, LGPL) is allowed for unmodified library use. Strong',
      '   copyleft (GPL, AGPL) is not permitted in anything distributed or network-served, and',
      '   the CI licence scan fails the merge request rather than raising a warning.',
      '4. **An unknown licence is a blocker,** not a risk to accept. The dependency is resolved,',
      '   replaced or explicitly waived by Andreas with a recorded reason.',
      '5. **Attribution is honoured.** Third-party notices are generated at build time and shipped',
      '   with the Super App release.',
      '6. **The group’s own IP.** Employment contracts and every contractor agreement assign work',
      '   product to PT Cakrawala Bumi Estetika. Source lives only in group-controlled Git;',
      '   pushing group code to a personal repository is a reportable incident.',
      '7. **Seat and dependency reconciliation** runs quarterly for commercial licences and',
      '   monthly for open-source dependencies. Unused seats are released at renewal.',
      '',
      '## Records',
      '',
      'The licence and open-source inventory (`FRM-A-5-32-01`), purchase records held by Pak Chen,',
      'monthly scan outputs and signed contractor IP assignments. Retained for the life of the',
      'licence plus three years.',
      '',
      '## Review',
      '',
      'Annually by Pak Chen with Andreas, ahead of the main renewal cycle in Q4.',
    ].join('\n'),
  },
  {
    code: 'ISMS-POL-A-5-33',
    title: 'Protection and Retention of Records',
    clause: 'A.5.33',
    crossRefs: ['A.5.31', 'A.5.28', '9001 7.5.3', 'A.8.10'],
    version: 'v2.0',
    owner: 'Rica',
    form: { code: 'FRM-A-5-33-01', name: 'Records retention schedule' },
    revisions: [
      {
        version: 'v1.6',
        date: '2024-11-19',
        author: 'Rica',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Retention periods separated by record class instead of a single seven-year rule applied to everything.',
      },
      {
        version: 'v2.0',
        date: '2026-04-21',
        author: 'Rica',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Deletion made automatic and evidenced by the ENG-SOP-001 job; legal hold introduced as an explicit override.',
      },
    ],
    evidence: [
      {
        name: 'records-retention-schedule-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-04-21',
        expiryDate: '2027-04-21',
        uploader: 'Rica',
        note: 'Retention period, legal basis, storage and disposal method for each record class.',
        body: [
          '# Records retention schedule — 2026',
          '',
          'Record class | Retention | Basis | Held in | Disposal',
          'Medical / treatment record | 10 years from last visit | Permenkes medical records | patient + treatment services | Automated soft delete then purge',
          'Before/after photographs | 10 years, or on withdrawal of consent | PDP Law + treatment contract | Object storage, encrypted | Purge with key destruction',
          'Consent records | Life of relationship + 5 years | PDP Law Art. 20 | patient service | Purge',
          'Billing and tax records | 10 years | Tax law | billing service + finance archive | Purge after Pak Rila sign-off',
          'Employment records | 5 years after leaving | Employment law | HR system | Shred / purge',
          'ISMS records (audits, reviews, incidents) | 5 years | ISO/IEC 27001 | Compliance repository | Purge',
          'Evidence items under hold | Until hold lifted | Legal | Evidence bucket, Object Lock | Purge on Rica’s release',
          'Application and access logs | 18 months | Operational + investigative need | CloudWatch | Automatic expiry',
          'CCTV footage | 30 days | Proportionality | On-site NVR | Overwrite',
          '',
          'Deletion is executed by the scheduled job in ENG-SOP-001; the June run purged 3,140',
          'records across four classes and acknowledged from every owning service.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-A-5-33 · Protection and Retention of Records',
      '',
      '**Owner** Rica · **Approver** Aris Ihwan · **Version** v2.0 · **Review** annually',
      '**Requirement** A.5.33 · **Also satisfies** A.5.31, A.5.28, ISO 9001 7.5.3, A.8.10',
      '',
      '## Purpose',
      '',
      'Records the group must keep have to survive — loss, tampering and quiet drift. Records it',
      'must not keep have to actually go. Both failures are common and both are visible to a',
      'regulator, so this policy sets one schedule that covers keeping and destroying alike.',
      '',
      '## Scope',
      '',
      'Medical and treatment records, consent records, billing and tax records, employment',
      'records, ISMS and QMS records, logs and CCTV footage, in every system the group runs and',
      'in physical form at the 13 clinic locations. Working drafts and ephemeral chat are not',
      'records and are not retained deliberately.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Rica** owns the schedule and is the only person who may place or lift a legal hold.',
      '- **Pak Andre** owns clinic-held physical records and their locked storage.',
      '- **Pak Rila** signs off before any financial record is destroyed.',
      '- **Agil** runs the automated deletion job and evidences each run.',
      '- **Tika** samples deletions quarterly to confirm the records actually left every service.',
      '',
      '## Policy',
      '',
      '1. **Every record class has a stated retention period and a legal basis** for that period.',
      '   A class with no basis defaults to the shortest period that supports the business need,',
      '   not the longest that feels safe.',
      '2. **Authenticity and integrity.** Records held electronically are write-protected once',
      '   final: treatment notes are amended by appending a correction, never by editing the',
      '   original, and the actor and timestamp are captured from the Zitadel claim.',
      '3. **Availability over time.** Records must remain readable for their whole period. Formats',
      '   are limited to PDF/A, plain text, CSV and the ERP’s own tables; a proprietary format',
      '   with no export path is not accepted for a record with a ten-year life.',
      '4. **Protection.** Electronic records are encrypted at rest in AWS ap-southeast-1 and',
      '   backed up under ISMS-SOP-A-5-30. Physical records are held in locked cabinets at the',
      '   clinic, accessible only to clinical staff of that location.',
      '5. **Destruction is deliberate and evidenced.** Deletion is executed by the scheduled job',
      '   in ENG-SOP-001, which requires acknowledgement from every owning service; paper is',
      '   cross-cut shredded with a destruction note countersigned by two people.',
      '6. **Legal hold overrides retention.** Where litigation, a regulatory request or an open',
      '   incident applies, Rica places a hold and deletion is suspended for those records only,',
      '   with the hold recorded and dated.',
      '7. **An erasure request under the PDP Law is honoured** except where a record is held under',
      '   a statutory retention obligation or a legal hold; the reason for any refusal is given to',
      '   the data subject in writing.',
      '',
      '## Records',
      '',
      'The retention schedule (`FRM-A-5-33-01`), deletion job run reports, destruction notes and',
      'the legal hold log. Held in the compliance repository, retained ten years.',
      '',
      '## Review',
      '',
      'Annually by Rica, and whenever the obligations register (ISMS-POL-A-5-31) records a change',
      'to a statutory retention period.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-5-35',
    title: 'Independent Review of Information Security',
    clause: 'A.5.35',
    crossRefs: ['A.5.36', '9001 9.2', 'A.5.1'],
    version: 'v1.2',
    owner: 'Tika',
    form: { code: 'FRM-A-5-35-01', name: 'Independent review report and finding log' },
    revisions: [
      {
        version: 'v1.1',
        date: '2025-07-29',
        author: 'Tika',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Independence rule stated after the first internal audit was carried out by the engineer who had built the control under review.',
      },
      {
        version: 'v1.2',
        date: '2026-02-10',
        author: 'Tika',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Three-year coverage plan added, plus the requirement for an external review of the ISMS at least every two years.',
      },
    ],
    evidence: [
      {
        name: 'internal-audit-report-2026-01-isms.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-02-06',
        uploader: 'Tika',
        note: 'Signed internal audit of access control, incident management and supplier security.',
        body: [
          '# Internal audit report — ISMS 2026/01',
          '',
          '**Auditor** Tika (QA Lead) · **Independence** no involvement in the audited controls',
          '**Audited** 26–30 January 2026 · **Areas** A.5.15–A.5.18, A.5.19–A.5.23, A.5.24–A.5.28',
          '**Auditee** Dhiaz Fathra, Agil, Pak Chen',
          '',
          '## Findings',
          '',
          'F-01 | Minor | Two contractor accounts remained active 9 and 14 days after end of engagement | A.5.18 | Dhiaz Fathra | 2026-03-15',
          'F-02 | Minor | Supplier review for one hosting vendor overdue by a quarter | A.5.22 | Pak Chen | 2026-03-31',
          'F-03 | Observation | Incident log complete, but two SEV-3 entries had no closing note | A.5.26 | Randy | 2026-02-28',
          '',
          '## Positive findings',
          '',
          'Evidence handling under ISMS-SOP-A-5-28 was followed precisely during INC-2026-007,',
          'including hashing at capture. Access reviews for clinic staff were current at all 13',
          'locations.',
          '',
          '## Opinion',
          '',
          'The controls examined are implemented and operating. No major nonconformity. The two',
          'minor findings share a cause — no calendar trigger for time-bound obligations — and are',
          'best fixed once rather than twice.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-5-35 · Independent Review of Information Security',
      '',
      '**Owner** Tika · **Approver** Aris Ihwan · **Version** v1.2 · **Review** annually',
      '**Requirement** A.5.35 · **Also satisfies** A.5.36, ISO 9001 9.2, A.5.1',
      '',
      '## Purpose',
      '',
      'Self-assessment finds what the team already knows. This procedure arranges for the ISMS to',
      'be examined by someone who did not build it, on a planned cycle, so that management’s',
      'confidence in the controls rests on something other than the assurances of the people',
      'operating them.',
      '',
      '## Scope',
      '',
      'The ISMS as a whole — its policy, risk process, Annex A controls in the statement of',
      'applicability, and the engineering practices that implement them. Financial audit and',
      'clinical quality inspection are separate and are not covered here.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Tika** plans and leads internal reviews. As QA Lead she operates no ISMS control and',
      '  is therefore independent of everything except the measurement pipeline, which is audited',
      '  by Andreas instead.',
      '- **Andreas** audits any area Tika owns.',
      '- **Dhiaz Fathra** is auditee for most areas and may not close his own findings without',
      '  Tika’s verification.',
      '- **Aris Ihwan** receives the report directly, not through the auditee.',
      '',
      '## Procedure',
      '',
      '1. **Plan on a three-year cycle.** Every control in the statement of applicability is',
      '   reviewed at least once in three years; controls rated high criticality, and any area',
      '   with a finding in the previous cycle, are reviewed annually.',
      '2. **Confirm independence in writing** at the start of each engagement. If no internal',
      '   person is independent of the area, the review is bought in.',
      '3. **Audit against evidence, not intent.** Sample records — a real access review, a real',
      '   incident, a real restore rehearsal — rather than accepting a description of the process.',
      '4. **Grade findings consistently.** Major: a control absent or systematically not working.',
      '   Minor: a control working but with lapses. Observation: works today, fragile tomorrow.',
      '5. **Report within 10 working days,** with each finding carrying a clause reference, a',
      '   named owner and an agreed date. The report goes to Aris Ihwan and to the management',
      '   review as an input.',
      '6. **Verify closure.** The auditor confirms the fix with fresh evidence. A finding is never',
      '   closed on the owner’s statement that it has been dealt with.',
      '7. **Commission an external review every two years,** or sooner after a major change to the',
      '   platform architecture or a SEV-1 incident that questioned a control’s design.',
      '',
      '## Records',
      '',
      'The audit plan, review reports and the finding log (`FRM-A-5-35-01`), held in the',
      'compliance repository for five years and presented at each management review.',
      '',
      '## Review',
      '',
      'Annually by Tika with Aris Ihwan, when the following year’s audit plan is set.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-5-36',
    title: 'Compliance Checking Against Security Policies and Standards',
    clause: 'A.5.36',
    crossRefs: ['A.5.35', 'A.5.1', 'A.5.37', 'A.8.8'],
    version: 'v1.3',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-5-36-01', name: 'Compliance check result and exception record' },
    revisions: [
      {
        version: 'v1.2',
        date: '2025-12-03',
        author: 'Agil',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Manual quarterly checklist replaced with automated configuration checks for the parts a machine can see.',
      },
      {
        version: 'v1.3',
        date: '2026-05-27',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Exceptions given a mandatory expiry date and an owner; the standing exception list was three years old in places.',
      },
    ],
    evidence: [
      {
        name: 'compliance-check-2026-q2.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-30',
        expiryDate: '2026-09-30',
        uploader: 'Agil',
        note: 'Q2 automated and manual compliance checks with pass rates and open exceptions.',
        body: [
          '# Compliance check — 2026 Q2',
          '',
          'Check | Method | Scope | Pass | Fail | Exception | Owner',
          'MFA enforced on all Zitadel accounts | Automated, daily | 164 accounts | 164 | 0 | 0 | Dhiaz Fathra',
          'No public S3 buckets | Automated, hourly | 31 buckets | 31 | 0 | 0 | Agil',
          'Disk encryption on managed laptops | MDM report, weekly | 47 devices | 45 | 2 | 2 (new starters, due 2026-07-05) | Agil',
          'Production changes reviewed by a second engineer | Git branch protection | 1,204 merges | 1,198 | 6 | 6 break-glass, all logged | Randy',
          'Dependency scan clean at merge | CI gate | every merge | pass | — | 0 | Andreas',
          'Clinic access review completed this quarter | Manual | 13 locations | 12 | 1 | 1 (Bintaro, due 2026-07-11) | Pak Andre',
          'Supplier security review current | Manual | 9 suppliers | 8 | 1 | 1 (overdue, F-02) | Pak Chen',
          '',
          'Overall 97% of checks passing. Three open items, all with owners and dates inside July.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-5-36 · Compliance Checking Against Security Policies and Standards',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v1.3 · **Review** annually',
      '**Requirement** A.5.36 · **Also satisfies** A.5.35, A.5.1, A.5.37, A.8.8',
      '',
      '## Purpose',
      '',
      'Policies drift out of practice quietly. This procedure checks, on a routine schedule and',
      'mostly without human effort, whether what the documents say is what the systems and the',
      'clinics actually do — and makes any accepted difference an explicit, dated exception',
      'rather than an unnoticed gap.',
      '',
      '## Scope',
      '',
      'All ISMS policies and procedures in this repository, the technical baselines applied to',
      'AWS ap-southeast-1 and to managed devices, and the operational practices of the 13 clinic',
      'locations. The independent audit under ISMS-SOP-A-5-35 is a different activity: this one',
      'is line management checking its own area, continuously.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Dhiaz Fathra** owns the check catalogue and approves exceptions up to 90 days.',
      '- **Agil** implements and maintains the automated checks and their alerting.',
      '- **Pak Andre** performs the clinic-side manual checks each quarter.',
      '- **Pak Chen** confirms supplier reviews are current.',
      '- **Aris Ihwan** approves any exception beyond 90 days or touching patient data.',
      '',
      '## Procedure',
      '',
      '1. **Automate anything a machine can see.** MFA coverage, public storage, encryption at',
      '   rest, branch protection, dependency and secret scanning, and log retention run',
      '   continuously and alert on failure rather than waiting for a quarterly sweep.',
      '2. **Check by hand only what needs judgement** — clinic physical practice, access review',
      '   quality, whether a supplier review actually asked anything. These are quarterly and are',
      '   done by the area’s manager.',
      '3. **Record the result either way.** A passing check is evidence and is kept; only',
      '   recording failures leaves nothing to show an auditor.',
      '4. **A failure is fixed or excepted, never left.** The owner has 5 working days for an',
      '   automated failure and until the end of the quarter for a manual one.',
      '5. **Exceptions have four fields and expire.** What is not being met, why, the',
      '   compensating measure, and an expiry date no more than 90 days out. An expired exception',
      '   reverts to a failure automatically and is escalated to Aris Ihwan.',
      '6. **Repeat failures become nonconformities.** The same check failing in three consecutive',
      '   quarters is raised as a nonconformity under ISO 9001 10.2 — the control is not working',
      '   and patching it again will not help.',
      '7. **Report a single figure quarterly** to the management review: checks passing as a',
      '   percentage, with the open exceptions listed by owner.',
      '',
      '## Records',
      '',
      'Quarterly check results and the exception register (`FRM-A-5-36-01`), in the compliance',
      'repository, retained three years.',
      '',
      '## Review',
      '',
      'Annually by Dhiaz Fathra with Agil, pruning checks that have never failed in two years and',
      'adding checks for controls introduced since.',
    ].join('\n'),
  },
  {
    code: 'ISMS-POL-A-5-37',
    title: 'Documented Operating Procedures Policy',
    clause: 'A.5.37',
    crossRefs: ['9001 7.5.2', 'A.8.25', 'A.5.36'],
    version: 'v1.1',
    owner: 'Andreas',
    form: { code: 'FRM-A-5-37-01', name: 'Operating procedure and runbook index' },
    revisions: [
      {
        version: 'v1.0',
        date: '2025-02-06',
        author: 'Andreas',
        approval: 'Drafted',
        status: 'Superseded',
        note: 'First statement of where runbooks live and who keeps them, written when three competing wikis were in use.',
      },
      {
        version: 'v1.1',
        date: '2026-01-15',
        author: 'Andreas',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Runbooks moved into the service repositories and made reviewable at merge; the wiki was retired.',
      },
    ],
    evidence: [
      {
        name: 'runbook-index-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-01-15',
        expiryDate: '2027-01-15',
        uploader: 'Andreas',
        note: 'Every controlled operating procedure and runbook, with owner, location and last exercise date.',
        body: [
          '# Operating procedure and runbook index — 2026',
          '',
          'Procedure | Location | Owner | Last exercised | Next due',
          'Database restore, tier-1 service | ops/runbooks/restore-postgres.md | Agil | 2026-06-08 | 2026-09-08',
          'NATS consumer wedged | ops/runbooks/nats-consumer.md | Randy | 2026-03-30 (real) | 2026-09-30',
          'Zitadel outage / auth degraded | ops/runbooks/auth-degraded.md | Dhiaz Fathra | 2026-04-18 | 2026-10-18',
          'Release and rollback | ops/runbooks/release.md | Andreas | continuous | —',
          'Clinic connectivity loss, paper fallback | clinic-ops/fallback.md | Pak Andre | 2026-03-21 (drill) | 2027-03-21',
          'Lost or stolen device | ops/runbooks/device-lost.md | Agil | 2026-05-06 (real) | 2026-11-06',
          'Secret rotation, compromised credential | ops/runbooks/rotate-secret.md | Agil | 2026-02-19 | 2026-08-19',
          '',
          'Seven controlled runbooks. All exercised within the last six months, four of them by a',
          'real event rather than a drill.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-A-5-37 · Documented Operating Procedures Policy',
      '',
      '**Owner** Andreas · **Approver** Aris Ihwan · **Version** v1.1 · **Review** annually',
      '**Requirement** A.5.37 · **Also satisfies** ISO 9001 7.5.2, A.8.25, A.5.36',
      '',
      '## Purpose',
      '',
      'The test of an operating procedure is whether the engineer who did not build the system',
      'can run it at 03:00 without waking anyone. This policy sets out which activities must have',
      'a written procedure, where it lives, and how it is kept honest — because a runbook that is',
      'wrong is worse than no runbook, since it is followed.',
      '',
      '## Scope',
      '',
      'Operating procedures for the Eternesia platform, the Super App and marketplace services,',
      'the AWS ap-southeast-1 estate, and the operational activities of clinic reception that',
      'touch group systems. It does not cover clinical procedures, which are controlled by Pak',
      'Andre under the clinic quality system.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Andreas** maintains the index and decides what warrants a controlled procedure.',
      '- **Each named runbook owner** keeps their procedure current and exercises it.',
      '- **Randy** — as the person most often woken by one — raises a correction whenever a',
      '  runbook did not match reality during a real event.',
      '- **Pak Andre** owns clinic-facing procedures and their local printed copies.',
      '',
      '## Policy',
      '',
      '1. **An activity needs a written procedure when** getting it wrong causes data loss,',
      '   exposure or a group-wide outage; when it is performed rarely enough to be forgotten; or',
      '   when it must be performed under pressure by whoever is on call.',
      '2. **Procedures live with the thing they operate** — Markdown in the service repository',
      '   under `ops/runbooks/`, versioned in Git, changed by merge request and reviewed like',
      '   code. There is one index (`FRM-A-5-37-01`) and no second wiki.',
      '3. **Written for the reader at 03:00.** Numbered steps, exact commands, the expected output',
      '   of each step, and a stated stop condition — the point at which the responder escalates',
      '   rather than improvising. Prose explaining the architecture belongs in the ADR, not here.',
      '4. **Every procedure names its owner and its last exercise date.** A procedure not',
      '   exercised — by drill or by a real event — within six months is marked stale in the index',
      '   and is not relied upon in a continuity claim.',
      '5. **A procedure that failed in use is corrected the same week,** by the person who hit the',
      '   problem, while the detail is still fresh. This is the single most common source of',
      '   revisions and is expected, not a criticism of the author.',
      '6. **Clinic procedures also exist on paper** at each location, because a connectivity loss',
      '   is precisely when the online copy is unavailable. Printed copies carry the version and',
      '   are replaced by Pak Andre on change.',
      '7. **Access matches need.** Runbooks are readable by every engineer; those containing',
      '   sensitive detail reference a secret by name rather than embedding it.',
      '',
      '## Records',
      '',
      'The runbook index, the procedures themselves in Git with their full history, and drill',
      'notes. Git history is the retention mechanism; the index is retained three years.',
      '',
      '## Review',
      '',
      'Annually by Andreas, and at every post-incident review where a procedure was found to be',
      'missing or wrong.',
    ].join('\n'),
  },
]
