import type { SeedDocument } from './types'

/** Annex A.5 organisational controls, second half: A.5.7 to A.5.13. */
export const ANNEX_A5_A_2: SeedDocument[] = [
  {
    code: 'ISMS-SOP-A-5-7',
    title: 'Threat Intelligence',
    clause: 'A.5.7',
    crossRefs: ['A.5.6', 'A.8.8', 'A.8.16', 'A.5.24'],
    version: 'v1.2',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-5-7-01', name: 'Threat intelligence triage log' },
    revisions: [
      {
        version: 'v1.1',
        date: '2025-10-07',
        author: 'Randy',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Technical feeds only; nothing covered the phishing and social engineering aimed at clinic reception.',
      },
      {
        version: 'v1.2',
        date: '2026-05-20',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Strategic and operational tiers added; clinic-facing threats routed to Pak Andre; patch SLAs bound to the CVSS band rather than to judgement.',
      },
    ],
    evidence: [
      {
        name: 'threat-intel-triage-log-2026q2.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-30',
        expiryDate: '2026-12-31',
        uploader: 'Randy',
        note: 'Each intelligence item, its assessed relevance to the estate, and what was done.',
        body: [
          'Date | Source | Item | Relevant? | Action | Closed',
          '2026-04-03 | Go announce | net/http request smuggling | yes, all 21 services | toolchain bumped, services rebuilt and deployed | 2026-04-05',
          '2026-04-19 | Gov-CSIRT | phishing campaign impersonating clinic booking confirmations | yes, patient facing | reception briefing, DMARC moved to reject, banner added to booking emails | 2026-04-26',
          '2026-05-02 | AWS bulletin | IMDSv1 deprecation guidance | yes, 4 legacy instances | IMDSv2 enforced by Terraform | 2026-05-08',
          '2026-05-15 | vendor | RCE in an image processing library | no — library not in the dependency tree, verified against the SBOM | dismissed with reason | 2026-05-15',
          '2026-06-11 | OWASP chapter | dependency confusion in private Go modules | partly | GOPRIVATE and checksum DB verified; no change needed | 2026-06-18',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-5-7 · Threat Intelligence',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v1.2 · **Review** half-yearly',
      '**Requirement** A.5.7 · **Also satisfies** A.5.6, A.8.8, A.8.16, A.5.24',
      '',
      '## Purpose',
      '',
      'The group does not buy a threat intelligence platform and does not need one. What it',
      'needs is a habit: someone reads what the vendors and the national CERT publish, decides',
      'in writing whether it touches this estate, and turns the ones that do into work with a',
      'deadline. This procedure is that habit written down, at three levels — strategic,',
      'operational and technical.',
      '',
      '## Scope',
      '',
      'Threats to the Super App, the ERP services in AWS ap-southeast-1, clinic endpoints and',
      'networks, and the people who use them. It covers intelligence intake and triage; the',
      'response to an actual compromise is the incident procedure, and patch delivery is the',
      'vulnerability management routine this procedure feeds.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Dhiaz Fathra** owns the procedure and takes the strategic tier to the quarterly',
      '  management review.',
      '- **Randy** runs technical triage on vendor and language advisories and keeps the log.',
      '- **Agil** owns infrastructure and provider advisories, and applies the fix.',
      '- **Andreas** assesses whether an item changes a design assumption or a threat model.',
      '- **Pak Andre** receives anything aimed at clinic staff and briefs the locations.',
      '',
      '## Procedure',
      '',
      '1. **Intake.** Sources are the ones registered under ISMS-SOP-A-5-6, plus anything a',
      '   colleague forwards. Everything lands in the security channel; nothing is assessed in a',
      '   private inbox.',
      '2. **Relevance.** Within two working days the assigned reader answers one question: does',
      '   this affect something we run? The SBOM and the asset inventory decide it, not memory.',
      '   A "no" is logged with the reason that made it a no.',
      '3. **Grade and schedule.** Relevant technical items take the CVSS band as the deadline —',
      '   critical patched or mitigated within 48 hours, high within 7 days, medium within 30',
      '   days, low at the next maintenance window. Where a fix is not available, a compensating',
      '   mitigation is recorded against the same deadline.',
      '4. **People-facing items** go to Pak Andre the same day with plain-language wording the',
      '   location coordinators can read out in the morning huddle. No CVE numbers in that text.',
      '5. **Strategic tier.** Quarterly, Dhiaz Fathra writes half a page on what changed in the',
      '   landscape for a clinic group and a small engineering team, and whether the risk',
      '   register still reflects it. This is the input that can move a treatment plan.',
      '6. **Feed back.** Anything that turned into an incident, or that should have been caught',
      '   earlier, is named at the half-yearly review of this procedure, with the source that',
      '   would have caught it.',
      '',
      '## Records',
      '',
      'Triage log (FRM-A-5-7-01) in this repository, retained two years. Patch and mitigation',
      'evidence lives on the change ticket referenced by the log row. Strategic notes are held',
      'with the management review pack.',
      '',
      '## Review',
      '',
      'Half-yearly by Dhiaz Fathra with Randy and Agil, measured on two numbers: items triaged',
      'within the two-day window, and critical items fixed within 48 hours.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-5-8',
    title: 'Information Security in Project Management',
    clause: 'A.5.8',
    crossRefs: ['A.8.25', 'A.8.27', 'A.5.9', 'A.8.31'],
    version: 'v1.3',
    owner: 'Andreas',
    form: { code: 'FRM-A-5-8-01', name: 'Project security assessment' },
    revisions: [
      {
        version: 'v1.2',
        date: '2025-06-30',
        author: 'Andreas',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Security review sat at the end of the project, where every finding was too expensive to act on.',
      },
      {
        version: 'v1.3',
        date: '2026-02-03',
        author: 'Andreas',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Assessment moved to kickoff with a lightweight gate at design and pre-launch; a one-page threat model made mandatory for anything touching patient data.',
      },
    ],
    evidence: [
      {
        name: 'project-security-assessment-loyalty-2026.md',
        fileType: 'MD',
        uploadedAt: '2026-03-21',
        expiryDate: '2027-03-21',
        uploader: 'Andreas',
        note: 'Kickoff assessment and threat model for the loyalty and membership project.',
        body: [
          '# Project security assessment — Loyalty and membership',
          '',
          '**Project lead** Wiwin · **Assessor** Andreas · **Kickoff** 21 March 2026',
          '',
          '## What the project handles',
          '',
          'Member identity linked to the existing patient record, point balances, tier status and',
          'redemption at the point of sale in 13 locations. It reads patient identity; it does not',
          'read treatment history.',
          '',
          '## Classification and legal basis',
          '',
          'Member profile is general personal data. The link to a patient record makes the join',
          'itself sensitive, so the loyalty service holds a pseudonymous member id and resolves',
          'identity through the patient service rather than copying names.',
          '',
          '## Threats considered',
          '',
          '| Threat | Decision |',
          '| --- | --- |',
          '| Points inflation through replayed redemption calls | idempotency key per redemption, enforced at the service |',
          '| Staff redeeming against a member who is not present | redemption requires the member OTP or an in-app scan |',
          '| Marketing export pulling treatment history via the member join | loyalty has no read scope on treatment; enforced in Zitadel, tested in CI |',
          '| Balance tampering by direct database write | four-eyes rule under ISMS-POL-A-5-3; balance changes are event-sourced |',
          '',
          '## Gate outcomes',
          '',
          'Design gate passed 2026-04-30 with one condition: the redemption audit trail must carry',
          'the operator identity. Pre-launch gate scheduled before the first location pilot.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-5-8 · Information Security in Project Management',
      '',
      '**Owner** Andreas · **Approver** Aris Ihwan · **Version** v1.3 · **Review** annual',
      '**Requirement** A.5.8 · **Also satisfies** A.8.25, A.8.27, A.5.9, A.8.31',
      '',
      '## Purpose',
      '',
      'Every expensive security problem this group has had was cheap at the design stage and',
      'unaffordable at launch. The previous version of this procedure put the review at the end,',
      'which produced findings nobody could act on without slipping a launch date. Security now',
      'enters at kickoff and is checked twice more, briefly.',
      '',
      '## Scope',
      '',
      'Any project that introduces a new service or vendor, changes how personal data is',
      'collected or shared, opens a new integration or network path, or changes an authorisation',
      'model. It also covers clinic-side projects — a new location, a new device fleet, a new',
      'paper-to-digital process. Routine feature work inside an existing service follows the',
      'merge request review instead.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Andreas** performs the assessment and chairs the gates.',
      '- **The project lead** — Wiwin for commercial projects, Pak Andre for clinic projects —',
      '  books the assessment and owns the resulting actions.',
      '- **Rica** signs off anything involving personal data, including whether a DPIA is needed.',
      '- **Dhiaz Fathra** is the escalation point when a gate condition and a launch date',
      '  conflict, and the only person who can waive a condition.',
      '- **Tika** samples closed projects at internal audit to confirm the gates were real.',
      '',
      '## Procedure',
      '',
      '1. **Kickoff assessment**, before the first line of code or the first vendor contract:',
      '   what information the project handles, its classification, the legal basis if personal',
      '   data, the systems it touches, and a one-page threat model — four to eight threats with',
      '   a decision each. Anything touching patient data must have the threat model; other',
      '   projects may record "none material" with a reason.',
      '2. **Design gate**, before build starts. Andreas confirms the threat decisions are',
      '   actually in the design: the authorisation model, the data flows, retention, logging,',
      '   and where secrets live. Outcome is pass, pass-with-conditions, or rework.',
      '3. **Pre-launch gate**, before the first real user or the first pilot location. Confirms',
      '   the conditions from the design gate are implemented and tested, access roles exist in',
      '   Zitadel, logging reaches the central store, backups cover the new data, and the new',
      '   assets are in the inventory under ISMS-SOP-A-5-9.',
      '4. **Conditions have owners and dates.** An open condition at launch requires a written',
      '   waiver from Dhiaz Fathra naming the risk accepted and a date to close it; the waiver',
      '   goes to the next management review.',
      '5. **Close out.** Within 30 days of launch the project lead confirms the asset inventory,',
      '   the RoPA where applicable, and the runbook are updated. A project is not closed until',
      '   these are done, whatever the delivery status says.',
      '',
      '## Records',
      '',
      'Project security assessments and gate outcomes (FRM-A-5-8-01), held in this repository',
      'against the project, retained three years after launch. Waivers are retained for the life',
      'of the system.',
      '',
      '## Review',
      '',
      'Annually by Andreas, using the internal audit sample: if closed projects show gates that',
      'were passed without conditions or evidence, the gate is theatre and the procedure changes.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-5-9',
    title: 'Inventory of Information and Associated Assets',
    clause: 'A.5.9',
    crossRefs: ['A.5.10', 'A.5.11', 'A.5.12', 'A.5.13'],
    version: 'v2.2',
    owner: 'Agil',
    form: { code: 'FRM-A-5-9-01', name: 'Asset and information inventory' },
    revisions: [
      {
        version: 'v2.1',
        date: '2025-07-22',
        author: 'Agil',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Hardware only, maintained by hand in a spreadsheet that drifted within weeks of each count.',
      },
      {
        version: 'v2.2',
        date: '2026-05-05',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Cloud assets discovered from Terraform state and tags rather than typed in; information assets added alongside hardware; every asset now needs an owner and a classification.',
      },
    ],
    evidence: [
      {
        name: 'asset-inventory-2026-06.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-05',
        expiryDate: '2026-12-05',
        uploader: 'Agil',
        note: 'Extract of the current inventory by asset class, with owner and classification.',
        body: [
          'Class | Count | Owner | Classification | Source of truth | Last reconciled',
          'Clinic workstations | 96 | Pak Andre | Internal | MDM enrolment | 2026-06-01',
          'Clinic tablets (Super App) | 41 | Pak Andre | Internal | MDM enrolment | 2026-06-01',
          'Engineering laptops | 24 | Agil | Confidential | MDM enrolment | 2026-06-01',
          'AWS resources ap-southeast-1 | 312 | Agil | varies by tag | Terraform state | 2026-06-05',
          'SaaS subscriptions | 19 | Pak Chen | varies | procurement register | 2026-05-28',
          'Information asset: patient records | 1 domain | Rica | Specific personal data | data domain register | 2026-05-05',
          'Information asset: pricing and promotions | 1 domain | Wiwin | Confidential (commercial) | data domain register | 2026-05-05',
          'Information asset: payroll | 1 domain | Pak Rila | Confidential | finance system | 2026-05-05',
          'Network equipment (13 sites) | 58 | Agil | Internal | site survey | 2026-04-18',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-5-9 · Inventory of Information and Associated Assets',
      '',
      '**Owner** Agil · **Approver** Aris Ihwan · **Version** v2.2 · **Review** half-yearly',
      '**Requirement** A.5.9 · **Also satisfies** A.5.10, A.5.11, A.5.12, A.5.13',
      '',
      '## Purpose',
      '',
      'Almost every other control in this system depends on knowing what exists. A patch cycle',
      'needs the machine list; a leaver process needs the device that person holds; a',
      'classification scheme needs something to attach to. The inventory that existed before',
      'this version was typed by hand and was wrong within a month, so the rule now is that',
      'anything discoverable is discovered, and only judgement is entered manually.',
      '',
      '## Scope',
      '',
      'Physical devices at head office and all 13 clinic locations, cloud resources in AWS',
      'ap-southeast-1, SaaS subscriptions, and information assets as data domains rather than',
      'as individual files. Personal devices are out of scope: they are not permitted to hold',
      'group information at all, which the acceptable use policy states.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Agil** owns the inventory and the discovery jobs that feed it.',
      '- **Pak Andre** owns clinic devices and confirms the location count.',
      '- **Pak Chen** owns the SaaS subscription list through procurement.',
      '- **Domain stewards** — Rica, Wiwin, Pak Rila, Tika — own their information assets and',
      '  their classification, per the data governance policy.',
      '- **Randy** reconciles the inventory against the access review each quarter.',
      '',
      '## Procedure',
      '',
      '1. **Discover, do not type.** Endpoints come from MDM enrolment, cloud resources from',
      '   Terraform state and resource tags, SaaS from the procurement register. The inventory',
      '   job runs nightly and writes the current picture.',
      '2. **Every asset carries four things**: an owner who is a named person, a classification,',
      '   a location or region, and a lifecycle state (in use, in stock, in repair, retired).',
      '   An asset that appears from discovery with no owner is assigned to the department head',
      '   of the site it sits at, within five working days.',
      '3. **A cloud resource without an owner tag fails the nightly check** and is listed in the',
      '   engineering channel. Untagged resources older than 14 days are candidates for removal',
      '   after Agil confirms with the team that created them.',
      '4. **New assets enter at receipt** — a device at MDM enrolment, a cloud resource at',
      '   apply, a subscription at purchase order. Nothing is added to the estate outside these',
      '   three routes.',
      '5. **Physical count half-yearly.** The location coordinator counts devices at their site',
      '   against the inventory extract; Agil reconciles the differences. A device missing at',
      '   two consecutive counts is treated as lost and raised as an incident.',
      '6. **Retirement** closes the loop with the return-of-assets procedure and the deletion',
      '   certificate: an asset is only marked retired once its data disposal record exists.',
      '',
      '## Records',
      '',
      'The inventory itself (FRM-A-5-9-01) is live; half-yearly extracts and reconciliation',
      'reports are retained three years as the evidence that it was checked, not just kept.',
      '',
      '## Review',
      '',
      'Half-yearly with the physical count, and after any new clinic location opens or closes.',
      'Accuracy is measured as the percentage of counted devices found in the inventory with the',
      'correct owner — below 95% triggers a corrective action.',
    ].join('\n'),
  },
  {
    code: 'ISMS-POL-A-5-10',
    title: 'Acceptable Use of Information and Assets',
    clause: 'A.5.10',
    crossRefs: ['A.5.9', 'A.5.13', 'A.8.1', 'A.6.7'],
    version: 'v2.1',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-5-10-01', name: 'Acceptable use exception request' },
    revisions: [
      {
        version: 'v2.0',
        date: '2025-03-14',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Superseded',
        note: 'Written for office staff; clinic reality — shared rooms, patient photographs, personal phones — was not addressed.',
      },
      {
        version: 'v2.1',
        date: '2026-04-02',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Clinic-specific rules added for treatment room screens and patient photography; exception route created so staff have somewhere to go other than a workaround.',
      },
    ],
    evidence: [
      {
        name: 'acceptable-use-exceptions-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-20',
        expiryDate: '2026-12-20',
        uploader: 'Randy',
        note: 'Requests to work outside the policy, and the decision on each.',
        body: [
          'Date | Requester | Request | Decision | Conditions | Expires',
          '2026-02-06 | Marketing | export patient before/after photos for a campaign | approved in part | only records with marketing consent true; export runs from the patient service, not the clinic device | 2026-08-06',
          '2026-03-18 | Clinic Kelapa Gading | shared reception login during system migration | rejected | named accounts issued within 48 hours instead | —',
          '2026-04-25 | Finance | spreadsheet of payment records on a personal laptop for month end | rejected | remote desktop access provisioned | —',
          '2026-05-30 | Engineering | production data subset on a laptop to reproduce a defect | approved | pseudonymised extract only, deleted within 7 days, deletion confirmed by Agil | 2026-06-06',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-A-5-10 · Acceptable Use of Information and Assets',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v2.1 · **Review** annual',
      '**Requirement** A.5.10 · **Also satisfies** A.5.9, A.5.13, A.8.1, A.6.7',
      '',
      '## Purpose',
      '',
      'This is the policy most staff will actually read, so it is written for them rather than',
      'for an auditor. It says what people may and may not do with group devices, accounts and',
      'information, in the two very different settings the group operates: a clinic treatment',
      'room and an engineering laptop.',
      '',
      '## Scope',
      '',
      'All staff, contractors and interns; all group devices and accounts; and group information',
      'wherever it is held, including on paper. It applies equally on site, at home and while',
      'travelling.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Dhiaz Fathra** owns the policy and decides exception requests jointly with the asset',
      '  owner; **Rica** must agree any exception involving personal data.',
      '- **Pak Andre** enforces the clinic-specific rules through the location coordinators.',
      '- **Randy** logs exception requests and their expiry.',
      '- **Every individual** is responsible for what happens under their account.',
      '',
      '## Policy',
      '',
      '### Accounts and devices',
      '',
      '1. Accounts are personal. Credentials are never shared, never written on a note at',
      '   reception, and never used by a colleague "just for a minute". Shared logins do not',
      '   exist in the estate; where one is found, it is withdrawn within 48 hours.',
      '2. Group information is handled only on group-managed devices. Personal laptops and',
      '   personal cloud storage are not permitted for group information of any classification.',
      '   Personal phones may be used for approved multi-factor authentication and for group',
      '   email in the managed app, and for nothing else.',
      '3. Devices lock automatically after 5 minutes and on badge-out at clinic locations.',
      '   Screens in a treatment room face away from the patient chair and are locked whenever',
      '   the room is left, even for a moment.',
      '',
      '### Information',
      '',
      '4. Patient information leaves a clinic only through the systems built for it. Photographs',
      '   of patients, consent forms or screens are taken with the clinic tablet in the Super',
      '   App, which uploads directly, and never with a personal phone camera.',
      '5. Paper records are put away before the desk is left and are shredded rather than binned.',
      '6. Group information is not posted to a public forum, a support ticket with an external',
      '   vendor, or an AI assistant, without the owner approving it. Where a vendor needs data',
      '   to diagnose a problem, an anonymised extract is prepared by engineering.',
      '',
      '### Reasonable personal use',
      '',
      '7. Occasional personal use of a group device and internet connection is fine, provided it',
      '   is lawful, does not interfere with work, and does not involve installing unmanaged',
      '   software. The group monitors for security purposes and does not read personal content',
      '   for any other reason.',
      '',
      '### Exceptions',
      '',
      '8. If the policy stops you doing your job, request an exception through FRM-A-5-10-01',
      '   rather than working around it. A decision is given within three working days. Every',
      '   approval carries conditions and an expiry date, and none exceed six months.',
      '',
      '## Records',
      '',
      'Exception requests and decisions (FRM-A-5-10-01) retained two years; acknowledgements are',
      'held with the policy framework register.',
      '',
      '## Review',
      '',
      'Annually by Dhiaz Fathra with Pak Andre. A rule that generates repeated exception requests',
      'is the wrong rule and is rewritten rather than re-enforced.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-5-11',
    title: 'Return of Assets on Exit or Role Change',
    clause: 'A.5.11',
    crossRefs: ['A.5.9', 'A.6.5', 'A.5.18', 'A.7.10'],
    version: 'v1.5',
    owner: 'Agil',
    form: { code: 'FRM-A-5-11-01', name: 'Asset return and clearance checklist' },
    revisions: [
      {
        version: 'v1.4',
        date: '2025-01-20',
        author: 'Agil',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Return was chased after the final salary payment, so leverage was gone before the laptop came back.',
      },
      {
        version: 'v1.5',
        date: '2026-03-30',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Clearance tied to the final payroll run; access revocation decoupled from physical return so it happens on the last working day regardless.',
      },
    ],
    evidence: [
      {
        name: 'asset-return-clearance-2026q2.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-07-01',
        expiryDate: '2027-07-01',
        uploader: 'Agil',
        note: 'Leavers in the quarter, what came back, when access was revoked.',
        body: [
          'Leaver | Department | Last day | Access revoked | Assets returned | Wiped | Clearance signed',
          'Therapist, Bintaro | Clinic operations | 2026-04-11 | 2026-04-11 | tablet, badge, locker key | 2026-04-14 | 2026-04-15',
          'Backend contractor | Engineering | 2026-04-30 | 2026-04-30 | laptop, YubiKey | 2026-05-02 | 2026-05-02',
          'Reception, Kemang | Clinic operations | 2026-05-23 | 2026-05-23 | badge; workstation is site-fixed | n/a | 2026-05-26',
          'Finance analyst | Finance | 2026-06-13 | 2026-06-13 | laptop, badge, filing cabinet key | 2026-06-16 | 2026-06-17',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-5-11 · Return of Assets on Exit or Role Change',
      '',
      '**Owner** Agil · **Approver** Aris Ihwan · **Version** v1.5 · **Review** annual',
      '**Requirement** A.5.11 · **Also satisfies** A.5.9, A.6.5, A.5.18, A.7.10',
      '',
      '## Purpose',
      '',
      'A leaver keeps whatever nobody asks for. In the previous version the ask came after the',
      'final payment, by which time a laptop in a leaver’s house was a favour rather than an',
      'obligation. This procedure moves the clearance in front of the final payroll run, and',
      'separates access revocation from physical return so that the slower one cannot delay the',
      'urgent one.',
      '',
      '## Scope',
      '',
      'Employees, contractors and interns leaving the group, and anyone changing role or',
      'location in a way that changes what they should hold. It covers devices, badges, keys,',
      'tokens, credentials, documents and any group information in the person’s possession.',
      '',
      '## Roles and responsibilities',
      '',
      '- **The leaving person’s manager** starts the process and confirms the last working day.',
      '- **HR** withholds clearance from the final payroll run until the checklist is signed.',
      '- **Randy** revokes access; **Agil** receives, wipes and re-stocks the hardware.',
      '- **Pak Andre** handles badges, locker and cabinet keys at clinic locations.',
      '- **Rica** is notified where the leaver held a personal data role.',
      '',
      '## Procedure',
      '',
      '1. **Notify on decision, not on last day.** The manager raises the leaver ticket the same',
      '   working day the resignation or end date is known, listing role, last working day and',
      '   known assets from the inventory.',
      '2. **Revoke on the last working day**, by 18:00, without exception and without waiting for',
      '   hardware: Zitadel account disabled, MFA tokens removed, VPN certificate revoked, SaaS',
      '   seats reclaimed, shared mailbox delegation removed, repository and cloud access',
      '   removed. Randy records the timestamp.',
      '3. **Collect physically** on or before the last working day: laptop or tablet with its',
      '   charger, access badge, locker and cabinet keys, hardware token, any paper records, and',
      '   any personal notes containing group information.',
      '4. **Check the inventory**, not the memory. The checklist is generated from the asset',
      '   inventory so that a device issued three years ago is still asked for.',
      '5. **Wipe and re-stock** within three working days. Devices are wiped through MDM, and',
      '   the wipe confirmation is attached to the checklist. Clinic-fixed workstations are not',
      '   returned; their local profile is removed instead.',
      '6. **Handover of information.** Before the last day the manager confirms that documents,',
      '   ongoing correspondence and any owned records have been transferred to a named',
      '   colleague. Mailboxes are converted to shared and retained 90 days, then deleted.',
      '7. **Sign clearance.** Manager, Agil and HR sign. HR releases the final payroll only on a',
      '   signed clearance; unreturned items are recovered at cost and recorded as an incident',
      '   where they held group information.',
      '8. **Role change** runs the same checklist for the assets and access the previous role',
      '   carried, on the day the new role starts, so that entitlements do not accumulate.',
      '',
      '## Records',
      '',
      'Clearance checklists (FRM-A-5-11-01) retained five years with the HR file; revocation',
      'timestamps retained two years in the access log; wipe confirmations attached to the',
      'checklist.',
      '',
      '## Review',
      '',
      'Annually, and quarterly as a sample within the access review: every leaver in the quarter',
      'is checked for an account still enabled. Any hit is an incident, not a finding to note.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-5-13',
    title: 'Labelling of Information',
    clause: 'A.5.13',
    crossRefs: ['A.5.12', 'A.5.10', 'A.5.14', 'A.8.12'],
    version: 'v1.3',
    owner: 'Rica',
    form: { code: 'FRM-A-5-13-01', name: 'Labelling conformance sample' },
    revisions: [
      {
        version: 'v1.2',
        date: '2025-09-08',
        author: 'Rica',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Four labels with overlapping definitions; staff defaulted everything to Confidential, which made the scheme meaningless.',
      },
      {
        version: 'v1.3',
        date: '2026-06-09',
        author: 'Rica',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Reduced to three labels plus the personal data marker; label now applied automatically at source for exports and reports rather than typed by the author.',
      },
    ],
    evidence: [
      {
        name: 'labelling-conformance-sample-2026-06.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-27',
        expiryDate: '2026-12-27',
        uploader: 'Tika',
        note: 'Sample of 40 documents and exports checked for the correct label at source.',
        body: [
          'Artefact type | Sampled | Correctly labelled | Wrong label | Unlabelled | Note',
          'System-generated reports (ERP) | 12 | 12 | 0 | 0 | label applied by the report template',
          'Data exports from the patient service | 8 | 8 | 0 | 0 | label and watermark applied at export',
          'Author-written documents (Docs) | 10 | 6 | 3 | 1 | three marked Confidential when Internal was correct',
          'Printed clinic paperwork | 6 | 5 | 0 | 1 | one consent form printed from an old template',
          'Email with attachments to suppliers | 4 | 3 | 1 | 0 | one commercial file sent unmarked',
          'Total | 40 | 34 | 4 | 2 | 85% conformance; author-written artefacts are the gap',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-5-13 · Labelling of Information',
      '',
      '**Owner** Rica · **Approver** Aris Ihwan · **Version** v1.3 · **Review** half-yearly',
      '**Requirement** A.5.13 · **Also satisfies** A.5.12, A.5.10, A.5.14, A.8.12',
      '',
      '## Purpose',
      '',
      'A label is only worth applying if it changes how the next person handles the thing. The',
      'earlier scheme had four levels whose definitions overlapped, so everyone chose the safest',
      'one and the label carried no information. This version has three levels, a separate',
      'marker for personal data, and one rule that does most of the work: where the system can',
      'apply the label, the human does not.',
      '',
      '## Scope',
      '',
      'Documents, reports, exports, emails, printed clinic paperwork and removable media that',
      'carry group information. Source code and infrastructure configuration are not labelled',
      'individually; the repository they live in carries the classification.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Rica** owns the scheme and rules on any disputed classification.',
      '- **Domain stewards** set the class for their data domain in the ownership register; every',
      '  artefact derived from a domain inherits that class.',
      '- **Andreas** ensures export and report templates apply the label automatically.',
      '- **Tika** runs the half-yearly conformance sample.',
      '- **Authors** label what they write when no system does it for them.',
      '',
      '## Procedure',
      '',
      '1. **Three labels.** *Public* — cleared for anyone outside the group. *Internal* — the',
      '   default for anything work-related; harmless individually, not for publication.',
      '   *Confidential* — commercial terms, pricing, contracts, payroll, security detail; harm',
      '   follows disclosure. Nothing is unlabelled; an unlabelled artefact is treated as',
      '   Internal until someone corrects it.',
      '2. **A separate marker for personal data.** Anything containing personal data is marked',
      '   *Personal data*, and *Specific personal data* where it includes health information.',
      '   The marker sits alongside the label rather than replacing it, because the handling',
      '   rules come from different places — the label from this scheme, the marker from the PDP',
      '   handling document.',
      '3. **Label at source, automatically.** Report templates, export jobs and the document',
      '   template in the group workspace apply the label in the header and the filename prefix.',
      '   Where a system can apply it, changing it by hand is not permitted.',
      '4. **Where a human labels**, the rule is one line at the top of the document, and the',
      '   label in the filename. Emails put the label in the subject prefix. Printed material',
      '   carries it in the footer of every page.',
      '5. **Removable media** is labelled physically and its contents recorded before it leaves a',
      '   site; Confidential information on removable media requires an exception under the',
      '   acceptable use policy.',
      '6. **Downgrading a label** requires the domain steward’s agreement, recorded on the',
      '   artefact. Upgrading needs no approval and anyone may do it.',
      '7. **Sample half-yearly.** Tika samples 40 artefacts across the types in the conformance',
      '   record. Below 90% correct, the cause is fixed at the template rather than by',
      '   retraining the authors again.',
      '',
      '## Records',
      '',
      'Conformance samples (FRM-A-5-13-01) retained three years. The label of a data domain is',
      'held in the data domain ownership register maintained under DG-POL-001.',
      '',
      '## Review',
      '',
      'Half-yearly by Rica with Tika, using the sample. The scheme changes only when the sample',
      'shows a level people cannot apply consistently — a fourth label will not be added.',
    ].join('\n'),
  },
]
