import type { SeedDocument } from './types'

/** Annex A.6 — people controls: hiring, terms, awareness, discipline, exit, NDAs, remote work, reporting. */
export const ANNEX_A6_PEOPLE: SeedDocument[] = [
  {
    code: 'ISMS-SOP-A-6-1',
    title: 'Pre-Employment Screening',
    clause: 'A.6.1',
    crossRefs: ['A.6.2', 'A.6.6', 'A.5.34'],
    version: 'v2.0',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-6-1-01', name: 'Candidate screening checklist and outcome' },
    revisions: [
      {
        version: 'v1.3',
        date: '2024-09-12',
        author: 'Pak Andre',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Clinic hiring only; engineering hires were screened informally by the hiring manager.',
      },
      {
        version: 'v2.0',
        date: '2025-08-19',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'One screening standard for clinic and engineering; risk tiers introduced so production access forces the higher tier.',
      },
    ],
    evidence: [
      {
        name: 'screening-outcome-register-2025-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-05-04',
        expiryDate: '2027-05-04',
        uploader: 'Pak Andre',
        note: 'Screening outcome per hire; candidate names held in the HR system, this register carries reference numbers only.',
        body: [
          'Reference | Role | Tier | Identity | Qualification | Reference check | Outcome | Closed',
          'SCR-2025-041 | Backend Engineer | 2 | Verified | Verified (degree) | 2 of 2 | Cleared | 2025-09-02',
          'SCR-2025-047 | Aesthetician, Kelapa Gading | 2 | Verified | STR verified with council | 2 of 2 | Cleared | 2025-09-30',
          'SCR-2025-058 | Infrastructure Engineer | 3 | Verified | Verified | 2 of 2 | Cleared with condition — start deferred to reference return | 2025-11-14',
          'SCR-2026-006 | Finance Officer | 3 | Verified | Verified | 1 of 2 | Cleared after director review | 2026-02-11',
          'SCR-2026-019 | QA Engineer (contract) | 2 | Verified | Not applicable | 2 of 2 | Cleared | 2026-04-08',
          'SCR-2026-023 | Front desk, Bandung | 1 | Verified | Not applicable | 1 of 1 | Cleared | 2026-04-27',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-6-1 · Pre-Employment Screening',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v2.0 · **Review** annually',
      '**Requirement** A.6.1 · **Also satisfies** A.6.2, A.6.6, A.5.34',
      '',
      '## Purpose',
      '',
      'Two kinds of people join Dermaster Indonesia: clinic staff who will stand in front of a',
      'patient and see their record, and engineers who will hold credentials to the systems that',
      'hold every patient record. Both need checking before they start, and until 2025 only the',
      'first group actually was. This procedure states one screening standard and makes the',
      'depth of the check follow the access the role carries.',
      '',
      '## Scope',
      '',
      'Every permanent hire, contractor and intern across the clinics and the engineering group.',
      'It covers checks made before a start date. It does not cover the periodic re-verification',
      'of practitioner licences, which clinic operations runs on its own annual cycle, nor',
      'supplier personnel — those are screened by the supplier under the clauses in',
      'ISMS-POL-A-6-6 and the procurement terms.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Pak Andre** runs screening for clinic roles and keeps the outcome register.',
      '- **Dhiaz Fathra** runs screening for engineering roles and sets the tier for any new role.',
      '- **Pak Rila** is consulted for any role with payment or ledger access.',
      '- **Aris Ihwan** is the only person who may clear a candidate whose check came back short.',
      '',
      '## Procedure',
      '',
      '1. The hiring manager assigns a tier when the vacancy is opened, not when the offer is',
      '   made. Tier 1: no system access beyond a mailbox. Tier 2: access to patient or',
      '   commercial data in the Super App or ERP. Tier 3: production infrastructure, finance',
      '   ledgers, or the ability to grant access to others.',
      '2. All tiers: identity verified against KTP or passport, and the right to work confirmed.',
      '3. Tier 2 and 3: qualifications verified at source — a degree with the institution, an STR',
      '   or SIP with the issuing council, never from a photocopy the candidate supplies.',
      '4. Tier 2 and 3: two employment references contacted by telephone, one of which must be a',
      '   direct former supervisor. Tier 1 needs one.',
      '5. Tier 3 additionally: a criminal record letter (SKCK) dated within six months, and a',
      '   declaration of directorships or outside interests that could conflict with the role.',
      '6. Results are recorded on FRM-A-6-1-01 within 5 working days of the last check returning.',
      '7. A candidate may not receive credentials before the checklist is closed. Where the',
      '   business wants a start date first, the start is deferred — an exception is a director',
      '   decision, recorded in the register with the reason.',
      '',
      '## Records',
      '',
      'The checklist and supporting documents live in the HR system with access limited to the',
      'hiring manager, Pak Andre and the director. The outcome register in this repository',
      'carries reference numbers rather than names. Screening records are kept for the duration',
      'of employment plus two years, then destroyed under CBE/ISMS/SOP/19.',
      '',
      '## Review',
      '',
      'Annually by Dhiaz Fathra and Pak Andre, and immediately after any incident where an',
      'employee misused access they should not have been granted.',
    ].join('\n'),
  },
  {
    code: 'ISMS-POL-A-6-2',
    title: 'Information Security in Terms and Conditions of Employment',
    clause: 'A.6.2',
    crossRefs: ['A.6.1', 'A.6.4', 'A.6.6', 'A.5.4'],
    version: 'v1.4',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-6-2-01', name: 'Signed security terms acknowledgement' },
    revisions: [
      {
        version: 'v1.2',
        date: '2024-06-03',
        author: 'Dhiaz Fathra',
        approval: 'Reviewed by Aris Ihwan',
        status: 'Superseded',
        note: 'Security wording lived in an annex nobody signed separately from the main contract.',
      },
      {
        version: 'v1.4',
        date: '2026-01-27',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Acknowledgement made a separate signature; PDP Law duties and post-employment obligations written into the contract body.',
      },
    ],
    evidence: [
      {
        name: 'security-terms-acknowledgement-coverage-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-05-30',
        expiryDate: '2027-05-30',
        uploader: 'Pak Andre',
        note: 'Coverage of the signed acknowledgement by department, checked before the June management review.',
        body: [
          'Department | Headcount | Acknowledged | Outstanding | Oldest outstanding',
          'Clinic operations | 148 | 148 | 0 | —',
          'Engineering | 19 | 19 | 0 | —',
          'Finance | 11 | 11 | 0 | —',
          'Procurement | 6 | 5 | 1 | 2026-04-14 (contractor, chased twice)',
          'Marketing and commercial | 14 | 14 | 0 | —',
          'Total | 198 | 197 | 1 | —',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-A-6-2 · Information Security in Terms and Conditions of Employment',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v1.4 · **Review** annually',
      '**Requirement** A.6.2 · **Also satisfies** A.6.1, A.6.4, A.6.6, A.5.4',
      '',
      '## Purpose',
      '',
      'An obligation that is not in the contract is not enforceable, and an obligation buried in',
      'an unsigned annex is not much better. This policy states what the employment agreement',
      'must say about information security so that the duties an employee carries are ones they',
      'have actually read and signed for.',
      '',
      '## Scope',
      '',
      'The employment agreement of every employee, and the engagement letter of every contractor',
      'and intern. Supplier staff are covered by the supplier contract instead; the clauses there',
      'are the responsibility of Pak Chen.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Dhiaz Fathra** owns the security clause set and any change to its wording.',
      '- **Pak Andre** issues contracts and collects the signed acknowledgement.',
      '- **Rica** approves any wording touching personal data before it is issued.',
      '- **Aris Ihwan** signs on behalf of the company.',
      '',
      '## Policy',
      '',
      '1. Every agreement carries, in the body and not in an annex, the employee’s duty to',
      '   protect information they handle, to follow the ISMS documents that apply to their role,',
      '   and to report anything that looks like a security event.',
      '2. Duties under UU No. 27/2022 (PDP) are stated explicitly for any role that touches',
      '   patient data, including that personal data may be used only for the purpose it was',
      '   collected for.',
      '3. Confidentiality survives the end of employment without time limit for patient data and',
      '   for five years for commercial information. The clause references ISMS-POL-A-6-6.',
      '4. Intellectual property in work produced for the company vests in the company, and',
      '   company code may not be published to a personal repository.',
      '5. The consequences of a breach are named and point at ISMS-SOP-A-6-4 rather than being',
      '   left to interpretation.',
      '6. A separate one-page acknowledgement (FRM-A-6-2-01) is signed on the first working day.',
      '   Signature is a precondition of credential issue — Pak Andre confirms it to the',
      '   engineering group before an account is created.',
      '7. Where the role changes materially — a move into a Tier 3 role under ISMS-SOP-A-6-1 — a',
      '   fresh acknowledgement is signed within 10 working days.',
      '',
      '## Records',
      '',
      'Signed agreements and acknowledgements are held in the HR system for the duration of',
      'employment plus five years. Coverage by department is reported to the management review',
      'each quarter; anything outstanding beyond 30 days is escalated to the director.',
      '',
      '## Review',
      '',
      'Annually, and whenever employment law, the PDP Law implementing regulation, or a change to',
      'the disciplinary process makes the current wording wrong.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-6-3',
    title: 'Security Awareness, Education and Training',
    clause: 'A.6.3',
    crossRefs: ['A.6.8', 'A.5.1', '7.2', 'A.8.7'],
    version: 'v3.0',
    owner: 'Tika',
    form: { code: 'FRM-A-6-3-01', name: 'Training attendance and competence record' },
    revisions: [
      {
        version: 'v2.2',
        date: '2024-11-05',
        author: 'Tika',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'One annual slide deck for everyone; no measure of whether anything was retained.',
      },
      {
        version: 'v3.0',
        date: '2026-03-16',
        author: 'Tika',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Split into three role tracks, phishing simulation added quarterly, competence measured rather than assumed.',
      },
    ],
    evidence: [
      {
        name: 'awareness-programme-results-h1-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-05',
        expiryDate: '2027-06-05',
        uploader: 'Tika',
        note: 'Completion, assessment pass rate and phishing simulation results for the first half of 2026.',
        body: [
          'Track | Audience | Due | Completed | Pass rate | Phishing click rate',
          'Core awareness | All staff (198) | 2026-03-31 | 191 | 94% | 6.1% (Q1) / 3.4% (Q2)',
          'Patient data handling | Clinic and front desk (152) | 2026-04-30 | 149 | 91% | —',
          'Secure engineering | Engineering (19) | 2026-05-31 | 19 | 100% | 0% (Q1) / 0% (Q2)',
          'Incident first response | On-call and department heads (14) | 2026-05-31 | 14 | 100% | —',
        ].join('\n'),
      },
      {
        name: 'phishing-simulation-q2-2026-debrief.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-06-12',
        uploader: 'Dhiaz Fathra',
        note: 'Debrief on the Q2 simulation, presented to department heads.',
        body: [
          '# Phishing simulation debrief — Q2 2026',
          '',
          '**Run** 2026-05-21 · **Population** 198 · **Pretext** an invoice approval request that',
          'appeared to come from the finance shared mailbox.',
          '',
          '## Result',
          '',
          '- 3.4% clicked the link (7 people), down from 6.1% in Q1.',
          '- 2 of the 7 entered credentials on the landing page. Both were front-desk staff at',
          '  locations that had not yet completed the patient data track.',
          '- 41 people reported the message. First report arrived 4 minutes after send, which is',
          '  the number worth watching: the control is reporting speed, not click rate.',
          '',
          '## Actions',
          '',
          '1. Both credential entries were walked through individually by Pak Andre the same week.',
          '   No disciplinary action — the point of a simulation is learning, per ISMS-SOP-A-6-4.',
          '2. The two locations were scheduled into the June session of the patient data track.',
          '3. The next simulation will use an internal-looking pretext rather than an external one,',
          '   because the external cues made this one easier than a real attempt would be.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-6-3 · Security Awareness, Education and Training',
      '',
      '**Owner** Tika · **Approver** Aris Ihwan · **Version** v3.0 · **Review** annually',
      '**Requirement** A.6.3 · **Also satisfies** A.6.8, A.5.1, ISO 9001 7.2, A.8.7',
      '',
      '## Purpose',
      '',
      'Most of what actually protects patient data at Dermaster is a person deciding not to click,',
      'not to share a login, not to photograph a screen. Training exists to make that decision',
      'easy and to give the organisation evidence that people are competent, not merely that they',
      'sat through a deck.',
      '',
      '## Scope',
      '',
      'All employees, contractors and interns from their first week onward. Patient-facing',
      'clinical technique training is out of scope — that is run by clinic operations against its',
      'own competence matrix.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Tika** runs the programme, keeps the attendance records and reports the numbers.',
      '- **Dhiaz Fathra** writes the secure engineering track and reviews the simulation pretexts.',
      '- **Rica** writes and delivers the patient data handling track.',
      '- **Pak Andre**, **Pak Chen** and **Pak Rila** are accountable for completion in their',
      '  departments; a completion below 90% is theirs to explain at the management review.',
      '',
      '## Procedure',
      '',
      '1. **Induction.** Within the first 5 working days, a new joiner completes the core',
      '   awareness module and, for Tier 2 and 3 roles, the track for their role.',
      '2. **Annual refresh.** The core track runs every 12 months, opening 1 February with a due',
      '   date of 31 March. Role tracks run to 31 May.',
      '3. **Tracks.** Core awareness — passwords, MFA, phishing, clean desk, reporting. Patient',
      '   data handling — lawful basis, consent purpose, what may leave the clinic. Secure',
      '   engineering — secrets handling, dependency and image provenance, code review for',
      '   security, production access discipline. Incident first response — the first 30 minutes.',
      '4. **Assessment.** Each track ends in a short assessment; the pass mark is 80%. A failure',
      '   is retaken within 10 working days with a walkthrough rather than a resit alone.',
      '5. **Phishing simulation.** Quarterly, across the whole population. The measure that',
      '   matters is time to first report; click rate is secondary and is never used to identify',
      '   or discipline an individual.',
      '6. **Event-driven training.** After an incident or a repeated finding, Tika schedules a',
      '   targeted session within 20 working days rather than waiting for the annual cycle.',
      '',
      '## Records',
      '',
      'Attendance, assessment scores and simulation results are held on FRM-A-6-3-01 and',
      'summarised into the measurement workbook. Individual results are visible to the person and',
      'their department head only. Records are kept for three years.',
      '',
      '## Review',
      '',
      'Annually by Tika, with the content of each track reviewed by its author. Programme',
      'effectiveness — pass rates, reporting speed, repeat incidents — is a standing input to the',
      'quarterly management review.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-6-4',
    title: 'Disciplinary Process for Information Security Breaches',
    clause: 'A.6.4',
    crossRefs: ['A.6.2', 'A.5.28', 'A.6.8'],
    version: 'v1.2',
    owner: 'Pak Andre',
    form: { code: 'FRM-A-6-4-01', name: 'Disciplinary case record and outcome' },
    revisions: [
      {
        version: 'v1.0',
        date: '2024-04-22',
        author: 'Pak Andre',
        approval: 'Drafted',
        status: 'Superseded',
        note: 'General HR disciplinary process with no distinct handling for security breaches.',
      },
      {
        version: 'v1.2',
        date: '2025-10-08',
        author: 'Pak Andre',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Severity bands added, evidence handling tied to the incident process, and a stated no-blame carve-out for honest reporting.',
      },
    ],
    evidence: [
      {
        name: 'disciplinary-panel-minute-2026-02.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-02-20',
        uploader: 'Aris Ihwan',
        note: 'Signed panel minute for the only formal security case opened in 2026 to date; names redacted in the controlled copy.',
        body: [
          '# Disciplinary panel minute — case DP-2026-01',
          '',
          '**Date** 2026-02-18 · **Panel** Aris Ihwan (chair), Pak Andre, Dhiaz Fathra',
          '**Employee** reference withheld · **Representation** colleague present throughout',
          '',
          '## Matter considered',
          '',
          'A shared clinic workstation login was used to view patient records at a location the',
          'employee did not work at, on three dates in January 2026. Discovered through the',
          'monthly access log review, not through a report.',
          '',
          '## Findings',
          '',
          '1. The account sharing was established and admitted. The records viewed belonged to a',
          '   family member of the employee.',
          '2. No data left the premises; no export or print was found in the logs.',
          '3. The employee had completed the patient data handling track in 2025 and understood',
          '   that curiosity access was not permitted.',
          '',
          '## Outcome',
          '',
          'Written warning held on file for 12 months, and repeat of the patient data handling',
          'track within 30 days. Not dismissal: the access was not concealed once asked about, no',
          'data was disclosed onward, and the shared login was itself a control failure the',
          'organisation owns. That failure is tracked as a corrective action against the location',
          'to remove shared workstation accounts by 31 March 2026.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-6-4 · Disciplinary Process for Information Security Breaches',
      '',
      '**Owner** Pak Andre · **Approver** Aris Ihwan · **Version** v1.2 · **Review** every two years',
      '**Requirement** A.6.4 · **Also satisfies** A.6.2, A.5.28, A.6.8',
      '',
      '## Purpose',
      '',
      'A disciplinary process is a control only if people can predict it. This procedure sets out',
      'how Dermaster Indonesia responds when someone breaks an information security rule — so',
      'that the response is consistent between the clinics and the engineering group, and so that',
      'nobody stays quiet about a mistake because they cannot guess what will happen to them.',
      '',
      '## Scope',
      '',
      'Breaches of the ISMS by employees, contractors and interns. It does not replace the',
      'general HR disciplinary process for conduct unrelated to information security, and it does',
      'not govern supplier personnel — a supplier breach is handled contractually by Pak Chen.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Pak Andre** owns the process and convenes the panel.',
      '- **Dhiaz Fathra** establishes the technical facts and hands over the incident record.',
      '- **Aris Ihwan** chairs any panel that could end in dismissal and is the appeal authority',
      '  only where he did not chair — otherwise the appeal goes to an external adviser.',
      '- **Rica** is consulted where the breach involved personal data and a regulator may need',
      '  to be told.',
      '',
      '## Procedure',
      '',
      '1. The security incident is handled first, under the incident process. Containment is',
      '   never delayed to establish blame.',
      '2. Pak Andre opens a case on FRM-A-6-4-01 within 5 working days of the incident record',
      '   being closed for facts.',
      '3. Facts are gathered from the incident record, access logs and interviews. Log extracts',
      '   are exported by Dhiaz Fathra with the query and time range noted, so the same extract',
      '   can be reproduced later.',
      '4. The employee is told in writing what is alleged, is given the evidence at least 3',
      '   working days before the meeting, and may bring a colleague.',
      '5. The panel places the matter in a band. **Minor** — a mistake despite reasonable care;',
      '   coaching and a note, no formal record. **Serious** — a knowing breach of a rule the',
      '   person was trained on; written warning. **Gross** — deliberate misuse or disclosure of',
      '   patient data, deliberate evasion of a control, or concealment; up to dismissal, and',
      '   reported to the authorities where the law requires it.',
      '6. The band takes account of whether the person reported it themselves. Honest self-',
      '   reporting of one’s own mistake is never treated as gross, and this is stated to staff',
      '   in the awareness programme — under-reporting costs more than any single mistake.',
      '7. Where the breach was possible because a control was weak, a corrective action is raised',
      '   against the control at the same time. Discipline never substitutes for the fix.',
      '8. The outcome is issued in writing within 10 working days of the meeting, with the appeal',
      '   route stated.',
      '',
      '## Records',
      '',
      'Case records are held in the HR system, restricted to Pak Andre and the director, and kept',
      'for the duration of employment plus two years. A count of cases by band, with no names, is',
      'reported to the management review.',
      '',
      '## Review',
      '',
      'Every two years, and after any case where the process itself was contested.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-6-5',
    title: 'Responsibilities on Termination or Change of Employment',
    clause: 'A.6.5',
    crossRefs: ['A.5.18', 'A.6.6', 'A.7.9', 'A.5.11'],
    version: 'v2.2',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-6-5-01', name: 'Leaver and role-change offboarding checklist' },
    revisions: [
      {
        version: 'v2.0',
        date: '2025-02-13',
        author: 'Agil',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Covered leavers only; internal transfers kept the access from their old role indefinitely.',
      },
      {
        version: 'v2.2',
        date: '2026-04-09',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Role changes brought in scope with a 5-day revocation deadline; same-day Zitadel disable made the single hard gate for leavers.',
      },
    ],
    evidence: [
      {
        name: 'offboarding-completion-register-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-01',
        expiryDate: '2027-06-01',
        uploader: 'Agil',
        note: 'Every leaver and role change in 2026 to date, with the time from last day to full revocation.',
        body: [
          'Reference | Type | Last day / effective | Zitadel disabled | Assets returned | All access closed | Days',
          'OFF-2026-02 | Leaver, clinic | 2026-01-31 | 2026-01-31 | 2026-01-31 | 2026-02-03 | 3',
          'OFF-2026-05 | Leaver, engineering | 2026-02-27 | 2026-02-27 | 2026-02-27 | 2026-03-02 | 3',
          'OFF-2026-07 | Role change, finance to procurement | 2026-03-16 | n/a | n/a | 2026-03-20 | 4',
          'OFF-2026-09 | Leaver, contractor | 2026-04-10 | 2026-04-10 | 2026-04-10 | 2026-04-10 | 0',
          'OFF-2026-11 | Role change, QA to engineering | 2026-05-04 | n/a | n/a | 2026-05-13 | 9 — breach, cause: no ticket raised until the manager chased',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-6-5 · Responsibilities on Termination or Change of Employment',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v2.2 · **Review** annually',
      '**Requirement** A.6.5 · **Also satisfies** A.5.18, A.6.6, A.7.9, A.5.11',
      '',
      '## Purpose',
      '',
      'The riskiest account in any organisation belongs to someone who left last month and to',
      'someone who moved department last year. This procedure closes both: it says what happens',
      'on the last day, what survives it, and what has to change when a person stays but their',
      'job does not.',
      '',
      '## Scope',
      '',
      'Resignation, dismissal, end of contract, retirement, internal transfer and secondment,',
      'for employees, contractors and interns. Supplier account closure is out of scope and sits',
      'with Pak Chen under the supplier procedure.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Pak Andre** raises the offboarding ticket the day notice is received or a transfer is',
      '  agreed, and runs the exit conversation.',
      '- **Agil** revokes system access and recovers hardware.',
      '- **Dhiaz Fathra** confirms revocation is complete and signs the checklist closed.',
      '- The **receiving department head** confirms what access the new role actually needs.',
      '',
      '## Procedure',
      '',
      '1. Pak Andre opens FRM-A-6-5-01 on the day notice is given, listing the person’s systems,',
      '   physical keys, devices and any external account held in the company’s name.',
      '2. **On the last working day**, Agil disables the Zitadel identity. Everything downstream',
      '   depends on it, so this is the one step that may not slip by even a day.',
      '3. Within 3 working days: standalone accounts that do not federate through Zitadel are',
      '   closed one by one — cloud console break-glass users, the payment gateway portal, the',
      '   registrar, supplier portals, social media. The list is taken from the access register',
      '   and not from memory.',
      '4. Devices, access cards, clinic keys and any hardware token are returned and logged. A',
      '   device is wiped and re-imaged before reissue; a lost item is raised as an incident.',
      '5. Shared credentials the person knew are rotated within 5 working days. Any credential',
      '   that cannot be rotated is a finding against the system that requires it.',
      '6. The exit conversation restates the obligations that survive employment — confidentiality',
      '   without time limit for patient data, five years for commercial information, and the',
      '   return or destruction of any company information held personally. The employee signs',
      '   the acknowledgement on the checklist.',
      '7. **Role change.** Access for the old role is removed within 5 working days of the',
      '   effective date. Access is granted for the new role only after the receiving head',
      '   approves it. Access is never simply added on top of what the person already had.',
      '8. Mailbox and file access are delegated to the manager for 90 days, then removed; the',
      '   account is deleted after 12 months unless a legal hold applies.',
      '',
      '## Records',
      '',
      'Completed checklists are held with the HR file for employment plus two years. The',
      'completion register in this repository records the elapsed days from last day to full',
      'revocation; anything over 5 days is reported to the management review with its cause.',
      '',
      '## Review',
      '',
      'Annually, and after any access review that finds an account belonging to a leaver.',
    ].join('\n'),
  },
  {
    code: 'ISMS-POL-A-6-6',
    title: 'Confidentiality and Non-Disclosure Agreements',
    clause: 'A.6.6',
    crossRefs: ['A.6.2', 'A.5.34', 'A.5.20', 'A.6.5'],
    version: 'v1.3',
    owner: 'Pak Chen',
    form: { code: 'FRM-A-6-6-01', name: 'Non-disclosure agreement register' },
    revisions: [
      {
        version: 'v1.1',
        date: '2024-08-30',
        author: 'Pak Chen',
        approval: 'Reviewed by Aris Ihwan',
        status: 'Superseded',
        note: 'Each supplier negotiated its own confidentiality wording; no central register of what had been signed.',
      },
      {
        version: 'v1.3',
        date: '2026-02-05',
        author: 'Pak Chen',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Standard NDA adopted for suppliers and visitors, patient data carved out as perpetual, and a review trigger set on the register.',
      },
    ],
    evidence: [
      {
        name: 'nda-register-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-05-22',
        expiryDate: '2027-05-22',
        uploader: 'Pak Chen',
        note: 'Live register of confidentiality agreements with third parties, reviewed each quarter.',
        body: [
          'Counterparty | Type | Signed | Term | Patient data in scope | Next review',
          'Cloud hosting provider | Supplier, mutual | 2025-03-11 | 5 years post-termination | Yes — processor terms attached | 2026-09-30',
          'Payment gateway | Supplier, mutual | 2025-06-02 | 5 years | No | 2026-09-30',
          'Aesthetic device vendor | Supplier, one-way | 2025-09-18 | 3 years | No | 2026-09-30',
          'Marketing agency | Supplier, one-way | 2026-01-20 | 3 years | Yes — campaign lists only | 2026-09-30',
          'External auditor | Professional, mutual | 2026-02-27 | perpetual for patient data | Yes | 2027-02-27',
          'Candidate CTO (recruitment) | Individual | 2026-04-03 | 2 years | No | closed 2026-05-15',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-A-6-6 · Confidentiality and Non-Disclosure Agreements',
      '',
      '**Owner** Pak Chen · **Approver** Aris Ihwan · **Version** v1.3 · **Review** annually',
      '**Requirement** A.6.6 · **Also satisfies** A.6.2, A.5.34, A.5.20, A.6.5',
      '',
      '## Purpose',
      '',
      'Information leaves this organisation legitimately every week — to an auditor, a device',
      'vendor, an agency preparing a campaign, a candidate seeing the architecture during an',
      'interview. This policy states when a confidentiality agreement is required before that',
      'happens, what it must say, and where the signed copy is recorded.',
      '',
      '## Scope',
      '',
      'Agreements with suppliers, professional advisers, prospective partners, individual',
      'contractors and visitors. Employee confidentiality is inside the employment contract',
      'under ISMS-POL-A-6-2 and is not re-papered here.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Pak Chen** owns the standard templates and the register, and signs supplier NDAs.',
      '- **Rica** must review any agreement where personal data will be disclosed, before signing.',
      '- **Dhiaz Fathra** approves the technical scope where source code or architecture is',
      '  disclosed.',
      '- **Aris Ihwan** signs anything that departs from the standard template.',
      '',
      '## Policy',
      '',
      '1. No confidential information is disclosed to a third party before an agreement is signed.',
      '   A meeting brought forward is not a reason to disclose first and paper it later.',
      '2. Two templates exist: a mutual agreement for suppliers and partners, and a one-way',
      '   agreement for parties receiving only. Both name the information covered by class rather',
      '   than by listing documents.',
      '3. Every agreement states: what is confidential, permitted purpose, permitted recipients,',
      '   the duty to return or destroy on request, the obligation to notify us of any',
      '   unauthorised disclosure within 72 hours, and the governing law of Indonesia.',
      '4. **Patient data is perpetual.** Obligations over patient or health information do not',
      '   expire. Commercial information is protected for five years after the relationship ends,',
      '   technical and architectural information for three.',
      '5. Where the counterparty will process personal data on our behalf, the NDA is not enough:',
      '   processor terms under UU No. 27/2022 are attached, reviewed by Rica.',
      '6. Departures from the template are permitted only with the director’s signature and are',
      '   flagged in the register so the weaker term is visible at renewal.',
      '7. Visitors to a clinic treatment area or to the engineering floor sign the short-form',
      '   visitor undertaking at reception; this is separate from the badge log.',
      '',
      '## Records',
      '',
      'Signed agreements are held by procurement; the register on FRM-A-6-6-01 carries',
      'counterparty, type, signature date, term, whether patient data is in scope, and the next',
      'review date. Signed copies are kept for the term plus six years.',
      '',
      '## Review',
      '',
      'The register is reviewed quarterly by Pak Chen. The templates are reviewed annually, and',
      'reissued whenever a supplier incident shows a clause that did not hold.',
    ].join('\n'),
  },
  {
    code: 'ISMS-POL-A-6-7',
    title: 'Remote and Hybrid Working',
    clause: 'A.6.7',
    crossRefs: ['A.8.1', 'A.7.9', 'A.5.14', 'A.8.5'],
    version: 'v2.1',
    owner: 'Agil',
    form: { code: 'FRM-A-6-7-01', name: 'Remote working authorisation and device attestation' },
    revisions: [
      {
        version: 'v2.0',
        date: '2025-05-26',
        author: 'Agil',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Pandemic-era policy carried forward; allowed personal laptops for engineering with no baseline.',
      },
      {
        version: 'v2.1',
        date: '2026-05-11',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Managed device baseline made mandatory for production access; personal devices limited to mail and chat.',
      },
    ],
    evidence: [
      {
        name: 'remote-device-baseline-attestation-2026-q2.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-18',
        expiryDate: '2026-12-18',
        uploader: 'Agil',
        note: 'Quarterly attestation of the device baseline for everyone authorised to work remotely.',
        body: [
          'Device | Holder role | Disk encrypted | OS current | Screen lock ≤5 min | Backup within 7 days | Production access | Result',
          'ENG-LT-004 | Backend Engineer | Yes | Yes | Yes | Yes | Yes | Pass',
          'ENG-LT-007 | Infrastructure Engineer | Yes | Yes | Yes | Yes | Yes | Pass',
          'ENG-LT-011 | QA Lead | Yes | Yes | Yes | No — last backup 19 days | No | Fail, remediated 2026-06-20',
          'ENG-LT-013 | Solutions Architect | Yes | Yes | Yes | Yes | Yes | Pass',
          'FIN-LT-002 | Finance Officer | Yes | No — two versions behind | Yes | Yes | No | Fail, patched 2026-06-19',
          'CMR-LT-001 | Commercial | Yes | Yes | Yes | Yes | No | Pass',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-A-6-7 · Remote and Hybrid Working',
      '',
      '**Owner** Agil · **Approver** Aris Ihwan · **Version** v2.1 · **Review** annually',
      '**Requirement** A.6.7 · **Also satisfies** A.8.1, A.7.9, A.5.14, A.8.5',
      '',
      '## Purpose',
      '',
      'The engineering group works two days a week away from the office, and finance and',
      'commercial staff work from home occasionally. The controls that hold inside a clinic —',
      'a locked room, a supervised screen, a network we run — are absent at a kitchen table.',
      'This policy says what replaces them.',
      '',
      '## Scope',
      '',
      'Any work on company information away from a Dermaster clinic or office, including from',
      'home, while travelling and from a co-working space. It does not cover clinical work, which',
      'never happens remotely, and it does not authorise cross-border working — that needs the',
      'director’s written approval because of data residency.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Agil** maintains the device baseline, runs the quarterly attestation and issues',
      '  managed laptops.',
      '- **Dhiaz Fathra** authorises remote production access, individually and in writing.',
      '- Department heads authorise remote working for their staff on FRM-A-6-7-01.',
      '- The **individual** is responsible for the physical security of the device and of what is',
      '  visible on its screen.',
      '',
      '## Policy',
      '',
      '1. Remote working is authorised per person, not assumed by role. The authorisation records',
      '   the device, the information classes the person will handle, and any limit on location.',
      '2. **Device baseline.** Full-disk encryption on; operating system within one minor version',
      '   of current; automatic screen lock at 5 minutes; endpoint protection running; backup',
      '   within the last 7 days. Attested quarterly; a failure suspends remote authorisation',
      '   until remediated.',
      '3. **Production and patient data only from a managed laptop.** Personal devices may reach',
      '   mail and chat through the browser with MFA and no local sync, and nothing else.',
      '4. Access to internal systems is over the company VPN or through Zitadel with MFA. Public',
      '   or hotel Wi-Fi is permitted only with the VPN established first; no exceptions for a',
      '   quick check.',
      '5. Patient data is not printed, photographed or displayed where a person outside the',
      '   company can see it. Working on patient records in a café is not permitted, regardless',
      '   of the device.',
      '6. Company information is not stored in personal cloud accounts or sent to a personal',
      '   mailbox, including "so I can look at it later".',
      '7. A lost or stolen device is reported within 1 hour under ISMS-SOP-A-6-8, at any hour.',
      '   Agil issues a remote wipe and the credentials on the device are rotated the same day.',
      '8. Home network guidance — change the router default password, keep its firmware current —',
      '   is issued with the device but is advisory; the controls the company relies on sit on',
      '   the device and in the identity provider, not on the home network.',
      '',
      '## Records',
      '',
      'Authorisations and quarterly attestations are held on FRM-A-6-7-01 in this repository.',
      'Attestation results and remediation times are reported to the management review. Records',
      'are kept for three years.',
      '',
      '## Review',
      '',
      'Annually by Agil with Dhiaz Fathra, and whenever the working pattern changes materially or',
      'a device-related incident occurs.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-6-8',
    title: 'Reporting Information Security Events',
    clause: 'A.6.8',
    crossRefs: ['A.5.24', 'A.5.25', 'A.6.3', 'A.5.26'],
    version: 'v2.3',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-6-8-01', name: 'Security event report and triage log' },
    revisions: [
      {
        version: 'v2.1',
        date: '2025-01-30',
        author: 'Randy',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Reporting went to a personal mailbox; out-of-hours reports waited until morning.',
      },
      {
        version: 'v2.3',
        date: '2026-06-01',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Single reporting channel with an on-call rotation, 1-hour acknowledgement target, and explicit no-blame statement for reporters.',
      },
    ],
    evidence: [
      {
        name: 'security-event-triage-log-2026-h1.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-30',
        expiryDate: '2027-06-30',
        uploader: 'Randy',
        note: 'Every event reported in the first half of 2026 with acknowledgement time and disposition.',
        body: [
          'Ref | Reported | Channel | Reporter type | Acknowledged | Category | Disposition',
          'EV-2026-014 | 2026-02-03 09:12 | Hotline | Front desk | 11 min | Suspicious email | Phishing confirmed, blocked at gateway',
          'EV-2026-021 | 2026-02-18 14:40 | Access log review | Automated | 4 min | Unauthorised record access | Escalated to incident and DP-2026-01',
          'EV-2026-033 | 2026-03-22 21:05 | Hotline | Engineer | 8 min | Exposed credential in a commit | Rotated within 40 min, no external use found',
          'EV-2026-047 | 2026-04-15 08:30 | Email | Clinic manager | 52 min | Lost access card | Card voided, no incident',
          'EV-2026-052 | 2026-05-09 16:22 | Hotline | Finance | 6 min | Payment request from a spoofed sender | Not paid, reported to the bank',
          'EV-2026-061 | 2026-06-11 10:03 | Hotline | Supplier contact | 19 min | Their subprocessor breach notice | Assessed, no Dermaster data in scope',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-6-8 · Reporting Information Security Events',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v2.3 · **Review** annually',
      '**Requirement** A.6.8 · **Also satisfies** A.5.24, A.5.25, A.6.3, A.5.26',
      '',
      '## Purpose',
      '',
      'Almost every incident this organisation has handled well started with someone saying',
      'something early. This procedure makes reporting the easiest thing a person can do when',
      'something looks wrong: one channel, one number, no judgement call about whether it is',
      '"really" a security matter.',
      '',
      '## Scope',
      '',
      'Anything observed by staff, contractors, suppliers or patients that could affect the',
      'confidentiality, integrity or availability of information — including things that turn out',
      'to be nothing. This procedure covers reporting and triage only; what happens after an event',
      'is classified as an incident is governed by the incident management procedure.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Anyone** who observes something reports it. There is no filtering step before',
      '  reporting.',
      '- **Randy** holds the on-call rotation and acknowledges and triages reports.',
      '- **Dhiaz Fathra** decides whether an event becomes an incident, and is the escalation',
      '  point out of hours.',
      '- **Rica** is notified within 2 hours of any event that may involve personal data, because',
      '  the PDP Law notification clock is short.',
      '',
      '## Procedure',
      '',
      '1. **Report immediately.** Call or message the security hotline, staffed by the on-call',
      '   engineer at all hours. Email is accepted but is checked in working hours only, so it is',
      '   not the channel for anything urgent.',
      '2. Say what you saw, when, on which system or at which location, and what you have already',
      '   done. An incomplete report now beats a complete one tomorrow.',
      '3. Do not investigate yourself. Do not delete the message, log out of the session, or wipe',
      '   the device — evidence is easy to destroy accidentally.',
      '4. The on-call engineer acknowledges within **1 hour** and opens FRM-A-6-8-01 with a',
      '   reference number, giving it back to the reporter.',
      '5. Triage within 4 working hours places the event in one of four categories: false alarm,',
      '   weakness (no event occurred, but a control is soft), event handled at first line, or',
      '   incident. Only Dhiaz Fathra may set the last.',
      '6. Anything touching patient data goes to Rica in parallel with triage, not after it.',
      '7. The reporter is told the outcome, including when it was a false alarm. A person who',
      '   never hears back stops reporting.',
      '8. **Reporting in good faith is never disciplined**, including where the reporter caused',
      '   the problem. This is stated in the awareness programme and honoured in',
      '   ISMS-SOP-A-6-4.',
      '',
      '## Records',
      '',
      'The triage log holds every report with its acknowledgement time, category and disposition,',
      'and is kept for three years. Volume, acknowledgement time and the share of reports coming',
      'from people rather than automated monitoring are reported to the quarterly management',
      'review — a falling human report count is treated as a warning sign, not a success.',
      '',
      '## Review',
      '',
      'Annually by Dhiaz Fathra with Randy, and after any incident that was visible to someone',
      'before it was reported.',
    ].join('\n'),
  },
]
