import type { SeedDocument } from './types'

/** Annex A.5 batch B, part 1: information transfer, access control and identity (A.5.14–A.5.19). */
export const ANNEX_A5_B_1: SeedDocument[] = [
  {
    code: 'ISMS-SOP-A-5-14',
    title: 'Information Transfer Procedure',
    clause: 'A.5.14',
    crossRefs: ['A.5.10', 'A.5.34', 'A.8.24'],
    version: 'v2.0',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-5-14-01', name: 'Approved transfer channel register' },
    revisions: [
      {
        version: 'v1.3',
        date: '2024-09-12',
        author: 'Andreas',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Written when clinic photographs were still being sent to the doctor group over consumer WhatsApp.',
      },
      {
        version: 'v2.0',
        date: '2026-01-27',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Consumer messaging withdrawn for clinical content; the in-app case thread became the only approved channel for before/after images.',
      },
    ],
    evidence: [
      {
        name: 'approved-transfer-channels-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-01-27',
        expiryDate: '2027-01-27',
        uploader: 'Andreas',
        note: 'The channel register referenced by step 2 of the procedure.',
        body: [
          'Channel | Permitted content | Prohibited content | Encryption | Owner',
          'Super App case thread | Clinical notes, before/after images, referrals | — | TLS 1.3 in transit, AES-256 at rest | Randy',
          'Corporate e-mail (Google Workspace) | Internal, general personal data | Specific personal data, credentials | TLS with MTA-STS enforced | Agil',
          'SFTP drop to insurer | Claim files, agreed schema only | Free-text clinical notes | SSH key pair, keys rotated yearly | Agil',
          'WhatsApp Business | Appointment reminders, marketing with consent | Any clinical content, any image of a patient | Vendor transport only | Wiwin',
          'Physical courier (sealed pouch) | Signed consent forms between clinics | Anything reproducible digitally | Tamper-evident seal, signed manifest | Pak Andre',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-5-14 · Information Transfer Procedure',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v2.0 · **Review** annually',
      '**Requirement** A.5.14 · **Also satisfies** A.5.10, A.5.34, A.8.24',
      '',
      '## Purpose',
      '',
      'Information leaves this organisation constantly: a clinic sends a photograph to a doctor',
      'for a second opinion, finance sends a reconciliation file to the bank, engineering sends a',
      'log excerpt to a vendor. Each of those is a transfer, and each has gone wrong somewhere in',
      'the industry. This procedure names the channels that are allowed, and the checks a person',
      'runs before sending.',
      '',
      '## Scope',
      '',
      'Every transfer of information out of a clinic or out of the engineering estate, whether',
      'electronic, verbal or physical, and transfers between the group and any third party. It',
      'excludes routine service-to-service traffic inside the Eternesia platform, which is',
      'governed by the network controls rather than by a person deciding.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Dhiaz Fathra** owns this procedure and the channel register, and approves any new',
      '  channel before first use.',
      '- **Agil** configures and monitors the technical channels (mail transport, SFTP endpoints,',
      '  key rotation).',
      '- **Pak Andre** is accountable for transfers initiated by clinic staff and for the monthly',
      '  spot check described below.',
      '- **Rica** rules on whether a proposed transfer of personal data has a lawful basis.',
      '',
      '## Procedure',
      '',
      '1. **Classify before you send.** The sender identifies the highest classification in the',
      '   payload using the register maintained under A.5.12. If any specific personal data is',
      '   present — treatment history, diagnosis, before/after images — the transfer is clinical.',
      '2. **Pick an approved channel.** Consult `FRM-A-5-14-01`. Clinical content moves only',
      '   through the Super App case thread. Nothing clinical goes over consumer messaging, and',
      '   this is enforced by the December 2025 withdrawal of the shared clinic handsets from the',
      '   doctor groups.',
      '3. **Check the recipient.** For an external recipient, confirm the address against the',
      '   contact held in the supplier or insurer record, not against the address in the last',
      '   e-mail. Address-in-reply is the failure mode that produced two of our three near misses',
      '   in 2025.',
      '4. **Establish the terms.** A recurring external transfer requires a written agreement',
      '   naming the purpose, the retention period and the return or destruction obligation,',
      '   recorded under A.5.20. Rica confirms the lawful basis for personal data.',
      '5. **Protect the payload.** Bulk extracts sent to a third party are encrypted with a',
      '   passphrase communicated over a different channel from the file. Passphrases are never',
      '   sent in the covering message.',
      '6. **Log it.** Recurring transfers are logged automatically by the sending system. One-off',
      '   transfers of specific personal data are logged by the sender in the case thread, naming',
      '   the recipient and the reason.',
      '7. **Verbal transfers.** Clinical detail is not discussed in reception areas or over an',
      '   open speakerphone. A call about a named patient is taken in the consultation room.',
      '8. **Physical transfers.** Consent forms moving between clinics travel in a tamper-evident',
      '   pouch with a signed manifest; the receiving clinic signs and returns the manifest within',
      '   2 working days.',
      '',
      '## Monitoring',
      '',
      'Pak Andre samples 10 outbound clinic transfers each month and records the result on the',
      'register. Agil reports MTA-STS failures and SFTP key age monthly. A transfer over an',
      'unapproved channel is raised as a security event under ISMS-SOP-A-5-25.',
      '',
      '## Records',
      '',
      'Approved transfer channel register (`FRM-A-5-14-01`, retained for the life of the',
      'procedure plus 3 years), monthly spot-check results (3 years), signed courier manifests',
      '(2 years), automatic transfer logs (12 months in the platform, then archived for 3 years).',
      '',
      '## Review',
      '',
      'Annually by Dhiaz Fathra with Pak Andre, and immediately after any transfer-related',
      'incident or the introduction of a new external counterparty.',
    ].join('\n'),
  },
  {
    code: 'ISMS-POL-A-5-15',
    title: 'Access Control Policy',
    clause: 'A.5.15',
    crossRefs: ['A.5.18', 'A.8.2', 'A.8.3'],
    version: 'v3.0',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-5-15-01', name: 'Role to entitlement matrix' },
    revisions: [
      {
        version: 'v2.2',
        date: '2024-11-05',
        author: 'Randy',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Per-service permission lists maintained by hand in each Go service; no single place to answer "what can this role do".',
      },
      {
        version: 'v3.0',
        date: '2026-02-18',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Role model consolidated into Zitadel; location scoping made mandatory for every clinic-facing role.',
      },
    ],
    evidence: [
      {
        name: 'role-entitlement-matrix-2026-q2.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-04-10',
        expiryDate: '2026-10-10',
        uploader: 'Randy',
        note: 'Entitlements per role as exported from Zitadel at the Q2 review.',
        body: [
          'Role | Scope | Patient read | Patient write | Pricing | Admin | Approver',
          'Receptionist | Own location | Identity and appointment only | Appointment | No | No | Pak Andre',
          'Practitioner | Own location | Full clinical record | Clinical notes, images | No | No | Pak Andre',
          'Clinic manager | Own location | Full clinical record | Appointment, refund request | Read | Staff roster | Pak Andre',
          'Commercial analyst | Group, pseudonymised | Pseudonymised only | No | Read and write | No | Wiwin',
          'Backend engineer | Non-production | Synthetic data only | Synthetic data only | No | Deployment | Dhiaz Fathra',
          'Platform administrator | Group | Break-glass only, logged | No | No | Full | Dhiaz Fathra',
        ].join('\n'),
      },
      {
        name: 'access-control-policy-approval-2026-02-18.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-02-18',
        uploader: 'Dhiaz Fathra',
        note: 'Signed approval of v3.0 by the Director.',
      },
    ],
    body: [
      '# ISMS-POL-A-5-15 · Access Control Policy',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v3.0 · **Review** every 6 months',
      '**Requirement** A.5.15 · **Also satisfies** A.5.18, A.8.2, A.8.3',
      '',
      '## Purpose',
      '',
      'Roughly 240,000 patient records sit behind the Eternesia platform, and the people who need',
      'them work across 13 locations with regular movement between clinics. This policy states the',
      'rules that decide who can reach what, so that access is a consequence of someone’s job',
      'rather than of how long they have worked here.',
      '',
      '## Scope',
      '',
      'All logical access to the Eternesia ERP, the Super App back office, the marketplace',
      'services, the AWS ap-southeast-1 account, the source repositories, and the finance and',
      'HR systems. Physical access to clinics and to the equipment room is covered separately',
      'under Annex A.7 and is out of scope here.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Dhiaz Fathra** owns the role model and is the only approver for platform',
      '  administrator and production database entitlements.',
      '- **Pak Andre** approves every clinic role and confirms the location scope.',
      '- **Wiwin** approves commercial and pricing entitlements.',
      '- **Pak Rila** approves finance system entitlements.',
      '- **Agil** implements approved entitlements in Zitadel and in AWS IAM; he does not approve',
      '  his own.',
      '',
      '## Policy',
      '',
      '1. **Deny by default.** A new account carries no entitlement. Everything is granted',
      '   explicitly against a named role in `FRM-A-5-15-01`.',
      '2. **Role, not person.** Entitlements attach to roles. A request for an entitlement that no',
      '   role carries is a request to change the role model, and Dhiaz Fathra decides it.',
      '3. **Location scope is mandatory.** Every clinic-facing role is scoped to one location.',
      '   Group-wide read of clinical data exists in exactly one role, platform administrator, and',
      '   only through break-glass.',
      '4. **Need to know beats convenience.** A receptionist sees identity and appointment data',
      '   and no clinical record. Requests to widen this because "it is easier at the front desk"',
      '   are refused; the fix is a workflow change, not an entitlement.',
      '5. **Separate duties.** The person who requests an entitlement, the person who approves it',
      '   and the person who implements it are three different people. No engineer approves a',
      '   production entitlement for themselves.',
      '6. **Privileged access is time-boxed.** Production database and platform administrator',
      '   sessions are granted for a maximum of 8 hours, require a stated reason, and are logged',
      '   with the Zitadel actor claim. Standing production access is not issued.',
      '7. **Non-production carries no real data.** Engineers work against synthetic data. A restore',
      '   of production data into a lower environment requires written approval from Dhiaz Fathra',
      '   and Rica, and the environment is destroyed within 5 working days.',
      '8. **Service accounts are owned.** Every machine identity names a human owner and a purpose',
      '   in the matrix; an unowned service account is disabled at the next quarterly review.',
      '9. **Access follows the person.** A change of role or location changes the entitlement set',
      '   the same day, under ISMS-SOP-A-5-18. Accumulated access from a previous role is removed,',
      '   not left in place "in case".',
      '',
      '## Exceptions',
      '',
      'An exception is time-limited, recorded against the matrix with an expiry date, and approved',
      'by Aris Ihwan. Exceptions older than 90 days are reported to the management review.',
      '',
      '## Records',
      '',
      'Role to entitlement matrix (`FRM-A-5-15-01`, current version plus 3 years of exports),',
      'signed approvals, quarterly entitlement export from Zitadel, break-glass session logs',
      '(retained 3 years).',
      '',
      '## Review',
      '',
      'Every 6 months by Dhiaz Fathra with the four approvers, and on any material change to the',
      'platform’s role model.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-5-16',
    title: 'Identity Management Procedure',
    clause: 'A.5.16',
    crossRefs: ['A.5.15', 'A.5.17', 'A.6.5'],
    version: 'v2.2',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-5-16-01', name: 'Identity lifecycle record' },
    revisions: [
      {
        version: 'v2.1',
        date: '2025-03-19',
        author: 'Randy',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Joiner records raised by e-mail to the engineering inbox; leaver notification depended on HR remembering.',
      },
      {
        version: 'v2.2',
        date: '2026-05-06',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'HR exit form made the trigger for deprovisioning, with a same-day service-level target and a weekly orphan sweep.',
      },
    ],
    evidence: [
      {
        name: 'identity-lifecycle-record-2026-h1.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-02',
        expiryDate: '2027-06-02',
        uploader: 'Agil',
        note: 'Joiner, mover and leaver events for the first half of 2026 with the elapsed time to action.',
        body: [
          'Date | Person type | Event | Trigger | Actioned by | Elapsed',
          '2026-01-14 | Clinic staff | Joiner | HR onboarding form | Agil | 1 working day',
          '2026-02-02 | Engineer | Joiner | HR onboarding form | Agil | same day',
          '2026-02-27 | Clinic staff | Mover, Kelapa Gading to Bintaro | Pak Andre roster change | Agil | same day',
          '2026-03-30 | Contractor | Leaver | Contract end date | Agil | same day',
          '2026-04-18 | Clinic staff | Leaver | HR exit form | Agil | 2 working days, escalated',
          '2026-05-21 | Engineer | Mover, backend to infrastructure | Dhiaz Fathra | same day',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-5-16 · Identity Management Procedure',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v2.2 · **Review** annually',
      '**Requirement** A.5.16 · **Also satisfies** A.5.15, A.5.17, A.6.5',
      '',
      '## Purpose',
      '',
      'Every action on the platform has to be attributable to one identifiable person. That only',
      'holds if identities are created deliberately, kept unique, and removed the day they stop',
      'being needed. This procedure describes how an identity is born, changed and retired.',
      '',
      '## Scope',
      '',
      'All human identities in Zitadel — clinic staff, engineering, commercial, finance and',
      'contractors — and all non-human identities (service accounts, CI credentials, integration',
      'users) in the Eternesia estate and the AWS ap-southeast-1 account. Patient accounts in the',
      'Super App are customer identities and follow the product’s own registration flow, not this',
      'procedure.',
      '',
      '## Roles and responsibilities',
      '',
      '- **HR** raises the onboarding and exit forms that trigger this procedure.',
      '- **Agil** creates, amends and disables identities in Zitadel and AWS IAM.',
      '- **Pak Andre** confirms the location and role for clinic identities.',
      '- **Dhiaz Fathra** owns the procedure, approves shared and service identities, and reviews',
      '  the weekly orphan sweep.',
      '',
      '## Procedure',
      '',
      '1. **Joiner.** HR submits the onboarding form at least 2 working days before the start',
      '   date, naming the role, location and manager. Agil creates one identity in Zitadel with',
      '   the entitlements the role carries under ISMS-POL-A-5-15, and nothing else.',
      '2. **Unique identity.** One person, one identity, for their whole time with the group.',
      '   Identities are never reused between people, and a returning employee is reactivated',
      '   rather than recreated so that historical log entries stay attributable.',
      '3. **Naming.** Human identities use `firstname.lastname`; a collision is resolved with a',
      '   middle initial, never with a number. Service accounts use `svc-<service>-<purpose>`.',
      '4. **Proof of identity.** For a clinic joiner, Pak Andre confirms in person on day one that',
      '   the person collecting the credential is the person named on the form.',
      '5. **Mover.** A change of role or location is actioned the same working day. The old',
      '   entitlement set is removed in the same change as the new one is granted.',
      '6. **Leaver.** The HR exit form disables the identity on the last working day, before the',
      '   person leaves the premises. Disable, do not delete: the account is retained disabled for',
      '   12 months so that audit trails resolve, then removed.',
      '7. **Contractors.** Every contractor identity carries an expiry date matching the contract',
      '   end. Zitadel disables it automatically on that date; an extension is a new approval.',
      '8. **Non-human identities.** Each is registered against a named human owner and a purpose.',
      '   Shared human accounts are not permitted anywhere in the estate.',
      '9. **Weekly orphan sweep.** Agil compares the Zitadel roster against the HR active-employee',
      '   list every Monday. Any identity with no matching employee, and any service account whose',
      '   owner has left, is reported to Dhiaz Fathra and disabled within 1 working day.',
      '',
      '## Records',
      '',
      'Identity lifecycle record (`FRM-A-5-16-01`, 3 years), HR onboarding and exit forms held by',
      'HR to their own retention, weekly orphan sweep output (12 months), Zitadel audit log',
      '(3 years).',
      '',
      '## Review',
      '',
      'Annually by Dhiaz Fathra, and after any leaver whose access was not removed on the day.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-5-17',
    title: 'Authentication Information Procedure',
    clause: 'A.5.17',
    crossRefs: ['A.5.16', 'A.8.5', 'A.6.3'],
    version: 'v2.1',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-5-17-01', name: 'Credential issue and reset log' },
    revisions: [
      {
        version: 'v2.0',
        date: '2024-06-11',
        author: 'Randy',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Complexity-and-90-day-expiry rules that pushed staff towards written-down passwords at the reception desk.',
      },
      {
        version: 'v2.1',
        date: '2025-10-08',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Routine expiry dropped in favour of length, a breached-password check and mandatory MFA; expiry now only on suspicion of compromise.',
      },
    ],
    evidence: [
      {
        name: 'credential-reset-log-2026-q2.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-30',
        expiryDate: '2029-06-30',
        uploader: 'Agil',
        note: 'Resets and initial issues for Q2 2026, with the verification method used.',
        body: [
          'Date | Identity | Event | Verification | Channel | Handled by',
          '2026-04-03 | receptionist, Bintaro | Initial issue | In person, Pak Andre confirmed | One-time link, expires 24h | Agil',
          '2026-04-22 | practitioner, Kemang | Self-service reset | MFA factor | Self-service | System',
          '2026-05-09 | backend engineer | Forced reset | Credential found in a public paste | One-time link | Agil',
          '2026-05-30 | clinic manager, PIK | Assisted reset, MFA device lost | Video call plus manager confirmation | One-time link, expires 1h | Agil',
          '2026-06-17 | svc-billing-export | Key rotation | Scheduled | Secrets manager | Agil',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-5-17 · Authentication Information Procedure',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v2.1 · **Review** annually',
      '**Requirement** A.5.17 · **Also satisfies** A.5.16, A.8.5, A.6.3',
      '',
      '## Purpose',
      '',
      'Passwords, MFA factors, API keys and signing keys are the things that make an identity',
      'usable. The previous version of this procedure demanded a new complex password every 90',
      'days, and the visible result was passwords on sticky notes under three reception counters.',
      'This version trades rotation theatre for length, a breach check and a second factor.',
      '',
      '## Scope',
      '',
      'All authentication information used to reach group systems: staff passwords and MFA',
      'factors in Zitadel, API keys and tokens issued to integrations, SSH and signing keys, and',
      'database credentials in the AWS ap-southeast-1 secrets manager. Patient credentials in the',
      'Super App follow the same technical rules but are administered by the product team.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Dhiaz Fathra** owns the rules below and approves any exception.',
      '- **Agil** operates issue, reset and rotation, and keeps the log.',
      '- **Randy** carries the on-call duty to force a reset out of hours when a credential is',
      '  believed to be exposed.',
      '- **Every user** is responsible for not sharing their own credential, including with a',
      '  colleague covering their shift.',
      '',
      '## Procedure',
      '',
      '1. **Initial issue.** Credentials are issued as a one-time link valid for 24 hours, sent to',
      '   a channel the recipient already controls. Clinic staff collect theirs in person on day',
      '   one with Pak Andre confirming who they are. Initial credentials are never dictated over',
      '   the phone or written on the onboarding pack.',
      '2. **Password rules.** Minimum 12 characters, no composition rules, no routine expiry. Every',
      '   new or changed password is checked against a breached-password list at the point of',
      '   entry and rejected on a match.',
      '3. **Second factor.** MFA is mandatory for all engineering, finance and administrator',
      '   identities, and for any access from outside a clinic network. Clinic-floor roles use a',
      '   shared-device flow with a personal PIN and an idle lock at 3 minutes.',
      '4. **Reset.** Self-service reset requires a registered MFA factor. An assisted reset — used',
      '   when the factor is lost — requires a video call plus confirmation from the person’s',
      '   manager. Agil records both the verification method and who authorised it.',
      '5. **Suspected compromise.** Anyone who suspects their credential is known to someone else',
      '   tells the on-call engineer immediately. Randy forces a reset and invalidates active',
      '   sessions within 1 hour, and raises a security event under ISMS-SOP-A-5-25. No one is',
      '   disciplined for reporting quickly.',
      '6. **Secrets in systems.** Application secrets live in the AWS secrets manager and are',
      '   injected at run time. A secret committed to a repository is treated as compromised the',
      '   moment it is found: rotate first, clean history second.',
      '7. **Machine credentials.** API keys and SSH keys are rotated at least every 12 months and',
      '   immediately when their owner leaves. Long-lived static keys are not issued where a',
      '   short-lived token will do.',
      '8. **Default credentials.** Any vendor default is changed before a device or service reaches',
      '   a production network. Agil records the change on the asset entry.',
      '',
      '## Records',
      '',
      'Credential issue and reset log (`FRM-A-5-17-01`, 3 years), secrets manager rotation history',
      '(3 years), forced-reset tickets and the linked security events (3 years).',
      '',
      '## Review',
      '',
      'Annually by Dhiaz Fathra, and whenever a credential-related incident is closed.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-5-18',
    title: 'Access Rights Provisioning and Review Procedure',
    clause: 'A.5.18',
    crossRefs: ['A.5.15', 'A.5.16', 'A.6.5'],
    version: 'v2.3',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-5-18-01', name: 'Quarterly access review sheet' },
    revisions: [
      {
        version: 'v2.2',
        date: '2025-01-23',
        author: 'Agil',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Annual review only; the 2024 review found 31 entitlements that no longer matched the holder’s job.',
      },
      {
        version: 'v2.3',
        date: '2026-03-11',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Review moved to quarterly with a named approver per system and a default-revoke rule for anything not confirmed.',
      },
    ],
    evidence: [
      {
        name: 'access-review-2026-q1-summary.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-03-31',
        expiryDate: '2029-03-31',
        uploader: 'Agil',
        note: 'Outcome of the first quarterly review under v2.3.',
        body: [
          'System | Reviewer | Identities reviewed | Confirmed | Reduced | Revoked | Completed',
          'Zitadel, clinic roles | Pak Andre | 148 | 139 | 6 | 3 | 2026-03-24',
          'Zitadel, engineering | Dhiaz Fathra | 22 | 19 | 2 | 1 | 2026-03-20',
          'AWS ap-southeast-1 IAM | Agil | 34 | 28 | 4 | 2 | 2026-03-26',
          'Finance system | Pak Rila | 11 | 10 | 0 | 1 | 2026-03-27',
          'Pricing and promotion | Wiwin | 9 | 8 | 1 | 0 | 2026-03-19',
          'Service accounts | Dhiaz Fathra | 41 | 33 | 0 | 8 | 2026-03-30',
        ].join('\n'),
      },
      {
        name: 'access-review-2026-q1-minute.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-04-02',
        uploader: 'Dhiaz Fathra',
        note: 'Signed closing minute, including the eight service accounts revoked as unowned.',
      },
    ],
    body: [
      '# ISMS-SOP-A-5-18 · Access Rights Provisioning and Review Procedure',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v2.3 · **Review** annually',
      '**Requirement** A.5.18 · **Also satisfies** A.5.15, A.5.16, A.6.5',
      '',
      '## Purpose',
      '',
      'ISMS-POL-A-5-15 says what access should look like. This procedure is how it is actually',
      'granted, changed, taken away and checked. Its reason for existing is drift: entitlements',
      'accumulate quietly, and only a scheduled review catches the receptionist who still has the',
      'clinic manager rights she held for two weeks of cover in 2024.',
      '',
      '## Scope',
      '',
      'Provisioning, modification, revocation and periodic review of access rights across',
      'Zitadel, AWS ap-southeast-1, the source repositories, the finance system and the pricing',
      'back office. Physical access rights are reviewed separately by Agil under Annex A.7.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Line manager** raises the request and states the business reason.',
      '- **System approver** — Pak Andre for clinic roles, Dhiaz Fathra for engineering and',
      '  service accounts, Pak Rila for finance, Wiwin for pricing — decides it.',
      '- **Agil** implements and evidences the change.',
      '- **Dhiaz Fathra** chairs the quarterly review and signs the closing minute.',
      '',
      '## Procedure',
      '',
      '1. **Request.** The line manager raises a request naming the person, the role, the location',
      '   and why the access is needed. "Same as her colleague" is not a business reason and is',
      '   returned.',
      '2. **Approve.** The system approver checks the request against the role model and approves',
      '   or reduces it. Approval is recorded in the ticket; verbal approval does not count.',
      '3. **Implement.** Agil applies the entitlement in Zitadel within 1 working day and links',
      '   the ticket to the identity record.',
      '4. **Privileged requests.** Anything carrying production data access, administrator rights',
      '   or the ability to move money needs a second approval from Aris Ihwan and is granted for',
      '   a stated window rather than permanently.',
      '5. **Temporary cover.** Access granted for shift cover or leave carries an explicit end date',
      '   at the point of approval. Zitadel removes it automatically; no one has to remember.',
      '6. **Revocation.** Triggered by the HR exit form, a role change, contract end, or a decision',
      '   at the quarterly review. Target is same working day; the maximum tolerated is 2 working',
      '   days and any breach is escalated to the Director.',
      '7. **Quarterly review.** In the last three weeks of each quarter, Agil exports current',
      '   entitlements per system and sends each approver their sheet. The approver marks each',
      '   line confirm, reduce or revoke and returns it within 10 working days.',
      '8. **Default revoke.** A line that no approver confirms within the window is revoked. The',
      '   burden is on justifying access, not on justifying its removal.',
      '9. **Close.** Agil applies the outcomes, Dhiaz Fathra signs the closing minute, and any',
      '   pattern worth acting on — a role that is always reduced, an approver who never responds —',
      '   goes to the management review.',
      '',
      '## Records',
      '',
      'Access request tickets (3 years), quarterly review sheets (`FRM-A-5-18-01`, 3 years),',
      'signed closing minutes (3 years), entitlement exports (retained per quarter for 3 years).',
      '',
      '## Review',
      '',
      'Annually by Dhiaz Fathra, and after any audit finding relating to access.',
    ].join('\n'),
  },
  {
    code: 'ISMS-POL-A-5-19',
    title: 'Supplier Information Security Policy',
    clause: 'A.5.19',
    crossRefs: ['A.5.20', 'A.5.22', '8.4.1'],
    version: 'v1.4',
    owner: 'Pak Chen',
    form: { code: 'FRM-A-5-19-01', name: 'Supplier security risk register' },
    revisions: [
      {
        version: 'v1.3',
        date: '2024-08-20',
        author: 'Pak Chen',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'One assessment questionnaire applied to every supplier, from the laundry contractor to the payment gateway.',
      },
      {
        version: 'v1.4',
        date: '2026-04-15',
        author: 'Pak Chen',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Three-tier model introduced so that assessment effort follows the data and access a supplier actually gets.',
      },
    ],
    evidence: [
      {
        name: 'supplier-security-risk-register-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-04-15',
        expiryDate: '2027-04-15',
        uploader: 'Pak Chen',
        note: 'Tiering and assessment status for the group’s active suppliers.',
        body: [
          'Supplier | Service | Data reached | Tier | Last assessed | Next due | Owner',
          'AWS | Cloud infrastructure, ap-southeast-1 | All production data | 1 | 2026-02-10 | 2027-02-10 | Agil',
          'Zitadel (self-hosted) | Identity provider | Credentials, staff identity | 1 | 2026-02-10 | 2027-02-10 | Agil',
          'Payment gateway | Card and QRIS acceptance | Payment, partial personal data | 1 | 2026-01-22 | 2027-01-22 | Pak Rila',
          'Medical records scanning vendor | Legacy paper digitisation | Specific personal data | 1 | 2026-03-05 | 2027-03-05 | Rica',
          'Marketing agency | Campaign execution | Contact data, consented only | 2 | 2026-03-28 | 2027-03-28 | Wiwin',
          'Equipment maintenance | Clinic device servicing | Physical access, no systems | 2 | 2026-02-19 | 2027-02-19 | Pak Andre',
          'Office stationery | Consumables | None | 3 | n/a | n/a | Pak Chen',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-A-5-19 · Supplier Information Security Policy',
      '',
      '**Owner** Pak Chen · **Approver** Aris Ihwan · **Version** v1.4 · **Review** annually',
      '**Requirement** A.5.19 · **Also satisfies** A.5.20, A.5.22, 9001 8.4.1',
      '',
      '## Purpose',
      '',
      'A good part of what the group relies on is run by someone else: the cloud account, the',
      'payment gateway, the vendor that digitises legacy paper records. Their weaknesses become',
      'ours. This policy sets how much scrutiny a supplier gets before we depend on them, and',
      'deliberately makes that proportionate — the stationery supplier should not receive the same',
      'questionnaire as the company holding scanned patient files.',
      '',
      '## Scope',
      '',
      'Every third party that processes group information, connects to a group system, or has',
      'unescorted physical access to a clinic or the equipment room. It covers software-as-a',
      '-service, professional services, clinical outsourcing and maintenance contractors. It',
      'excludes intra-group arrangements between brands, which are governed internally.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Pak Chen** owns this policy and the supplier register, and runs procurement.',
      '- **Dhiaz Fathra** sets the security requirements a supplier must meet and signs off tier 1',
      '  assessments.',
      '- **Rica** assesses any supplier that will process personal data and decides whether a',
      '  processor agreement is required.',
      '- **The requesting department head** — Pak Andre, Pak Rila, Wiwin or Dhiaz Fathra — owns the',
      '  relationship after signature and is named on the register.',
      '',
      '## Policy',
      '',
      '1. **Tier before you assess.** Tier 1 suppliers process personal data, hold credentials or',
      '   have privileged access to production. Tier 2 have limited data or physical access. Tier 3',
      '   have neither. Tiering is decided by Pak Chen with Dhiaz Fathra and recorded before any',
      '   contract discussion.',
      '2. **Assessment depth follows tier.** Tier 1 requires a full security assessment, evidence',
      '   of an independent certification or audit report where one exists, and a named security',
      '   contact. Tier 2 requires a short questionnaire and a reference check. Tier 3 requires',
      '   nothing beyond normal commercial diligence.',
      '3. **No access before assessment.** A tier 1 or tier 2 supplier receives no credential, no',
      '   data and no unescorted access until the assessment is complete and Dhiaz Fathra has',
      '   signed it off. Urgency is not a reason to skip this; it is a reason to scope the first',
      '   engagement more narrowly.',
      '4. **Least privilege applies to suppliers too.** A supplier gets a named, time-boxed',
      '   identity under ISMS-SOP-A-5-16, scoped to what the contract requires. Shared vendor',
      '   accounts are not issued.',
      '5. **Personal data needs a written basis.** Where a supplier processes personal data on our',
      '   behalf, Rica confirms the processor agreement under the PDP Law is in place before any',
      '   data moves.',
      '6. **Reassess on a cycle.** Tier 1 annually, tier 2 every two years, and any tier immediately',
      '   after a security incident at the supplier or a material change in the service.',
      '7. **Concentration is a risk in its own right.** Where a single supplier underpins a service',
      '   the clinics cannot operate without, the register records what the group would do if it',
      '   became unavailable — even if the answer is an uncomfortable one.',
      '8. **Exit is part of entry.** Return or destruction of our data, and revocation of access,',
      '   are agreed at contract signature rather than negotiated at termination.',
      '',
      '## Records',
      '',
      'Supplier security risk register (`FRM-A-5-19-01`, kept current, versions retained 5 years),',
      'completed assessments and questionnaires (contract term plus 3 years), sign-off records,',
      'processor agreements held by Rica.',
      '',
      '## Review',
      '',
      'Annually by Pak Chen with Dhiaz Fathra and Rica, and reported to the management review',
      'alongside the supplier performance data from ISMS-SOP-A-5-22.',
    ].join('\n'),
  },
]
