import type { SeedDocument } from './types'

/**
 * Annex A.8 — the development, test and audit end of the technological controls
 * (A.8.23 to A.8.34). Complements ENG-SOP-001, which owns the life cycle itself:
 * these documents state the specific controls that life cycle has to satisfy.
 */
export const ANNEX_A8_C: SeedDocument[] = [
  {
    code: 'ISMS-POL-A-8-23',
    title: 'Web and Outbound Traffic Filtering Policy',
    clause: 'A.8.23',
    crossRefs: ['A.8.7', 'A.8.12', 'A.8.20', 'A.6.7'],
    version: 'v1.3',
    owner: 'Agil',
    form: { code: 'FRM-A-8-23-01', name: 'Filtering category exception request' },
    revisions: [
      {
        version: 'v1.1',
        date: '2025-05-19',
        author: 'Agil',
        approval: 'Drafted',
        status: 'Superseded',
        note: 'First written rule set after clinic reception machines were found reaching file-sharing sites.',
      },
      {
        version: 'v1.3',
        date: '2026-04-07',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Server-side egress allow-list added; generative AI category moved from blocked to permitted-with-conditions for engineering.',
      },
    ],
    evidence: [
      {
        name: 'filtering-exception-register-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-05-04',
        expiryDate: '2027-05-04',
        uploader: 'Agil',
        note: 'Every standing exception to the blocked categories, with requester, reason and review date.',
        body: [
          'Ref | Category | Requested by | Reason | Scope | Approved | Next review',
          'EX-2026-01 | Generative AI assistants | Dhiaz Fathra | Agent-assisted development | Engineering group only | 2026-01-12 | 2026-07-12',
          'EX-2026-02 | Cloud file storage | Wiwin | Supplier catalogue exchange with two vendors | Two named domains | 2026-02-03 | 2026-08-03',
          'EX-2026-03 | Remote support tooling | Pak Andre | Vendor support for the clinic queue display | Reception VLAN, session-based | 2026-03-11 | 2026-09-11',
          'EX-2026-04 | Social media | Wiwin | Brand account management | Two marketing endpoints | 2026-04-22 | 2026-10-22',
          'EX-2025-09 | Torrent protocols | — | Withdrawn; no legitimate use found | — | Revoked 2026-01-20 | closed',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-A-8-23 · Web and Outbound Traffic Filtering Policy',
      '',
      '**Owner** Agil (Infrastructure) · **Approver** Aris Ihwan · **Version** v1.3 · **Review** annual',
      '**Requirement** A.8.23 · **Also satisfies** A.8.7, A.8.12, A.8.20, A.6.7',
      '',
      '## Purpose',
      '',
      'Two different risks share one control here. Clinic endpoints sit on the same network as',
      'the queue displays and the payment terminal, and a receptionist following a malicious link',
      'is the cheapest way into that network. Separately, a production server that can reach any',
      'address on the internet is a data-exfiltration path that no amount of access control',
      'closes. This policy states what each class of machine is allowed to reach.',
      '',
      '## Scope',
      '',
      'Clinic workstations and reception machines at all locations, engineering laptops on the',
      'corporate network or on the VPN, and outbound traffic from production hosts in AWS',
      'ap-southeast-1. Patient-owned devices on the guest wireless are out of scope — that',
      'network is isolated and carries no group traffic.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Agil** maintains the category rule set and the egress allow-list, and reviews the',
      '  exception register quarterly.',
      '- **Pak Andre** raises and justifies exceptions needed for clinic operations.',
      '- **Dhiaz Fathra** approves exceptions affecting engineering; anything widening the rule',
      '  set for all users goes to Aris Ihwan.',
      '',
      '## Policy',
      '',
      '1. **Clinic and corporate endpoints filter by category at the resolver.** Malware and',
      '   phishing, anonymisers and proxy avoidance, remote-desktop-as-a-service, cryptomining,',
      '   and unclassified newly registered domains (under 30 days old) are blocked outright.',
      '2. **Blocked does not mean silent.** A blocked request returns the group block page naming',
      '   the category and the request route; users are told what to do rather than left guessing.',
      '3. **Production egress is deny-by-default.** A service reaches only the destinations named',
      '   in its OpenTofu security group — the payment gateway, the SMS provider, the object',
      '   store, the package registries used at build time. A new destination is a code change,',
      '   reviewed like any other.',
      '4. **Generative AI tools are permitted for the engineering group** under exception EX-2026-01,',
      '   subject to the no-production-data rule in CBE/ISMS/SOP/19 §4. They stay blocked on',
      '   clinic endpoints, where any prompt would by definition contain patient information.',
      '5. **Exceptions are time-boxed.** Six months maximum, recorded in the exception register',
      '   with a named requester, and revoked automatically if not renewed.',
      '6. **Filtering logs are not browsing surveillance.** Agil reviews aggregate category hits',
      '   and blocked-malware events. Per-user history is opened only as part of a declared',
      '   incident, with Dhiaz Fathra recorded as authorising it.',
      '',
      '## Records',
      '',
      'Exception register (this repository, retained 3 years after revocation), resolver rule set',
      'in the infrastructure repository, and 90 days of blocked-request logs in the log store.',
      '',
      '## Review',
      '',
      'Rule set reviewed annually by Agil; exception register reviewed each quarter and reported',
      'to the management review as a count of open and expired exceptions.',
    ].join('\n'),
  },

  {
    code: 'ISMS-POL-A-8-24',
    title: 'Cryptography and Key Management Policy',
    clause: 'A.8.24',
    crossRefs: ['A.5.34', 'A.8.5', 'A.8.13', 'A.8.26'],
    version: 'v2.0',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-8-24-01', name: 'Key inventory and rotation record' },
    revisions: [
      {
        version: 'v1.2',
        date: '2024-11-25',
        author: 'Andreas',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Algorithm table written; key custody still described per service rather than centrally.',
      },
      {
        version: 'v2.0',
        date: '2026-05-12',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'All application keys moved to AWS KMS after the March Zitadel key rotation outage; rotation intervals and owners fixed.',
      },
    ],
    evidence: [
      {
        name: 'key-inventory-2026-q2.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-30',
        expiryDate: '2026-12-31',
        uploader: 'Agil',
        note: 'Every key in use, its custodian, algorithm, rotation interval and last rotation.',
        body: [
          'Key | Purpose | Algorithm | Custodian | Rotation | Last rotated',
          'kms/patient-column | Column encryption, patient service | AES-256-GCM (KMS CMK) | Agil | 12 months | 2026-02-14',
          'kms/object-store | Before/after photographs at rest | AES-256-GCM (KMS CMK) | Agil | 12 months | 2026-02-14',
          'zitadel/signing | Access token signing | RSA-2048 | Randy | 6 months | 2026-03-20',
          'tls/*.dermaster.co.id | Public TLS termination at Caddy | ECDSA P-256, ACME | Agil | 90 days, automatic | 2026-06-18',
          'db/backup-envelope | Backup envelope encryption | AES-256-GCM (KMS CMK) | Agil | 12 months | 2025-12-02',
          'ci/artifact-signing | Container image signing | Ed25519 | Randy | 12 months | 2026-01-09',
        ].join('\n'),
      },
      {
        name: 'zitadel-key-rotation-rehearsal-2026-06.docx',
        fileType: 'DOCX',
        uploadedAt: '2026-06-24',
        uploader: 'Randy',
        note: 'Staging rehearsal of the token signing key rotation, run quarterly since RCA-2026-03.',
      },
    ],
    body: [
      '# ISMS-POL-A-8-24 · Cryptography and Key Management Policy',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v2.0 · **Review** annual',
      '**Requirement** A.8.24 · **Also satisfies** A.5.34, A.8.5, A.8.13, A.8.26',
      '',
      '## Purpose',
      '',
      'Encryption is not the hard part; knowing where every key is, who holds it and when it was',
      'last rotated is. The March 2026 login outage was caused by a signing key rotated without',
      'the consuming services revalidating it — a key management failure, not a cryptographic one.',
      'This policy fixes which algorithms are acceptable and, more importantly, how keys are held.',
      '',
      '## Scope',
      '',
      'All cryptography in group systems: data at rest, data in transit, token signing, backup',
      'encryption and artifact signing. It does not cover clinical device encryption supplied by',
      'the equipment vendor, which is governed by the supplier agreement.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Agil** is custodian for infrastructure and data-at-rest keys and maintains the key',
      '  inventory each quarter.',
      '- **Randy** is custodian for identity and artifact signing keys and runs the quarterly',
      '  rotation rehearsal in staging.',
      '- **Andreas** approves any new use of cryptography in a service design.',
      '- **Dhiaz Fathra** approves exceptions and owns this policy.',
      '',
      '## Policy',
      '',
      '1. **Approved algorithms.** AES-256-GCM for symmetric encryption, RSA-2048 or ECDSA P-256',
      '   for signatures, TLS 1.2 minimum with 1.3 preferred, Argon2id for password hashing.',
      '   MD5, SHA-1, DES/3DES and RSA below 2048 bits are prohibited in new code and are a',
      '   finding wherever they remain.',
      '2. **No hand-rolled cryptography.** Engineers use the platform library or the cloud',
      '   provider primitive. A merge request implementing a cipher, a padding scheme or a token',
      '   format from scratch is rejected on sight.',
      '3. **Keys live in AWS KMS or the secret manager, never in the repository, never in an',
      '   environment file committed anywhere.** The CI secret scan blocks a merge that adds one.',
      '4. **Every key has a named custodian and a rotation interval** recorded in the key',
      '   inventory. Data keys rotate every 12 months, token signing keys every 6, TLS',
      '   certificates every 90 days automatically.',
      '5. **Rotation is rehearsed before it is real.** Any key with dependent services is rotated',
      '   in staging first, each quarter, with the dependants observed. Consumers must tolerate',
      '   an unknown key identifier by refetching, not by failing closed permanently.',
      '6. **Patient data is encrypted at rest at the column level** for specific personal data',
      '   under TRD-SEC-002, in addition to volume encryption. Volume encryption alone protects',
      '   against a stolen disk, not against a query.',
      '7. **Key compromise is a P1 incident.** Revoke, rotate, then determine exposure — in that',
      '   order.',
      '',
      '## Records',
      '',
      'Key inventory (quarterly, retained 5 years), rotation rehearsal notes, and KMS CloudTrail',
      'events retained 12 months for key use and administration.',
      '',
      '## Review',
      '',
      'Annually by Dhiaz Fathra, and immediately after any incident involving a key, a certificate',
      'or an algorithm deprecation announcement.',
    ].join('\n'),
  },

  {
    code: 'ISMS-SOP-A-8-26',
    title: 'Application Security Requirements Procedure',
    clause: 'A.8.26',
    crossRefs: ['A.8.25', 'A.8.28', 'A.5.34', '8.3'],
    version: 'v1.4',
    owner: 'Andreas',
    form: { code: 'FRM-A-8-26-01', name: 'Application security requirement checklist' },
    revisions: [
      {
        version: 'v1.0',
        date: '2025-07-08',
        author: 'Andreas',
        approval: 'Drafted',
        status: 'Superseded',
        note: 'Checklist extracted from the TRD template so it could be applied to services with no TRD.',
      },
      {
        version: 'v1.4',
        date: '2026-05-26',
        author: 'Andreas',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Abuse-case section added; multi-tenant location scoping made a mandatory requirement after a cross-clinic read was found in review.',
      },
    ],
    evidence: [
      {
        name: 'appsec-checklist-marketplace-orders-2026.md',
        fileType: 'MD',
        uploadedAt: '2026-05-30',
        expiryDate: '2027-05-30',
        uploader: 'Andreas',
        note: 'Completed checklist for the marketplace order service, signed off before the design was frozen.',
        body: [
          '# Application security requirements — marketplace order service',
          '',
          '**Assessed by** Andreas · **Design frozen** 30 May 2026 · **TRD** TRD-MKT-014',
          '',
          '| Requirement | Decision | Verified by |',
          '| --- | --- | --- |',
          '| Authentication | Zitadel OIDC, no local accounts | Randy |',
          '| Authorisation | Order readable only by owning customer and finance role | Randy |',
          '| Tenancy scoping | `location_id` enforced in the repository layer, not the handler | Andreas |',
          '| Input validation | Protobuf schema plus explicit money-range checks | Tika |',
          '| Sensitive data | No card data touches the service; gateway token only | Rica |',
          '| Audit logging | Every state transition logged with actor claim | Randy |',
          '| Rate limiting | 60 req/min per customer at Caddy | Agil |',
          '',
          '**Abuse cases considered:** replayed payment callbacks (idempotency key required),',
          'price tampering in the client payload (server recalculates from the catalogue),',
          'enumeration of order identifiers (ULIDs, plus ownership check before 404 vs 403).',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-8-26 · Application Security Requirements Procedure',
      '',
      '**Owner** Andreas (Solutions Architect) · **Approver** Aris Ihwan · **Version** v1.4',
      '**Requirement** A.8.26 · **Also satisfies** A.8.25, A.8.28, A.5.34, ISO 9001 8.3',
      '',
      '## Purpose',
      '',
      'Security requirements decided after a service is built become a backlog nobody clears.',
      'This procedure puts them at the point where they are cheap: before the design is frozen.',
      'It sets out how security requirements are identified, recorded and checked off for every',
      'new or materially changed application in the group.',
      '',
      '## Scope',
      '',
      'Every service in the Eternesia platform, the Super App, the marketplace services, and any',
      'internal tool that reads production data. Purchased software is covered by the supplier',
      'process instead; this procedure applies to what the group builds.',
      '',
      '## Roles and responsibilities',
      '',
      'Andreas completes the checklist as part of the TRD. Randy and Agil verify the requirements',
      'that land in code and infrastructure respectively. Rica signs off any requirement touching',
      'personal data. Tika confirms each requirement has a test before the service goes live.',
      '',
      '## Procedure',
      '',
      '1. **Trigger.** A new service, a new externally reachable endpoint, or a change to how an',
      '   existing service authenticates, authorises or stores personal data.',
      '2. **Complete the checklist** (FRM-A-8-26-01) inside the TRD. The eight headings are fixed:',
      '   authentication, authorisation, tenancy scoping, input validation, sensitive data',
      '   handling, audit logging, rate limiting, and error and failure behaviour.',
      '3. **Write the abuse cases.** At least three per service: what an authenticated but',
      '   malicious customer would try, what a compromised internal account would reach, and what',
      '   happens when a dependency returns something unexpected. Each abuse case names its',
      '   countermeasure.',
      '4. **Fix the non-negotiables.** Location scoping is enforced in the repository layer, never',
      '   in a handler. Authorisation decisions are made server-side from the token claims.',
      '   Money is recalculated from the catalogue, never trusted from a client payload.',
      '   Identifiers exposed externally are ULIDs and are not sequential.',
      '5. **Review with Andreas and the owning engineer** before the design is frozen. An',
      '   unresolved requirement blocks the freeze; it does not become a follow-up ticket.',
      '6. **Hand to QA.** Tika turns each requirement into a test case in the acceptance pack',
      '   under ISMS-SOP-A-8-29. A requirement with no test is not a requirement, it is a hope.',
      '7. **Re-run the checklist** whenever the service gains a new trust boundary — a new caller',
      '   type, a new data class, or exposure to the public internet.',
      '',
      '## Records',
      '',
      'Completed checklists are held with the TRD in the engineering handbook repository and',
      'retained for the life of the service plus 3 years. Abuse cases stay in the same document',
      'so that the reasoning survives the people who wrote it.',
      '',
      '## Review',
      '',
      'Andreas reviews the checklist headings annually and after any incident whose root cause',
      'was a requirement that was never stated.',
    ].join('\n'),
  },

  {
    code: 'ISMS-SOP-A-8-28',
    title: 'Secure Coding Standard',
    clause: 'A.8.28',
    crossRefs: ['A.8.25', 'A.8.26', 'A.8.8', 'A.8.4'],
    version: 'v2.2',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-8-28-01', name: 'Secure code review finding record' },
    revisions: [
      {
        version: 'v2.0',
        date: '2025-09-15',
        author: 'Randy',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Go-specific rules separated from the general standard; SAST wired into GitLab CI.',
      },
      {
        version: 'v2.2',
        date: '2026-06-09',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Dependency provenance rules added; the standard made explicitly binding on agent-authored code.',
      },
    ],
    evidence: [
      {
        name: 'sast-findings-2026-q2.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-07-02',
        expiryDate: '2027-07-02',
        uploader: 'Randy',
        note: 'Static analysis and dependency findings for the quarter, with disposition.',
        body: [
          'Finding | Service | Severity | Rule | Raised | Disposition',
          'SAST-2026-041 | billing | High | SQL built by string concatenation in a report query | 2026-04-08 | Fixed, parameterised, 2026-04-09',
          'SAST-2026-047 | patient | Medium | Error returned to caller included the SQL constraint name | 2026-04-21 | Fixed 2026-04-24',
          'DEP-2026-012 | super-app-api | High | Transitive JWT library with a known signature bypass | 2026-05-02 | Upgraded 2026-05-02',
          'SAST-2026-055 | catalogue | Low | Unbounded slice allocation from a request field | 2026-05-19 | Fixed 2026-05-27',
          'SAST-2026-061 | notification | Medium | Template rendered without escaping in an internal report | 2026-06-11 | Fixed 2026-06-12',
          'DEP-2026-019 | marketplace | Medium | Unmaintained image library, no fix available | 2026-06-20 | Accepted to 2026-09-30, replacement planned',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-8-28 · Secure Coding Standard',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v2.2 · **Review** twice yearly',
      '**Requirement** A.8.28 · **Also satisfies** A.8.25, A.8.26, A.8.8, A.8.4',
      '',
      '## Purpose',
      '',
      'ENG-SOP-001 says how a change gets reviewed and merged. This standard says what the',
      'reviewer is looking for. It is deliberately short and specific: a list of rules that can',
      'be checked, not a survey of application security.',
      '',
      '## Scope',
      '',
      'All first-party code — Go services, the Flutter application, the Express.js marketplace',
      'services, OpenTofu modules and CI pipeline definitions. It binds code written by a person',
      'and code written by an agent identically; the reviewer who approves the merge request is',
      'accountable either way.',
      '',
      '## Roles and responsibilities',
      '',
      'Every engineer applies the standard while writing. The named human reviewer applies it',
      'while reviewing. Randy maintains the SAST rule set and triages its findings. Dhiaz Fathra',
      'decides on risk acceptances where no fix exists.',
      '',
      '## The rules',
      '',
      '1. **Never build a query by concatenation.** Parameterised statements or the query builder,',
      '   with no exception for "it is only an internal report".',
      '2. **Validate at the boundary, once, explicitly.** Protobuf or schema validation is the',
      '   floor; ranges, lengths and enumerations are checked on top of it. Trust nothing that',
      '   arrived over the wire, including from another internal service.',
      '3. **Errors returned to a caller carry no internals** — no stack traces, no SQL, no host',
      '   names, no library versions. The detail goes to the log with a correlation identifier.',
      '4. **No secrets in code, comments, tests or fixtures.** The CI secret scan is a gate, not',
      '   a warning.',
      '5. **Authorisation is checked in the same layer that reads the data.** A handler that',
      '   checks and a repository that does not is one refactor away from a data leak.',
      '6. **Handle every error.** In Go, a discarded error is a review rejection. Panics do not',
      '   cross a service boundary.',
      '7. **Concurrency is bounded.** Every goroutine has an owner and a context that can cancel',
      '   it; every external call has a timeout.',
      '8. **Dependencies are pinned and provenance-checked.** New direct dependencies need a',
      '   reviewer other than the author, and are checked for maintenance status before adoption.',
      '   Lock files are committed and never regenerated as a side effect of an unrelated change.',
      '9. **Logs never contain personal data or credentials.** Identifiers, not values.',
      '',
      '## Enforcement',
      '',
      'The linter and SAST job run on every merge request and block on High findings. Medium',
      'findings are fixed within 30 days or accepted in writing by Dhiaz Fathra with an expiry',
      'date. The internal review agent comments first against this standard; its approval never',
      'substitutes for the human reviewer named in ENG-SOP-001 §3.',
      '',
      '## Records',
      '',
      'Merge request review records in GitLab (retained with the repository), the quarterly SAST',
      'findings workbook (3 years), and written risk acceptances (until expiry plus 1 year).',
      '',
      '## Review',
      '',
      'Twice yearly by Dhiaz Fathra with Randy, and whenever a finding shows a rule was missing',
      'rather than ignored.',
    ].join('\n'),
  },

  {
    code: 'ISMS-SOP-A-8-29',
    title: 'Security Testing and Acceptance Procedure',
    clause: 'A.8.29',
    crossRefs: ['A.8.26', 'A.8.28', 'A.8.8', 'A.8.33'],
    version: 'v1.6',
    owner: 'Tika',
    form: { code: 'FRM-A-8-29-01', name: 'Release acceptance test record' },
    revisions: [
      {
        version: 'v1.2',
        date: '2025-08-27',
        author: 'Tika',
        approval: 'Drafted',
        status: 'Superseded',
        note: 'Acceptance pack defined; penetration testing still arranged ad hoc per project.',
      },
      {
        version: 'v1.6',
        date: '2026-04-14',
        author: 'Tika',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Annual external penetration test made mandatory for internet-facing services; retest rule added for High findings.',
      },
    ],
    evidence: [
      {
        name: 'pentest-super-app-2026-report.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-03-31',
        expiryDate: '2027-03-31',
        uploader: 'Dhiaz Fathra',
        note: 'External penetration test of the Super App and its public API, with the retest letter attached.',
      },
      {
        name: 'acceptance-record-2026-06-release.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-27',
        expiryDate: '2027-06-27',
        uploader: 'Tika',
        note: 'Security acceptance results for the June release train.',
        body: [
          'Test | Target | Result | Evidence | Signed off',
          'Authentication bypass suite (14 cases) | Super App API | Pass | CI job 8841 | Tika',
          'Authorisation matrix, 6 roles x 9 endpoints | patient, billing | Pass | CI job 8842 | Randy',
          'Cross-location read attempts | patient | Pass, 0 of 40 leaked | CI job 8843 | Andreas',
          'Dependency scan, High threshold | all services | Pass | CI job 8844 | Randy',
          'Rate limit and lockout behaviour | Caddy, Zitadel | Pass | manual, 2026-06-25 | Agil',
          'Backup restore with encrypted columns | patient | Pass, 41 min | manual, 2026-06-26 | Agil',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-8-29 · Security Testing and Acceptance Procedure',
      '',
      '**Owner** Tika (QA Lead) · **Approver** Aris Ihwan · **Version** v1.6 · **Review** annual',
      '**Requirement** A.8.29 · **Also satisfies** A.8.26, A.8.28, A.8.8, A.8.33',
      '',
      '## Purpose',
      '',
      'To make security testing a scheduled, repeatable part of every release rather than an',
      'activity that happens when someone remembers. It defines what is tested automatically on',
      'every change, what is tested before a release train ships, and what is tested annually by',
      'someone outside the group.',
      '',
      '## Scope',
      '',
      'All changes to the Eternesia services, the Super App and the marketplace. Configuration-only',
      'changes to non-production infrastructure are exempt from the release pack but not from the',
      'pipeline tests.',
      '',
      '## Roles and responsibilities',
      '',
      'Tika owns the acceptance pack and the release sign-off. Randy maintains the pipeline',
      'security jobs. Andreas verifies the tenancy and authorisation cases. Dhiaz Fathra',
      'commissions the annual external test and accepts or rejects residual findings.',
      '',
      '## Procedure',
      '',
      '**Every merge request** — SAST, dependency scan, secret scan and the unit tests covering',
      'the authorisation rules of the service touched. High findings block the merge.',
      '',
      '**Every release train (monthly)** —',
      '',
      '1. Tika runs the acceptance pack against the staging environment loaded with the synthetic',
      '   dataset defined in ISMS-SOP-A-8-33. Production data is never used for this.',
      '2. The pack covers, at minimum: the authentication bypass suite, the full role-by-endpoint',
      '   authorisation matrix, cross-location read attempts, rate limiting and account lockout,',
      '   and a restore of an encrypted backup.',
      '3. Results are recorded in FRM-A-8-29-01 with the CI job reference or the tester name.',
      '4. Any failed case blocks the release. A case cannot be waived by the team that wrote the',
      '   code it tests.',
      '5. Tika signs the record; Dhiaz Fathra countersigns where a finding is being accepted.',
      '',
      '**Annually** —',
      '',
      '6. An external tester assesses the internet-facing surface: the Super App, its public API,',
      '   and the marketplace. Scope, dates and rules of engagement are agreed in writing and the',
      '   testing itself follows the safeguards in ISMS-SOP-A-8-34.',
      '7. High findings are fixed within 30 days and retested by the same tester; the retest',
      '   letter is filed with the report. Medium findings are scheduled into a named sprint.',
      '8. The report and the fix status go to the management review.',
      '',
      '## Records',
      '',
      'Release acceptance records (3 years), pipeline job artefacts (12 months), external test',
      'reports and retest letters (5 years, restricted to Dhiaz Fathra, Aris Ihwan and the',
      'assigned engineers).',
      '',
      '## Review',
      '',
      'Tika reviews the acceptance pack annually and adds a case after every incident whose cause',
      'a test could have caught.',
    ].join('\n'),
  },

  {
    code: 'ISMS-SOP-A-8-30',
    title: 'Outsourced and Contracted Development Procedure',
    clause: 'A.8.30',
    crossRefs: ['A.5.20', 'A.5.21', 'A.8.4', '8.4'],
    version: 'v1.2',
    owner: 'Pak Chen',
    form: { code: 'FRM-A-8-30-01', name: 'Contracted development security schedule' },
    revisions: [
      {
        version: 'v1.0',
        date: '2025-06-30',
        author: 'Pak Chen',
        approval: 'Drafted',
        status: 'Superseded',
        note: 'Written when the queue-display vendor was engaged without any security terms in the contract.',
      },
      {
        version: 'v1.2',
        date: '2026-03-23',
        author: 'Pak Chen',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Source code escrow and repository access rules added; handover acceptance made a payment milestone.',
      },
    ],
    evidence: [
      {
        name: 'vendor-security-schedule-queue-display-2026.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-03-30',
        expiryDate: '2027-03-30',
        uploader: 'Pak Chen',
        note: 'Signed security schedule annexed to the queue-display development contract.',
      },
      {
        name: 'contracted-development-register-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-30',
        expiryDate: '2027-06-30',
        uploader: 'Pak Chen',
        note: 'Active and closed contracted development engagements with their control status.',
        body: [
          'Engagement | Vendor scope | Data access | Schedule signed | Code review by | Handover accepted',
          'Clinic queue display v2 | UI and on-device app | None, display only | 2026-03-30 | Randy | 2026-06-12',
          'Loyalty points engine | Backend module | Pseudonymised only | 2025-11-18 | Andreas | 2026-01-30',
          'Marketing site refresh | Static site | None | 2026-02-05 | Wiwin | 2026-04-02',
          'Legacy Strapi migration support | Read-only migration scripts | Production read, supervised | 2025-09-22 | Dhiaz Fathra | 2026-05-08',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-8-30 · Outsourced and Contracted Development Procedure',
      '',
      '**Owner** Pak Chen (Supplier and Procurement) · **Approver** Aris Ihwan · **Version** v1.2',
      '**Requirement** A.8.30 · **Also satisfies** A.5.20, A.5.21, A.8.4, ISO 9001 8.4',
      '',
      '## Purpose',
      '',
      'The group builds most software in house, but not all of it: clinic-floor hardware',
      'integrations, occasional front-end work and migration support are contracted out. Code',
      'the group did not write still runs in the group’s environment and still carries the',
      'group’s liability. This procedure sets the terms and the checks that apply before that',
      'code is accepted.',
      '',
      '## Scope',
      '',
      'Any engagement where a party outside the group writes, modifies or operates software that',
      'runs in group environments or touches group data. It does not cover purchased SaaS, which',
      'goes through the cloud services and supplier assessment route instead.',
      '',
      '## Roles and responsibilities',
      '',
      'Pak Chen owns the commercial relationship and the security schedule. Andreas defines the',
      'technical requirements the vendor must meet. Randy or a nominated engineer reviews the',
      'delivered code. Rica must approve before any engagement is given access to personal data.',
      'Dhiaz Fathra accepts or rejects the handover.',
      '',
      '## Procedure',
      '',
      '1. **Before contract.** Pak Chen confirms the vendor can meet the security schedule',
      '   (FRM-A-8-30-01). No schedule, no signature — this rule exists because the first queue',
      '   display contract had none.',
      '2. **The schedule fixes, as a minimum:** the secure coding standard the vendor works to,',
      '   ownership of the resulting intellectual property, the group’s right to review and test',
      '   the code, breach notification within 24 hours, sub-contracting only with written',
      '   consent, and deletion of group data within 30 days of the engagement ending.',
      '3. **Access is the minimum that works.** Vendors get a dedicated repository or a fork, not',
      '   the group monorepo, and never a standing production credential. Where production access',
      '   is unavoidable it is time-boxed, read-only, and supervised by a named engineer.',
      '4. **No production data reaches a vendor environment.** The synthetic dataset under',
      '   ISMS-SOP-A-8-33 is provided instead.',
      '5. **Delivered code is reviewed by a group engineer** against ISMS-SOP-A-8-28 and scanned',
      '   by the same pipeline as first-party code. Findings are the vendor’s to fix before',
      '   acceptance.',
      '6. **Handover is a milestone, not a courtesy.** Source, build instructions, dependency',
      '   manifest, deployment notes and known limitations are delivered and reproduced by the',
      '   group before the final payment is released.',
      '7. **Closure.** Access revoked within 5 working days, deletion confirmation obtained in',
      '   writing, and the register updated.',
      '',
      '## Records',
      '',
      'Signed security schedules and deletion confirmations (contract term plus 5 years), the',
      'contracted development register (this repository), and code review records with the',
      'repository.',
      '',
      '## Review',
      '',
      'Register reviewed quarterly by Pak Chen with Dhiaz Fathra; the schedule template reviewed',
      'annually or when the PDP Law guidance on processors changes.',
    ].join('\n'),
  },

  {
    code: 'ISMS-POL-A-8-31',
    title: 'Environment Separation Policy',
    clause: 'A.8.31',
    crossRefs: ['A.8.9', 'A.8.32', 'A.8.33', 'A.8.2'],
    version: 'v1.5',
    owner: 'Agil',
    form: { code: 'FRM-A-8-31-01', name: 'Environment inventory and access record' },
    revisions: [
      {
        version: 'v1.3',
        date: '2025-04-16',
        author: 'Agil',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Separate AWS accounts adopted for production and non-production.',
      },
      {
        version: 'v1.5',
        date: '2026-02-18',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Ephemeral review environments brought under the policy; shared staging database with production credentials removed.',
      },
    ],
    evidence: [
      {
        name: 'environment-inventory-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-15',
        expiryDate: '2027-06-15',
        uploader: 'Agil',
        note: 'Every environment, its account, its data class and who can reach it.',
        body: [
          'Environment | AWS account | Data | Deploy route | Human access | Retention',
          'production | cbe-prod | Live patient and payment data | Tagged release via CI only | Break-glass, 2 named engineers | permanent',
          'staging | cbe-nonprod | Synthetic dataset v4 | Automatic from main | Engineering group | rebuilt weekly',
          'review-<mr> | cbe-nonprod | Synthetic subset | Automatic per merge request | Author and reviewer | destroyed on merge',
          'sandbox | cbe-nonprod | None or self-generated | Manual | Engineering group | destroyed after 14 days idle',
          'dr-warm | cbe-prod-dr | Replica of production | Replication only | Break-glass only | permanent',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-A-8-31 · Environment Separation Policy',
      '',
      '**Owner** Agil (Infrastructure) · **Approver** Aris Ihwan · **Version** v1.5 · **Review** annual',
      '**Requirement** A.8.31 · **Also satisfies** A.8.9, A.8.32, A.8.33, A.8.2',
      '',
      '## Purpose',
      '',
      'Development, test and production must not be able to reach one another by accident. The',
      'failure this policy prevents is mundane and common: a staging job holding a production',
      'credential, or a developer pointing a local tool at the live database because the',
      'connection string was in the same secret store.',
      '',
      '## Scope',
      '',
      'All group compute and data environments in AWS ap-southeast-1, the ephemeral review',
      'environments created per merge request, and engineer local machines insofar as they hold',
      'credentials. Clinic on-premise equipment is covered by the physical and network controls.',
      '',
      '## Roles and responsibilities',
      '',
      'Agil owns the environment inventory and the account boundaries. Randy owns the deployment',
      'pipeline that is the only route into production. Dhiaz Fathra holds the break-glass',
      'approval and reviews its use. Tika confirms staging holds only synthetic data before each',
      'release test.',
      '',
      '## Policy',
      '',
      '1. **Separate cloud accounts, not separate tags.** Production and disaster recovery live in',
      '   their own AWS accounts; staging, review and sandbox share a non-production account.',
      '   There is no network route between the two.',
      '2. **Credentials never cross the boundary.** Each account has its own secret store and its',
      '   own KMS keys. A production secret existing anywhere in the non-production account is a',
      '   P2 incident and forces rotation.',
      '3. **Production receives deployments only from the pipeline**, from a tagged commit on',
      '   `main`. There is no interactive deploy path and no manual `tofu apply` against',
      '   production.',
      '4. **Interactive production access is break-glass.** Two named engineers hold it, it is',
      '   requested with a reason, it expires after 4 hours, and every session is recorded and',
      '   reviewed by Dhiaz Fathra the following working day.',
      '5. **Non-production never holds live data.** Only the synthetic dataset governed by',
      '   ISMS-SOP-A-8-33. A restore of a production backup into staging requires written',
      '   approval from Dhiaz Fathra and Rica, and the environment is destroyed afterwards.',
      '6. **Environments look alike where it matters.** Same container images, same OpenTofu',
      '   modules, same runtime versions. Differences are limited to sizing, data and secrets,',
      '   and are visible in the module variables rather than hidden in a console setting.',
      '7. **Review environments are disposable** — created per merge request, destroyed on merge,',
      '   and never given a persistent hostname.',
      '',
      '## Records',
      '',
      'Environment inventory (quarterly refresh, retained 3 years), break-glass session logs (12',
      'months), and pipeline deployment history with the repository.',
      '',
      '## Review',
      '',
      'Annually by Agil with Dhiaz Fathra, and whenever a new environment class is introduced.',
    ].join('\n'),
  },

  {
    code: 'ISMS-SOP-A-8-32',
    title: 'Change Management Procedure',
    clause: 'A.8.32',
    crossRefs: ['A.8.9', 'A.8.31', 'A.8.25', '6.3'],
    version: 'v2.1',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-8-32-01', name: 'Change record and approval' },
    revisions: [
      {
        version: 'v2.0',
        date: '2025-12-09',
        author: 'Dhiaz Fathra',
        approval: 'Reviewed by Andreas',
        status: 'Superseded',
        note: 'Standard, normal and emergency change classes introduced to stop every deploy needing a meeting.',
      },
      {
        version: 'v2.1',
        date: '2026-05-05',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Emergency change retrospective made mandatory within 2 working days; clinic-impacting changes given a fixed window.',
      },
    ],
    evidence: [
      {
        name: 'change-register-2026-q2.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-07-01',
        expiryDate: '2029-07-01',
        uploader: 'Randy',
        note: 'All normal and emergency changes for the quarter with approval and outcome.',
        body: [
          'Ref | Change | Class | Approved by | Window | Outcome',
          'CHG-2026-088 | Patient service schema migration, add consent purpose | Normal | Andreas | 2026-04-11 22:00 WIB | Success',
          'CHG-2026-094 | Caddy upgrade across all edge hosts | Normal | Agil | 2026-04-25 22:00 WIB | Success',
          'CHG-2026-101 | Emergency rollback of billing release 2026.5.2 | Emergency | Randy (on-call) | 2026-05-14 09:40 WIB | Success, retrospective CHG-R-014',
          'CHG-2026-107 | Zitadel signing key rotation | Normal | Dhiaz Fathra | 2026-05-30 23:00 WIB | Success, rehearsed first',
          'CHG-2026-115 | Queue display firmware, 13 locations | Normal | Pak Andre | 2026-06-18, clinic closed | Partial, 2 units retried 2026-06-19',
          'CHG-2026-121 | Backup retention increase to 35 days | Standard | pre-authorised | 2026-06-24 | Success',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-8-32 · Change Management Procedure',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v2.1 · **Review** annual',
      '**Requirement** A.8.32 · **Also satisfies** A.8.9, A.8.31, A.8.25, ISO 9001 6.3',
      '',
      '## Purpose',
      '',
      'To control changes to production systems without turning routine delivery into paperwork.',
      'The group deploys several times a week; a process that treats every deployment as an event',
      'would be ignored within a month. So changes are classified, and the weight of the process',
      'follows the risk.',
      '',
      '## Scope',
      '',
      'Changes to production services, production infrastructure, network and identity',
      'configuration, and clinic-floor systems. Documentation-only changes and non-production',
      'work are out of scope. Changes to the ISMS documents themselves follow the document',
      'control procedure instead.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Change requester** — the engineer making the change; writes the record and the rollback.',
      '- **Approver** — Andreas for anything crossing a service contract, Agil for infrastructure,',
      '  Pak Andre for anything affecting clinic operations during opening hours, Dhiaz Fathra for',
      '  identity and cryptographic changes.',
      '- **On-call engineer (Randy)** — may authorise an emergency change alone.',
      '',
      '## Change classes',
      '',
      '- **Standard** — pre-authorised, low risk, repeatedly performed: certificate renewal,',
      '  retention setting within policy, scaling within agreed bounds. Logged, not approved.',
      '- **Normal** — everything else. Recorded in FRM-A-8-32-01 with impact, rollback and window;',
      '  approved before it runs.',
      '- **Emergency** — restoring service or closing an active vulnerability. Executed first,',
      '  recorded within 24 hours, retrospective within 2 working days.',
      '',
      '## Procedure for a normal change',
      '',
      '1. Raise the record: what changes, which services and clinics are affected, how it is',
      '   verified afterwards, and how it is rolled back. "Roll forward with a fix" is not a',
      '   rollback plan.',
      '2. Choose a window. Anything that can interrupt a clinic runs after 22:00 WIB or on a',
      '   closed day; Pak Andre confirms the date against the appointment book.',
      '3. Get the approval named above. Self-approval is not permitted for normal changes.',
      '4. Execute from the pipeline. Database migrations are additive and forward-only per',
      '   ENG-SOP-001 §6.',
      '5. Verify against the check written in step 1, and record the result — including partial',
      '   success, which is recorded as partial and not as success.',
      '6. If the verification fails, roll back immediately and reclassify the recovery as an',
      '   emergency change. Do not debug forward in production.',
      '',
      '## Records',
      '',
      'Change register, retained 3 years. Emergency retrospectives are filed with it and reviewed',
      'as a batch at each management review — a rising emergency count is treated as a signal',
      'about planning, not about the on-call engineer.',
      '',
      '## Review',
      '',
      'Annually, and after any incident caused by a change that followed this procedure — which',
      'means the procedure missed something.',
    ].join('\n'),
  },

  {
    code: 'ISMS-SOP-A-8-33',
    title: 'Test Information and Synthetic Dataset Procedure',
    clause: 'A.8.33',
    crossRefs: ['A.8.11', 'A.8.31', 'A.5.34', 'A.8.29'],
    version: 'v1.4',
    owner: 'Tika',
    form: { code: 'FRM-A-8-33-01', name: 'Test dataset generation and approval record' },
    revisions: [
      {
        version: 'v1.1',
        date: '2025-03-12',
        author: 'Tika',
        approval: 'Drafted',
        status: 'Superseded',
        note: 'Masking script written after a production extract was found in a QA spreadsheet.',
      },
      {
        version: 'v1.4',
        date: '2026-01-27',
        author: 'Tika',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Masking replaced by fully generated data; the only remaining copy route now needs Rica and Dhiaz Fathra to approve jointly.',
      },
    ],
    evidence: [
      {
        name: 'synthetic-dataset-v4-generation-record.md',
        fileType: 'MD',
        uploadedAt: '2026-01-27',
        expiryDate: '2027-01-27',
        uploader: 'Tika',
        note: 'What version 4 of the synthetic dataset contains and how it is generated.',
        body: [
          '# Synthetic dataset v4 — generation record',
          '',
          '**Generated by** `make testdata` in the platform repository · **Owner** Tika · **Seeded** deterministic, seed 4',
          '',
          '| Entity | Rows | Source of values |',
          '| --- | --- | --- |',
          '| Patients | 12,000 | Generated names from an Indonesian name corpus, no real NIK — checksum-valid but reserved range |',
          '| Treatments | 61,000 | Sampled distribution from anonymised aggregate counts, no linkage to real records |',
          '| Photographs | 400 | Synthetic images, generated, no human subject |',
          '| Orders and payments | 44,000 | Generated, gateway sandbox tokens only |',
          '| Staff | 180 | Generated, no real employee |',
          '',
          'Edge cases deliberately included: a patient with two phone numbers, a name at the column',
          'length limit, a refunded order, a treatment recorded at a closed location, a consent',
          'record withdrawn mid-history, and one patient with 300 treatments to exercise pagination.',
          '',
          'No row in this dataset originates from production. Verified by Rica, 27 January 2026.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-8-33 · Test Information and Synthetic Dataset Procedure',
      '',
      '**Owner** Tika (QA Lead) · **Approver** Aris Ihwan · **Version** v1.4 · **Review** annual',
      '**Requirement** A.8.33 · **Also satisfies** A.8.11, A.8.31, A.5.34, A.8.29',
      '',
      '## Purpose',
      '',
      'Test data has a habit of being real data with the names changed, sitting somewhere nobody',
      'is watching. In March 2025 an extract of live patient rows was found in a QA spreadsheet on',
      'a shared drive. This procedure removes the need for that extract entirely by defining a',
      'generated dataset good enough to test against, and by making the remaining copy route',
      'deliberately awkward.',
      '',
      '## Scope',
      '',
      'All test information used in staging, review environments, sandboxes, local development,',
      'vendor environments and demonstrations. It applies equally to data used in a prompt given',
      'to a coding agent.',
      '',
      '## Roles and responsibilities',
      '',
      'Tika owns the synthetic dataset and its generator. Randy maintains the generator code.',
      'Rica verifies that no generated value traces back to a real person. Dhiaz Fathra and Rica',
      'jointly approve the rare exception where production data must be restored for diagnosis.',
      '',
      '## Procedure',
      '',
      '1. **Default: generate, do not copy.** `make testdata` in the platform repository builds',
      '   dataset v4 from a fixed seed. It is deterministic, so a failing test reproduces.',
      '2. **The dataset must carry the awkward cases**, not just the happy path — boundary-length',
      '   names, withdrawn consent, refunds, a patient with hundreds of records. A dataset that',
      '   only contains tidy rows produces tests that only pass on tidy rows.',
      '3. **Identifiers are structurally valid but reserved.** NIK values pass checksum validation',
      '   and fall in a range that cannot be issued; phone numbers use the documentation prefix.',
      '4. **No production personal data leaves production.** Not into staging, not into a laptop,',
      '   not into a spreadsheet, not into an agent prompt, not into a screenshot in a ticket.',
      '5. **Exception route.** Where a defect cannot be reproduced synthetically, Rica and Dhiaz',
      '   Fathra both approve in writing; the restore goes into an isolated environment, access is',
      '   limited to the named engineers, the environment is destroyed within 72 hours, and the',
      '   record is filed in FRM-A-8-33-01. Three such restores were approved in the last 12 months.',
      '6. **Demonstrations use the dataset**, including demonstrations to the board and to',
      '   prospective partners.',
      '7. **Regenerate quarterly** so that stale assumptions in the fixtures surface.',
      '',
      '## Records',
      '',
      'Generation records and dataset version notes (3 years), exception approvals with their',
      'destruction confirmations (5 years, held by Rica).',
      '',
      '## Review',
      '',
      'Annually by Tika with Rica, and whenever a new data class enters the platform.',
    ].join('\n'),
  },

  {
    code: 'ISMS-SOP-A-8-34',
    title: 'Safeguards for Audit and Assessment Testing',
    clause: 'A.8.34',
    crossRefs: ['A.5.35', 'A.8.29', 'A.8.15', '9.2'],
    version: 'v1.1',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-8-34-01', name: 'Audit testing rules of engagement' },
    revisions: [
      {
        version: 'v1.0',
        date: '2025-10-20',
        author: 'Dhiaz Fathra',
        approval: 'Drafted',
        status: 'Superseded',
        note: 'Written after an internal audit query locked a billing table for eleven minutes during clinic hours.',
      },
      {
        version: 'v1.1',
        date: '2026-02-09',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Read-only auditor role defined in Zitadel; penetration testing rules of engagement folded in.',
      },
    ],
    evidence: [
      {
        name: 'rules-of-engagement-external-pentest-2026.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-03-02',
        uploader: 'Dhiaz Fathra',
        note: 'Signed rules of engagement for the 2026 external test, including the stop conditions.',
      },
      {
        name: 'audit-access-log-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-30',
        expiryDate: '2029-06-30',
        uploader: 'Agil',
        note: 'Every audit or assessment access granted this year, with scope, window and revocation.',
        body: [
          'Ref | Assessor | Systems | Access | Window | Revoked | Incidents',
          'AUD-2026-01 | Internal audit (Tika) | billing, patient read models | auditor-readonly, staging replica | 2026-02-16 to 2026-02-20 | 2026-02-20 | none',
          'AUD-2026-02 | External pentest vendor | Super App, public API | Test accounts, no infra access | 2026-03-09 to 2026-03-20 | 2026-03-20 | 1 rate-limit trip, agreed',
          'AUD-2026-03 | Certification body, stage 1 | Document review only | Read-only KMS app account | 2026-05-11 | 2026-05-12 | none',
          'AUD-2026-04 | Internal audit (Tika) | change and access records | auditor-readonly | 2026-06-22 to 2026-06-26 | 2026-06-26 | none',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-8-34 · Safeguards for Audit and Assessment Testing',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v1.1 · **Review** annual',
      '**Requirement** A.8.34 · **Also satisfies** A.5.35, A.8.29, A.8.15, ISO 9001 9.2',
      '',
      '## Purpose',
      '',
      'Auditing a live clinic platform can itself cause the disruption it is meant to prevent. In',
      'October 2025 an internal audit query held a lock on the billing table for eleven minutes',
      'during opening hours and reception could not close payments. This procedure sets how audit',
      'and assessment activity is planned and executed so that it produces evidence without',
      'producing an incident.',
      '',
      '## Scope',
      '',
      'Internal audits, external certification audits, penetration tests, vulnerability scans,',
      'supplier assessments and any regulator inspection touching group systems.',
      '',
      '## Roles and responsibilities',
      '',
      'Dhiaz Fathra agrees and signs the rules of engagement for every assessment. Agil provisions',
      'and revokes assessor access. Randy is the technical contact during a test and holds the',
      'authority to stop it. Tika, as internal auditor, plans internal audit access against the',
      'same rules. Pak Andre is told before anything runs that could affect a clinic.',
      '',
      '## Procedure',
      '',
      '1. **Agree the rules of engagement in writing before any access is granted.** They state:',
      '   systems in scope, systems explicitly excluded, permitted techniques, the window in WIB,',
      '   the named technical contact, and the stop conditions.',
      '2. **Prefer a replica.** Read-heavy audit work runs against the staging replica or the',
      '   read models, never against the production write path. Where production is unavoidable,',
      '   queries are reviewed by Randy and run outside 09:00–20:00 WIB.',
      '3. **Access is read-only, scoped and time-boxed.** Assessors receive the',
      '   `auditor-readonly` role in Zitadel, valid only for the agreed window, and never a shared',
      '   account. Every access is recorded in the audit access log.',
      '4. **Destructive techniques are excluded by default** — no denial-of-service testing, no',
      '   data modification, no social engineering of clinic staff without separate written',
      '   authorisation from Aris Ihwan.',
      '5. **Everything the assessor does is logged**, on the group’s side as well as the',
      '   assessor’s, so that a later alert can be attributed rather than investigated twice.',
      '   Monitoring stays on; alerts are annotated, not suppressed.',
      '6. **Stop conditions are absolute.** Randy or the on-call engineer stops the test',
      '   immediately on patient-facing degradation, any unintended write, or any sign of real',
      '   data leaving the environment. Stopping is never treated as an audit obstruction.',
      '7. **Close out.** Access revoked within one working day of the window closing, assessor',
      '   confirms destruction of any extracted data, and the log is updated. Findings go into the',
      '   corrective action process, not into a private mail thread.',
      '',
      '## Records',
      '',
      'Signed rules of engagement and audit access log (retained 3 years), assessor activity logs',
      '(12 months), and findings tracked to closure in the corrective action register.',
      '',
      '## Review',
      '',
      'Annually by Dhiaz Fathra with Tika, and after any assessment that caused an operational',
      'impact.',
    ].join('\n'),
  },
]
