import type { SeedDocument } from './types'

/** Annex A.8 technological controls, first batch: endpoints, access, capacity, hygiene. */
export const ANNEX_A8_A: SeedDocument[] = [
  {
    code: 'ISMS-SOP-A-8-1',
    title: 'End User Device Standard and Enrolment Procedure',
    clause: 'A.8.1',
    crossRefs: ['A.6.7', 'A.7.9', 'A.8.7', 'A.5.10'],
    version: 'v2.0',
    owner: 'Agil',
    form: { code: 'FRM-A-8-1-01', name: 'Device enrolment and return record' },
    revisions: [
      {
        version: 'v1.2',
        date: '2024-09-12',
        author: 'Agil',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Written when laptops were still handed out unmanaged; enrolment was a checklist on paper.',
      },
      {
        version: 'v2.0',
        date: '2026-03-19',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'MDM enrolment made a precondition of network access; personal-device use narrowed to the Super App only.',
      },
    ],
    evidence: [
      {
        name: 'device-fleet-register-2026-q2.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-04-07',
        expiryDate: '2026-10-07',
        uploader: 'Agil',
        note: 'Quarterly reconciliation of issued devices against MDM enrolment and disk encryption state.',
        body: [
          'Asset tag | Holder | Type | OS | Encrypted | MDM | Last check-in | Note',
          'DM-LT-0041 | Dhiaz Fathra | Laptop | macOS 15 | Yes | Enrolled | 2026-04-06 | —',
          'DM-LT-0052 | Randy | Laptop | macOS 15 | Yes | Enrolled | 2026-04-07 | On-call device, second SSH key',
          'DM-LT-0058 | Tika | Laptop | Ubuntu 24.04 | Yes | Enrolled | 2026-04-05 | LUKS, verified manually',
          'DM-LT-0060 | Andreas | Laptop | macOS 15 | Yes | Enrolled | 2026-04-07 | —',
          'DM-DT-0012 | Clinic Kelapa Gading | Desktop | Windows 11 | Yes | Enrolled | 2026-04-03 | Reception, shared login removed Feb 2026',
          'DM-DT-0019 | Clinic Bandung | Desktop | Windows 11 | No | Enrolled | 2026-03-28 | Nonconformity NC-2026-011, BitLocker enabled 2026-04-09',
          'DM-TB-0007 | Pak Andre | Tablet | iPadOS 18 | Yes | Enrolled | 2026-04-06 | Consultation room, kiosk profile',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-8-1 · End User Device Standard and Enrolment Procedure',
      '',
      '**Owner** Agil · **Approver** Aris Ihwan · **Version** v2.0 · **Review** every 6 months',
      '**Requirement** A.8.1 · **Also satisfies** A.6.7, A.7.9, A.8.7, A.5.10',
      '',
      '## Purpose',
      '',
      'Most of the information this organisation holds — patient records in the Super App admin,',
      'treatment pricing, engineering credentials — is reached from a laptop, a reception desktop',
      'or a consultation-room tablet. A device that is lost unencrypted, or that never receives a',
      'patch because nobody knows it exists, is the cheapest route into all of it. This procedure',
      'says what a device must be before it is allowed to hold company data, and how it is',
      'enrolled, checked and taken back.',
      '',
      '## Scope',
      '',
      'Every laptop, desktop, tablet and phone issued by the organisation, at head office and at',
      'all clinic locations. It also covers a personal phone used to reach the Super App or company',
      'mail. It does not cover clinical devices governed by their own maintenance regime, or',
      'servers and containers, which are covered by ISMS-SOP-A-8-9.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Agil** (Infrastructure Engineer) keeps the fleet register, runs enrolment and the',
      '  quarterly reconciliation.',
      '- **Dhiaz Fathra** approves any exception and reviews the reconciliation result.',
      '- **Pak Andre** confirms which clinic staff need a device and tells Agil the same working',
      '  day a device is lost or a holder leaves.',
      '- The device holder is responsible for physical custody and for not disabling controls.',
      '',
      '## Procedure',
      '',
      '1. **Request.** The department head raises the request naming the holder, the role and the',
      '   systems the device must reach. Agil records it against the fleet register.',
      '2. **Build.** Agil applies the baseline before handover: full-disk encryption (FileVault,',
      '   BitLocker or LUKS), automatic OS updates on, screen lock at 5 minutes, local firewall on,',
      '   endpoint protection installed per ISMS-POL-A-8-7, and no local administrator rights for',
      '   the holder.',
      '3. **Enrol.** The device is enrolled in MDM and issued an asset tag. An unenrolled device is',
      '   not given a Zitadel device certificate, and without that certificate it cannot reach',
      '   internal services.',
      '4. **Hand over.** The holder signs FRM-A-8-1-01, which lists the asset tag, the baseline',
      '   applied and the acceptable-use terms. A copy goes to the holder.',
      '5. **Operate.** MDM reports check-in, OS version and encryption state daily. A device that',
      '   has not checked in for 21 days is chased by Agil; at 45 days its certificate is revoked.',
      '6. **Reconcile.** Once a quarter Agil compares the register against MDM and against the HR',
      '   staff list, and records the result as evidence. Differences are closed within 10 working',
      '   days or raised as a nonconformity.',
      '7. **Return or dispose.** On the holder leaving or changing role, the device is returned',
      '   within 2 working days, wiped, and the return half of FRM-A-8-1-01 is signed. Disposal',
      '   follows the media rules in the physical security set.',
      '',
      '## Personal devices',
      '',
      'A personal phone may be used for the Super App and company mail only, and only with a device',
      'passcode and remote wipe of the company profile enabled. Personal laptops are not permitted',
      'to hold patient or commercial data under any circumstances; there is no exception route.',
      '',
      '## Records',
      '',
      'FRM-A-8-1-01 signed enrolment and return records, and the quarterly fleet reconciliation,',
      'are held in the compliance repository for 3 years after the device leaves the fleet.',
      '',
      '## Review',
      '',
      'Every 6 months by Agil, and immediately after any lost-device incident.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-8-2',
    title: 'Privileged Access Management Procedure',
    clause: 'A.8.2',
    crossRefs: ['A.5.15', 'A.5.18', 'A.8.18', 'A.5.3'],
    version: 'v3.0',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-8-2-01', name: 'Privileged access grant and review record' },
    revisions: [
      {
        version: 'v2.0',
        date: '2025-02-06',
        author: 'Randy',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Standing production admin was still the norm; the review was annual and done from memory.',
      },
      {
        version: 'v3.0',
        date: '2026-05-11',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Standing admin withdrawn in favour of time-boxed elevation; quarterly recertification made evidence-bearing.',
      },
    ],
    evidence: [
      {
        name: 'privileged-access-recertification-2026-q2.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-05-29',
        expiryDate: '2026-08-29',
        uploader: 'Dhiaz Fathra',
        note: 'Quarterly recertification of every privileged role, with the decision recorded per holder.',
        body: [
          'System | Privileged role | Holder | Basis | Decision | Actioned',
          'AWS ap-southeast-1 | AdministratorAccess | Agil | Infrastructure owner | Retained, break-glass only | 2026-05-29',
          'AWS ap-southeast-1 | AdministratorAccess | Randy | On-call escalation | Converted to 4h elevation | 2026-05-30',
          'PostgreSQL production | rds_superuser | Agil | Schema migrations | Retained | 2026-05-29',
          'PostgreSQL production | rds_superuser | Andreas | Legacy from migration project | Revoked | 2026-05-30',
          'Zitadel | Org owner | Dhiaz Fathra | ISMS representative | Retained | 2026-05-29',
          'Zitadel | Org owner | Randy | Added during outage Jan 2026 | Revoked | 2026-05-30',
          'GitHub org | Owner | Dhiaz Fathra, Andreas | Two-person rule | Retained | 2026-05-29',
          'Clinic PMS | Superuser | Pak Andre | Operations head | Retained, scoped to own locations | 2026-06-02',
        ].join('\n'),
      },
      {
        name: 'break-glass-drill-minute-2026-04.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-04-22',
        uploader: 'Randy',
        note: 'Signed minute of the half-yearly break-glass drill, including the credential rotation that followed.',
      },
    ],
    body: [
      '# ISMS-SOP-A-8-2 · Privileged Access Management Procedure',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v3.0 · **Review** quarterly',
      '**Requirement** A.8.2 · **Also satisfies** A.5.15, A.5.18, A.8.18, A.5.3',
      '',
      '## Purpose',
      '',
      'A privileged account can read every patient record, drop every table and erase the log that',
      'would have shown it. The organisation therefore treats privilege as something borrowed for a',
      'stated task and handed back, not as a property of a job title. This procedure sets out how',
      'privilege is requested, granted, used, recorded and withdrawn.',
      '',
      '## Scope',
      '',
      'Administrative rights on AWS ap-southeast-1, production PostgreSQL, Zitadel, the GitHub',
      'organisation, the clinic practice management system, and any service account that can act',
      'across tenants. Ordinary application roles are covered by ISMS-POL-A-8-3.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Dhiaz Fathra** owns this procedure and chairs the quarterly recertification.',
      '- **Agil** holds the standing infrastructure administrator role and operates the elevation',
      '  tooling.',
      '- **Randy** is the on-call engineer and the usual requester of out-of-hours elevation.',
      '- **Aris Ihwan** approves any grant that would give one person both change and approval',
      '  rights over the same system.',
      '',
      '## Procedure',
      '',
      '1. **No standing admin by default.** Except for the two break-glass identities named in the',
      '   recertification record, privileged roles are not held permanently. An engineer requests',
      '   elevation for a stated task.',
      '2. **Request and approval.** Elevation is requested in the engineering channel with the task,',
      '   the system and the duration. Dhiaz Fathra or Agil approves. Out of hours, the on-call',
      '   engineer may self-elevate and must post the reason within 30 minutes.',
      '3. **Time box.** Elevation expires automatically after 4 hours. There is no renewal without a',
      '   fresh request.',
      '4. **Separate identity.** Privileged work is done under a distinct account (`ops-<name>`),',
      '   never under the everyday account, so that logs separate routine work from administrative',
      '   work.',
      '5. **Multi-factor always.** Every privileged account requires a hardware or TOTP second',
      '   factor at each elevation, not once per session.',
      '6. **Break glass.** Two sealed break-glass credentials exist for AWS and Zitadel. Use is',
      '   alarmed to Dhiaz Fathra and Aris Ihwan, and the credential is rotated within 24 hours of',
      '   use. A drill is run every 6 months and minuted.',
      '7. **Recertify quarterly.** Every privileged role and holder is listed, and each line gets an',
      '   explicit retain, scope-down or revoke decision. Revocations are actioned within 2 working',
      '   days and the record signed off.',
      '8. **Leavers.** Privilege is withdrawn on the last working day, before the general access',
      '   removal, and confirmed by Agil the same day.',
      '',
      '## Records',
      '',
      'FRM-A-8-2-01 grant records, the quarterly recertification workbook and break-glass drill',
      'minutes are retained for 3 years. Elevation events themselves are held in the audit log',
      'under the retention set by the logging control.',
      '',
      '## Review',
      '',
      'Quarterly by Dhiaz Fathra alongside the recertification, and after any incident where',
      'privilege was a contributing factor.',
    ].join('\n'),
  },
  {
    code: 'ISMS-POL-A-8-3',
    title: 'Information Access Restriction Policy',
    clause: 'A.8.3',
    crossRefs: ['A.5.15', 'A.5.12', 'A.8.11', 'A.5.18'],
    version: 'v2.2',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-8-3-01', name: 'Role-to-data entitlement matrix' },
    revisions: [
      {
        version: 'v2.0',
        date: '2025-06-30',
        author: 'Andreas',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Entitlements were expressed per screen; two roles could reach patient notes through a report export.',
      },
      {
        version: 'v2.2',
        date: '2026-04-15',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Entitlements restated per data class and enforced at the service boundary; export paths brought under the same check.',
      },
    ],
    evidence: [
      {
        name: 'role-entitlement-matrix-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-04-15',
        expiryDate: '2027-04-15',
        uploader: 'Rica',
        note: 'Approved matrix of what each role may read, write and export, by data class.',
        body: [
          'Role | Patient clinical | Patient identity | Pricing | Staff records | Export permitted',
          'Practitioner | Read/write, own patients | Read, own patients | None | Own record only | No',
          'Reception | None | Read/write, own location | Read | Own record only | No',
          'Clinic manager | Summary counts only | Read, own location | Read | Own location | Aggregates only',
          'Finance (Pak Rila) | None | Name and invoice ref only | Read/write | Payroll fields | Yes, invoiced totals',
          'Product (Wiwin) | None | Pseudonymised only | Read/write | None | Yes, pseudonymised',
          'Engineering on-call | Break-glass, logged | Break-glass, logged | Read | None | No',
          'QA (Tika) | Masked test data only | Masked test data only | Read | None | No',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-A-8-3 · Information Access Restriction Policy',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v2.2 · **Review** twice a year',
      '**Requirement** A.8.3 · **Also satisfies** A.5.15, A.5.12, A.8.11, A.5.18',
      '',
      '## Purpose',
      '',
      'Access control that is drawn per screen leaks: the same data comes back out through a report,',
      'an export or an API a role was never meant to hold. This policy states entitlements in terms',
      'of the data itself, so that a restriction holds whichever door the data is asked for through.',
      '',
      '## Scope',
      '',
      'All application data in the Super App, the clinic practice management system, the data',
      'warehouse and every reporting or export path over them. Infrastructure-level administrative',
      'access is out of scope and sits with ISMS-SOP-A-8-2.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Dhiaz Fathra** owns the policy and approves the entitlement matrix.',
      '- **Rica** approves every entitlement that touches personal data and keeps the matrix current.',
      '- **Wiwin** and **Pak Rila** are the business owners of the commercial and finance data',
      '  classes and approve access to them.',
      '- **Andreas** ensures the service design enforces the matrix rather than the user interface.',
      '',
      '## Policy',
      '',
      '1. **Least privilege by data class.** Entitlements are recorded in FRM-A-8-3-01 against the',
      '   classes set by the classification policy, not against menus. A role gets the narrowest',
      '   class that lets it do its job.',
      '2. **Enforced at the service boundary.** Authorisation is decided in the owning service from',
      '   the Zitadel token, before data is read. A UI that hides a control is a convenience, never',
      '   the control itself.',
      '3. **Location and patient scoping.** Clinical and identity data are scoped to the requester’s',
      '   location, and clinical notes further to the practitioner’s own patient list.',
      '4. **Exports are access.** Any report, CSV or warehouse query is subject to the same matrix.',
      '   Exports of personal data outside the aggregate and pseudonymised cases in the matrix need',
      '   Rica’s written approval per instance.',
      '5. **Break glass is visible.** Where an engineer must read live clinical data to resolve an',
      '   incident, access is time-boxed to 2 hours, alarmed to Dhiaz Fathra, and reviewed in the',
      '   post-incident record.',
      '6. **No shared logins.** Every access is attributable to a named person. Shared reception',
      '   logins were withdrawn in February 2026 and must not be reintroduced.',
      '7. **Recertification.** Entitlements are reviewed twice a year with the business owners; the',
      '   review either reconfirms or changes each line, and silence is not reconfirmation.',
      '',
      '## Records',
      '',
      'The approved entitlement matrix, per-instance export approvals and the half-yearly review',
      'record are held in the compliance repository. Personal-data approvals are retained for 5',
      'years to match the privacy retention schedule.',
      '',
      '## Review',
      '',
      'Twice a year by Dhiaz Fathra with Rica, and whenever a new data class or reporting surface is',
      'introduced.',
    ].join('\n'),
  },
  {
    code: 'ISMS-POL-A-8-4',
    title: 'Source Code Access and Repository Control Policy',
    clause: 'A.8.4',
    crossRefs: ['A.8.31', 'A.8.25', 'A.5.32', 'A.8.28'],
    version: 'v1.4',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-8-4-01', name: 'Repository access and branch protection register' },
    revisions: [
      {
        version: 'v1.2',
        date: '2024-11-05',
        author: 'Andreas',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Covered repository permissions only; said nothing about secrets in history or about contractors.',
      },
      {
        version: 'v1.4',
        date: '2026-02-27',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Secret scanning made blocking, contractor access time-boxed, and branch protection listed per repository.',
      },
    ],
    evidence: [
      {
        name: 'repository-access-register-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-02-27',
        expiryDate: '2026-08-27',
        uploader: 'Andreas',
        note: 'Every repository with its visibility, protected branch settings and who holds write access.',
        body: [
          'Repository | Visibility | Protected branch | Required reviews | Write access | Secret scanning',
          'super-app-api | Private | main | 2 | Backend team (5) | Blocking',
          'super-app-web | Private | main | 1 | Frontend team (3) | Blocking',
          'clinic-integrations | Private | main | 2 | Randy, Andreas | Blocking',
          'infra-terraform | Private | main | 2 | Agil, Dhiaz Fathra | Blocking',
          'iso-compliance-kms | Private | main | 1 | Dhiaz Fathra, Tika | Blocking',
          'data-pipeline | Private | main | 1 | Tika, Wiwin | Blocking',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-A-8-4 · Source Code Access and Repository Control Policy',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v1.4 · **Review** every 6 months',
      '**Requirement** A.8.4 · **Also satisfies** A.8.31, A.8.25, A.5.32, A.8.28',
      '',
      '## Purpose',
      '',
      'The source repositories describe how patient data is stored, how authentication is decided',
      'and where the integrations reach. Read access to them is close to a design document for an',
      'attack; write access to them is production, one merge away. This policy sets who may read,',
      'who may write, and what the repository must enforce regardless of who is pushing.',
      '',
      '## Scope',
      '',
      'All repositories in the organisation’s GitHub organisation, the CI configuration attached to',
      'them, and any copy of the code on a developer machine or in a contractor’s environment.',
      'Third-party dependencies are governed by the supplier controls, not here.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Dhiaz Fathra** and **Andreas** hold GitHub organisation owner, deliberately two people so',
      '  neither can act alone unobserved.',
      '- **Agil** owns the CI runners and the secrets they may read.',
      '- **Tika** verifies that the required checks on protected branches are actually running.',
      '- Every engineer is responsible for not committing a credential and for reporting one that',
      '  reaches history.',
      '',
      '## Policy',
      '',
      '1. **Private by default.** No repository is public without Aris Ihwan’s written approval and',
      '   a licence review. Nothing under an internal namespace is mirrored to a personal account.',
      '2. **Write by team, not by person.** Access is granted through a GitHub team that maps to a',
      '   role. Direct per-person grants are removed at the half-yearly review.',
      '3. **Protected main.** `main` is protected on every repository: no force push, no deletion,',
      '   at least one review — two on `super-app-api`, `clinic-integrations` and `infra-terraform`',
      '   — and all required checks green before merge.',
      '4. **No self-merge on the two-review repositories.** The author’s own approval does not count',
      '   toward the required reviews.',
      '5. **Secrets never in code.** Secret scanning and a pre-commit hook run on every push and',
      '   block the merge. A credential that reaches history is rotated within 4 hours of discovery',
      '   and the incident recorded, whether or not the repository is private.',
      '6. **Contractors are time-boxed.** External developers get access to named repositories only,',
      '   expiring after 90 days, with an NDA in place and no organisation-owner rights.',
      '7. **Leavers.** GitHub access is revoked on the last working day and any personal access',
      '   token they issued is deleted, not merely left to expire.',
      '',
      '## Records',
      '',
      'The repository access register, secret-rotation incident notes and the half-yearly access',
      'review are kept in the compliance repository for 3 years.',
      '',
      '## Review',
      '',
      'Every 6 months by Andreas with Dhiaz Fathra, and whenever a repository is created or a',
      'contractor engagement starts.',
    ].join('\n'),
  },
  {
    code: 'ISMS-POL-A-8-5',
    title: 'Authentication Standard',
    clause: 'A.8.5',
    crossRefs: ['A.5.17', 'A.5.16', 'A.8.2', 'A.8.24'],
    version: 'v3.1',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-8-5-01', name: 'Authentication method approval record' },
    revisions: [
      {
        version: 'v3.0',
        date: '2025-08-14',
        author: 'Andreas',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Zitadel adopted as the single identity provider; forced 90-day password rotation still in force.',
      },
      {
        version: 'v3.1',
        date: '2026-05-05',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Scheduled password expiry dropped in favour of breach-list screening; passkeys allowed for engineering.',
      },
    ],
    evidence: [
      {
        name: 'zitadel-policy-baseline-2026-05.md',
        fileType: 'MD',
        uploadedAt: '2026-05-05',
        expiryDate: '2027-05-05',
        uploader: 'Randy',
        note: 'Exported identity provider settings compared against this standard, line by line.',
        body: [
          '# Zitadel policy baseline — May 2026',
          '',
          '| Setting | Required | Configured | Result |',
          '| --- | --- | --- | --- |',
          '| Minimum password length | 12 | 12 | Pass |',
          '| Complexity rules | Off | Off | Pass |',
          '| Breach-list screening | On | On | Pass |',
          '| Password expiry | None | None | Pass |',
          '| MFA for staff | Required | Required | Pass |',
          '| MFA for patients | Optional, prompted | Optional, prompted | Pass |',
          '| Failed-attempt lockout | 10 attempts / 15 min | 10 / 15 min | Pass |',
          '| Session lifetime, admin | 8 hours | 8 hours | Pass |',
          '| Session lifetime, clinic | 12 hours, idle 30 min | 12 h / 30 min | Pass |',
          '| Passkey (WebAuthn) | Allowed | Enabled for engineering org | Pass |',
          '',
          'One deviation found and closed: the legacy PMS bridge still accepted a static API key.',
          'Replaced with a Zitadel service user and short-lived token on 2026-05-04.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-A-8-5 · Authentication Standard',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v3.1 · **Review** yearly',
      '**Requirement** A.8.5 · **Also satisfies** A.5.17, A.5.16, A.8.2, A.8.24',
      '',
      '## Purpose',
      '',
      'Every route into the organisation’s systems — a patient booking a treatment, a receptionist',
      'opening a record, an engineer reaching production — passes an authentication decision. This',
      'standard fixes how that decision is made so it is the same everywhere and can be tested from',
      'one place.',
      '',
      '## Scope',
      '',
      'Human and machine authentication to the Super App, the clinic practice management system,',
      'internal engineering tooling, AWS, and the marketplace integrations. Physical entry is out of',
      'scope.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Dhiaz Fathra** owns this standard and approves any authentication method not listed here.',
      '- **Andreas** designs how services consume Zitadel tokens.',
      '- **Randy** operates the identity provider day to day and produces the yearly baseline check.',
      '- **Pak Andre** ensures clinic staff hold their own credentials and do not share a terminal',
      '  session.',
      '',
      '## Policy',
      '',
      '1. **One identity provider.** Zitadel is the only authority for staff and patient identity.',
      '   A service that implements its own login is a nonconformity, not a variation.',
      '2. **Passwords.** Minimum 12 characters, screened against a known-breach list at set time.',
      '   No composition rules and no scheduled expiry — both push people toward predictable',
      '   variants. A password is changed on suspicion of compromise, immediately.',
      '3. **Second factor.** Required for every staff account without exception, including clinic',
      '   reception. TOTP or a hardware key; SMS is accepted only for patient accounts, and even',
      '   there only as a fallback.',
      '4. **Passkeys.** WebAuthn passkeys are permitted and preferred for engineering accounts and',
      '   satisfy the second-factor requirement on their own.',
      '5. **Lockout and rate limiting.** Ten failed attempts in 15 minutes locks the account; the',
      '   lock is released by Randy after identity confirmation, not automatically.',
      '6. **Sessions.** Administrative sessions last at most 8 hours. Clinic sessions last 12 hours',
      '   with a 30-minute idle timeout, because a terminal left open at reception is the realistic',
      '   risk in that setting.',
      '7. **Machine identity.** Service-to-service calls use short-lived Zitadel tokens. Static API',
      '   keys are prohibited; the last one, in the PMS bridge, was removed in May 2026.',
      '8. **Credential transport.** An initial credential is issued out of band and must be changed',
      '   at first use. Credentials are never sent over chat or email in readable form.',
      '',
      '## Records',
      '',
      'The yearly Zitadel baseline check, method approval records on FRM-A-8-5-01, and lockout',
      'release notes are kept for 3 years in the compliance repository.',
      '',
      '## Review',
      '',
      'Yearly by Dhiaz Fathra, and on any change to the identity provider or to a login flow.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-8-6',
    title: 'Capacity and Performance Management Procedure',
    clause: 'A.8.6',
    crossRefs: ['A.8.16', 'A.8.14', '9001 9.1.3', 'A.5.30'],
    version: 'v1.3',
    owner: 'Agil',
    form: { code: 'FRM-A-8-6-01', name: 'Capacity forecast and headroom review' },
    revisions: [
      {
        version: 'v1.1',
        date: '2025-03-20',
        author: 'Agil',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Capacity was watched reactively; the first Ramadan promotion peak was absorbed by scaling during the incident.',
      },
      {
        version: 'v1.3',
        date: '2026-01-26',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Monthly forecast introduced, with thresholds tied to the promotional calendar and to new clinic openings.',
      },
    ],
    evidence: [
      {
        name: 'capacity-headroom-2026-q1.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-02-02',
        expiryDate: '2026-05-02',
        uploader: 'Agil',
        note: 'Quarterly headroom position per resource against the 6-month forecast.',
        body: [
          'Resource | Current peak | Provisioned | Headroom | 6-month forecast | Action',
          'API pods (super-app-api) | 62% CPU | 12 pods | 38% | 78% at 16 clinics | Raise HPA ceiling to 18',
          'PostgreSQL primary | 71% CPU, 340 GB | db.r6g.2xlarge, 500 GB | 29% | 88% | Resize to 4xlarge before Q3',
          'PostgreSQL storage | 340 GB | 500 GB | 32% | 470 GB | Autoscaling to 1 TB enabled',
          'NATS throughput | 2.1k msg/s | 8k msg/s | 74% | 3.4k msg/s | None',
          'S3 media | 4.2 TB | Unmetered | n/a | 6.8 TB | Lifecycle to IA at 90 days',
          'Warehouse ETL window | 3h 40m | 6h window | 39% | 5h 10m | Split patient dimension load',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-8-6 · Capacity and Performance Management Procedure',
      '',
      '**Owner** Agil · **Approver** Aris Ihwan · **Version** v1.3 · **Review** quarterly',
      '**Requirement** A.8.6 · **Also satisfies** A.8.16, A.8.14, 9001 9.1.3, A.5.30',
      '',
      '## Purpose',
      '',
      'Availability of the booking and clinic systems is an information security property here, not',
      'only a service one: a receptionist who cannot open the system falls back to paper, and paper',
      'in a waiting room is an uncontrolled record. Demand in this business is not smooth — a',
      'promotion or a new clinic opening moves load in a step. This procedure makes capacity a',
      'planned position rather than a reaction.',
      '',
      '## Scope',
      '',
      'Compute, database, message bus, object storage and the warehouse ETL window for all',
      'production workloads in AWS ap-southeast-1, plus the network links at each clinic. Individual',
      'end user devices are out of scope.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Agil** runs the forecast, holds the thresholds and executes scaling changes.',
      '- **Wiwin** gives the promotional and marketing calendar 6 weeks ahead so demand can be',
      '  anticipated rather than discovered.',
      '- **Pak Andre** notifies planned clinic openings and any change to opening hours.',
      '- **Tika** reports latency and error-rate trends from the measurement workbook.',
      '- **Dhiaz Fathra** approves spend above the standing infrastructure budget.',
      '',
      '## Procedure',
      '',
      '1. **Measure continuously.** CPU, memory, connection count, queue depth, disk usage, p95',
      '   latency and error rate are collected for every production resource and retained 13 months',
      '   so year-on-year seasonality is visible.',
      '2. **Forecast monthly.** On the first working day of each month Agil projects 6 months ahead',
      '   from the trailing trend, the promotional calendar and the clinic opening plan.',
      '3. **Thresholds.** Sustained peak use above 70% of a provisioned resource opens a capacity',
      '   action; above 85% it becomes a priority action with a date. Below 25% for two consecutive',
      '   months triggers a downsizing review — over-provisioning is a cost risk, not a safety net.',
      '4. **Act.** Horizontal scaling limits are raised by pull request against `infra-terraform`;',
      '   instance resizes are scheduled in a change window under the change control procedure.',
      '5. **Prepare for known peaks.** For a promotion of expected uplift above 2x, autoscaling',
      '   floors are raised 48 hours before it starts and held for 24 hours after it ends.',
      '6. **Review quarterly.** Headroom per resource is tabled at the management review with the',
      '   actions taken and outstanding.',
      '',
      '## Records',
      '',
      'Monthly forecasts and the quarterly headroom workbook are held in the compliance repository',
      'for 3 years. Raw metrics are retained 13 months in the monitoring platform.',
      '',
      '## Review',
      '',
      'Quarterly by Agil, and after any incident whose cause was exhaustion of a resource.',
    ].join('\n'),
  },
  {
    code: 'ISMS-POL-A-8-7',
    title: 'Malware Protection Policy',
    clause: 'A.8.7',
    crossRefs: ['A.8.1', 'A.8.19', 'A.6.3', 'A.8.23'],
    version: 'v2.1',
    owner: 'Agil',
    form: { code: 'FRM-A-8-7-01', name: 'Endpoint protection coverage and detection log' },
    revisions: [
      {
        version: 'v2.0',
        date: '2025-05-08',
        author: 'Agil',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Covered Windows reception desktops only; engineering laptops and container images were unaddressed.',
      },
      {
        version: 'v2.1',
        date: '2026-04-02',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Extended to macOS and Linux endpoints and to container image scanning in CI; detection handling steps added.',
      },
    ],
    evidence: [
      {
        name: 'malware-detection-log-2026-h1.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-30',
        expiryDate: '2027-06-30',
        uploader: 'Agil',
        note: 'Every detection in the first half of 2026 with its handling and outcome.',
        body: [
          'Date | Device | Detection | Source | Action | Closed',
          '2026-01-19 | DM-DT-0012 | Trojan:Win32/Wacatac | Email attachment, invoice lure | Quarantined, device reimaged | 2026-01-20',
          '2026-02-11 | DM-LT-0052 | PUA:MacOS/Adload | Downloaded utility | Removed, awareness note to team | 2026-02-11',
          '2026-03-04 | CI runner | Vulnerable base image, CVE-2026-1094 | Container scan | Base image bumped, build blocked | 2026-03-04',
          '2026-05-22 | DM-DT-0019 | Trojan:Win32/Phonzy | USB stick from supplier | Quarantined, USB use blocked at clinics | 2026-05-23',
        ].join('\n'),
      },
      {
        name: 'usb-restriction-decision-2026-05.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-05-26',
        uploader: 'Dhiaz Fathra',
        note: 'Signed decision to block removable media at clinic desktops following the May detection.',
      },
    ],
    body: [
      '# ISMS-POL-A-8-7 · Malware Protection Policy',
      '',
      '**Owner** Agil · **Approver** Aris Ihwan · **Version** v2.1 · **Review** yearly',
      '**Requirement** A.8.7 · **Also satisfies** A.8.1, A.8.19, A.6.3, A.8.23',
      '',
      '## Purpose',
      '',
      'The realistic malware routes into this organisation are a phishing attachment opened at a',
      'reception desk, a utility downloaded onto an engineering laptop, and a compromised base image',
      'pulled into a build. All three have occurred. This policy states the protection required on',
      'each of those routes and what happens when something is found.',
      '',
      '## Scope',
      '',
      'All company endpoints, all container images built or run by the organisation, email and web',
      'traffic, and removable media at clinic locations. Patient-owned devices are out of scope.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Agil** operates endpoint protection and the image scanning in CI, and keeps the detection',
      '  log.',
      '- **Randy** is the first responder to a detection out of hours.',
      '- **Pak Andre** enforces the removable-media rule at clinic locations.',
      '- **Dhiaz Fathra** decides when a detection is escalated to an incident under the incident',
      '  procedure.',
      '',
      '## Policy',
      '',
      '1. **Every endpoint protected.** Managed endpoint protection with real-time scanning runs on',
      '   every Windows, macOS and Linux endpoint. Coverage is reconciled against the fleet register',
      '   quarterly; an unprotected device loses network access rather than being tolerated.',
      '2. **Signatures and agent current.** Definitions update automatically at least daily; an',
      '   endpoint more than 7 days stale is chased, and at 14 days quarantined from the network.',
      '3. **Email and web.** Attachments are scanned and executable types blocked at the gateway.',
      '   Known-malicious and uncategorised-risk web categories are blocked on company devices.',
      '4. **Container images.** Every image is scanned in CI before push. A critical finding fails',
      '   the build; there is no override flag. Base images are rebuilt at least monthly so that',
      '   long-lived services do not carry a stale layer.',
      '5. **Removable media.** USB mass storage is blocked on clinic desktops since May 2026.',
      '   Engineering laptops permit it but a mounted device is scanned automatically.',
      '6. **Handling a detection.** Isolate the device from the network first, then triage. Anything',
      '   on a device that holds patient data, or any detection that resisted removal, is reimaged',
      '   rather than cleaned, and treated as an incident.',
      '7. **People.** Simulated phishing runs twice a year; the result feeds the awareness training',
      '   rather than any individual sanction.',
      '',
      '## Records',
      '',
      'The detection log, quarterly coverage reconciliation and phishing simulation results are kept',
      'for 3 years. Reimaging decisions are recorded against the device in the fleet register.',
      '',
      '## Review',
      '',
      'Yearly by Agil, and after any detection classified as an incident.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-8-8',
    title: 'Technical Vulnerability Management Procedure',
    clause: 'A.8.8',
    crossRefs: ['A.5.7', 'A.8.32', 'A.8.29', 'A.8.9'],
    version: 'v2.3',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-8-8-01', name: 'Vulnerability register and remediation record' },
    revisions: [
      {
        version: 'v2.1',
        date: '2025-07-17',
        author: 'Randy',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Remediation targets were expressed as best effort; the register was a spreadsheet updated after the fact.',
      },
      {
        version: 'v2.3',
        date: '2026-06-01',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Fixed remediation clocks by severity, exception route with an expiry, and internet-facing assets separated out.',
      },
    ],
    evidence: [
      {
        name: 'vulnerability-register-2026-06.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-05',
        expiryDate: '2026-09-05',
        uploader: 'Randy',
        note: 'Open and recently closed findings with their clock, owner and status.',
        body: [
          'ID | Asset | Finding | Severity | Found | Due | Owner | Status',
          'VUL-2026-041 | super-app-api | Go stdlib CVE-2026-2201 | High | 2026-05-12 | 2026-06-09 | Randy | Closed 2026-05-16',
          'VUL-2026-047 | infra, EKS nodes | Kernel CVE-2026-1877 | Critical | 2026-05-28 | 2026-06-04 | Agil | Closed 2026-06-02',
          'VUL-2026-052 | clinic PMS bridge | Outdated TLS library | Medium | 2026-06-01 | 2026-08-30 | Randy | Open, in progress',
          'VUL-2026-053 | data-pipeline | Transitive dep, prototype pollution | Low | 2026-06-02 | 2026-12-02 | Tika | Open',
          'VUL-2026-055 | reception desktops | Windows update deferral | Medium | 2026-06-03 | 2026-09-01 | Agil | Open',
          'VUL-2026-038 | marketplace connector | Vendor-side finding | High | 2026-04-30 | 2026-05-28 | Pak Chen | Exception to 2026-07-31',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-8-8 · Technical Vulnerability Management Procedure',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v2.3 · **Review** quarterly',
      '**Requirement** A.8.8 · **Also satisfies** A.5.7, A.8.32, A.8.29, A.8.9',
      '',
      '## Purpose',
      '',
      'Vulnerabilities arrive continuously and mostly through dependencies nobody chose directly.',
      'What decides whether they matter is not whether they are found but whether they are closed on',
      'a clock. This procedure sets the clock, names who holds each finding, and gives an honest',
      'route for the cases that cannot be fixed in time.',
      '',
      '## Scope',
      '',
      'Operating systems, container images, application dependencies, infrastructure modules, and',
      'third-party SaaS the organisation depends on. Findings in a supplier’s own product are',
      'tracked here but remediated through the supplier relationship.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Dhiaz Fathra** owns the register and approves exceptions.',
      '- **Randy** triages application and dependency findings.',
      '- **Agil** triages operating system, cluster and network findings.',
      '- **Tika** confirms the fix is verified by a test or a rescan, not by assertion.',
      '- **Pak Chen** carries findings that belong to a supplier and chases them contractually.',
      '',
      '## Procedure',
      '',
      '1. **Collect.** Dependency scanning runs on every pull request and nightly on `main`. Image',
      '   and host scans run nightly. Advisories from the cloud provider and from the sector CERT',
      '   are reviewed weekly under the threat intelligence control.',
      '2. **Triage within 2 working days.** Each finding is confirmed as applicable or dismissed with',
      '   a written reason, and given a severity based on the vendor score adjusted for exposure —',
      '   an internet-facing asset raises the severity by one band.',
      '3. **Remediation clocks**, from the date of triage: Critical 7 days, High 30 days, Medium 90',
      '   days, Low 180 days. An internet-facing Critical is handled as an incident and patched',
      '   within 48 hours.',
      '4. **Change control.** Patches go through the normal change procedure, except an emergency',
      '   patch, which may be applied first and recorded within 24 hours.',
      '5. **Verify.** The owner closes a finding only after a rescan or a specific test confirms it.',
      '   Tika samples 10% of closures each quarter.',
      '6. **Exceptions.** Where a fix is not possible in time, Dhiaz Fathra may grant an exception',
      '   with a compensating control, a named owner and an expiry date no more than 90 days out.',
      '   An expired exception is a nonconformity.',
      '7. **Report.** Open findings by severity and clock adherence are reported at each quarterly',
      '   management review.',
      '',
      '## Records',
      '',
      'The vulnerability register, exception approvals and verification samples are held in the',
      'compliance repository for 3 years. Scanner output is retained 12 months.',
      '',
      '## Review',
      '',
      'Quarterly by Dhiaz Fathra with Randy and Agil, and after any incident traced to an unpatched',
      'vulnerability.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-8-9',
    title: 'Configuration Management Procedure',
    clause: 'A.8.9',
    crossRefs: ['A.8.32', 'A.8.31', 'A.8.19', 'A.5.37'],
    version: 'v2.0',
    owner: 'Agil',
    form: { code: 'FRM-A-8-9-01', name: 'Baseline configuration and drift review record' },
    revisions: [
      {
        version: 'v1.3',
        date: '2024-12-09',
        author: 'Agil',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Baselines were documented but applied by hand; three environments had drifted apart by the December check.',
      },
      {
        version: 'v2.0',
        date: '2026-02-10',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Infrastructure moved to Terraform as the single source; manual console change made an exception requiring same-day reconciliation.',
      },
    ],
    evidence: [
      {
        name: 'drift-review-2026-05.md',
        fileType: 'MD',
        uploadedAt: '2026-05-18',
        expiryDate: '2026-08-18',
        uploader: 'Agil',
        note: 'Monthly drift detection run against the Terraform state, with each difference explained and closed.',
        body: [
          '# Configuration drift review — May 2026',
          '',
          'Run: `terraform plan` against all four workspaces, 2026-05-18, plus CIS benchmark scan on EKS nodes.',
          '',
          '| Workspace | Differences | Cause | Resolution |',
          '| --- | --- | --- | --- |',
          '| prod-network | 1 | Security group rule added in console during 2026-05-11 incident | Codified and merged, PR #812 |',
          '| prod-compute | 0 | — | — |',
          '| prod-data | 2 | Parameter group tuned by hand for the ETL window | Codified; second change reverted as unnecessary |',
          '| staging | 4 | Deliberate divergence, smaller instances | Documented as an accepted variance |',
          '',
          'CIS benchmark: 96% pass. Two failures on audit log retention were raised as VUL-2026-049',
          'and closed on 2026-05-21.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-8-9 · Configuration Management Procedure',
      '',
      '**Owner** Agil · **Approver** Aris Ihwan · **Version** v2.0 · **Review** every 6 months',
      '**Requirement** A.8.9 · **Also satisfies** A.8.32, A.8.31, A.8.19, A.5.37',
      '',
      '## Purpose',
      '',
      'A control that was configured once and then quietly changed in a console during an incident',
      'is not a control. This procedure keeps the intended configuration of every production system',
      'written down in a place that can be diffed, and makes divergence something that is detected',
      'and closed rather than discovered by an auditor.',
      '',
      '## Scope',
      '',
      'AWS infrastructure in ap-southeast-1, the EKS cluster and its node configuration, database',
      'parameter groups, application runtime configuration, and the security baseline on managed',
      'endpoints. Source code itself is covered by the development lifecycle controls.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Agil** owns the baselines, the Terraform repository and the monthly drift review.',
      '- **Andreas** approves changes to a baseline that alter a security property.',
      '- **Randy** may make an emergency console change during an incident and must reconcile it.',
      '- **Dhiaz Fathra** reviews accepted variances at the management review.',
      '',
      '## Procedure',
      '',
      '1. **Declare the baseline.** Every production resource is described in `infra-terraform`.',
      '   Node hardening follows the CIS benchmark for the running distribution; deviations from the',
      '   benchmark are listed in the repository with the reason.',
      '2. **Change through code.** A configuration change is a pull request with two reviews, planned',
      '   in CI and applied from CI, never from a laptop.',
      '3. **Emergency changes.** During an active incident the on-call engineer may change',
      '   configuration directly. The change must be codified and merged, or reverted, before the',
      '   end of the next working day; the incident record names which.',
      '4. **Detect drift monthly.** Agil runs a plan against every workspace and a CIS scan against',
      '   the nodes on the third Monday of each month. Every difference is explained: codified,',
      '   reverted, or recorded as an accepted variance with an owner.',
      '5. **Environments differ deliberately.** Staging is intentionally smaller. Accepted variances',
      '   are listed so that a difference is never read as drift, and the list is reviewed at the',
      '   half-yearly review.',
      '6. **Secrets are not configuration.** Values live in AWS Secrets Manager and are referenced,',
      '   never written into a Terraform file or a container image.',
      '7. **Rebuild test.** Once a year a non-production environment is rebuilt from the repository',
      '   alone to prove the declaration is complete.',
      '',
      '## Records',
      '',
      'Monthly drift reviews, accepted variance lists and the yearly rebuild result are held in the',
      'compliance repository for 3 years. Terraform state history is retained in versioned S3.',
      '',
      '## Review',
      '',
      'Every 6 months by Agil with Andreas, and after any incident where an undocumented',
      'configuration contributed.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-8-11',
    title: 'Data Masking and Test Data Preparation Procedure',
    clause: 'A.8.11',
    crossRefs: ['A.8.33', 'A.5.34', 'A.8.3', 'A.8.12'],
    version: 'v1.2',
    owner: 'Rica',
    form: { code: 'FRM-A-8-11-01', name: 'Masked dataset generation and approval record' },
    revisions: [
      {
        version: 'v1.0',
        date: '2025-09-25',
        author: 'Tika',
        approval: 'Reviewed by Rica',
        status: 'Superseded',
        note: 'First version, written after a production extract was found in a QA environment during the September review.',
      },
      {
        version: 'v1.2',
        date: '2026-03-31',
        author: 'Rica',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Masking rules set per field with a re-identification check; analytics pseudonymisation brought under the same procedure.',
      },
    ],
    evidence: [
      {
        name: 'masking-rule-set-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-03-31',
        expiryDate: '2027-03-31',
        uploader: 'Rica',
        note: 'Field-level masking rules applied by the extract job, approved by the controller representative.',
        body: [
          'Field | Class | Technique | Rule | Reversible',
          'patient.full_name | Specific personal | Substitution | Locale-consistent fake name from fixed pool | No',
          'patient.nik | Specific personal | Redaction | Replaced with format-valid random digits | No',
          'patient.phone | General personal | Substitution | +62 prefix retained, remainder randomised | No',
          'patient.dob | Specific personal | Generalisation | Year kept, month and day set to 01-01 | No',
          'patient.address | General personal | Generalisation | City and province kept, street removed | No',
          'clinical.note_text | Specific personal | Removal | Free text dropped entirely | No',
          'clinical.treatment_code | Specific personal | Retained | Needed for test realism, not identifying alone | n/a',
          'billing.amount | Confidential | Perturbation | Jittered plus or minus 5%, totals preserved | No',
          'patient.id | Specific personal | Tokenisation | HMAC with per-dataset key, key destroyed after run | No',
        ].join('\n'),
      },
      {
        name: 'reidentification-check-2026-03.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-03-31',
        uploader: 'Tika',
        note: 'Signed result of the re-identification attempt against the March masked dataset.',
      },
    ],
    body: [
      '# ISMS-SOP-A-8-11 · Data Masking and Test Data Preparation Procedure',
      '',
      '**Owner** Rica · **Approver** Aris Ihwan · **Version** v1.2 · **Review** yearly',
      '**Requirement** A.8.11 · **Also satisfies** A.8.33, A.5.34, A.8.3, A.8.12',
      '',
      '## Purpose',
      '',
      'Engineering and analytics both need data that behaves like the real thing. Neither needs to',
      'know who the patient is. In September 2025 a production extract was found sitting in a QA',
      'environment, which is what this procedure exists to prevent: it defines the only sanctioned',
      'way to get realistic data out of production, and what must be removed on the way.',
      '',
      '## Scope',
      '',
      'Any dataset derived from production for use in development, test, QA, demonstration or',
      'analytics. It covers the Super App databases, the clinic practice management system and the',
      'warehouse. Aggregated statistics published to management are covered by the reporting rules,',
      'not here.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Rica** owns the masking rule set and approves every dataset release as controller',
      '  representative.',
      '- **Tika** runs the extract job, performs the re-identification check and signs the result.',
      '- **Andreas** maintains the extract tooling and the tokenisation implementation.',
      '- **Wiwin** requests analytics datasets and states the purpose each one serves.',
      '',
      '## Procedure',
      '',
      '1. **Request.** The requester states the purpose, the fields genuinely needed, the environment',
      '   the data will live in, and how long it is needed. Fields that are not needed are not',
      '   extracted; masking is the second line, minimisation is the first.',
      '2. **Apply the rule set.** The extract job applies FRM-A-8-11-01 field by field. Direct',
      '   identifiers are substituted or redacted, dates generalised, free-text clinical notes',
      '   dropped, and the patient key replaced by an HMAC token whose key is destroyed at the end',
      '   of the run so the mapping cannot be recovered.',
      '3. **Preserve what makes it useful.** Referential integrity across tables, value distributions',
      '   and format validity are kept, so that tests exercise real shapes without real people.',
      '4. **Re-identification check.** Before release Tika attempts to re-identify 20 records by',
      '   combining quasi-identifiers with public information. A single success blocks the release',
      '   and the rule set is tightened.',
      '5. **Approve and record.** Rica approves the release in writing. The record names the dataset,',
      '   its purpose, the rule set version and the destruction date.',
      '6. **Contain and expire.** Masked datasets live only in the environment they were approved',
      '   for, are never copied to a laptop, and are deleted at the stated date — 90 days at most',
      '   for QA datasets.',
      '7. **No unmasked exception.** There is no route to unmasked production data in a lower',
      '   environment. Where production behaviour must be reproduced, the work is done in production',
      '   under break-glass access with the access restriction policy in force.',
      '',
      '## Records',
      '',
      'Approval records, the rule set as applied and re-identification check results are held in the',
      'compliance repository for 5 years, matching the privacy retention schedule. Deletion of each',
      'dataset is confirmed against the record.',
      '',
      '## Review',
      '',
      'Yearly by Rica with Tika, and whenever a new field of personal data enters the platform.',
    ].join('\n'),
  },
]
