import type { SeedDocument } from './types'

/** Annex A.5 batch B, part 2: supplier agreements, supply chain, cloud and incidents (A.5.20–A.5.25). */
export const ANNEX_A5_B_2: SeedDocument[] = [
  {
    code: 'ISMS-POL-A-5-20',
    title: 'Security Requirements in Supplier Agreements',
    clause: 'A.5.20',
    crossRefs: ['A.5.19', 'A.5.22', '8.4.2'],
    version: 'v1.2',
    owner: 'Pak Chen',
    form: { code: 'FRM-A-5-20-01', name: 'Contract security clause checklist' },
    revisions: [
      {
        version: 'v1.1',
        date: '2024-10-02',
        author: 'Pak Chen',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Security terms negotiated case by case, which meant two SaaS contracts signed in 2024 carried no breach-notification obligation at all.',
      },
      {
        version: 'v1.2',
        date: '2026-05-19',
        author: 'Pak Chen',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Standard clause set adopted; a signed checklist is now a precondition of the purchase order.',
      },
    ],
    evidence: [
      {
        name: 'contract-security-clause-checklist-template.docx',
        fileType: 'DOCX',
        uploadedAt: '2026-05-19',
        expiryDate: '2027-05-19',
        uploader: 'Pak Chen',
        note: 'The checklist attached to every tier 1 and tier 2 contract file before signature.',
        body: [
          '# Contract security clause checklist',
          '',
          '**Supplier** ______________ · **Tier** ___ · **Relationship owner** ______________',
          '',
          'Each line is marked present, negotiated variation, or not applicable with a reason.',
          '',
          '- Confidentiality surviving termination by at least 5 years',
          '- Purpose limitation — our data used only to deliver the contracted service',
          '- No sub-processing without prior written approval, with a current sub-processor list',
          '- Breach notification to Dhiaz Fathra within 24 hours of the supplier becoming aware',
          '- Right for the group to audit, or to receive a current independent audit report yearly',
          '- Named security contact with an out-of-hours route',
          '- Personnel screening and confidentiality undertakings for staff touching our data',
          '- Encryption in transit and at rest for any group data held by the supplier',
          '- Data location stated; approval required before any move outside the agreed region',
          '- Service levels and the measures reported monthly',
          '- Return or verified destruction of our data within 30 days of termination',
          '- Access revocation on termination or on the supplier’s staff leaving',
          '',
          '**Legal review** ____________ **Security sign-off (Dhiaz Fathra)** ____________ **Date** ______',
        ].join('\n'),
      },
      {
        name: 'scanning-vendor-agreement-security-annex-2026.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-03-05',
        expiryDate: '2028-03-05',
        uploader: 'Rica',
        note: 'Signed security annex and processor agreement with the medical records scanning vendor.',
      },
    ],
    body: [
      '# ISMS-POL-A-5-20 · Security Requirements in Supplier Agreements',
      '',
      '**Owner** Pak Chen · **Approver** Aris Ihwan · **Version** v1.2 · **Review** annually',
      '**Requirement** A.5.20 · **Also satisfies** A.5.19, A.5.22, 9001 8.4.2',
      '',
      '## Purpose',
      '',
      'Assessing a supplier tells you what they do today. The contract is what you can rely on',
      'when they change, or when something goes wrong at three in the morning. This policy states',
      'the security terms that must appear in an agreement before the group signs it.',
      '',
      '## Scope',
      '',
      'All new and renewed agreements with tier 1 and tier 2 suppliers as tiered under',
      'ISMS-POL-A-5-19, including click-through terms for software the engineering team wants to',
      'adopt. Tier 3 agreements need only the standard confidentiality wording. Employment',
      'contracts are out of scope and are covered under Annex A.6.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Pak Chen** runs the contracting process and holds the executed agreements.',
      '- **Dhiaz Fathra** gives the security sign-off and decides on any negotiated variation to',
      '  the standard clause set.',
      '- **Rica** provides the processor terms wherever personal data is involved.',
      '- **Aris Ihwan** signs.',
      '',
      '## Policy',
      '',
      '1. **A signed checklist precedes the purchase order.** `FRM-A-5-20-01` is completed and',
      '   signed off before procurement raises the order. No checklist, no order — including for',
      '   renewals.',
      '2. **The standard clause set is the starting position.** Confidentiality surviving',
      '   termination, purpose limitation, sub-processing control, breach notification, audit',
      '   right, encryption, data location, service levels, and return or destruction on exit.',
      '3. **Breach notification is 24 hours.** The supplier notifies Dhiaz Fathra within 24 hours',
      '   of becoming aware of an incident affecting group information — not within 24 hours of',
      '   confirming its impact. A longer window is a variation and needs Director approval.',
      '4. **Sub-processors are visible and approved.** The supplier maintains a current',
      '   sub-processor list and gives 30 days’ notice of a change, with a right for the group to',
      '   object.',
      '5. **Data stays where we agreed.** For anything holding personal data, the agreement names',
      '   the processing location. Movement outside the agreed region requires prior written',
      '   approval from Rica.',
      '6. **Audit or evidence.** Either the group holds a right to audit, or the supplier provides',
      '   a current independent audit report or certification annually. One of the two must be',
      '   present in every tier 1 agreement.',
      '7. **Exit terms are written at entry.** Return or verified destruction of group data within',
      '   30 days of termination, and revocation of all supplier access on the last day of the',
      '   contract.',
      '8. **Variations are recorded, not assumed.** Where a supplier will not accept a clause, the',
      '   variation, the reason and the compensating control are written on the checklist and',
      '   signed by Dhiaz Fathra. Silence is not acceptance.',
      '9. **Click-through terms count.** An engineer adopting a SaaS tool under standard online',
      '   terms follows the same route; the checklist records which clauses the standard terms do',
      '   and do not cover.',
      '',
      '## Records',
      '',
      'Signed clause checklists (`FRM-A-5-20-01`, contract term plus 6 years), executed agreements',
      'and security annexes held by Pak Chen, processor agreements held by Rica, variation',
      'approvals (contract term plus 6 years).',
      '',
      '## Review',
      '',
      'Annually by Pak Chen with Dhiaz Fathra, and whenever a supplier incident shows the standard',
      'clause set to be missing something.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-5-21',
    title: 'ICT Supply Chain Security Procedure',
    clause: 'A.5.21',
    crossRefs: ['A.5.19', 'A.8.28', 'A.8.30'],
    version: 'v1.3',
    owner: 'Agil',
    form: { code: 'FRM-A-5-21-01', name: 'Component and dependency provenance record' },
    revisions: [
      {
        version: 'v1.2',
        date: '2025-05-14',
        author: 'Andreas',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Dependency review done at release time by eye; no inventory of what the 21 Go services actually pull in.',
      },
      {
        version: 'v1.3',
        date: '2026-06-01',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Build-time inventory and pinned digests made mandatory; new-dependency review added to the merge gate.',
      },
    ],
    evidence: [
      {
        name: 'dependency-provenance-2026-05.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-01',
        expiryDate: '2026-12-01',
        uploader: 'Agil',
        note: 'Provenance and risk position for the components the platform depends on most heavily.',
        body: [
          'Component | Used by | Source | Pinning | Known issues open | Reviewer',
          'Go toolchain 1.23 | all 21 services | upstream release, checksum verified | version and checksum | 0 | Agil',
          'Base container image (distroless) | all services | vendor registry | digest | 0 | Agil',
          'ConnectRPC | all services | module proxy | version and go.sum | 0 | Randy',
          'NATS / Watermill | event transport | module proxy | version and go.sum | 1 low, patch scheduled | Randy',
          'Flutter SDK 3.x | Super App | upstream release | version | 0 | Andreas',
          'Payment gateway SDK | billing | vendor, signed artefact | version and signature | 0 | Pak Rila',
          'Turso / libSQL client | compliance repository | module proxy | version and go.sum | 0 | Agil',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-5-21 · ICT Supply Chain Security Procedure',
      '',
      '**Owner** Agil · **Approver** Aris Ihwan · **Version** v1.3 · **Review** every 6 months',
      '**Requirement** A.5.21 · **Also satisfies** A.5.19, A.8.28, A.8.30',
      '',
      '## Purpose',
      '',
      'The platform is 21 Go services, a Flutter application and a handful of Node services, and',
      'the overwhelming majority of the code that runs in production was written by someone else.',
      'A compromised dependency or a tampered base image reaches production the same way our own',
      'code does. This procedure describes what the engineering group does about that.',
      '',
      '## Scope',
      '',
      'Software dependencies, container base images, build tooling, CI runners, vendor SDKs and',
      'purchased hardware used in the Eternesia estate and the compliance repository. Clinical',
      'equipment procurement is Pak Andre’s and follows the general supplier policy; the network',
      'and computing hardware in the equipment room is in scope here.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Agil** owns this procedure, the build pipeline and the provenance record.',
      '- **Randy** reviews new dependency requests for the backend services.',
      '- **Andreas** does the same for the Super App and reviews architectural dependencies.',
      '- **Dhiaz Fathra** decides where a component carries a risk the team cannot mitigate.',
      '- **Pak Chen** handles the commercial relationship for any paid component.',
      '',
      '## Procedure',
      '',
      '1. **Know what you ship.** Every build emits a component inventory listing each direct and',
      '   transitive dependency with its resolved version. The inventory is stored with the build',
      '   artefact and is retained for 12 months.',
      '2. **Pin everything.** Dependencies are pinned by version and checksum; container images by',
      '   digest, never by a floating tag. A build that resolves a version it did not pin fails.',
      '3. **New dependency review.** Adding a direct dependency requires a reviewer — Randy for',
      '   backend, Andreas for the app — who checks maintenance activity, licence, the size of the',
      '   transitive set it drags in, and whether the standard library already covers it. The',
      '   cheapest supply chain control is not adding the dependency.',
      '4. **Verify what you download.** Toolchains, vendor SDKs and signed artefacts are checked',
      '   against the publisher’s checksum or signature before they enter the build. An artefact',
      '   that cannot be verified is not used.',
      '5. **Build in a controlled place.** Builds run only on managed CI runners in the group’s AWS',
      '   ap-southeast-1 account. Nothing is built on an engineer’s laptop and pushed to a',
      '   production registry.',
      '6. **Watch for known issues.** The inventory is checked daily against public advisory data.',
      '   A critical finding on a component reachable from production is patched or mitigated',
      '   within 7 calendar days; high within 30; anything else at the next release.',
      '7. **Registry hygiene.** Only images built by our own pipeline, or pulled from an approved',
      '   vendor registry, run in production. Agil reviews the approved registry list every 6',
      '   months.',
      '8. **Hardware.** Network and compute hardware is bought through Pak Chen from an authorised',
      '   reseller, recorded on the asset register, and its firmware brought current before it',
      '   joins a production network.',
      '9. **Escalate what cannot be fixed.** Where a component is unmaintained or a supplier will',
      '   not patch, Agil records the exposure and Dhiaz Fathra decides between replacement,',
      '   isolation, or accepting the risk with a review date.',
      '',
      '## Records',
      '',
      'Component and dependency provenance record (`FRM-A-5-21-01`, refreshed monthly, 2 years),',
      'per-build component inventories (12 months), new-dependency review comments in the merge',
      'request (retained with the repository), advisory findings and their remediation tickets',
      '(3 years).',
      '',
      '## Review',
      '',
      'Every 6 months by Agil with Randy and Andreas, and after any advisory that required an',
      'out-of-cycle release.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-5-22',
    title: 'Supplier Service Monitoring and Change Procedure',
    clause: 'A.5.22',
    crossRefs: ['A.5.19', 'A.5.20', '9.1.1'],
    version: 'v1.3',
    owner: 'Pak Chen',
    form: { code: 'FRM-A-5-22-01', name: 'Supplier service review record' },
    revisions: [
      {
        version: 'v1.2',
        date: '2024-12-09',
        author: 'Pak Chen',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Supplier reviews held only at renewal, so a gateway change of sub-processor in mid-2024 was noticed six months late.',
      },
      {
        version: 'v1.3',
        date: '2026-04-22',
        author: 'Pak Chen',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Quarterly review for tier 1, a standing change-notification obligation, and a documented route for reassessment when a supplier changes materially.',
      },
    ],
    evidence: [
      {
        name: 'supplier-service-review-2026-q2.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-26',
        expiryDate: '2029-06-26',
        uploader: 'Pak Chen',
        note: 'Q2 review outcomes for tier 1 suppliers, including two notified changes.',
        body: [
          'Supplier | Availability vs target | Incidents notified | Changes notified | Actions | Outcome',
          'AWS | 99.99 vs 99.9 | 1 regional, no impact | Instance family deprecation, Sep 2026 | Agil to plan migration by Aug | Continue',
          'Payment gateway | 99.94 vs 99.9 | 0 | New sub-processor for fraud scoring | Rica reviewing, objection window open | Continue, under review',
          'Zitadel (self-hosted) | 100 vs 99.9 | 0 | Upgrade to current major | Agil scheduled for July window | Continue',
          'Scanning vendor | n/a, batch service | 0 | None | Spot check of 20 scanned files passed | Continue',
        ].join('\n'),
      },
      {
        name: 'gateway-subprocessor-change-assessment-2026-06.docx',
        fileType: 'DOCX',
        uploadedAt: '2026-06-20',
        expiryDate: '2027-06-20',
        uploader: 'Rica',
        note: 'Assessment of the payment gateway’s new fraud-scoring sub-processor, raised under the change clause.',
      },
    ],
    body: [
      '# ISMS-SOP-A-5-22 · Supplier Service Monitoring and Change Procedure',
      '',
      '**Owner** Pak Chen · **Approver** Aris Ihwan · **Version** v1.3 · **Review** annually',
      '**Requirement** A.5.22 · **Also satisfies** A.5.19, A.5.20, 9001 9.1.1',
      '',
      '## Purpose',
      '',
      'A supplier assessed in January can look quite different by September: new sub-processors,',
      'a new region, an acquisition, a service quietly re-platformed. This procedure keeps the',
      'group looking at its suppliers between renewals, and gives changes a route in.',
      '',
      '## Scope',
      '',
      'Ongoing monitoring of tier 1 and tier 2 suppliers, and the handling of any change a',
      'supplier makes to a service the group depends on. Initial selection and contracting are',
      'covered by ISMS-POL-A-5-19 and ISMS-POL-A-5-20.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Pak Chen** schedules and chairs the reviews and keeps the review record.',
      '- **The named relationship owner** on the supplier register brings the performance data.',
      '- **Dhiaz Fathra** assesses the security impact of a notified change.',
      '- **Rica** assesses any change affecting personal data, including a new sub-processor.',
      '- **Tika** supplies the service quality measures where a supplier feeds a clinical or',
      '  measurement process.',
      '',
      '## Procedure',
      '',
      '1. **Review cadence.** Tier 1 suppliers are reviewed quarterly, tier 2 annually. Reviews are',
      '   scheduled at the start of the year so they are not lost to operational pressure.',
      '2. **What the review looks at.** Service levels achieved against the contract, incidents the',
      '   supplier notified and how quickly, incidents we noticed first, changes notified, open',
      '   actions from last time, and whether the supplier’s tier is still right.',
      '3. **Bring evidence, not impressions.** The relationship owner brings the supplier’s own',
      '   reporting plus our measurement of the same thing where we have it. Where the two',
      '   disagree, the discrepancy is the agenda item.',
      '4. **Change notification.** Suppliers are contractually required to notify a material change',
      '   — sub-processor, processing location, ownership, or a substantive change to the service.',
      '   Pak Chen logs the notification the day it arrives and routes it to Dhiaz Fathra and, for',
      '   personal data, to Rica.',
      '5. **Assess before it lands.** A notified change is assessed within 10 working days. Where',
      '   the contract gives an objection window, the assessment is completed inside it. The',
      '   outcome is accept, accept with conditions, or object.',
      '6. **Unnotified change.** A change discovered rather than notified is a contract breach as',
      '   well as a risk. It is raised as a security event under ISMS-SOP-A-5-25 and recorded',
      '   against the supplier for the next review.',
      '7. **Reassessment triggers.** A security incident at the supplier, a change of ownership, a',
      '   move of data outside the agreed region, or two consecutive quarters below service level',
      '   trigger a full reassessment under ISMS-POL-A-5-19 regardless of when the last one was.',
      '8. **Escalation.** Persistent underperformance goes to Aris Ihwan with a recommendation to',
      '   remediate, re-scope or exit. Where exit is recommended, the exit terms agreed under',
      '   ISMS-POL-A-5-20 are read before the conversation, not after it.',
      '',
      '## Records',
      '',
      'Supplier service review record (`FRM-A-5-22-01`, 3 years), change notifications and their',
      'assessments (contract term plus 3 years), escalation decisions (6 years), supplier',
      'performance summary reported to the management review each quarter.',
      '',
      '## Review',
      '',
      'Annually by Pak Chen with Dhiaz Fathra, and after any supplier exit.',
    ].join('\n'),
  },
  {
    code: 'ISMS-POL-A-5-23',
    title: 'Cloud Services Security Policy',
    clause: 'A.5.23',
    crossRefs: ['A.5.19', 'A.8.9', 'A.8.16'],
    version: 'v2.0',
    owner: 'Agil',
    form: {
      code: 'FRM-A-5-23-01',
      name: 'Cloud service inventory and shared responsibility record',
    },
    revisions: [
      {
        version: 'v1.4',
        date: '2025-02-06',
        author: 'Agil',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Covered the AWS account only; SaaS adopted directly by teams sat outside any policy.',
      },
      {
        version: 'v2.0',
        date: '2026-05-28',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Extended to all cloud services including SaaS, with a shared responsibility record per service and a region constraint for personal data.',
      },
    ],
    evidence: [
      {
        name: 'cloud-service-inventory-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-05-28',
        expiryDate: '2027-05-28',
        uploader: 'Agil',
        note: 'Every cloud service in use, with region, data class and who is responsible for what.',
        body: [
          'Service | Model | Region | Data class | Our responsibility | Provider responsibility | Owner',
          'AWS ap-southeast-1 | IaaS | Singapore | All classes | OS, config, IAM, data, encryption keys | Hypervisor, physical, region availability | Agil',
          'Managed database (AWS) | PaaS | Singapore | Specific personal data | Schema, access, backup verification, encryption choice | Engine patching, replication | Randy',
          'Object storage (AWS S3) | PaaS | Singapore | Images, specific personal data | Bucket policy, lifecycle, encryption | Durability | Agil',
          'Google Workspace | SaaS | Multi-region | Internal, general personal data | Accounts, sharing rules, retention | Platform security | Agil',
          'Turso (compliance repository) | SaaS | Singapore | Internal | Schema, access tokens, backup export | Platform and durability | Dhiaz Fathra',
          'Marketing automation | SaaS | Singapore | Consented contact data | Consent filter on export, list hygiene | Platform security | Wiwin',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-A-5-23 · Cloud Services Security Policy',
      '',
      '**Owner** Agil · **Approver** Aris Ihwan · **Version** v2.0 · **Review** annually',
      '**Requirement** A.5.23 · **Also satisfies** A.5.19, A.8.9, A.8.16',
      '',
      '## Purpose',
      '',
      'Everything the group runs, runs in someone else’s data centre. That is a deliberate choice',
      'and a good one at this size, but it only works if the boundary between what the provider',
      'secures and what we secure is written down rather than assumed. Most cloud incidents in',
      'this industry are on our side of that line: a bucket policy, an IAM role, a backup nobody',
      'restored.',
      '',
      '## Scope',
      '',
      'All cloud services used to store or process group information: the AWS ap-southeast-1',
      'account carrying the Eternesia platform, the managed database and object storage, Google',
      'Workspace, the Turso-hosted compliance repository, and every SaaS product adopted by any',
      'department. Clinic-local equipment with no cloud component is out of scope.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Agil** owns this policy, the cloud inventory and the AWS account configuration.',
      '- **Dhiaz Fathra** approves the adoption of any new cloud service.',
      '- **Rica** approves any service that will hold personal data and confirms the region.',
      '- **Randy** owns the data-tier configuration and the restore tests.',
      '- **Each department head** is the named owner of the SaaS their department uses.',
      '',
      '## Policy',
      '',
      '1. **Nothing is adopted informally.** A new cloud service — including a free tier — is',
      '   approved by Dhiaz Fathra and entered on `FRM-A-5-23-01` before any group data goes into',
      '   it. A service found in use without approval is assessed immediately and removed if it',
      '   cannot be brought into line.',
      '2. **The responsibility split is written per service.** The inventory states, in plain',
      '   words, what the provider secures and what we secure. "The provider handles security" is',
      '   not an acceptable entry.',
      '3. **Region is fixed for personal data.** Personal data of patients and staff is processed',
      '   in Singapore (ap-southeast-1) or in Indonesia. A service that cannot guarantee its',
      '   region is not used for personal data.',
      '4. **Encryption is ours to choose.** Data at rest is encrypted with keys the group controls',
      '   where the provider supports it, and in transit with TLS 1.2 or better everywhere.',
      '5. **Identity federates.** Cloud services authenticate through Zitadel wherever they support',
      '   it, so that joiners and leavers are handled once. Where they do not, the service is',
      '   listed as an exception and included in the quarterly access review.',
      '6. **Configuration is code.** The AWS account is defined in infrastructure code and changed',
      '   through the pipeline. Console changes are for emergencies, are logged, and are',
      '   reconciled back into code within 5 working days.',
      '7. **Backups are proven, not assumed.** Randy runs a restore test each quarter against the',
      '   managed database and records the elapsed time and the result. An untested backup is',
      '   treated as no backup.',
      '8. **Logging is enabled and shipped.** Control-plane and access logs are enabled on every',
      '   service that offers them and retained for 12 months under A.8.15.',
      '9. **Exit is planned for the ones that matter.** For each service the clinics cannot operate',
      '   without, the inventory records how data would be extracted and roughly what a move would',
      '   cost. This is a written position, not a rehearsed migration, and the policy says so',
      '   honestly.',
      '',
      '## Records',
      '',
      'Cloud service inventory and shared responsibility record (`FRM-A-5-23-01`, kept current,',
      'versions retained 3 years), adoption approvals (3 years), quarterly restore test results',
      '(3 years), console-change reconciliation tickets (12 months).',
      '',
      '## Review',
      '',
      'Annually by Agil with Dhiaz Fathra and Rica, and on the adoption of any tier 1 cloud',
      'service.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-5-24',
    title: 'Information Security Incident Management Planning',
    clause: 'A.5.24',
    crossRefs: ['A.5.25', 'A.5.26', 'A.6.8'],
    version: 'v2.1',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-5-24-01', name: 'Incident response readiness record' },
    revisions: [
      {
        version: 'v2.0',
        date: '2025-07-15',
        author: 'Dhiaz Fathra',
        approval: 'Reviewed by Aris Ihwan',
        status: 'Superseded',
        note: 'Roles defined but no out-of-hours route and no rehearsal; the March 2025 exercise stalled while people looked for a phone number.',
      },
      {
        version: 'v2.1',
        date: '2026-02-04',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'On-call rota, severity matrix and a twice-yearly exercise added; PDP notification timing written into the plan.',
      },
    ],
    evidence: [
      {
        name: 'incident-response-readiness-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-02-04',
        expiryDate: '2027-02-04',
        uploader: 'Randy',
        note: 'Roles, contact route and readiness checks confirmed at the February refresh.',
        body: [
          'Role | Person | Backup | Reachable | Last confirmed',
          'Incident manager | Dhiaz Fathra | Andreas | Phone, 24/7 | 2026-02-04',
          'On-call engineer | Randy (rota) | Agil | Pager rota, 24/7 | 2026-02-04',
          'Infrastructure lead | Agil | Randy | Phone, 24/7 | 2026-02-04',
          'Personal data lead | Rica | Dhiaz Fathra | Phone, working hours | 2026-02-04',
          'Clinic operations | Pak Andre | Clinic manager on duty | Phone, clinic hours | 2026-02-04',
          'Communications and Director | Aris Ihwan | — | Phone, 24/7 | 2026-02-04',
        ].join('\n'),
      },
      {
        name: 'incident-exercise-report-2026-05.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-05-15',
        expiryDate: '2027-05-15',
        uploader: 'Dhiaz Fathra',
        note: 'Report of the May 2026 tabletop exercise: simulated exfiltration of a patient export, with the three findings raised.',
      },
    ],
    body: [
      '# ISMS-SOP-A-5-24 · Information Security Incident Management Planning',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v2.1 · **Review** annually',
      '**Requirement** A.5.24 · **Also satisfies** A.5.25, A.5.26, A.6.8',
      '',
      '## Purpose',
      '',
      'The worst time to work out who decides, who calls the Director and who talks to the',
      'regulator is during an incident. This document is the preparation: the roles, the routes,',
      'the severity scale and the rehearsal schedule. Responding to a specific incident is',
      'ISMS-SOP-A-5-25 and the response procedure under A.5.26.',
      '',
      '## Scope',
      '',
      'Preparation for information security incidents affecting the Eternesia platform, the Super',
      'App, the clinic systems, the corporate systems, and information held on paper in the',
      'clinics. Clinical adverse events are handled under the clinic’s own protocol; where one',
      'has an information security dimension, both run in parallel.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Incident manager (Dhiaz Fathra, backup Andreas)** declares an incident, sets severity,',
      '  and owns the response until closure.',
      '- **On-call engineer (Randy, rota with Agil)** is the first responder out of hours.',
      '- **Agil** provides infrastructure containment: isolate, revoke, snapshot.',
      '- **Rica** decides on notification to data subjects and the authority under the PDP Law.',
      '- **Pak Andre** manages clinic-side impact and patient-facing messaging on the floor.',
      '- **Aris Ihwan** approves external communication and any regulatory submission.',
      '',
      '## Procedure',
      '',
      '1. **Maintain the readiness record.** `FRM-A-5-24-01` names every role, its backup and a',
      '   reachable number. It is confirmed at least twice a year and immediately when someone in',
      '   it changes job.',
      '2. **One reporting route.** Anyone in the group reports a suspected incident to the on-call',
      '   engineer, by the number printed at every reception desk and pinned in the engineering',
      '   channel. Reporting is expected to be fast and imperfect; no one is criticised for a false',
      '   alarm.',
      '3. **Severity scale.** S1 — patient data confidentiality lost, or clinics cannot operate.',
      '   S2 — a system compromised or unavailable with a workaround. S3 — contained, no data',
      '   exposure. S4 — a weakness with no evidence of exploitation. S1 and S2 wake the incident',
      '   manager immediately; S3 and S4 wait for working hours.',
      '4. **Response times.** S1 acknowledged within 15 minutes and the incident manager engaged',
      '   within 30. S2 acknowledged within 1 hour. S3 within 1 working day. S4 at the next',
      '   triage.',
      '5. **Prepared capability.** Before an incident happens, the group keeps ready: the ability to',
      '   revoke any session and credential in Zitadel within minutes, snapshot an instance for',
      '   forensics before rebuilding it, isolate a service at the network layer, and restore the',
      '   managed database from a tested backup.',
      '6. **Notification clock.** Where personal data may have been exposed, Rica assesses against',
      '   the PDP Law notification duty from the moment of awareness, not from the moment of',
      '   confirmation. The plan assumes a 3×24-hour outer limit and works backwards from it.',
      '7. **Evidence discipline.** The on-call engineer preserves logs and snapshots before',
      '   remediation wherever it does not delay containment. Timestamps are recorded in WIB with',
      '   the source system named.',
      '8. **Exercise twice a year.** One tabletop and one technical exercise annually, each with a',
      '   written report and dated actions. The May 2026 tabletop is the current evidence of this.',
      '9. **Learn in public.** Findings from exercises and real incidents go to the management',
      '   review and, where they change behaviour on the clinic floor, into the awareness',
      '   programme under A.6.3.',
      '',
      '## Records',
      '',
      'Incident response readiness record (`FRM-A-5-24-01`, current plus 3 years), exercise reports',
      'and action logs (3 years), the incident register maintained under ISMS-SOP-A-5-25, on-call',
      'rota (12 months).',
      '',
      '## Review',
      '',
      'Annually by Dhiaz Fathra with Randy, Agil and Rica, after every exercise, and after every',
      'S1 or S2 incident.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-5-25',
    title: 'Security Event Assessment and Decision Procedure',
    clause: 'A.5.25',
    crossRefs: ['A.5.24', 'A.5.26', 'A.6.8'],
    version: 'v1.5',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-5-25-01', name: 'Security event triage register' },
    revisions: [
      {
        version: 'v1.4',
        date: '2025-06-30',
        author: 'Randy',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Triage judgement left entirely to the responder, so similar events were classified differently depending on who was on call.',
      },
      {
        version: 'v1.5',
        date: '2026-03-02',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Written triage criteria and a weekly review of everything closed as "not an incident" to catch the misses.',
      },
    ],
    evidence: [
      {
        name: 'security-event-triage-register-2026-q2.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-30',
        expiryDate: '2029-06-30',
        uploader: 'Randy',
        note: 'Events triaged in Q2 2026 and the decision taken on each.',
        body: [
          'Date | Source | Event | Decision | Severity | Rationale',
          '2026-04-05 | Staff report | Phishing mail impersonating the Director | Incident | S3 | Credible, targeted, awareness note issued',
          '2026-04-19 | Monitoring | Repeated failed logins, one clinic account | Not an incident | — | New starter, wrong keyboard layout, confirmed with Pak Andre',
          '2026-05-02 | Engineer | API key found in a merge request | Incident | S2 | Key rotated within 40 minutes, no use observed',
          '2026-05-24 | Monitoring | Unusual export volume, commercial analyst | Not an incident | — | Approved quarterly board pack, checked with Wiwin',
          '2026-06-08 | Clinic | Paper consent forms left on a counter overnight | Incident | S3 | Physical exposure, retraining at that location',
          '2026-06-21 | Supplier | Gateway notified an upstream outage | Not an incident | — | Availability only, tracked under A.5.22',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-5-25 · Security Event Assessment and Decision Procedure',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v1.5 · **Review** annually',
      '**Requirement** A.5.25 · **Also satisfies** A.5.24, A.5.26, A.6.8',
      '',
      '## Purpose',
      '',
      'Most things reported are not incidents. A failed login is usually a new starter with the',
      'wrong keyboard layout; a large export is usually the quarterly board pack. This procedure',
      'is the step between "something was reported" and "we are running an incident", and its job',
      'is to make that decision consistently regardless of who is on call.',
      '',
      '## Scope',
      '',
      'Every security event reaching the group from any source: staff and patient reports,',
      'platform monitoring and alerting, the daily advisory feed, supplier notifications, audit',
      'findings and clinic observations. It ends at the decision. Running a declared incident is',
      'covered by the response procedure under A.5.26.',
      '',
      '## Roles and responsibilities',
      '',
      '- **On-call engineer (Randy, rota with Agil)** performs first triage on every event and',
      '  records the decision.',
      '- **Dhiaz Fathra** decides anything the on-call engineer is unsure of, and reviews the',
      '  weekly register.',
      '- **Rica** is consulted whenever personal data may be involved, before the event is closed.',
      '- **Pak Andre** confirms the facts behind clinic-floor events.',
      '- **Tika** feeds recurring event patterns into the QMS improvement process.',
      '',
      '## Procedure',
      '',
      '1. **Log first, judge second.** Every reported event is entered on `FRM-A-5-25-01` within 1',
      '   hour of receipt with its source, timestamp in WIB and a plain description. Nothing is',
      '   dismissed verbally.',
      '2. **Establish the facts.** The on-call engineer collects what is actually known: which',
      '   system, which identity, which data, over what period. Assumptions are marked as',
      '   assumptions.',
      '3. **Apply the criteria.** An event becomes an incident if any of the following is true:',
      '   personal data may have been accessed by someone without a right to it; a credential or',
      '   key may be known to an unauthorised party; a production system behaved in a way no',
      '   authorised change explains; a control that should have prevented something did not; a',
      '   clinic cannot operate a system it needs.',
      '4. **Escalate when unsure.** If the on-call engineer cannot place an event confidently,',
      '   it is treated as an incident until Dhiaz Fathra says otherwise. The cost of over-',
      '   declaring is an hour of attention; the cost of under-declaring is measured in weeks.',
      '5. **Personal data is never closed alone.** Any event touching personal data is reviewed',
      '   with Rica before it is closed as not an incident, because the notification clock under',
      '   the PDP Law starts at awareness.',
      '6. **Set the severity.** Where the decision is incident, the on-call engineer assigns S1 to',
      '   S4 using the scale in ISMS-SOP-A-5-24 and hands to the incident manager. Severity is',
      '   revisited as facts change and the change is recorded with its reason.',
      '7. **Record the rationale for a closure.** An event closed as not an incident carries a',
      '   written reason and who confirmed it. "Investigated, no issue" is not a reason.',
      '8. **Weekly review of the closures.** Every Monday Dhiaz Fathra reads the events closed in',
      '   the previous week. Anything wrongly closed is reopened at the correct severity, and the',
      '   criteria above are amended if the same misjudgement appears twice.',
      '9. **Look for patterns.** Repeated low-severity events of the same kind — the same clinic,',
      '   the same control, the same supplier — are raised as a single improvement item rather',
      '   than closed individually forever.',
      '',
      '## Records',
      '',
      'Security event triage register (`FRM-A-5-25-01`, 3 years), weekly closure review notes',
      '(12 months), escalation decisions and severity changes recorded against the event, patterns',
      'referred to the improvement process (3 years).',
      '',
      '## Review',
      '',
      'Annually by Dhiaz Fathra with the on-call engineers, and whenever the weekly review',
      'reopens an event that should not have been closed.',
    ].join('\n'),
  },
]
