import type { SeedDocument } from './types'

/** Annex A.7 physical controls, part 1: perimeters through clear desk (A.7.1–A.7.7). */
export const ANNEX_A7_PHYSICAL_1: SeedDocument[] = [
  {
    code: 'ISMS-POL-A-7-1',
    title: 'Site Perimeters and Security Zones',
    clause: 'A.7.1',
    crossRefs: ['A.7.2', 'A.7.3', 'A.5.9'],
    version: 'v2.0',
    owner: 'Agil',
    form: { code: 'FRM-A-7-1-01', name: 'Site zone and perimeter register' },
    revisions: [
      {
        version: 'v1.2',
        date: '2024-09-09',
        author: 'Agil',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Written when the group still ran two on-premise racks; the zone model assumed a server room at every branch.',
      },
      {
        version: 'v2.0',
        date: '2026-02-17',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Rewritten after the move to AWS ap-southeast-1: branch racks reduced to a comms cabinet, and the four-zone model replaced the old public/private split.',
      },
    ],
    evidence: [
      {
        name: 'site-zone-register-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-02-17',
        expiryDate: '2027-02-17',
        uploader: 'Agil',
        note: 'Every occupied site with its zone breakdown and the person accountable for the perimeter.',
        body: [
          'Site | Zone 0 (public) | Zone 1 (clinical) | Zone 2 (restricted) | Zone 3 (comms cabinet) | Site custodian',
          'Jakarta HQ, Kebayoran | lobby, reception | — | finance room, HR room | 4th floor cabinet | Agil',
          'Dermaster Kemang | waiting area | 6 treatment rooms | records room | wall cabinet, back corridor | Pak Andre',
          'Dermaster PIK | waiting area | 8 treatment rooms | records room, drug store | wall cabinet, staff room | Pak Andre',
          'Dermaster Surabaya Pakuwon | waiting area | 5 treatment rooms | records room | wall cabinet, staff room | Pak Andre',
          'Dermaster Bandung Dago | waiting area | 4 treatment rooms | records room | wall cabinet, staff room | Pak Andre',
          'Warehouse, Cakung | goods-in bay | — | bonded consumables cage | none | Pak Chen',
          '',
          'Two findings from the February walk: the Bandung Dago cabinet shared a corridor with the',
          'cleaner store and was refitted with its own lock on 3 March 2026; the Cakung cage had no',
          'zone label and was relabelled the same week.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-A-7-1 · Site Perimeters and Security Zones',
      '',
      '**Owner** Agil · **Approver** Aris Ihwan · **Version** v2.0 · **Review** annually, each February',
      '**Requirement** A.7.1 · **Also satisfies** A.7.2, A.7.3, A.5.9',
      '',
      '## Purpose',
      '',
      'Dermaster occupies rented clinic units inside shopping centres and office towers. The',
      'landlord owns the building shell, the fire system and often the lifts, so the perimeter',
      'this organisation can actually control starts at the unit door. This document says where',
      'that line runs at each site, what sits inside it, and who is answerable when it is breached.',
      '',
      '## Scope',
      '',
      'All occupied sites: the Jakarta head office, every clinic branch, and the Cakung consumables',
      'warehouse. It does not cover the AWS ap-southeast-1 regions that hold production data —',
      'physical security there is the provider’s and is evidenced through their certification under',
      'the supplier controls, not inspected by us.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Agil** (Infrastructure Engineer) owns this document, maintains the zone register and runs',
      '  the annual perimeter walk.',
      '- **Pak Andre** (clinic operations) is site custodian for every branch: he holds the unit keys,',
      '  approves layout changes and signs the branch section of the walk report.',
      '- **Pak Chen** is custodian for the Cakung warehouse.',
      '- **Dhiaz Fathra** decides, with the custodian, whether a perimeter weakness is accepted as a',
      '  risk or funded as a fix.',
      '',
      '## Policy',
      '',
      '1. **Four zones, everywhere.** Zone 0 is public — lobby, waiting area, goods-in bay. Zone 1 is',
      '   clinical — treatment rooms, reachable only with a member of staff. Zone 2 is restricted —',
      '   patient records, finance, HR, the drug store. Zone 3 is the comms cabinet holding the',
      '   switch, the router and the branch UPS.',
      '2. **A zone boundary is a physical thing.** A painted line, a rope or a sign is not a boundary.',
      '   Zone 1 upward needs a door that latches and a lock the site custodian controls.',
      '3. **No Zone 2 or Zone 3 room may be reachable from a public corridor without passing a staffed',
      '   point.** Where a new lease makes that impossible, the branch does not open until a',
      '   compensating control is agreed in writing by Agil and Pak Andre.',
      '4. **Shared services stay outside.** Cleaning cupboards, landlord riser rooms and shared',
      '   pantries are Zone 0 by definition, whatever their position in the floor plan.',
      '5. **New site, new register row.** A branch is added to the zone register before handover, not',
      '   after opening. The register row names the custodian and lists every Zone 2 and Zone 3 space.',
      '6. **Annual walk.** Agil physically visits every site once a year and records, per zone, whether',
      '   the boundary held, whether locks work and whether the layout still matches the register.',
      '   A branch that fails on a Zone 2 or Zone 3 point is re-walked within 20 working days.',
      '',
      '## What we deliberately do not do',
      '',
      'The group does not operate a manned guard post, a perimeter fence or an intrusion alarm at any',
      'clinic. Branch units sit inside malls with their own overnight security, and the highest-value',
      'asset on site is a locked records cabinet rather than a server. If a branch ever holds primary',
      'data again, that decision is revisited before the equipment is installed.',
      '',
      '## Records',
      '',
      'The zone register (FRM-A-7-1-01) and the annual walk reports live in this repository against',
      'A.7.1 and are retained for three years. Layout change requests are kept with the branch lease',
      'file held by Pak Andre.',
      '',
      '## Review',
      '',
      'Annually each February by Agil, and on any of: a new lease, a branch relocation, or a physical',
      'security incident raised under the event reporting control.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-7-2',
    title: 'Physical Entry and Visitor Control',
    clause: 'A.7.2',
    crossRefs: ['A.7.1', 'A.7.4', 'A.6.5'],
    version: 'v2.2',
    owner: 'Pak Andre',
    form: { code: 'FRM-A-7-2-01', name: 'Visitor and contractor entry log' },
    revisions: [
      {
        version: 'v2.1',
        date: '2025-05-21',
        author: 'Pak Andre',
        approval: 'Reviewed by Agil',
        status: 'Superseded',
        note: 'Paper visitor book standardised across branches after three sites were found using notebooks with no columns.',
      },
      {
        version: 'v2.2',
        date: '2026-01-13',
        author: 'Pak Andre',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Contractor escort rule added for Zone 3 work; leaver key return tied to the offboarding checklist.',
      },
    ],
    evidence: [
      {
        name: 'visitor-entry-log-kemang-2026-q2.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-07-02',
        expiryDate: '2027-07-02',
        uploader: 'Pak Andre',
        note: 'Second-quarter entry log for the Kemang branch, sampled at the internal audit.',
        body: [
          'Date | Visitor | Organisation | Purpose | Zone | Host | In | Out',
          '2026-04-08 | Sutrisno | PT Mitra Dingin | AC service, treatment wing | 1 | Kemang duty nurse | 09:10 | 11:40',
          '2026-04-22 | Hendra | Telkom | Fibre fault, comms cabinet | 3 | Agil (remote approval) | 14:05 | 15:20',
          '2026-05-06 | Lisa Marbun | BPOM inspector | Drug store inspection | 2 | Pak Andre | 10:00 | 12:30',
          '2026-05-19 | Yudi | PT Bersih Jaya | Deep clean, waiting area | 0 | Kemang receptionist | 20:00 | 22:15',
          '2026-06-11 | Andreas | Dermaster HQ | Wi-Fi survey | 1, 3 | Pak Andre | 13:00 | 16:00',
          '',
          'Sample of 40 rows: two had no exit time recorded, both cleaning visits. The receptionist was',
          'retrained on 6 July 2026 and the log now closes at end of shift rather than end of visit.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-7-2 · Physical Entry and Visitor Control',
      '',
      '**Owner** Pak Andre · **Approver** Aris Ihwan · **Version** v2.2 · **Review** every six months',
      '**Requirement** A.7.2 · **Also satisfies** A.7.1, A.7.4, A.6.5',
      '',
      '## Purpose',
      '',
      'Most physical risk at a clinic arrives through the front door on an ordinary weekday: a',
      'contractor who needs the comms cabinet, an inspector who needs the drug store, a courier who',
      'walks past reception because nobody stopped him. This procedure sets out who may pass each',
      'zone boundary and how that passage is recorded.',
      '',
      '## Scope',
      '',
      'Entry by staff, contractors, regulators, patients and couriers at every clinic branch, the',
      'Jakarta head office and the Cakung warehouse. Patient movement into Zone 1 for treatment is',
      'governed by the clinical booking process and is not logged here; a patient entering Zone 2 is.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Pak Andre** owns the procedure and holds the master key schedule for all branches.',
      '- The **branch receptionist** on duty operates the log and challenges anyone unbadged.',
      '- **Agil** approves Zone 3 access and names the escort before a comms cabinet is opened.',
      '- **Randy**, as on-call, may authorise an out-of-hours Zone 3 entry when Agil is unreachable,',
      '  and must tell Agil the same day.',
      '',
      '## Procedure',
      '',
      '1. **Staff entry.** Staff enter Zone 1 with their own key or card. Keys are issued by Pak Andre',
      '   against the branch key schedule and are personal — a shared key is a finding.',
      '2. **Visitor arrival.** The receptionist records name, organisation, purpose, the highest zone',
      '   needed, the host and the time in, then issues a numbered visitor badge.',
      '3. **Escort rule.** Zone 1 and Zone 2 visitors move with a member of staff. Zone 3 visitors are',
      '   escorted the whole time the cabinet is open, without exception, including Telkom engineers.',
      '4. **Zone 3 pre-approval.** Cabinet work is approved by Agil before the visit, by message or',
      '   ticket, and the approval reference goes in the log. Unapproved cabinet work is refused.',
      '5. **Departure.** The receptionist takes the badge back and writes the time out. Any badge not',
      '   returned by close of shift is reported to Pak Andre that evening.',
      '6. **Out of hours.** Entry outside 08:00–21:00 needs the site custodian’s agreement in advance.',
      '   Cleaning crews work only while a member of staff is on site.',
      '7. **Leavers.** Key and badge return is a line on the offboarding checklist; Pak Andre confirms',
      '   it within 2 working days of the last working day, and rekeys the branch if a key is missing.',
      '8. **Monthly check.** Pak Andre reviews one week of each branch’s log per month for blank exit',
      '   times, missing hosts and unescorted Zone 3 rows, and raises corrections at the branch.',
      '',
      '## Records',
      '',
      'Entry logs (FRM-A-7-2-01) are kept at the branch for the current quarter, then scanned and',
      'filed against A.7.2 for two years. Key schedules and rekeying notes are retained for the life',
      'of the lease plus one year.',
      '',
      '## Review',
      '',
      'Every six months by Pak Andre with Agil, and immediately after any unescorted-access incident.',
    ].join('\n'),
  },
  {
    code: 'ISMS-POL-A-7-3',
    title: 'Securing Offices, Rooms and Facilities',
    clause: 'A.7.3',
    crossRefs: ['A.7.1', 'A.7.7', 'A.7.10'],
    version: 'v1.4',
    owner: 'Agil',
    form: { code: 'FRM-A-7-3-01', name: 'Secured room inspection record' },
    revisions: [
      {
        version: 'v1.3',
        date: '2024-11-26',
        author: 'Agil',
        approval: 'Reviewed by Pak Andre',
        status: 'Superseded',
        note: 'First version covering the HQ finance and HR rooms only.',
      },
      {
        version: 'v1.4',
        date: '2026-03-30',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Extended to branch records rooms and drug stores; signage rule reversed after a mall directory listed our records room by name.',
      },
    ],
    evidence: [
      {
        name: 'secured-room-inspection-2026-h1.docx',
        fileType: 'DOCX',
        uploadedAt: '2026-04-04',
        expiryDate: '2027-04-04',
        uploader: 'Agil',
        note: 'First-half inspection of every Zone 2 room, with the two defects raised and their closure.',
      },
    ],
    body: [
      '# ISMS-POL-A-7-3 · Securing Offices, Rooms and Facilities',
      '',
      '**Owner** Agil · **Approver** Aris Ihwan · **Version** v1.4 · **Review** twice yearly',
      '**Requirement** A.7.3 · **Also satisfies** A.7.1, A.7.7, A.7.10',
      '',
      '## Purpose',
      '',
      'A zone boundary only means something if the rooms behind it are built and used to hold it.',
      'This policy states the minimum physical standard for a room that holds patient records,',
      'finance papers, personnel files or controlled consumables, and what staff must do with those',
      'rooms day to day.',
      '',
      '## Scope',
      '',
      'Every Zone 2 room named in the site zone register: branch records rooms, branch drug stores,',
      'the HQ finance room, the HQ HR room and the Cakung bonded cage. Treatment rooms are Zone 1 and',
      'are covered by clinical procedure, not by this document. Comms cabinets are Zone 3 and are',
      'covered by ISMS-SOP-A-7-6.',
      '',
      '## Roles and responsibilities',
      '',
      'Agil sets the standard and inspects against it. Pak Andre is responsible for the branch rooms',
      'meeting it in daily use, and Pak Rila for the finance room. Dhiaz Fathra approves any',
      'exception, which is time-boxed and recorded with the compensating control.',
      '',
      '## Policy',
      '',
      '1. **Lock standard.** A Zone 2 room has a self-latching door with a deadlocking mechanism. The',
      '   key is held by the custodian and one named deputy; there is no third copy.',
      '2. **Closed by default.** The door is closed and locked whenever the room is not occupied, not',
      '   merely at end of day. A propped-open Zone 2 door is a reportable event.',
      '3. **No external signage.** Room function is not advertised on the door, on a mall directory or',
      '   on a public floor plan. Internal wayfinding uses room numbers.',
      '4. **No visual exposure.** Records cabinets and monitors are positioned so that nothing readable',
      '   is visible from a Zone 0 or Zone 1 space, including through a glazed door or an interior',
      '   window. Where glazing exists, it is filmed.',
      '5. **Nothing personal stays out.** Patient files, personnel files and printed invoices are',
      '   returned to a locked cabinet before the room is left, as required by the clear desk rule.',
      '6. **Fabric integrity.** Walls of a Zone 2 room run slab to slab where the landlord permits it.',
      '   Where a partition stops at a suspended ceiling, the room may not hold original patient',
      '   records, and an alternative room is designated.',
      '7. **Inspection.** Agil inspects every Zone 2 room twice a year against points 1 to 6 and',
      '   records the result. A defect on points 1, 2 or 5 is corrected within 10 working days.',
      '',
      '## Records',
      '',
      'Inspection records (FRM-A-7-3-01) are filed against A.7.3 and retained for three years.',
      'Exceptions and their expiry dates are held in the same folder and are reported to the',
      'management review while open.',
      '',
      '## Review',
      '',
      'Twice yearly by Agil with Pak Andre, and on any change to a room’s use or occupancy.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-7-4',
    title: 'Physical Security Monitoring',
    clause: 'A.7.4',
    crossRefs: ['A.7.2', 'A.6.8', 'A.8.15'],
    version: 'v1.3',
    owner: 'Agil',
    form: { code: 'FRM-A-7-4-01', name: 'CCTV retrieval and review record' },
    revisions: [
      {
        version: 'v1.1',
        date: '2025-02-04',
        author: 'Agil',
        approval: 'Reviewed by Rica',
        status: 'Superseded',
        note: 'Camera placement agreed with the controller representative; no camera in a treatment room.',
      },
      {
        version: 'v1.3',
        date: '2026-05-12',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Retention cut from 90 to 30 days on Rica’s advice, and the retrieval request route formalised after an ad-hoc export in March.',
      },
    ],
    evidence: [
      {
        name: 'cctv-retrieval-record-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-29',
        expiryDate: '2027-06-29',
        uploader: 'Agil',
        note: 'Every footage retrieval in the year to date, with the requester and the lawful basis.',
        body: [
          'Ref | Date | Site | Period requested | Requester | Reason | Approved by | Disposed',
          'CCTV-2026-01 | 2026-02-11 | PIK | 2026-02-09 18:00–20:00 | Pak Andre | Missing consumables stock | Agil | 2026-03-13',
          'CCTV-2026-02 | 2026-03-24 | Kemang | 2026-03-23 all day | Pak Rila | Cash reconciliation dispute | Agil | 2026-04-25',
          'CCTV-2026-03 | 2026-05-02 | Surabaya | 2026-05-01 07:00–09:00 | Pak Andre | Unescorted contractor report | Dhiaz Fathra | 2026-06-03',
          '',
          'CCTV-2026-02 was exported to a laptop before the request form existed; the gap prompted',
          'v1.3 of the procedure. All three exports were confirmed deleted within 30 days of retrieval.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-7-4 · Physical Security Monitoring',
      '',
      '**Owner** Agil · **Approver** Aris Ihwan · **Version** v1.3 · **Review** annually, each May',
      '**Requirement** A.7.4 · **Also satisfies** A.7.2, A.6.8, A.8.15',
      '',
      '## Purpose',
      '',
      'Cameras in a clinic sit awkwardly between two duties: they help us know who entered a records',
      'room, and they are themselves a processing of personal data belonging to patients and staff.',
      'This procedure describes what is monitored, what is deliberately not, and the only route by',
      'which footage may be looked at.',
      '',
      '## Scope',
      '',
      'CCTV and door-contact monitoring at all clinic branches, the Jakarta head office and the',
      'Cakung warehouse. Logical monitoring of systems is out of scope and lives with the logging',
      'control. Landlord cameras in mall corridors are not ours and we hold no footage from them.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Agil** operates the recorders, holds the only administrator credential and approves',
      '  routine retrievals.',
      '- **Rica** advises as controller representative on placement, signage and retention, and must',
      '  be told of any retrieval involving an identifiable patient.',
      '- **Pak Andre** puts up the notices at each branch and answers staff questions about coverage.',
      '- **Dhiaz Fathra** approves any retrieval connected to a suspected disciplinary matter.',
      '',
      '## Procedure',
      '',
      '1. **Where cameras go.** Entrances, reception, the corridor outside each Zone 2 room, the',
      '   goods-in bay and the comms cabinet approach.',
      '2. **Where they never go.** Treatment rooms, consultation rooms, changing areas, toilets and',
      '   staff rest rooms. No exception to this is available to any manager.',
      '3. **Notice.** A visible notice in Bahasa Indonesia and English at every entrance names',
      '   Dermaster as operator, the purpose and the contact point. Pak Andre checks the notices are',
      '   present at each branch visit.',
      '4. **Retention.** Recordings overwrite after 30 days. Nobody may extend retention on a live',
      '   recorder; footage needed beyond 30 days is exported under step 5.',
      '5. **Retrieval.** A request states the site, the exact period and the reason. Agil approves',
      '   routine operational requests; Dhiaz Fathra approves anything disciplinary; Rica is informed',
      '   where a patient is identifiable. Agil exports to an encrypted volume, logs the request in',
      '   FRM-A-7-4-01, and deletes the export within 30 days unless it is evidence in an open case.',
      '6. **No live viewing as supervision.** Cameras are not used to monitor staff performance, and',
      '   the recorder interface is not available at reception.',
      '7. **Health check.** Agil confirms monthly that every camera is recording and that the recorder',
      '   clock is within a minute of network time; a dead camera is replaced within 10 working days.',
      '8. **Incidents.** Anything the footage shows that looks like an intrusion or an unescorted entry',
      '   is raised as a security event under the event reporting control the same working day.',
      '',
      '## Records',
      '',
      'The retrieval record (FRM-A-7-4-01) is retained for three years. Camera health checks are',
      'noted in the monthly infrastructure log. Footage itself is not a controlled record and is not',
      'archived.',
      '',
      '## Review',
      '',
      'Annually each May by Agil with Rica, and whenever a camera is added, moved or removed.',
    ].join('\n'),
  },
  {
    code: 'ISMS-POL-A-7-5',
    title: 'Protection Against Physical and Environmental Threats',
    clause: 'A.7.5',
    crossRefs: ['A.7.11', 'A.8.14', 'A.5.29'],
    version: 'v2.0',
    owner: 'Agil',
    form: { code: 'FRM-A-7-5-01', name: 'Site environmental threat assessment' },
    revisions: [
      {
        version: 'v1.0',
        date: '2024-06-18',
        author: 'Andreas',
        approval: 'Drafted',
        status: 'Superseded',
        note: 'Initial assessment written around fire and theft only.',
      },
      {
        version: 'v2.0',
        date: '2026-04-21',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Flood added as the leading threat after the January 2026 Kelapa Gading inundation; ground-floor records storage prohibited.',
      },
    ],
    evidence: [
      {
        name: 'site-threat-assessment-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-04-21',
        expiryDate: '2027-04-21',
        uploader: 'Agil',
        note: 'Per-site threat rating with the control in place and the residual position.',
        body: [
          'Site | Flood | Fire | Power loss | Civil disturbance | Leading control | Residual',
          'Jakarta HQ (4th floor) | Low | Medium | Medium | Low | Building sprinkler + UPS on cabinet | Accepted',
          'Kemang (ground floor) | High | Medium | Medium | Low | Records moved to first floor, Feb 2026 | Accepted',
          'PIK (mall, level 2) | Low | Medium | Low | Low | Mall fire system, monthly extinguisher check | Accepted',
          'Surabaya Pakuwon (mall) | Low | Medium | Low | Low | Mall fire system | Accepted',
          'Bandung Dago (ground floor) | Medium | Medium | High | Low | UPS replaced Mar 2026, records on racking 40cm up | Accepted',
          'Cakung warehouse | High | High | Medium | Medium | Pallet racking 30cm clear, foam extinguishers | Monitored',
          '',
          'Cakung remains the only site with a monitored residual: consumables at floor level cannot be',
          'raised further without new racking, quoted and deferred to the 2027 budget.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-A-7-5 · Protection Against Physical and Environmental Threats',
      '',
      '**Owner** Agil · **Approver** Aris Ihwan · **Version** v2.0 · **Review** annually, each April',
      '**Requirement** A.7.5 · **Also satisfies** A.7.11, A.8.14, A.5.29',
      '',
      '## Purpose',
      '',
      'Jakarta floods, malls lose power, and a clinic that cannot open loses a day of bookings and',
      'the records that were on the desk when the water arrived. This policy sets out how the group',
      'assesses environmental threats per site and what protection each site must have in place.',
      '',
      '## Scope',
      '',
      'Fire, flood, power loss, water ingress and civil disturbance at all occupied sites. Pandemic',
      'and public health disruption are handled under clinical continuity planning. Threats to the',
      'production platform are the cloud provider’s and are addressed through redundancy rather than',
      'physical protection.',
      '',
      '## Roles and responsibilities',
      '',
      'Agil runs the annual per-site assessment and maintains the threat register. Pak Andre executes',
      'the branch-level protections and organises the drills. Pak Chen does the same at Cakung.',
      'Aris Ihwan approves the residual position for any site that cannot be brought to the standard.',
      '',
      '## Policy',
      '',
      '1. **Every site is assessed annually** against fire, flood, power loss, water ingress and civil',
      '   disturbance, rated High, Medium or Low, with the control in place named for each rating.',
      '2. **No original patient records at ground level in a flood-rated site.** Where a site is rated',
      '   Medium or High for flood, paper records sit at least 40 cm above floor level or on an upper',
      '   floor. Kemang moved its records room upstairs in February 2026 under this rule.',
      '3. **Fire cover.** Each site carries extinguishers appropriate to its contents, inspected',
      '   monthly by the branch and serviced annually by the contractor. A CO₂ or clean-agent',
      '   extinguisher is within five metres of every comms cabinet — never water or foam.',
      '4. **No storage of flammables in Zone 2 or Zone 3.** Alcohol-based consumables are stored in the',
      '   designated store only, and never in a records room or beside a cabinet.',
      '5. **Water ingress.** Nothing electrical or paper-based sits directly beneath a pipe run, a',
      '   chilled-water line or an AC unit. Where the landlord’s services cross a Zone 2 room, a drip',
      '   tray and a monthly visual check are required.',
      '6. **Evacuation drill twice a year** at every branch, run with the landlord where the building',
      '   mandates it, with attendance recorded by Pak Andre.',
      '7. **Accepted residuals are named and dated.** A site that cannot meet a point above is recorded',
      '   with its residual rating, the reason and a review date, and is reported to the management',
      '   review while it remains open.',
      '',
      '## Records',
      '',
      'The site threat assessment (FRM-A-7-5-01), extinguisher service certificates and drill',
      'attendance sheets are filed against A.7.5 and retained for three years.',
      '',
      '## Review',
      '',
      'Annually each April, and after any fire, flood or forced closure at any site.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-7-6',
    title: 'Working in Secure Areas',
    clause: 'A.7.6',
    crossRefs: ['A.7.3', 'A.7.2', 'A.7.7'],
    version: 'v1.2',
    owner: 'Agil',
    form: { code: 'FRM-A-7-6-01', name: 'Secure area work permit' },
    revisions: [
      {
        version: 'v1.1',
        date: '2025-08-07',
        author: 'Randy',
        approval: 'Reviewed by Agil',
        status: 'Superseded',
        note: 'Drafted after an out-of-hours switch replacement went ahead with no record of who opened the cabinet.',
      },
      {
        version: 'v1.2',
        date: '2026-02-25',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Photography rule and the lone-working prohibition for Zone 3 added; permit made mandatory for cabinet work of any length.',
      },
    ],
    evidence: [
      {
        name: 'secure-area-work-permit-pik-switch-2026-05.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-05-28',
        uploader: 'Randy',
        note: 'Signed permit for the PIK branch switch replacement, with before-and-after cabinet photographs referenced.',
      },
    ],
    body: [
      '# ISMS-SOP-A-7-6 · Working in Secure Areas',
      '',
      '**Owner** Agil · **Approver** Aris Ihwan · **Version** v1.2 · **Review** annually, each February',
      '**Requirement** A.7.6 · **Also satisfies** A.7.3, A.7.2, A.7.7',
      '',
      '## Purpose',
      '',
      'Zone 2 and Zone 3 spaces are secure because of how people behave inside them, not only because',
      'of the lock on the door. This procedure sets the rules for working in one, and the permit that',
      'records the work when it is done by someone who does not normally hold that key.',
      '',
      '## Scope',
      '',
      'All work carried out inside a records room, drug store, finance room, HR room, bonded cage or',
      'comms cabinet. Routine retrieval of a single patient file by clinical staff is not work under',
      'this procedure; a stock count, a cabinet change or a contractor visit is.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Agil** issues permits for Zone 3 and reviews every closed permit.',
      '- **Pak Andre** issues permits for branch Zone 2 spaces; **Pak Rila** for the finance room.',
      '- **Randy** may issue and act on a Zone 3 permit out of hours as on-call, and tells Agil the',
      '  same day.',
      '- Anyone working in a secure area is responsible for leaving it in the state described in step 7.',
      '',
      '## Procedure',
      '',
      '1. **Raise a permit before the work.** The permit names the room, the work, the people, the',
      '   window and the issuer. Verbal approval is not a permit; a message thread with the same four',
      '   facts, filed afterwards, is acceptable for an out-of-hours fault.',
      '2. **Two people for Zone 3.** Nobody works alone in an open comms cabinet. The second person may',
      '   be branch staff and does not need to be technical.',
      '3. **Contractors are escorted continuously**, as required by the entry procedure, and are named',
      '   on the permit before arrival.',
      '4. **No photography or recording** inside a Zone 2 room. Photographs inside a cabinet are allowed',
      '   and expected — before and after — and are attached to the permit rather than kept on a phone.',
      '5. **No personal storage devices.** USB drives and personal laptops do not enter Zone 3. Where a',
      '   device is needed to configure equipment, it is a company machine listed on the permit.',
      '6. **Nothing leaves without a line on the permit.** Removing a disk, a file, a drug or a piece of',
      '   equipment is written on the permit at the moment it happens, not reconstructed later.',
      '7. **Close-out.** The room or cabinet is locked, the key returned, cabling dressed, and the',
      '   permit signed off with the actual finish time. The issuer reviews it within 5 working days.',
      '8. **Unattended is not permitted.** A secure area is never left open while the worker steps out,',
      '   however briefly, including to fetch a tool.',
      '',
      '## Records',
      '',
      'Permits (FRM-A-7-6-01) are filed against A.7.6 with any attached photographs and retained for',
      'three years. Permits touching drug storage are also copied to the branch clinical file.',
      '',
      '## Review',
      '',
      'Annually each February by Agil, and after any incident where work in a secure area caused an',
      'outage or a loss.',
    ].join('\n'),
  },
  {
    code: 'ISMS-POL-A-7-7',
    title: 'Clear Desk and Clear Screen',
    clause: 'A.7.7',
    crossRefs: ['A.7.3', 'A.8.1', 'A.5.10'],
    version: 'v2.1',
    owner: 'Pak Andre',
    form: { code: 'FRM-A-7-7-01', name: 'Clear desk spot-check record' },
    revisions: [
      {
        version: 'v2.0',
        date: '2025-03-18',
        author: 'Pak Andre',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Rewritten for reception desks after patient names were visible on a monitor in a waiting-area photograph posted online.',
      },
      {
        version: 'v2.1',
        date: '2026-06-02',
        author: 'Pak Andre',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Screen lock reduced to 5 minutes at reception, 10 elsewhere; printer collection rule added after unclaimed invoices were found in the HQ tray.',
      },
    ],
    evidence: [
      {
        name: 'clear-desk-spot-checks-2026-h1.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-30',
        expiryDate: '2027-06-30',
        uploader: 'Pak Andre',
        note: 'Spot-check results across branches and HQ for the first half of 2026.',
        body: [
          'Date | Site | Desks checked | Papers left out | Screen unlocked | Printer tray | Action',
          '2026-01-20 | Kemang | 6 | 1 | 0 | clear | Verbal, receptionist',
          '2026-02-17 | HQ | 14 | 2 | 1 | 3 invoices | Toolbox talk, 19 Feb',
          '2026-03-24 | PIK | 8 | 0 | 1 | clear | Verbal, duty nurse',
          '2026-04-21 | Surabaya | 5 | 0 | 0 | clear | None',
          '2026-05-19 | Bandung | 5 | 1 | 0 | 1 lab form | Verbal, branch admin',
          '2026-06-16 | HQ | 14 | 0 | 0 | clear | None',
          '',
          'Trend: the February HQ result drove the printer rule in v2.1. Two consecutive clean HQ',
          'checks followed. Screen-unlock findings are now rare since the 5-minute reception policy.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-A-7-7 · Clear Desk and Clear Screen',
      '',
      '**Owner** Pak Andre · **Approver** Aris Ihwan · **Version** v2.1 · **Review** twice yearly',
      '**Requirement** A.7.7 · **Also satisfies** A.7.3, A.8.1, A.5.10',
      '',
      '## Purpose',
      '',
      'The most common way patient information leaves this organisation is not an attack. It is a',
      'name left on a reception monitor while a stranger stands at the counter, or a consent form left',
      'in a printer tray overnight. This policy sets what may be visible, and for how long.',
      '',
      '## Scope',
      '',
      'Every desk, counter, printer, whiteboard and screen at every site, plus company laptops used',
      'at home or in a café under the remote working control. It applies equally to clinical, admin',
      'and engineering staff.',
      '',
      '## Roles and responsibilities',
      '',
      'Pak Andre owns the policy and runs the spot checks at branches; Dhiaz Fathra does the same for',
      'the engineering floor at HQ. Every member of staff is responsible for their own desk and',
      'screen. Agil configures the screen lock centrally so it is not a matter of individual habit.',
      '',
      '## Policy',
      '',
      '1. **Nothing with a patient name stays on a surface unattended.** Files, consent forms, lab',
      '   results and printed schedules go into a locked drawer or the records room the moment the',
      '   desk is left.',
      '2. **Screen lock is enforced, not requested.** Five minutes on reception and shared clinical',
      '   machines, ten minutes elsewhere, applied by policy on the device rather than left to the user.',
      '   Staff lock manually when stepping away — the timeout is a backstop.',
      '3. **Reception monitors face away from the counter,** or carry a privacy filter where the layout',
      '   makes that impossible. Pak Andre checks this at each branch visit.',
      '4. **Print and collect.** Documents are collected from the printer immediately. Trays are cleared',
      '   at the end of every shift; anything left is shredded, not refiled.',
      '5. **Whiteboards are wiped** at the end of any meeting where a patient, a supplier price or a',
      '   credential was written. Engineering diagrams may stay.',
      '6. **No credentials on paper.** Passwords, PINs and door codes are never written on a note, a',
      '   monitor or under a keyboard. Use the password manager.',
      '7. **End of day.** Desks are clear of paper, drawers locked, laptops taken home or locked away.',
      '8. **Spot checks.** One site per month, unannounced, recording desks checked and findings by',
      '   type. Two findings for the same person within six months is a conversation with the line',
      '   manager, not a disciplinary step.',
      '',
      '## Records',
      '',
      'Spot-check records (FRM-A-7-7-01) are filed against A.7.7 and retained for two years. The',
      'half-yearly trend is an input to the management review.',
      '',
      '## Review',
      '',
      'Twice yearly by Pak Andre with Dhiaz Fathra, and after any incident where information was',
      'exposed in a work area.',
    ].join('\n'),
  },
]
