import type { SeedDocument } from './types'

/** Annex A.5 organisational controls, first half: A.5.1 to A.5.6. */
export const ANNEX_A5_A_1: SeedDocument[] = [
  {
    code: 'ISMS-POL-A-5-1',
    title: 'Information Security Policy Framework',
    clause: 'A.5.1',
    crossRefs: ['A.5.2', 'A.5.4', 'A.5.31', 'A.5.36'],
    version: 'v2.0',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-5-1-01', name: 'Policy acknowledgement register' },
    revisions: [
      {
        version: 'v1.2',
        date: '2024-09-12',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Superseded',
        note: 'First framework issued when the ISMS scope still covered head office only.',
      },
      {
        version: 'v2.0',
        date: '2026-02-19',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Scope extended to all clinic locations and the engineering group; topic policy list replaced the old flat index; acknowledgement moved from paper to the HR portal.',
      },
    ],
    evidence: [
      {
        name: 'policy-acknowledgement-register-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-03-02',
        expiryDate: '2027-03-02',
        uploader: 'Dhiaz Fathra',
        note: 'Who has acknowledged the current framework and each topic policy, by department.',
        body: [
          'Department | Headcount | Acknowledged v2.0 | Outstanding | Chased on',
          'Clinic operations | 168 | 164 | 4 | 2026-03-02',
          'Engineering | 22 | 22 | 0 | —',
          'Finance | 9 | 9 | 0 | —',
          'Procurement | 6 | 5 | 1 | 2026-03-02',
          'Marketing | 11 | 11 | 0 | —',
          'Directors | 3 | 3 | 0 | —',
          'Total | 219 | 214 | 5 | five leavers-in-notice, closed 2026-03-14',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-A-5-1 · Information Security Policy Framework',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v2.0 · **Review** annual',
      '**Requirement** A.5.1 · **Also satisfies** A.5.2, A.5.4, A.5.31, A.5.36',
      '',
      '## Purpose',
      '',
      'Dermaster Indonesia runs 13 clinic locations and an in-house engineering group on the',
      'same information estate. Clinic staff handle patient records at a treatment room desk;',
      'engineers handle the same records as rows in a database in AWS ap-southeast-1. One',
      'sentence of intent has to cover both, and the detail has to sit somewhere a nurse and a',
      'backend engineer can each find their own part. This document is that top-level intent',
      'and the index of the topic policies beneath it.',
      '',
      '## Scope',
      '',
      'Every employee, contractor, intern and clinic partner with an account in Zitadel, and',
      'every system that stores or moves group information — clinical systems, the Super App,',
      'the ERP services, finance systems, and the office and clinic networks. It does not cover',
      'the clinical safety of a treatment itself, which sits under the medical governance',
      'committee, nor the physical building fabric, which is landlord-managed at nine sites.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Aris Ihwan (Director)** approves this framework and each topic policy, and is the',
      '  authority for any accepted risk above the tolerance set in the risk method.',
      '- **Dhiaz Fathra (Head of Engineering, ISMS Management Representative)** maintains the',
      '  framework, keeps the topic policy list current, and reports coverage at the management',
      '  review.',
      '- **Department heads** — Pak Andre (clinic operations), Pak Chen (procurement), Pak Rila',
      '  (finance) — make the policies real inside their function and confirm acknowledgement.',
      '- **Every individual** reads the policies that apply to their role and works to them.',
      '',
      '## Policy',
      '',
      '1. The group protects the confidentiality, integrity and availability of patient,',
      '   commercial and employee information as a condition of operating, not as a project.',
      '2. This framework is supported by topic policies, each with a single named owner: access',
      '   control, acceptable use, classification and labelling, supplier security, incident',
      '   management, secure development, business continuity, personal data handling, and',
      '   physical security. A topic policy without a named owner is withdrawn at the next',
      '   review rather than carried as an orphan.',
      '3. Every policy is reviewed at least annually, and additionally after any incident rated',
      '   major, any change of scope, and any change to Indonesian law that touches the estate.',
      '4. Policies are published in this repository. The version in the repository is the',
      '   controlled version; a copy printed, emailed or pinned to a clinic notice board is',
      '   uncontrolled and is marked as such.',
      '5. New joiners acknowledge the framework and the policies for their role within 10',
      '   working days of their start date, through the HR portal. Department heads clear',
      '   outstanding acknowledgements monthly.',
      '6. Deliberate breach of a policy is a disciplinary matter under the employee handbook.',
      '   An honest report of an own mistake is not: the incident procedure depends on people',
      '   speaking early, and that is worth more than the deterrent.',
      '',
      '## Records',
      '',
      'The acknowledgement register (FRM-A-5-1-01) is held in the HR portal and exported to',
      'this repository quarterly, retained three years. Approved policy versions and their',
      'revision history are retained for the life of the ISMS plus three years.',
      '',
      '## Review',
      '',
      'Annually by Dhiaz Fathra, approved by Aris Ihwan, with the coverage figure tabled at the',
      'quarterly management review.',
    ].join('\n'),
  },
  {
    code: 'ISMS-POL-A-5-2',
    title: 'Information Security Roles and Responsibilities',
    clause: 'A.5.2',
    crossRefs: ['A.5.1', 'A.5.3', 'A.5.4', 'A.6.3'],
    version: 'v1.4',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-5-2-01', name: 'Security responsibility assignment matrix' },
    revisions: [
      {
        version: 'v1.3',
        date: '2025-05-06',
        author: 'Dhiaz Fathra',
        approval: 'Reviewed by Aris Ihwan',
        status: 'Superseded',
        note: 'Matrix held only head-office roles; clinic-side ownership was implied rather than assigned.',
      },
      {
        version: 'v1.4',
        date: '2026-01-27',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Clinic location security coordinator role created under Pak Andre; on-call security duty formalised for Randy and Agil.',
      },
    ],
    evidence: [
      {
        name: 'security-responsibility-matrix-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-01-27',
        expiryDate: '2027-01-27',
        uploader: 'Dhiaz Fathra',
        note: 'Accountable and responsible person for each security activity, reviewed at appointment.',
        body: [
          'Activity | Accountable | Responsible | Consulted | Cadence',
          'Risk assessment and treatment plan | Aris Ihwan | Dhiaz Fathra | department heads | quarterly',
          'Access review | Dhiaz Fathra | Randy | Pak Andre | quarterly',
          'Vulnerability triage and patching | Dhiaz Fathra | Agil | Randy | continuous',
          'Incident first response | Dhiaz Fathra | on-call engineer | Rica (if personal data) | on event',
          'Personal data requests and RoPA | Aris Ihwan | Rica | Dhiaz Fathra | monthly',
          'Supplier security assessment | Pak Chen | Andreas | Dhiaz Fathra | at onboarding, then annual',
          'Clinic device and record handling | Pak Andre | location coordinator | Agil | monthly walk',
          'Measurement and internal audit data | Dhiaz Fathra | Tika | all owners | quarterly',
        ].join('\n'),
      },
      {
        name: 'isms-representative-appointment-2026.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-01-27',
        uploader: 'Aris Ihwan',
        note: 'Signed appointment of the ISMS management representative and delegated authorities.',
        body: [
          '# Appointment of the ISMS Management Representative',
          '',
          '**Appointee** Dhiaz Fathra, Head of Engineering · **Signed** Aris Ihwan, Director,',
          '27 January 2026',
          '',
          'Dhiaz Fathra is appointed management representative for the information security',
          'management system, with authority to:',
          '',
          '1. Halt a release, a supplier onboarding or a data export where it would breach an',
          '   approved policy, reporting the decision to the Director within one working day.',
          '2. Convene an incident response and declare a major incident without prior approval.',
          '3. Commit spend up to IDR 50 million against an approved treatment action.',
          '',
          'The appointment does not transfer accountability for the ISMS, which remains with the',
          'Director. It runs until withdrawn in writing.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-A-5-2 · Information Security Roles and Responsibilities',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v1.4 · **Review** annual',
      '**Requirement** A.5.2 · **Also satisfies** A.5.1, A.5.3, A.5.4, A.6.3',
      '',
      '## Purpose',
      '',
      'A control with no name against it is a control nobody performs. The group is small',
      'enough that most people can name the person who runs a given security activity, and',
      'exactly for that reason the assignments were never written down. This document writes',
      'them down, so that an activity survives a resignation and an auditor can be handed one',
      'answer rather than three.',
      '',
      '## Scope',
      '',
      'All security activities in the ISMS scope statement, across clinic operations and the',
      'engineering group. Job descriptions and remuneration are out of scope; this document',
      'assigns duties, HR owns the contract of employment they sit in.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Director, Aris Ihwan** — accountable for the ISMS. Approves the risk tolerance,',
      '  accepts residual risk, chairs the management review.',
      '- **ISMS Management Representative, Dhiaz Fathra** — runs the system day to day under',
      '  the signed appointment held with this document.',
      '- **Solutions Architect, Andreas** — security in design: threat models, architecture',
      '  decision records, supplier technical assessment.',
      '- **Backend Engineer, Randy** — access administration, on-call first response.',
      '- **Infrastructure Engineer, Agil** — patching, backups, logging, clinic device build.',
      '- **QA Lead, Tika** — measurement, evidence collection, internal audit sampling.',
      '- **Controller representative, Rica** — personal data subject requests, RoPA, DPIA.',
      '- **Department heads (Pak Andre, Pak Chen, Pak Rila)** — asset ownership, joiner and',
      '  leaver notification, local enforcement.',
      '- **Clinic location security coordinator** — one named person per location, appointed by',
      '  Pak Andre, who performs the monthly clean-desk and device walk and raises incidents.',
      '',
      '## Policy',
      '',
      '1. Every security activity in the responsibility matrix has exactly one accountable role',
      '   and one responsible person. Two names in the accountable column is a defect and is',
      '   corrected at the review, not left as shared ownership.',
      '2. A person appointed to a security role is told so in writing and given the time. The',
      '   clinic coordinator role is budgeted at four hours a month; if the walk is not',
      '   happening, the cause is treated as a resourcing issue rather than a discipline issue.',
      '3. Where a role is vacant, its duties fall to the accountable role until filled, and the',
      '   vacancy is reported at the next management review with an expected fill date.',
      '4. Delegated authority is explicit and bounded — see the signed appointment. Nobody',
      '   assumes authority from seniority alone.',
      '5. The matrix is reconciled against the HR establishment quarterly by Tika, so that',
      '   leavers do not remain named against a live control.',
      '',
      '## Records',
      '',
      'Responsibility matrix (FRM-A-5-2-01) and signed appointments, held in this repository,',
      'retained for the life of the ISMS plus three years. Quarterly reconciliation output is',
      'attached to the management review pack.',
      '',
      '## Review',
      '',
      'Annually, and immediately on any change of department head, ISMS representative or',
      'clinic coordinator.',
    ].join('\n'),
  },
  {
    code: 'ISMS-POL-A-5-3',
    title: 'Segregation of Duties',
    clause: 'A.5.3',
    crossRefs: ['A.5.2', 'A.5.15', 'A.5.18', 'A.8.31'],
    version: 'v1.2',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-5-3-01', name: 'Conflicting duty register and compensating controls' },
    revisions: [
      {
        version: 'v1.1',
        date: '2025-02-11',
        author: 'Andreas',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Covered production access only; payment and procurement conflicts were not listed.',
      },
      {
        version: 'v1.2',
        date: '2026-04-08',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Procurement and refund conflicts added after the finance walkthrough; four-eyes rule on production data changes made mandatory rather than advisory.',
      },
    ],
    evidence: [
      {
        name: 'conflicting-duty-register-2026q2.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-04-08',
        expiryDate: '2026-10-08',
        uploader: 'Tika',
        note: 'Conflicts that cannot be separated at this headcount, and what compensates for each.',
        body: [
          'Conflict | Why it cannot be split | Compensating control | Reviewer | Last tested',
          'Agil builds and approves infrastructure changes | one infrastructure engineer | Andreas reviews every Terraform plan before apply; applies are logged | Dhiaz Fathra | 2026-04-02',
          'Randy administers access and holds production access | on-call must act at 02:00 | quarterly access review by Dhiaz Fathra; Randy cannot approve his own grant | Dhiaz Fathra | 2026-04-04',
          'Pak Chen selects and approves suppliers under IDR 25m | small procurement function | Pak Rila countersigns payment; supplier list sampled at internal audit | Aris Ihwan | 2026-03-27',
          'Clinic manager issues and approves refunds | single manager per site | refunds over IDR 2m need finance approval; daily refund report to Pak Rila | Pak Rila | 2026-04-06',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-A-5-3 · Segregation of Duties',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v1.2 · **Review** half-yearly',
      '**Requirement** A.5.3 · **Also satisfies** A.5.2, A.5.15, A.5.18, A.8.31',
      '',
      '## Purpose',
      '',
      'At 22 engineers and a lean finance function, textbook separation is not always available:',
      'the person who can fix production at two in the morning is also the person who grants',
      'that access. Pretending otherwise produces a policy nobody follows. This document states',
      'which combinations of duty the group refuses outright, and for the ones it cannot',
      'separate, what stands in their place and who checks it.',
      '',
      '## Scope',
      '',
      'Duties over production systems, access administration, procurement, payments and refunds,',
      'and the release path from merge request to deployment. Clinical decision-making is out of',
      'scope.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Dhiaz Fathra** maintains the conflicting duty register and approves each compensating',
      '  control.',
      '- **Andreas** is the independent reviewer for infrastructure and architecture changes.',
      '- **Tika** tests the compensating controls half-yearly and records the result.',
      '- **Pak Rila** owns the financial separation between raising, approving and paying.',
      '- **Aris Ihwan** approves any conflict the register cannot compensate.',
      '',
      '## Policy',
      '',
      '1. The following are never held by one person, at any headcount: raising and approving a',
      '   purchase order above IDR 25 million; requesting and approving a privileged access',
      '   grant; writing and approving the merge request that carries the same change; issuing',
      '   and approving a refund above IDR 2 million.',
      '2. Every production data change — an UPDATE or DELETE run outside the application —',
      '   requires a second engineer to review the statement before it runs, and both names go',
      '   on the change record. This is the four-eyes rule and it has no exception for urgency;',
      '   the on-call engineer wakes a second person instead.',
      '3. Where the group genuinely cannot separate a duty, the conflict is entered in the',
      '   register with a named compensating control, a reviewer and a test date. An unlisted',
      '   conflict discovered at audit is a nonconformity; a listed one is a managed risk.',
      '4. Compensating controls are tested half-yearly by Tika, by sampling actual records — a',
      '   Terraform apply log, an access grant, a refund over threshold — not by asking whether',
      '   the control exists.',
      '5. Deployment to production runs through the pipeline with an approval from someone other',
      '   than the author. Manual deployment from a laptop is not permitted; where the pipeline',
      '   is down, the deployment waits or the incident procedure is used.',
      '',
      '## Records',
      '',
      'Conflicting duty register (FRM-A-5-3-01) in this repository, retained three years.',
      'Four-eyes change records live in the change tickets, retained two years. Half-yearly',
      'test results are attached to the register entry they test.',
      '',
      '## Review',
      '',
      'Half-yearly by Dhiaz Fathra with Tika, and whenever headcount in a function changes',
      'enough to make a listed conflict separable — the register should shrink as the group',
      'grows.',
    ].join('\n'),
  },
  {
    code: 'ISMS-POL-A-5-4',
    title: 'Management Responsibilities for Information Security',
    clause: 'A.5.4',
    crossRefs: ['A.5.1', 'A.5.2', 'A.6.3', 'A.5.36'],
    version: 'v1.3',
    owner: 'Aris Ihwan',
    form: { code: 'FRM-A-5-4-01', name: 'Departmental security commitment record' },
    revisions: [
      {
        version: 'v1.2',
        date: '2024-11-25',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Superseded',
        note: 'Stated the expectation but gave department heads no cadence and nothing to sign.',
      },
      {
        version: 'v1.3',
        date: '2026-05-11',
        author: 'Aris Ihwan',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Monthly departmental commitment record introduced; security added as a standing item in each department meeting agenda.',
      },
    ],
    evidence: [
      {
        name: 'departmental-security-commitment-2026-05.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-05-30',
        uploader: 'Pak Andre',
        note: 'Signed monthly record from clinic operations: what was reinforced and what was escalated.',
        body: [
          '# Departmental security commitment — Clinic Operations, May 2026',
          '',
          '**Department head** Pak Andre · **Locations covered** 13 · **Signed** 30 May 2026',
          '',
          '## Reinforced this month',
          '',
          'Shared reception logins were withdrawn at four locations and replaced with named',
          'accounts; the front desk teams were briefed in the Monday huddle. Clean-desk walk',
          'completed at every location by the location coordinator.',
          '',
          '## Raised by staff',
          '',
          'Two coordinators reported that the treatment room screens lock too aggressively at 60',
          'seconds and staff work around it by tapping the trackpad. Raised with Agil rather than',
          'left to become a habit; timeout moved to 5 minutes with a badge-out lock.',
          '',
          '## Escalated',
          '',
          'One incident: a patient consent form photographed on a personal phone to send to head',
          'office. Reported by the coordinator the same day, handled under the incident procedure,',
          'the image was deleted and the correct upload route was retrained at that location.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-A-5-4 · Management Responsibilities for Information Security',
      '',
      '**Owner** Aris Ihwan · **Approver** Aris Ihwan · **Version** v1.3 · **Review** annual',
      '**Requirement** A.5.4 · **Also satisfies** A.5.1, A.5.2, A.6.3, A.5.36',
      '',
      '## Purpose',
      '',
      'Policies published by the engineering group and never mentioned again by a clinic manager',
      'are read once and forgotten. What people actually do is set by what their own manager',
      'asks about. This document states what the group requires of its managers, so that',
      'security arrives through the line rather than around it.',
      '',
      '## Scope',
      '',
      'Every person who manages staff or contractors: the Director, department heads, clinic',
      'managers, and engineering leads. It covers what they must do, not what their teams must',
      'do — that is in the acceptable use policy and the topic policies.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Aris Ihwan** owns this document, provides the resources the ISMS needs, and holds',
      '  department heads to the commitment record at the monthly leadership meeting.',
      '- **Pak Andre, Pak Chen, Pak Rila** sign a monthly commitment record for their function.',
      '- **Dhiaz Fathra** gives managers the material they need — briefing notes, the incident',
      '  route, the current policy set — so that the ask is practical.',
      '- **Tika** collates the monthly records into the management review pack.',
      '',
      '## Policy',
      '',
      '1. Every manager makes sure the people reporting to them know which policies apply to',
      '   their role, and have acknowledged them, before they touch patient or commercial data.',
      '2. Information security is a standing agenda item in every department meeting. Five',
      '   minutes and a real example beats an annual hour of slides.',
      '3. Managers notify HR and Randy on the same working day for every joiner, mover and',
      '   leaver. A leaver whose access is still live 24 hours after their last day is reported',
      '   as an incident, and the notification failure is attributed to the manager, not to the',
      '   engineer who was never told.',
      '4. Managers give staff the time and the tools to work securely. Where a control makes the',
      '   job impossible, the manager escalates it to Dhiaz Fathra rather than tolerating a',
      '   workaround — the May 2026 screen-lock change is the pattern to follow.',
      '5. Managers report incidents and near misses upward the day they hear of them, and do not',
      '   penalise the person who reported. The measure watched is time-to-report, not the',
      '   number of incidents.',
      '6. Each department head signs a monthly commitment record: what was reinforced, what',
      '   staff raised, what was escalated. An empty record is acceptable and is still signed;',
      '   a missing record is chased by the Director.',
      '',
      '## Records',
      '',
      'Monthly commitment records (FRM-A-5-4-01), retained two years, and summarised quarterly',
      'into the management review minutes.',
      '',
      '## Review',
      '',
      'Annually by the Director, informed by whether the monthly records are being produced and',
      'whether they carry anything real.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-5-5',
    title: 'Contact with Authorities',
    clause: 'A.5.5',
    crossRefs: ['A.5.24', 'A.5.26', 'A.5.31', 'A.5.34'],
    version: 'v2.0',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-A-5-5-01', name: 'Authority contact log' },
    revisions: [
      {
        version: 'v1.0',
        date: '2024-06-03',
        author: 'Rica',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'A contact list with no procedure; nobody knew who was allowed to make the call.',
      },
      {
        version: 'v2.0',
        date: '2026-03-17',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Notification steps and the 3x24-hour personal data breach clock written in; single spokesperson rule adopted; contact list moved to a quarterly verification.',
      },
    ],
    evidence: [
      {
        name: 'authority-contact-log-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-01',
        expiryDate: '2026-09-01',
        uploader: 'Rica',
        note: 'Every contact with a regulator or law enforcement, and the quarterly verification of the list.',
        body: [
          'Date | Authority | Reason | Initiated by | Spokesperson | Outcome',
          '2026-01-15 | Dinas Kesehatan (provincial health office) | routine clinic licensing inspection, records handling questions | authority | Pak Andre | no findings on record handling',
          '2026-02-09 | Kominfo / PDP supervisory contact | verification call, contact details for the controller representative | Dermaster | Rica | contact registered, no case opened',
          '2026-04-22 | Polda cyber unit | phishing domain impersonating the Super App | Dermaster | Dhiaz Fathra | domain takedown requested, completed 2026-05-06',
          '2026-06-01 | — | quarterly verification of all listed numbers and mailboxes | Dermaster | Rica | two numbers stale, corrected same day',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-5-5 · Contact with Authorities',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v2.0 · **Review** quarterly',
      '**Requirement** A.5.5 · **Also satisfies** A.5.24, A.5.26, A.5.31, A.5.34',
      '',
      '## Purpose',
      '',
      'When a clinic is inspected, a patient complains to the supervisory authority, or a',
      'ransomware note appears on a Monday morning, the group needs to already know who calls',
      'whom. Finding the right number during an incident costs hours the notification clock does',
      'not give back. This procedure holds the contacts, the triggers and the steps.',
      '',
      '## Scope',
      '',
      'Contact with health regulators, the personal data supervisory authority, law enforcement,',
      'the tax authority on matters touching information systems, and CERT-type bodies. Routine',
      'commercial correspondence and licensing paperwork handled by clinic administration are',
      'out of scope unless they concern an incident or a data subject.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Aris Ihwan** is the only person who authorises a notification to a regulator, and the',
      '  named spokesperson for anything that reaches the press.',
      '- **Rica** is the registered controller representative for personal data matters and',
      '  keeps the contact list verified.',
      '- **Dhiaz Fathra** is the technical point of contact for law enforcement and CERT',
      '  matters, and assembles the factual account.',
      '- **Pak Andre** hosts health-office inspections at clinic locations.',
      '',
      '## Procedure',
      '',
      '1. **Recognise the trigger.** Notification is required for: a personal data breach',
      '   (notify the supervisory authority and affected subjects within 3x24 hours of becoming',
      '   aware, under UU No. 27/2022); a criminal act against or using group systems; a',
      '   regulator request; a court order or subpoena.',
      '2. **Tell the Director within one hour** of recognising the trigger, through the incident',
      '   channel. No one else contacts an authority in the meantime.',
      '3. **Assemble the facts** — Dhiaz Fathra prepares what is known, what is not yet known,',
      '   when it started, how many records, what has been contained. State the unknowns as',
      '   unknown; do not estimate to fill a form.',
      '4. **Authorise and notify.** Aris Ihwan authorises. Rica sends personal data',
      '   notifications; Dhiaz Fathra makes law enforcement contact. Every notification goes in',
      '   writing, with the sent copy filed the same day.',
      '5. **One voice.** All follow-up questions route to the spokesperson named in step 4. Any',
      '   other employee contacted directly by an authority takes the caller details, says the',
      '   matter is handled by the named contact, and forwards it — this is not obstruction and',
      '   staff are briefed that it is expected of them.',
      '6. **Log it.** Every contact, inbound or outbound, is entered in the authority contact log',
      '   within one working day, including contacts that led nowhere.',
      '7. **Verify quarterly.** Rica calls or emails each listed contact once a quarter to',
      '   confirm the number, mailbox and named officer are still current, and records the check',
      '   in the log.',
      '',
      '## Records',
      '',
      'Authority contact log (FRM-A-5-5-01) and copies of every notification sent, retained five',
      'years given the limitation periods that apply to regulatory matters. Held with restricted',
      'access — Aris Ihwan, Dhiaz Fathra, Rica.',
      '',
      '## Review',
      '',
      'The contact list is verified quarterly by Rica. The procedure itself is reviewed annually',
      'and after any use of it in anger.',
    ].join('\n'),
  },
  {
    code: 'ISMS-SOP-A-5-6',
    title: 'Contact with Special Interest Groups',
    clause: 'A.5.6',
    crossRefs: ['A.5.7', 'A.6.3', 'A.8.8', 'A.5.5'],
    version: 'v1.1',
    owner: 'Andreas',
    form: { code: 'FRM-A-5-6-01', name: 'Professional membership and advisory feed register' },
    revisions: [
      {
        version: 'v1.0',
        date: '2025-08-19',
        author: 'Andreas',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Listed memberships but nothing said what the group did with what it learned.',
      },
      {
        version: 'v1.1',
        date: '2026-04-14',
        author: 'Andreas',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Routing rule added — every advisory that matters becomes a ticket or is explicitly dismissed with a reason; two dead mailing lists dropped.',
      },
    ],
    evidence: [
      {
        name: 'membership-and-feed-register-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-04-14',
        expiryDate: '2027-04-14',
        uploader: 'Andreas',
        note: 'Which external sources the group subscribes to, who reads them and how often they produced something actionable.',
        body: [
          'Source | Type | Reader | Frequency | Actionable items last 12 months',
          'Go security announce list | vendor advisory | Randy | as published | 6 (all patched within SLA)',
          'PostgreSQL announce | vendor advisory | Agil | as published | 3',
          'AWS security bulletins ap-southeast-1 | provider | Agil | weekly digest | 4',
          'ID-CERT / Gov-CSIRT advisories | national CERT | Dhiaz Fathra | weekly | 2 (one phishing campaign targeting clinics)',
          'OWASP Indonesia chapter | community | Andreas | monthly meetup | 1 (dependency confusion review)',
          'Healthcare privacy practitioner group (PDP) | peer network | Rica | monthly | 2 (consent wording, breach clock practice)',
          'Flutter / mobile security newsletter | community | Randy | monthly | 0 — retained, low cost',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-SOP-A-5-6 · Contact with Special Interest Groups',
      '',
      '**Owner** Andreas · **Approver** Aris Ihwan · **Version** v1.1 · **Review** annual',
      '**Requirement** A.5.6 · **Also satisfies** A.5.7, A.6.3, A.8.8, A.5.5',
      '',
      '## Purpose',
      '',
      'A 22-person engineering group cannot generate its own view of the threat landscape, and',
      'a clinic operator cannot invent good practice for handling patient consent on its own.',
      'Both come from outside — vendor advisories, the national CERT, practitioner peers. This',
      'procedure says which sources the group keeps, who reads them, and what happens to what',
      'they say, because a subscription nobody acts on is worse than none: it looks like',
      'coverage.',
      '',
      '## Scope',
      '',
      'Professional bodies, security mailing lists, vendor advisory feeds, national CERT',
      'channels and peer practitioner groups. Marketing newsletters and general technology',
      'press are not in scope and are not counted as sources.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Andreas** owns the register and reviews it annually for sources that have produced',
      '  nothing usable.',
      '- **A named reader per source** — no source is subscribed to a shared mailbox that',
      '  belongs to everyone and therefore to no one.',
      '- **Dhiaz Fathra** approves joining or leaving a paid body and funds attendance.',
      '- **Rica** carries the personal data practitioner network; **Tika** carries quality and',
      '  audit practice sources.',
      '',
      '## Procedure',
      '',
      '1. Propose a source to Andreas with the reason it is expected to be useful and the person',
      '   who will read it. Sources without a named reader are not added.',
      '2. The reader triages what arrives within two working days. An item is either raised as a',
      '   ticket in the engineering backlog with a severity, forwarded to the affected owner, or',
      '   dismissed with a one-line reason recorded against the item. Silent dismissal is not',
      '   available.',
      '3. Anything rated critical by the source goes straight into the threat intelligence route',
      '   under ISMS-SOP-A-5-7 and, if exploited, the incident procedure — it does not wait for',
      '   the two-day triage window.',
      '4. Attendance at a chapter meetup or practitioner group is written up in three sentences',
      '   in the engineering channel within a week. If it cannot be summarised, the group did',
      '   not learn anything and the membership is questioned at review.',
      '5. Nothing about the group is disclosed to an external forum without Dhiaz Fathra',
      '   approving it — no architecture detail, no incident specifics, no patient data of any',
      '   kind, however abstracted.',
      '6. Annually, Andreas scores each source on actionable items produced. A source with zero',
      '   in twelve months is dropped unless the cost is nil and the coverage is deliberate.',
      '',
      '## Records',
      '',
      'Membership and feed register (FRM-A-5-6-01) with the annual score, retained three years.',
      'Triage decisions live on the ticket or the register row that dismissed them.',
      '',
      '## Review',
      '',
      'Annually by Andreas with Dhiaz Fathra, alongside the threat intelligence review so the',
      'two sets of sources are judged together.',
    ].join('\n'),
  },
]
