import type { SeedDocument } from './types'

/** Engineering practice documents: SDLC, architecture decisions, measurement, management review. */
export const ENGINEERING_DOCUMENTS: SeedDocument[] = [
  {
    code: 'ENG-SOP-001',
    title: 'Engineering Standard Operating Procedure',
    clause: 'A.8.25',
    crossRefs: ['A.8.28', 'A.8.27', 'A.5.37', '7.5.3'],
    version: 'v3.0',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-SDLC-01', name: 'Merge request review record' },
    revisions: [
      {
        version: 'v2.0',
        date: '2025-10-06',
        author: 'Dhiaz Fathra',
        approval: 'Drafted',
        status: 'Superseded',
        note: 'Consolidated the branch, review and release rules that were spread across three wiki pages.',
      },
      {
        version: 'v2.4',
        date: '2026-02-11',
        author: 'Andreas',
        approval: 'Reviewed by Engineering',
        status: 'Superseded',
        note: 'BRS/TRD standard added; TRD made a precondition for any change touching patient data.',
      },
      {
        version: 'v3.0',
        date: '2026-06-02',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Agentic SDLC section added — human accountability for agent-authored changes made explicit.',
      },
    ],
    evidence: [
      {
        name: 'eng-sop-001-v3.0.md',
        fileType: 'MD',
        uploadedAt: '2026-06-02',
        expiryDate: '2027-06-02',
        uploader: 'Dhiaz Fathra',
        note: 'Current procedure as published in the engineering handbook repository.',
      },
      {
        name: 'rca-2026-03-super-app-login-outage.md',
        fileType: 'MD',
        uploadedAt: '2026-03-18',
        expiryDate: '2029-03-18',
        uploader: 'Randy',
        note: 'Blameless postmortem for the 51-minute Super App login outage, with actions tracked to closure.',
        body: [
          '# RCA-2026-03 — Super App login outage',
          '',
          '**Severity** P1 · **Duration** 51 minutes (14:12–15:03 WIB, 12 March 2026)',
          '**Author** Randy · **Reviewed** Dhiaz Fathra, Andreas · **Status** actions closed',
          '',
          '## Impact',
          '',
          'Roughly 4,100 patients could not sign in to the Super App. Clinic front desks were',
          'unaffected — they use the ERP directly. No data was lost or exposed.',
          '',
          '## What happened',
          '',
          'A Zitadel upgrade rotated the signing key. The Super App gateway cached the JWKS',
          'document for 24 hours with no revalidation, so every token minted after the rotation',
          'failed signature verification at the gateway while Zitadel itself was healthy.',
          '',
          '## Timeline (WIB)',
          '',
          '| Time | Event |',
          '| --- | --- |',
          '| 14:08 | Zitadel upgrade applied, signing key rotated |',
          '| 14:12 | Login failure rate crosses the alert threshold |',
          '| 14:19 | On-call acknowledges; Zitadel dashboards all green, attention goes to the mobile release |',
          '| 14:41 | Gateway logs show `signature verification failed`, not `invalid credentials` |',
          '| 14:52 | JWKS cache identified as stale |',
          '| 15:03 | Gateway restarted, cache refreshed, logins recover |',
          '',
          '## Why it happened — five whys',
          '',
          '1. Logins failed → the gateway rejected valid tokens.',
          '2. It rejected them → it verified against a key that no longer existed.',
          '3. It used the old key → the JWKS cache had a 24-hour TTL and no `kid` miss revalidation.',
          '4. No revalidation → the cache was written for latency, before key rotation was routine.',
          '5. It was never revisited → key rotation was not on the change checklist for identity.',
          '',
          '## Blameless statement',
          '',
          'The upgrade was applied correctly and within the change window. The failure was in a',
          'caching decision made months earlier that nobody had reason to revisit. No individual',
          'action caused this outage, and the actions below are about the system, not the operator.',
          '',
          '## Actions',
          '',
          '| Action | Owner | Due | Status |',
          '| --- | --- | --- | --- |',
          '| Revalidate JWKS on unknown `kid`, cap TTL at 10 minutes | Randy | 2026-03-20 | Done |',
          '| Alert on signature-verification failures separately from credential failures | Agil | 2026-03-27 | Done |',
          '| Add key rotation to the identity change checklist | Dhiaz Fathra | 2026-03-31 | Done |',
          '| Rehearse a Zitadel key rotation in staging each quarter | Randy | 2026-06-30 | Done |',
        ].join('\n'),
      },
    ],
    body: [
      '# ENG-SOP-001 — Engineering Standard Operating Procedure',
      '',
      '**Owner** Dhiaz Fathra (Head of Engineering) · **Approver** Aris Ihwan · **Version** v3.0',
      '**Requirement** A.8.25 · **Also satisfies** A.8.28, A.8.27, A.5.37, ISO 9001 7.5.3',
      '',
      '## 1. Purpose and scope',
      '',
      'How the 13-person engineering team of PT Cakrawala Bumi Estetika takes a change from',
      'request to production: what is written down, who reviews it, what evidence the change',
      'leaves behind. It covers backend (Go, go-kratos, chi, ConnectRPC), mobile (Flutter,',
      'Riverpod, MVVM), frontend, QA and solutions architecture.',
      '',
      '## 2. Documents before code',
      '',
      '- **BRS — business requirement specification** — Written by: Requesting department with solutions architecture · Required when: Any change a department asks for',
      '- **TRD — technical requirement document** — Written by: Solutions architecture (Andreas) · Required when: Any change crossing a service boundary, touching patient data, or altering a published contract',
      '- **ADR — architecture decision record** — Written by: The engineer making the decision · Required when: A decision that is costly to reverse (see the ADR procedure)',
      '',
      'A BRS states the outcome and the acceptance criteria in the department’s language. A TRD',
      'states the contracts, the data touched and its classification, the failure modes and the',
      'rollback. A change touching personal data without a TRD referencing TRD-SEC-002 does not',
      'enter the sprint.',
      '',
      '## 3. Branch, review, merge',
      '',
      '1. One merge request per change, against `main`, with the BRS or issue linked.',
      '2. GitLab CI must be green: build, unit tests, linter, secret scan.',
      '3. The internal Go review agent comments first — style, obvious defects, and the data',
      '   rules of TRD-SEC-002 §3 and §5.',
      '4. A named human reviewer approves. The agent’s approval is not an approval.',
      '5. Squash merge, with the issue reference in the message.',
      '',
      'The reviewer is accountable for what merges. "The agent approved it" is not a defence in',
      'a postmortem, and neither is "the agent wrote it".',
      '',
      '## 4. Agentic SDLC',
      '',
      'Agents (Claude Code, OpenCode, the internal review agent) are used routinely. The rules:',
      '',
      '1. **A human owns every merge request**, whoever or whatever typed the diff.',
      '2. **Repository conventions live in `CLAUDE.md` / `AGENTS.md`**, in the repository, reviewed',
      '   with it. An agent that needs a rule gets it there, not in a private prompt.',
      '3. **No production data in prompts** (CBE/ISMS/SOP/19 §4).',
      '4. **Agent-authored changes are tested like any other.** No exemption for volume.',
      '5. **Scope discipline.** An agent asked for a fix that returns an abstraction layer is',
      '   sent back. The same standard applies to humans; it is stated here because agents',
      '   produce plausible over-engineering faster than anyone can review it.',
      '',
      '## 5. Incidents and blameless RCA',
      '',
      '- Severity is declared by the on-call engineer, not negotiated. P1 is patient-facing',
      '  unavailability, suspected data exposure, or anything that starts a regulatory clock.',
      '- Restore service first, diagnose second, but preserve logs before restarting anything.',
      '- Every P1 and every P2 lasting over an hour gets a written RCA within five working days.',
      '- The RCA is blameless: it names systems, decisions and gaps, never a culprit. An RCA that',
      '  concludes "human error" is not finished — ask what allowed the error to reach production.',
      '- Actions have a single named owner and a date, and are tracked in the sprint like any',
      '  other work. An RCA with no closed actions is an open finding at the management review.',
      '',
      '## 6. Release and rollback',
      '',
      'Services deploy as Podman containers managed by Quadlet units, fronted by Caddy.',
      'Infrastructure is described in OpenTofu; a change applied by hand and not committed is a',
      'finding. Every deployment is one commit, tagged, and reversible by redeploying the',
      'previous tag. Database migrations are forward-only and additive; a migration that cannot',
      'be rolled forward past is split.',
      '',
      '## 7. Measurement',
      '',
      'Delivery is measured with the SPACE/DORA framework document, reported quarterly to the',
      'management review. Metrics describe the system; they are not used to rank individuals.',
      '',
      '## 8. Related documents',
      '',
      '- TRD-SEC-002 — Personal Data Handling',
      '- CBE/ISMS/SOP/19 — Data Security and Leakage Prevention',
      '- ADR procedure and template',
      '- SPACE/DORA engineering measurement framework',
    ].join('\n'),
  },

  {
    code: 'ENG-SOP-002',
    title: 'Architecture Decision Record — Procedure and Template',
    clause: 'A.8.27',
    crossRefs: ['A.8.25', 'A.5.37', '7.5.3'],
    version: 'v1.2',
    owner: 'Andreas',
    form: { code: 'FRM-ADR-01', name: 'Architecture decision record' },
    revisions: [
      {
        version: 'v1.0',
        date: '2025-12-15',
        author: 'Andreas',
        approval: 'Drafted',
        status: 'Superseded',
        note: 'Adopted during the Eternesia decomposition, after two services were rewritten for reasons nobody could reconstruct.',
      },
      {
        version: 'v1.2',
        date: '2026-05-19',
        author: 'Andreas',
        approval: 'Approved by Dhiaz Fathra',
        status: 'Current',
        note: 'Alternatives-considered section made mandatory; "what we deliberately did not build" added.',
      },
    ],
    evidence: [
      {
        name: 'adr-0042-nats-over-kafka-eternesia.md',
        fileType: 'MD',
        uploadedAt: '2026-05-19',
        expiryDate: '2029-05-19',
        uploader: 'Andreas',
        note: 'Worked example of the template as accepted.',
        body: [
          '# ADR-0042: Watermill over NATS JetStream, not Kafka',
          '',
          '## Status',
          '',
          'Accepted',
          '',
          '## Date',
          '',
          '2026-05-19',
          '',
          '## Context',
          '',
          'The Eternesia services need durable events between 21 Go services — appointment',
          'created, treatment completed, erasure requested. Peak is roughly 40 events per second',
          'across 13 clinic locations, with retention measured in days, not months. The platform',
          'runs on Nutanix, operated by a team of 13 with no dedicated platform engineer.',
          '',
          '## Decision',
          '',
          'Watermill over NATS JetStream, one stream per bounded context, deployed as three',
          'Quadlet-managed containers.',
          '',
          '## Alternatives considered',
          '',
          '### Kafka (Strimzi or self-managed)',
          '',
          '- Pros: the default answer; ecosystem, tooling, ordered partitions at any volume.',
          '- Cons: ZooKeeper-free Kafka still means brokers, rebalancing and retention tuning that',
          '  someone must own at 3am. Our peak is two orders of magnitude below where Kafka starts',
          '  paying for itself.',
          '- Rejected: operational cost disproportionate to the volume.',
          '',
          '### PostgreSQL outbox polled directly, no broker',
          '',
          '- Pros: no new infrastructure; the database is already there.',
          '- Cons: fan-out to many consumers becomes bespoke code per consumer, and the erasure',
          '  orchestration in TRD-SEC-002 §6 needs per-consumer acknowledgement we would hand-roll.',
          '- Rejected, but narrowly. It remains the right answer for a single consumer.',
          '',
          '## Consequences',
          '',
          '- One dependency to operate, with a Go client the team already uses in Watermill.',
          '- JetStream retention is set per stream; `pii.*` streams retain 7 days, which is inside',
          '  the deletion policy’s deferred-deletion window.',
          '- If sustained throughput exceeds roughly 5,000 events per second, revisit. It will not',
          '  in this business.',
          '',
          '## What we deliberately did not build',
          '',
          'No schema registry, no per-service consumer framework, no replay tooling beyond',
          'JetStream’s own. Each would be a system to maintain for a problem we do not have yet.',
        ].join('\n'),
      },
    ],
    body: [
      '# Architecture Decision Record — Procedure and Template',
      '',
      '**Owner** Andreas (Solutions Architecture) · **Approver** Dhiaz Fathra · **Version** v1.2',
      '**Requirement** A.8.27 · **Also satisfies** A.8.25, A.5.37, ISO 9001 7.5.3',
      '',
      '## 1. Why',
      '',
      'A design decision is cheap to make and expensive to reconstruct. Two Eternesia services',
      'were rewritten in 2025 because the reason for the original design had left with the person',
      'who made it. An ADR is the record that stops that happening again, and it is what an',
      'auditor reads when asking how secure architecture principles were applied.',
      '',
      '## 2. When an ADR is required',
      '',
      'Write one when the decision is costly to reverse:',
      '',
      '- A new runtime dependency — a broker, a database, an identity provider.',
      '- A service boundary: what owns which data (see the MDM policy).',
      '- A published contract other teams depend on.',
      '- A security control choice, or a deliberate acceptance of a risk.',
      '- Anything the team argued about for more than a day.',
      '',
      'Do not write one for a library upgrade, a refactor with no external effect, or a decision',
      'the code already states plainly.',
      '',
      '## 3. Where they live',
      '',
      '`docs/decisions/NNNN-kebab-title.md` in the repository the decision affects, numbered',
      'sequentially, never renumbered. A superseded ADR is not deleted: its status becomes',
      '`Superseded by ADR-NNNN` and the text stays. The history is the point.',
      '',
      '## 4. Template',
      '',
      '```',
      '# ADR-NNNN: <decision in one line>',
      '',
      '## Status',
      'Proposed | Accepted | Superseded by ADR-NNNN',
      '',
      '## Date',
      'YYYY-MM-DD',
      '',
      '## Context',
      'The forces at play: volume, team size, constraints, deadlines. Facts, not preferences.',
      '',
      '## Decision',
      'What we are doing, stated so a reader can act on it.',
      '',
      '## Alternatives considered',
      'Each with pros, cons and why it was rejected. An ADR with no rejected alternative is a',
      'note, not a decision.',
      '',
      '## Consequences',
      'What becomes easier, what becomes harder, and the threshold at which we revisit.',
      '',
      '## What we deliberately did not build',
      'The scope we cut and the signal that would justify adding it.',
      '```',
      '',
      '## 5. Review',
      '',
      'ADRs are reviewed in the merge request that carries them, by one engineer other than the',
      'author. The Head of Engineering reviews any ADR that accepts a security risk.',
      '',
      'The last section is not decoration. The team’s recurring failure mode is building for a',
      'scale that has not arrived; naming the cut scope and its trigger makes that reviewable.',
    ].join('\n'),
  },
]
