import type { SeedDocument } from './types'

/** Data governance and master data management. */
export const GOVERNANCE_DOCUMENTS: SeedDocument[] = [
  {
    code: 'DG-POL-001',
    title: 'Data Governance and Master Data Management Policy',
    clause: 'A.5.12',
    crossRefs: ['A.5.9', 'A.5.13', 'A.8.27'],
    version: 'v1.0',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-MDM-01', name: 'Data domain ownership register' },
    revisions: [
      {
        version: 'v0.9',
        date: '2026-02-24',
        author: 'Andreas',
        approval: 'Drafted',
        status: 'Superseded',
        note: 'Written during the Eternesia service decomposition to settle who owns patient identity.',
      },
      {
        version: 'v1.0',
        date: '2026-04-28',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Single-writer rule and read-model rule adopted; classification tied to CBE/ISMS/SOP/19.',
      },
    ],
    evidence: [
      {
        name: 'data-domain-ownership-register-2026.md',
        fileType: 'MD',
        uploadedAt: '2026-04-28',
        expiryDate: '2027-04-28',
        uploader: 'Andreas',
        note: 'Current owner, writer service and classification for each master data domain.',
        body: [
          '# Data domain ownership register — 2026',
          '',
          '| Domain | Owning service | Steward | Classification | Consumers |',
          '| --- | --- | --- | --- | --- |',
          '| Patient identity | `patient` | Rica | Specific personal data | Super App, treatment, billing, loyalty |',
          '| Treatment catalogue | `catalogue` | Wiwin | Confidential (commercial) | Super App, marketplace, billing |',
          '| Clinic and location | `org` | Tika | Internal | every service |',
          '| Staff and practitioner | `staff` | Randy | General personal data | scheduling, treatment |',
          '| Pricing and promotion | `pricing` | Wiwin | Confidential (commercial) | Super App, marketplace |',
          '| Order and payment | `billing` | Agil | Confidential + general personal data | finance reporting |',
          '',
          'Every consumer above reads a projection, not the owner’s tables. Two projections were',
          'found writing back during the April review and were corrected before sign-off.',
        ].join('\n'),
      },
    ],
    body: [
      '# Data Governance and Master Data Management Policy',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v1.0',
      '**Requirement** A.5.12 · **Also satisfies** A.5.9, A.5.13, A.8.27',
      '',
      '## 1. Purpose',
      '',
      'The Eternesia platform is 21 Go services across three brands. Without a stated owner for',
      'each kind of data, the same patient exists three times with three spellings and no one is',
      'accountable for either version. This policy names an owner per domain and states how',
      'other services may use that data.',
      '',
      '## 2. Rules',
      '',
      '1. **One writer.** Each master data domain has exactly one owning service. Only that',
      '   service accepts writes. A service that needs a change asks the owner over ConnectRPC;',
      '   it does not write the owner’s tables.',
      '2. **Read models are copies, not sources.** Consumers subscribe to the owner’s events over',
      '   Watermill/NATS and keep their own projection. A projection is disposable and must be',
      '   rebuildable from the event stream.',
      '3. **One identifier.** Cross-service references use the owner’s identifier. No service',
      '   invents a second key for the same entity.',
      '4. **Classification travels with the domain.** The class in the ownership register decides',
      '   the handling under CBE/ISMS/SOP/19; a projection inherits the class of its source.',
      '5. **Every domain has a named steward** — a person, not a team — who approves schema',
      '   changes and answers for data quality.',
      '',
      '## 3. Changing a schema',
      '',
      'A change to an owned domain is proposed in the owning repository, reviewed by the steward,',
      'and recorded as an ADR where it changes a contract other services depend on. Contract',
      'changes are additive first; a field is deprecated for one release before it is removed.',
      '',
      '## 4. Data quality',
      '',
      'Each steward reports two numbers to the quarterly management review: duplicate rate within',
      'the domain, and projection lag at the 95th percentile. Both are read from the SPACE/DORA',
      'measurement workbook rather than gathered by hand.',
      '',
      '## 5. Deliberate limits',
      '',
      'The group does not run a central MDM product, a data catalogue tool or a golden-record',
      'matching engine. At 13 locations and six domains, a register kept in this repository and',
      'reviewed quarterly is proportionate. Revisit only if the domain count or the duplicate',
      'rate makes the register the bottleneck.',
      '',
      '## 6. Review',
      '',
      'Quarterly, at the management review, and whenever a new service takes ownership of a',
      'domain.',
    ].join('\n'),
  },
]
