import type { SeedDocument } from './types'

/** ISO/IEC 27001:2022 management-system clauses 8, 9 and 10 — operation, evaluation, improvement. */
export const ISMS_CLAUSES_8_10: SeedDocument[] = [
  {
    code: 'ISMS-POL-C8-1',
    title: 'ISMS Operational Planning and Control Procedure',
    clause: '27001 8.1',
    crossRefs: ['27001 8.2', '27001 8.3', 'A.5.8', 'A.8.32', '9001 8.1'],
    version: 'v2.1',
    owner: 'Dhiaz Fathra',
    form: {
      code: 'FRM-ISMS-C8-1-01',
      name: 'ISMS operational control register and change gate record',
    },
    revisions: [
      {
        version: 'v1.0',
        date: '2024-11-18',
        author: 'Andreas',
        approval: 'Approved by Dhiaz Fathra',
        status: 'Superseded',
        note: 'First issue at ISMS establishment; controls listed but no gate on unplanned change.',
      },
      {
        version: 'v2.0',
        date: '2025-09-22',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Superseded',
        note: 'Outsourced processes (Zitadel, AWS, the Jakarta radiology courier) brought inside the control register after an audit finding.',
      },
      {
        version: 'v2.1',
        date: '2026-04-13',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Unplanned-change review added with a 5 working-day consequence assessment and a named reviewer.',
      },
    ],
    evidence: [
      {
        name: 'isms-c8-1-operational-control-register-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-04-13',
        expiryDate: '2027-04-13',
        uploader: 'Dhiaz Fathra',
        note: 'The controlled register of ISMS operational processes, their criteria and the evidence each one produces.',
        body: [
          'ISMS operational control register — 2026 (PT Cakrawala Bumi Estetika)',
          '',
          'Process | Criterion | Control evidence produced | Frequency | Owner',
          'Production change deployment | Peer review + passing pipeline before merge | Deployment log, MR approval | Per change | Agil',
          'Access provisioning | Zitadel role granted only from an approved request | Access request ticket | Per request | Agil',
          'Access recertification | Every production role reviewed by its owner | Recertification sheet | Quarterly | Agil',
          'Backup and restore rehearsal | One service restored end to end from S3 | Restore rehearsal note | Monthly | Andreas',
          'Vulnerability remediation | Critical closed <= 7 days, high <= 30 days | Scanner export + ticket | Weekly scan | Agil',
          'Supplier security review | Current attestation on file before renewal | Supplier review sheet | Annual per supplier | Pak Chen',
          'Clinic device hardening check | Disk encryption + MDM enrolment verified | Device check sheet | Quarterly, 13 sites | Pak Andre',
          'Patient data erasure run | Every service acknowledges the delete event | NATS acknowledgement report | Monthly | Andreas',
          '',
          'Unplanned changes recorded in 2026 to date: 4.',
          'CHG-2026-0117 Zitadel emergency version bump (vendor CVE) — consequences reviewed 2026-02-04, no ISMS impact.',
          'CHG-2026-0203 Surabaya Pakuwon link failover to LTE — reviewed 2026-03-11, raised risk R-041 to high for 9 days.',
          'CHG-2026-0288 marketplace cutover rolled back — reviewed 2026-05-30, corrective action CAR-2026-052 raised.',
          'CHG-2026-0341 courier substitution for radiology media — reviewed 2026-07-21, supplier review brought forward.',
        ].join('\n'),
      },
      {
        name: 'isms-c8-1-outsourced-process-control-2026.md',
        fileType: 'MD',
        uploadedAt: '2026-04-20',
        expiryDate: '2027-04-20',
        uploader: 'Pak Chen',
        note: 'How each outsourced process that touches the ISMS scope is determined and controlled.',
        body: [
          '# Outsourced processes under ISMS control — 2026',
          '',
          '| Process | Provider | Control applied | Verification | Last checked |',
          '| --- | --- | --- | --- | --- |',
          '| Identity and access management | Zitadel Cloud (Singapore) | Contractual security schedule, SSO enforced, admin actions exported to our log store | SOC 2 Type II report read by Agil | 2026-03-02 |',
          '| Compute, storage, network | AWS ap-southeast-1 | Shared responsibility split written into ENG-SOP-004; our side audited internally | Config rules + quarterly account review | 2026-06-30 |',
          '| Payroll processing | PT Mitra Sumber Daya | Written processing instruction under Art. 51 PDP Law, data minimised to what payroll needs | Annual supplier review sheet | 2026-01-27 |',
          '| Radiology media courier | Kurir Medika Nusantara | Sealed transport, chain-of-custody sheet signed both ends | Sample audit of 20 movements | 2026-07-21 |',
          '| Clinical waste disposal | PT Wastindo | Manifest returned per collection | Manifest reconciliation, monthly | 2026-08-05 |',
          '',
          'Outsourcing does not move accountability. Where a provider will not evidence a control,',
          'the group applies a compensating control on its own side or does not use the provider.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-C8-1 · ISMS Operational Planning and Control Procedure',
      '',
      '**Owner** Dhiaz Fathra (Management Representative) · **Approver** Aris Ihwan · **Version** v2.1',
      '**Requirement** ISO/IEC 27001:2022 8.1 · **Also satisfies** 27001 8.2, 27001 8.3, A.5.8, A.8.32, ISO 9001 8.1',
      '',
      '## Purpose',
      '',
      'An ISMS that exists only as policy text protects nothing. This procedure states how the',
      'processes needed to meet Dermaster information security requirements are actually planned,',
      'run and controlled day to day across 13 clinic locations and the in-house engineering team,',
      'and how the organisation keeps documented information sufficient to have confidence that',
      'those processes ran as planned.',
      '',
      '## Scope',
      '',
      'Every process whose failure would breach the ISMS objectives set in the Information',
      'Security Policy: production change, access provisioning and recertification, backup and',
      'restore, vulnerability remediation, supplier security review, clinic device hardening and',
      'patient data erasure. It covers the Eternesia ERP, the Super App, the marketplace services',
      'and the clinic estate. It excludes clinical treatment protocols, which are governed by the',
      'medical director, and excludes purely financial controls owned by Pak Rila.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Dhiaz Fathra** owns this procedure and the operational control register `FRM-ISMS-C8-1-01`.',
      '- **Agil** runs change, access and vulnerability control and answers for their evidence.',
      '- **Andreas** runs backup rehearsal and the erasure orchestration.',
      '- **Pak Andre** answers for clinic-side device and physical controls at all 13 sites.',
      '- **Pak Chen** answers for outsourced processes and supplier security review.',
      '- **Aris Ihwan** approves this procedure and receives exceptions that cannot be closed.',
      '',
      '## Procedure',
      '',
      '1. **Plan.** Each process in the register carries a criterion that can be judged true or',
      '   false, a named owner, a frequency and the record it produces. A process with no record',
      '   is not admitted — an unrecorded control cannot be audited.',
      '2. **Implement.** Controls are implemented where the work happens: in the CI pipeline, in',
      '   Zitadel role definitions, in the MDM policy, in the NATS erasure consumer. Manual checks',
      '   are used only where automation is genuinely unavailable, and are then dated and signed.',
      '3. **Control planned change.** Any change to a process in the register is raised through',
      '   ENG-SOP-002, assessed for information security consequence, and approved before it runs.',
      '4. **Control unplanned change.** Where a change happened without approval — an emergency',
      '   patch, a failover, a supplier substitution — Dhiaz Fathra reviews the consequences within',
      '   five working days, records them against the change identifier and takes action to mitigate',
      '   any adverse effect. Four such changes were recorded in the first eight months of 2026.',
      '5. **Control outsourced processes.** Processes performed by an external provider stay in',
      '   scope. Each is listed with the control applied and the verification the group performs,',
      '   and the verification is done by a Dermaster employee, never by the provider alone.',
      '6. **Retain evidence.** Records named in the register are held in the compliance repository',
      '   for three years, or for the contract term plus one year where a supplier is involved.',
      '',
      '## Records',
      '',
      'Operational control register, change gate records, outsourced process control sheet, and the',
      'per-process evidence each control produces.',
      '',
      '## Review',
      '',
      'Annually, and whenever a process enters or leaves the ISMS scope. The register itself is',
      'reviewed at each management review against what the internal audit actually found.',
    ].join('\n'),
  },

  {
    code: 'ISMS-POL-C8-2',
    title: 'Information Security Risk Assessment — Operational Procedure and 2026 Assessment',
    clause: '27001 8.2',
    crossRefs: ['27001 6.1.2', '27001 8.3', '27001 9.3.2', 'A.5.7', 'A.8.8'],
    version: 'v3.0',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-ISMS-C8-2-01', name: 'Information security risk assessment worksheet' },
    revisions: [
      {
        version: 'v2.0',
        date: '2024-10-07',
        author: 'Andreas',
        approval: 'Approved by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Asset-threat-vulnerability method replaced by a scenario method after the first assessment produced 400 unusable rows.',
      },
      {
        version: 'v2.4',
        date: '2025-10-06',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Superseded',
        note: 'Risk owners named individually; "Engineering" was not an acceptable owner.',
      },
      {
        version: 'v3.0',
        date: '2026-05-11',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Trigger-based reassessment added; the annual cycle alone missed the marketplace migration risk by four months.',
      },
    ],
    evidence: [
      {
        name: 'isms-c8-2-risk-assessment-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-05-11',
        expiryDate: '2027-05-11',
        uploader: 'Dhiaz Fathra',
        note: 'The executed 2026 assessment: scored scenarios with named risk owners, as accepted by top management.',
        body: [
          'Information security risk assessment — executed 2026-05-11',
          '',
          'ID | Scenario | Likelihood | Impact | Score | Level | Risk owner',
          'R-012 | Clinic staff account reused after resignation, patient records read | 3 | 4 | 12 | High | Agil',
          'R-017 | Before/after photographs exfiltrated from a clinic tablet | 2 | 5 | 10 | High | Pak Andre',
          'R-023 | S3 bucket for treatment media made public by a misconfigured Terraform change | 2 | 5 | 10 | High | Andreas',
          'R-029 | Ransomware on the Kelapa Gading clinic file server | 2 | 4 | 8 | Medium | Agil',
          'R-034 | Zitadel outage blocks all clinic logins for a business day | 3 | 3 | 9 | Medium | Agil',
          'R-041 | Surabaya Pakuwon link failure forces unencrypted fallback path | 3 | 3 | 9 | Medium | Pak Andre',
          'R-046 | Payroll processor mishandles staff NIK data | 2 | 4 | 8 | Medium | Rica',
          'R-052 | Marketplace migration exposes order data linked to patient identity | 3 | 4 | 12 | High | Dhiaz Fathra',
          'R-058 | Developer laptop stolen with a production database restore on disk | 2 | 4 | 8 | Medium | Andreas',
          'R-063 | Vendor engineer retains standing admin access after project close | 3 | 3 | 9 | Medium | Pak Chen',
          'R-070 | Patient erasure request not honoured by one of 21 services | 3 | 4 | 12 | High | Andreas',
          'R-075 | Phishing of a finance mailbox leads to fraudulent supplier payment | 3 | 3 | 9 | Medium | Pak Rila',
          '',
          'Scale: likelihood 1-5, impact 1-5, score = product. Level: >= 10 High, 5-9 Medium, <= 4 Low.',
          'Scenarios assessed 34; shown here are the 12 scoring Medium or above.',
          'Compared with 2025: 3 new (R-052, R-063, R-070), 5 reduced, 2 retired.',
          'Acceptance criterion: High risks may not be accepted; they must be treated or escalated to Aris Ihwan in writing.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-C8-2 · Information Security Risk Assessment — Operational Procedure',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v3.0 · **Review** annually',
      '**Requirement** ISO/IEC 27001:2022 8.2 · **Also satisfies** 27001 6.1.2, 27001 8.3, 27001 9.3.2, A.5.7, A.8.8',
      '',
      '## Purpose',
      '',
      'Clause 6.1.2 defines the method. This procedure is about performing it: when an assessment',
      'is actually run at Dermaster, who sits in the room, how the result is recorded and what',
      'happens to it afterwards. The 2026 assessment executed under this procedure is filed as the',
      'evidence attached to this document.',
      '',
      '## Scope',
      '',
      'All information assets and processing inside the ISMS scope statement: the Eternesia ERP',
      '(21 Go services on AWS ap-southeast-1), the Super App, the marketplace services, the clinic',
      'estate at 13 locations, and the corporate functions that handle staff and patient data.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Dhiaz Fathra** convenes and facilitates each assessment and holds the risk register.',
      '- **Named risk owners** — one person per risk, never a team — accept the score or argue it',
      '  down with evidence at the workshop, not afterwards by e-mail.',
      '- **Agil, Andreas, Rica, Pak Andre, Pak Chen, Pak Rila** contribute the operational reality',
      '  of their areas; a scenario nobody in the room recognises is not scored, it is investigated.',
      '- **Aris Ihwan** receives the completed assessment and is the only person who may accept a',
      '  High-level risk, in writing, with an end date.',
      '',
      '## Procedure',
      '',
      '1. **Trigger.** An assessment is performed at least annually in the second quarter, and',
      '   additionally on any of these triggers: a new service handling patient data enters',
      '   production, a new clinic location opens, a supplier with access to personal data is',
      '   engaged, a significant incident is closed, or the scope statement changes. The trigger',
      '   rule exists because the 2025 annual cycle missed the marketplace migration by four months.',
      '2. **Prepare.** Dhiaz Fathra circulates the previous register, the incident log since the',
      '   last assessment, the open audit findings and the change log, five working days ahead.',
      '3. **Workshop.** Scenarios are stated as a sentence with an actor, an action and a',
      '   consequence — never as a bare asset name. Each is scored for likelihood and impact on the',
      '   1-5 scale against the criteria in ISMS-POL-C6-1, and the score is agreed in the room.',
      '4. **Assign.** Every scenario leaves the workshop with one named risk owner who has the',
      '   authority to act on it. A risk owned by a function is treated as unowned.',
      '5. **Record.** Results are written to `FRM-ISMS-C8-2-01` with the date performed, the',
      '   participants, the score, the level and the comparison against the previous assessment.',
      '6. **Hand over.** The completed assessment is the input to risk treatment under',
      '   ISMS-POL-C8-3 and a documented input to management review under 27001 9.3.2.',
      '',
      '## Records',
      '',
      'Completed assessment worksheets are retained for five years so that a trend across cycles',
      'can be shown to a certification auditor; workshop attendance is recorded on the worksheet.',
      '',
      '## Review',
      '',
      'Annually, and whenever the scoring criteria change — a criteria change breaks comparability',
      'and the break is noted on the first worksheet that follows it.',
    ].join('\n'),
  },

  {
    code: 'ISMS-POL-C8-3',
    title: 'Information Security Risk Treatment — Operational Procedure and 2026 Treatment Plan',
    clause: '27001 8.3',
    crossRefs: ['27001 6.1.3', '27001 8.2', '27001 9.3.2', 'A.5.1', 'A.5.8'],
    version: 'v2.3',
    owner: 'Dhiaz Fathra',
    form: {
      code: 'FRM-ISMS-C8-3-01',
      name: 'Risk treatment plan and residual risk acceptance sheet',
    },
    revisions: [
      {
        version: 'v2.0',
        date: '2024-12-09',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Superseded',
        note: 'Treatment plan separated from the risk register; the combined sheet was never updated after actions closed.',
      },
      {
        version: 'v2.3',
        date: '2026-05-25',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Residual risk acceptance now requires the risk owner and Aris Ihwan to sign the same line, with a review date.',
      },
    ],
    evidence: [
      {
        name: 'isms-c8-3-risk-treatment-plan-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-05-25',
        expiryDate: '2027-05-25',
        uploader: 'Dhiaz Fathra',
        note: 'The executed treatment plan for the 2026 assessment, with residual scores and acceptance signatures.',
        body: [
          'Risk treatment plan — 2026 cycle (implemented under ISMS-POL-C8-3)',
          '',
          'Risk | Option | Annex A controls | Action | Owner | Due | Status | Residual',
          'R-012 | Modify | A.5.18, A.5.11 | Zitadel deprovision triggered by the HR leaver event, not by ticket | Agil | 2026-07-31 | Closed 2026-07-18 | 4 Low',
          'R-017 | Modify | A.8.1, A.7.9 | Clinic tablets locked to the Super App kiosk profile, no local gallery write | Pak Andre | 2026-08-29 | Closed 2026-08-22 | 5 Medium',
          'R-023 | Modify | A.8.9, A.8.32 | Terraform plan gate blocks public ACLs on media buckets | Andreas | 2026-06-30 | Closed 2026-06-24 | 5 Medium',
          'R-029 | Modify | A.8.13, A.8.7 | Clinic file servers retired; shares moved to the ERP document service | Agil | 2026-10-31 | In progress, 9 of 13 sites | 8 Medium',
          'R-034 | Share | A.5.30, A.5.29 | Offline booking fallback rehearsed; Zitadel SLA credit clause signed | Agil | 2026-09-30 | In progress | 6 Medium',
          'R-041 | Modify | A.8.20, A.8.21 | Second carrier at Surabaya Pakuwon, IPSec enforced on both paths | Pak Andre | 2026-11-28 | In progress | 6 Medium',
          'R-046 | Share | A.5.19, A.5.20 | Processing instruction and audit right added at contract renewal | Rica | 2026-04-30 | Closed 2026-04-16 | 4 Low',
          'R-052 | Modify | A.8.31, A.8.33 | Order data pseudonymised before it leaves the patient service | Dhiaz Fathra | 2026-09-30 | In progress | 6 Medium',
          'R-063 | Modify | A.5.19, A.8.2 | Vendor accounts time-boxed to the statement of work end date | Pak Chen | 2026-07-31 | Closed 2026-07-09 | 4 Low',
          'R-070 | Modify | A.5.34, A.8.10 | Erasure acknowledgement report; a missing service fails the run | Andreas | 2026-08-31 | Closed 2026-08-27 | 5 Medium',
          'R-075 | Modify | A.6.3, A.5.14 | Payment change requires callback verification on a known number | Pak Rila | 2026-06-30 | Closed 2026-06-11 | 5 Medium',
          '',
          'Risks accepted without further treatment: R-081 (loss of the Bali Seminyak signage CMS,',
          'score 4) accepted by Wiwin and Aris Ihwan on 2026-05-25, review 2027-05-25.',
          'No High residual risk is carried. Controls determined necessary are reconciled against',
          'Annex A in the Statement of Applicability revision 2026-05-25; two exclusions remain',
          'justified (A.7.4 dedicated surveillance staff, A.8.34 audit tooling isolation).',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-C8-3 · Information Security Risk Treatment — Operational Procedure',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v2.3 · **Review** annually',
      '**Requirement** ISO/IEC 27001:2022 8.3 · **Also satisfies** 27001 6.1.3, 27001 8.2, 27001 9.3.2, A.5.1, A.5.8',
      '',
      '## Purpose',
      '',
      'To implement the risk treatment plan and to retain evidence that it was implemented, rather',
      'than only that it was written. This procedure covers the step between an assessed risk and a',
      'working control at Dermaster, and the point at which a residual risk is formally accepted by',
      'someone with the authority to accept it.',
      '',
      '## Scope',
      '',
      'Every risk scored Medium or above in the current assessment, across the ERP, the Super App,',
      'the marketplace services and the 13 clinic locations. Low risks are recorded and monitored',
      'but do not require a treatment action.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Dhiaz Fathra** maintains the treatment plan and reports progress monthly.',
      '- **Risk owners** implement the actions against their risks and produce the evidence.',
      '- **Agil** confirms that a technical control is actually enforced, not merely configured.',
      '- **Aris Ihwan** and the risk owner jointly sign residual risk acceptance.',
      '',
      '## Procedure',
      '',
      '1. **Choose an option.** For each risk: modify, share, avoid or retain. The choice and the',
      '   reason are recorded; "retain" is only available where the residual score is Low.',
      '2. **Determine controls.** The controls necessary to implement the option are determined',
      '   first from the operational reality, then compared against Annex A to check that nothing',
      '   necessary was omitted. The comparison result is written into the Statement of',
      '   Applicability, with a justification for every exclusion.',
      '3. **Plan.** Each action carries an owner, a due date and a definition of done that names',
      '   the evidence. "Improve awareness" is not a definition of done; "all 13 site leads have',
      '   completed module 4 and the completion export is filed" is.',
      '4. **Implement and verify.** The owner implements; Agil or Andreas verifies independently.',
      '   Verification means observing the control working — a blocked deploy, a denied login, a',
      '   failed erasure run — not reading the configuration that should cause it.',
      '5. **Score the residual.** After verification the risk is rescored. If the residual is still',
      '   High, the action failed and a further action is raised; the risk is not simply reaccepted.',
      '6. **Accept.** Residual risk is accepted on `FRM-ISMS-C8-3-01`, signed by the risk owner and',
      '   Aris Ihwan on the same line, with a review date no more than 12 months ahead.',
      '7. **Report.** Plan status is a standing item at the monthly ISMS operations meeting and a',
      '   documented input to management review.',
      '',
      '## Records',
      '',
      'Treatment plan, verification notes, Statement of Applicability revisions and signed',
      'acceptance sheets, retained for five years.',
      '',
      '## Review',
      '',
      'Annually, and after any incident that a treated risk should have prevented — an incident of',
      'that shape is evidence that the treatment, not only the risk, was misjudged.',
    ].join('\n'),
  },

  {
    code: 'ISMS-POL-C9-1',
    title: 'Information Security Monitoring, Measurement, Analysis and Evaluation',
    clause: '27001 9.1',
    crossRefs: ['27001 9.3.2', '27001 10.2', 'A.5.36', 'A.8.15', 'A.8.16'],
    version: 'v2.2',
    owner: 'Agil',
    form: {
      code: 'FRM-ISMS-C9-1-01',
      name: 'Information security metric definition and monthly result sheet',
    },
    revisions: [
      {
        version: 'v2.0',
        date: '2025-02-17',
        author: 'Agil',
        approval: 'Approved by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Metrics reduced from 31 to 11; the long list was reported but never acted on.',
      },
      {
        version: 'v2.2',
        date: '2026-02-16',
        author: 'Agil',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Every metric now names the query or export that produces it, and who is expected to react when it breaches.',
      },
    ],
    evidence: [
      {
        name: 'isms-c9-1-security-metrics-2026-08.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-09-04',
        expiryDate: '2027-09-04',
        uploader: 'Agil',
        note: 'August 2026 monthly security metric sheet as reported to the ISMS operations meeting.',
        body: [
          'Information security metrics — August 2026',
          '',
          'Metric | Source | Target | Jun | Jul | Aug | Reacts',
          'Critical vulnerabilities open beyond 7 days | Scanner export | 0 | 2 | 0 | 0 | Agil',
          'High vulnerabilities open beyond 30 days | Scanner export | <= 3 | 6 | 4 | 3 | Agil',
          'Production accounts without MFA | Zitadel report | 0 | 1 | 0 | 0 | Agil',
          'Leaver accounts disabled within 24h | HR event vs Zitadel log | 100% | 91% | 100% | 100% | Agil',
          'Privileged access reviews completed on time | Recertification sheet | 100% | 100% | 88% | 100% | Agil',
          'Backup restore rehearsals passed | Rehearsal note | 1 per month | 1 | 1 | 1 | Andreas',
          'Mean time to detect a reported incident | Incident log | <= 4 hours | 6.1h | 3.4h | 2.9h | Agil',
          'Mean time to contain a confirmed incident | Incident log | <= 24 hours | 19h | 11h | 14h | Agil',
          'Phishing simulation click rate | Awareness platform | <= 8% | 12.4% | — | 7.6% | Rica',
          'Clinic devices out of MDM compliance | MDM export | <= 5 | 14 | 9 | 4 | Pak Andre',
          'Erasure runs with an unacknowledged service | Erasure report | 0 | 3 | 1 | 0 | Andreas',
          '',
          'Two breaches carried into September: none. Two closed in August: high-vulnerability',
          'backlog reached target, phishing click rate returned below 8% after the June retraining.',
          'Evaluation: ISMS effectiveness judged adequate for August; the July recertification miss',
          'at Bandung Dago was raised as CAR-2026-061 and is closed.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-C9-1 · Information Security Monitoring, Measurement, Analysis and Evaluation',
      '',
      '**Owner** Agil (Infrastructure and Security Operations) · **Approver** Aris Ihwan · **Version** v2.2',
      '**Requirement** ISO/IEC 27001:2022 9.1 · **Also satisfies** 27001 9.3.2, 27001 10.2, A.5.36, A.8.15, A.8.16',
      '',
      '## Purpose',
      '',
      'To determine what Dermaster measures about information security, how it measures it, and how',
      'it decides from those numbers whether the ISMS and its controls are actually effective. The',
      'test applied to every candidate metric is simple: if this number moved, who would do',
      'something differently? A metric with no answer is not collected.',
      '',
      '## Scope',
      '',
      'The ISMS as a whole and the controls in the Statement of Applicability, across the ERP, the',
      'Super App, the marketplace services and the 13 clinic sites. It excludes service performance',
      'monitoring (latency, uptime) except where availability is itself a security objective.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Agil** owns this procedure, produces the monthly sheet and answers for the technical',
      '  metric sources.',
      '- **Andreas** answers for backup, restore and erasure metrics.',
      '- **Pak Andre** answers for the clinic device compliance metric across all 13 locations.',
      '- **Rica** answers for awareness and phishing simulation results.',
      '- **Dhiaz Fathra** performs the evaluation and takes the result to management review.',
      '',
      '## What is measured and how',
      '',
      '1. **Definition.** Each metric on `FRM-ISMS-C9-1-01` names the objective it serves, the',
      '   exact source query or export, the target, the frequency, the producer and the person',
      '   expected to react. Eleven metrics are in force; the 2024 list of 31 was cut because most',
      '   of it was reported and ignored.',
      '2. **Timing.** Technical metrics are produced on the second working day of each month from',
      '   the previous month closed data. Awareness metrics run per campaign. Nobody hand-counts:',
      '   a metric that cannot be produced from a system is retired.',
      '3. **Analysis.** Agil compares each result against target and against the two preceding',
      '   months. A single breach is noted; two consecutive breaches raise a corrective action',
      '   under ISMS-POL-C10-2 with the metric owner as action owner.',
      '4. **Evaluation.** Dhiaz Fathra records a written judgement each month on whether the ISMS',
      '   remains effective, referencing the metrics, open incidents and open audit findings. The',
      '   judgement is a sentence with a reason, not a colour.',
      '5. **Escalation.** Results are presented at the monthly ISMS operations meeting and',
      '   consolidated quarterly as a management review input under 27001 9.3.2.',
      '',
      '## Records',
      '',
      'Metric definition sheet and monthly result sheets, retained three years; the underlying',
      'exports are retained for 12 months in the log store in AWS ap-southeast-1.',
      '',
      '## Review',
      '',
      'Annually, and whenever a metric breaches target for three consecutive months without the',
      'corrective action changing it — that pattern usually means the metric, not the control,',
      'is wrong.',
    ].join('\n'),
  },

  {
    code: 'ISMS-POL-C9-2',
    title: 'ISMS Internal Audit Procedure',
    clause: '27001 9.2',
    crossRefs: ['27001 9.2.1', '27001 9.2.2', '27001 10.2', '9001 9.2', 'A.5.35'],
    version: 'v3.1',
    owner: 'Tika',
    form: { code: 'FRM-ISMS-C9-2-01', name: 'Internal audit plan, checklist and finding sheet' },
    revisions: [
      {
        version: 'v3.0',
        date: '2025-01-20',
        author: 'Tika',
        approval: 'Approved by Aris Ihwan',
        status: 'Superseded',
        note: 'ISMS and QMS audits merged into one combined audit visit per clinic to stop duplicate disruption.',
      },
      {
        version: 'v3.1',
        date: '2026-01-19',
        author: 'Tika',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Auditor independence rule tightened after an engineer audited a control he had built.',
      },
    ],
    evidence: [
      {
        name: 'isms-c9-2-audit-report-2026-h1.docx',
        fileType: 'DOCX',
        uploadedAt: '2026-06-19',
        expiryDate: '2027-06-19',
        uploader: 'Tika',
        note: 'Report of the H1 2026 ISMS internal audit, with findings, evidence and agreed actions.',
        body: [
          '# ISMS internal audit report — H1 2026',
          '',
          '**Audit** IA-2026-02 · **Dates** 8-16 June 2026 · **Lead auditor** Tika · **Auditor** Randy',
          '**Scope** 27001 clauses 6, 8, 9; Annex A.5.15-A.5.18, A.8.2, A.8.13, A.8.15',
          '**Sites** Head office Jakarta, Kelapa Gading, Surabaya Pakuwon, engineering (remote)',
          '',
          '## Findings',
          '',
          '| Ref | Type | Clause | Statement | Owner | Due |',
          '| --- | --- | --- | --- | --- | --- |',
          '| F-2026-11 | Minor NC | A.5.18 | 3 of 20 sampled leavers kept an active Zitadel session for 2-6 days after their last day | Agil | 2026-07-31 |',
          '| F-2026-12 | Minor NC | A.8.13 | Restore rehearsal for the billing service was recorded as done but no evidence of the restored record count was kept | Andreas | 2026-07-15 |',
          '| F-2026-13 | Minor NC | 27001 8.1 | Two emergency changes in Q1 had no documented consequence review | Dhiaz Fathra | 2026-07-31 |',
          '| F-2026-14 | Observation | A.8.2 | Privileged access review is done in a spreadsheet copied per quarter; version confusion is likely | Agil | — |',
          '| F-2026-15 | Observation | A.5.15 | Surabaya reception shares one PMS login during the evening shift although individual accounts exist | Pak Andre | — |',
          '',
          '## Evidence sampled',
          '',
          '20 leaver records against Zitadel logs; 6 restore rehearsal notes; 14 change records;',
          '2 quarterly access review sheets; on-site observation at two clinics; 11 staff interviews.',
          '',
          '## Conclusion',
          '',
          'The ISMS conforms to the organisation own requirements and to ISO/IEC 27001:2022 for the',
          'scope audited, with three minor nonconformities. No major nonconformity was raised. All',
          'three minors were accepted by their owners at the closing meeting on 16 June 2026 and',
          'routed to the corrective action register as CAR-2026-057, CAR-2026-058 and CAR-2026-059.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-C9-2 · ISMS Internal Audit Procedure',
      '',
      '**Owner** Tika (QA Lead) · **Approver** Aris Ihwan · **Version** v3.1 · **Review** annually',
      '**Requirement** ISO/IEC 27001:2022 9.2 · **Also satisfies** 27001 9.2.1, 27001 9.2.2, 27001 10.2, ISO 9001 9.2, A.5.35',
      '',
      '## Purpose',
      '',
      'To provide Dermaster management with independent, evidence-based information on whether the',
      'ISMS conforms to the organisation own requirements and to ISO/IEC 27001:2022, and whether it',
      'is effectively implemented and maintained. The audit exists to find problems while they are',
      'still cheap; an audit that finds nothing is treated as a sampling failure, not a success.',
      '',
      '## Scope',
      '',
      'The whole ISMS: clauses 4 to 10 and every control declared applicable in the Statement of',
      'Applicability, across head office, the 13 clinic locations, the engineering team and the',
      'outsourced processes the group verifies itself.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Tika** is the audit programme manager and usually the lead auditor.',
      '- **Randy** audits engineering-side controls; he does not audit anything he has operated.',
      '- **Auditees** — control owners — provide evidence during the audit, not after it.',
      '- **Aris Ihwan** receives the report and is accountable for the actions arising.',
      '',
      '## Procedure',
      '',
      '1. **Plan the audit.** Each audit in the programme has an objective, a scope, criteria, a',
      '   sample plan and dates agreed with the auditee at least ten working days ahead.',
      '2. **Select auditors.** An auditor may not audit their own work, the work of their direct',
      '   reports, or a control they designed. This rule was tightened in v3.1 after an engineer',
      '   audited a deployment gate he had written himself. Where independence cannot be met',
      '   internally, a contracted auditor is used.',
      '3. **Conduct.** Evidence is gathered by sampling records, observing the control operating,',
      '   and interviewing the people who run it. A statement without a record behind it is an',
      '   observation, never a conformity.',
      '4. **Classify findings.** Major nonconformity: a control absent, or a failure with actual',
      '   information security consequence. Minor: an isolated lapse in an otherwise working',
      '   control. Observation: a weakness that has not yet failed. Each finding names the clause,',
      '   the evidence and the sample size.',
      '5. **Close the audit.** A closing meeting is held with the auditees and Dhiaz Fathra; the',
      '   report is issued within five working days. Nonconformities are transferred to the',
      '   corrective action register under ISMS-POL-C10-2 with an owner and a due date.',
      '6. **Follow up.** Tika verifies effectiveness of each action before closing it, and reports',
      '   audit results and open findings to the management review.',
      '',
      '## Records',
      '',
      'Audit plans, checklists, evidence notes, reports and follow-up verification, retained five',
      'years — long enough to cover a full certification cycle.',
      '',
      '## Review',
      '',
      'Annually, and after any external audit that raises a finding the internal programme should',
      'have caught first.',
    ].join('\n'),
  },

  {
    code: 'ISMS-POL-C9-2-1',
    title: 'Internal Audit — General Requirements and Auditor Competence',
    clause: '27001 9.2.1',
    crossRefs: ['27001 9.2', '27001 7.2', '27001 9.2.2', 'A.6.3', '9001 7.2'],
    version: 'v1.3',
    owner: 'Tika',
    form: {
      code: 'FRM-ISMS-C9-2-1-01',
      name: 'Internal auditor competence and independence record',
    },
    revisions: [
      {
        version: 'v1.0',
        date: '2024-08-26',
        author: 'Tika',
        approval: 'Approved by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Issued when the second internal auditor joined the programme and consistency became a risk.',
      },
      {
        version: 'v1.3',
        date: '2026-02-02',
        author: 'Tika',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Competence criteria split into ISMS-specific and audit-technique elements; witness audit added before a first solo lead.',
      },
    ],
    evidence: [
      {
        name: 'isms-c9-2-1-auditor-competence-register-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-02-02',
        expiryDate: '2027-02-02',
        uploader: 'Tika',
        note: 'Who may audit what, on what basis, and what they are barred from auditing.',
        body: [
          'Internal auditor competence and independence register — 2026',
          '',
          'Auditor | Training | Witnessed lead | May lead | May audit | May NOT audit',
          'Tika | ISO 27001 Lead Auditor (PECB, 2024-05, valid 2027-05); ISO 9001 LA 2023 | n/a, programme manager | Yes | All clauses and Annex A | QMS documentation she authors',
          'Randy | ISO 27001 Internal Auditor (2025-03); AWS Security Specialty | 2025-11-12, witnessed by Tika | Yes, technical scopes | Clauses 6-10, Annex A.8 | Deployment pipeline controls he operated until 2025-06',
          'Rica | ISO 27001 Foundation (2025-09); PDP Law practitioner course | 2026-04-08, witnessed by Tika | Not yet | A.5 privacy controls, clause 7 | Legal and privacy processes she owns',
          'Wiwin | Internal auditor workshop (in-house, 2026-01) | Scheduled 2026-11 | Not yet | Clinic-side A.5.15, A.7 observations only | Customer complaint handling she owns',
          'External — Bapak Setiawan, KAP Mitra Andalan | ISO 27001 LA, IRCA | n/a | Yes | Any scope where internal independence fails | n/a',
          '',
          'Independence conflicts declared in 2026: Randy declared prior ownership of the deployment',
          'gate and was replaced by Tika for finding F-2026-13. Rica declared ownership of the',
          'processing instruction template and did not audit A.5.19 in the H1 cycle.',
          'Competence is re-evaluated each January against audits performed and report quality.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-C9-2-1 · Internal Audit — General Requirements and Auditor Competence',
      '',
      '**Owner** Tika · **Approver** Aris Ihwan · **Version** v1.3 · **Review** annually',
      '**Requirement** ISO/IEC 27001:2022 9.2.1 · **Also satisfies** 27001 9.2, 27001 7.2, 27001 9.2.2, A.6.3, ISO 9001 7.2',
      '',
      '## Purpose',
      '',
      'Clause 9.2.1 asks two questions of every internal audit: does the ISMS conform to what the',
      'organisation itself decided, and to ISO/IEC 27001:2022; and is it effectively implemented',
      'and maintained. This document states how Dermaster makes an audit capable of answering both',
      '— principally through auditor competence, objectivity and impartiality.',
      '',
      '## Scope',
      '',
      'All internal auditors used on the ISMS programme, whether employees of PT Cakrawala Bumi',
      'Estetika or contracted, and every audit conducted under ISMS-POL-C9-2.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Tika** maintains the competence register and assigns auditors to audits.',
      '- **Auditors** declare any conflict before an audit begins, in writing on the audit plan.',
      '- **Aris Ihwan** approves the use of an external auditor where internal independence fails.',
      '',
      '## Requirements',
      '',
      '1. **Conformity is assessed against two criteria, separately.** The report states, for each',
      '   scope area, whether it conforms to the organisation own documented requirements and',
      '   whether it conforms to the standard. The two can diverge: a procedure may be followed',
      '   exactly and still fall short of the standard, and that case must be visible in the report.',
      '2. **Effectiveness is assessed, not only presence.** An auditor who confirms a control',
      '   exists has done half the job. Effectiveness is judged by observing the control acting on',
      '   real traffic — a real leaver, a real change, a real restore — and by tracing outcomes.',
      '3. **Competence.** An auditor must hold recognised audit training, demonstrate knowledge of',
      '   the ISMS scope area, and complete one witnessed audit before leading. Competence is',
      '   recorded on `FRM-ISMS-C9-2-1-01` and re-evaluated each January.',
      '4. **Objectivity and impartiality.** An auditor may not audit their own work, their own',
      '   team output, or a control they designed or operated in the preceding 12 months. Conflicts',
      '   are declared on the plan and resolved by reassignment, not by disclosure alone.',
      '5. **Evidence discipline.** Every finding cites the record examined, the sample size and the',
      '   population it was drawn from. "Several accounts" is not a finding; "3 of 20 sampled',
      '   leavers" is.',
      '6. **Reporting to management.** Results are reported to the relevant control owner',
      '   immediately and to top management through the management review; an audit result is never',
      '   filtered by the auditee before it reaches Aris Ihwan.',
      '',
      '## Records',
      '',
      'Competence register, declared conflicts, witnessed audit notes and training certificates,',
      'retained for five years.',
      '',
      '## Review',
      '',
      'Annually, and whenever an auditor joins or leaves the programme.',
    ].join('\n'),
  },

  {
    code: 'ISMS-POL-C9-2-2',
    title: 'ISMS Internal Audit Programme 2026-2027',
    clause: '27001 9.2.2',
    crossRefs: ['27001 9.2', '27001 9.2.1', '27001 9.3.2', '27001 6.1.2', 'A.5.35'],
    version: 'v4.0',
    owner: 'Tika',
    form: { code: 'FRM-ISMS-C9-2-2-01', name: 'Multi-year internal audit programme schedule' },
    revisions: [
      {
        version: 'v3.2',
        date: '2025-01-13',
        author: 'Tika',
        approval: 'Approved by Aris Ihwan',
        status: 'Superseded',
        note: 'Two audits per year covering everything equally; high-risk areas got the same attention as low-risk ones.',
      },
      {
        version: 'v4.0',
        date: '2026-01-12',
        author: 'Tika',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Programme reweighted by risk and by previous results; three cycles per year, clinic sites sampled on rotation.',
      },
    ],
    evidence: [
      {
        name: 'isms-c9-2-2-audit-programme-2026-2027.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-01-12',
        expiryDate: '2027-01-12',
        uploader: 'Tika',
        note: 'The approved multi-year programme: what is audited when, by whom, and why it was weighted that way.',
        body: [
          'ISMS internal audit programme 2026-2027 (approved 2026-01-12)',
          '',
          'Audit | Window | Scope | Lead | Sites | Weighting reason',
          'IA-2026-01 | Feb 2026 | Clauses 4, 5, 7; A.6, A.7 | Tika | Head office, Kemang, Bandung Dago | Routine cycle',
          'IA-2026-02 | Jun 2026 | Clauses 6, 8, 9; A.5.15-A.5.18, A.8.2, A.8.13, A.8.15 | Tika | Head office, Kelapa Gading, Surabaya Pakuwon, engineering | Access control carried 2 findings in 2025',
          'IA-2026-03 | Oct 2026 | Clause 10; A.5.19-A.5.23 supplier chain; A.8.25-A.8.31 | Randy | Engineering, procurement | Marketplace migration risk R-052',
          'IA-2027-01 | Feb 2027 | Clauses 4, 5, 7; A.6, A.7 | Tika | Head office, Bali Seminyak, Medan | Site rotation',
          'IA-2027-02 | Jun 2027 | Clauses 6, 8, 9; A.8 technical controls | Randy | Engineering, Kelapa Gading | Full technical re-audit before recertification',
          'IA-2027-03 | Oct 2027 | Full ISMS readiness audit ahead of surveillance visit | External, Bapak Setiawan | Head office + 3 sites | Independence for the pre-certification check',
          '',
          'Clinic site rotation: all 13 sites are visited at least once across a rolling 24 months.',
          'Sites visited in 2026: Kemang, Bandung Dago, Kelapa Gading, Surabaya Pakuwon.',
          'Programme inputs used for weighting: 2025 audit results (7 minors, 4 in access control),',
          'the 2026 risk assessment (3 High risks), incident log (2 confirmed incidents in 2025),',
          'and the marketplace migration change.',
          'Programme change log: IA-2026-03 scope widened on 2026-08-14 to include A.8.31 after the',
          'rolled-back cutover CHG-2026-0288.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-C9-2-2 · ISMS Internal Audit Programme 2026-2027',
      '',
      '**Owner** Tika · **Approver** Aris Ihwan · **Version** v4.0 · **Review** annually, each January',
      '**Requirement** ISO/IEC 27001:2022 9.2.2 · **Also satisfies** 27001 9.2, 27001 9.2.1, 27001 9.3.2, 27001 6.1.2, A.5.35',
      '',
      '## Purpose',
      '',
      'To plan, establish, implement and maintain the audit programme itself — the schedule across',
      'years rather than the conduct of any single audit — including frequency, methods,',
      'responsibilities, planning requirements and reporting. The programme is the instrument that',
      'ensures the whole ISMS is audited over time rather than the same convenient parts repeatedly.',
      '',
      '## Scope',
      '',
      'A rolling 24-month programme covering all ISO/IEC 27001:2022 clauses, all applicable Annex A',
      'controls, head office, the engineering team and all 13 clinic locations on rotation.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Tika** establishes and maintains the programme and reports its status.',
      '- **Randy** leads technical audits within it.',
      '- **Aris Ihwan** approves the programme annually and any mid-year change to it.',
      '- **Dhiaz Fathra** supplies the risk and change inputs used for weighting.',
      '',
      '## How the programme is built',
      '',
      '1. **Frequency by importance, not by calendar convenience.** Three audit cycles run per',
      '   year. Areas are weighted by the current risk assessment, the results of previous audits,',
      '   incident history and significant change. Access control is audited in every cycle because',
      '   four of the seven 2025 minors were raised against it; the clinic signage CMS is not',
      '   audited at all this cycle because its worst case is a defaced screen.',
      '2. **Coverage guarantee.** Every applicable clause and control is audited at least once per',
      '   rolling 24 months, and every clinic location is visited at least once in that window.',
      '   Coverage is tracked on `FRM-ISMS-C9-2-2-01` so a gap is visible before it becomes a',
      '   certification finding.',
      '3. **Methods.** Document review, record sampling, observation on site, interview, and',
      '   technical verification against live systems in AWS ap-southeast-1. Remote audit is',
      '   permitted for engineering scopes and never for clinic physical controls.',
      '4. **Responsibilities and planning.** Each audit has a named lead assigned from the',
      '   competence register, a defined scope and criteria, and dates agreed with the auditee.',
      '5. **Change to the programme.** The programme is amended when a significant incident, a new',
      '   High risk or a major change occurs — as when IA-2026-03 was widened after the rolled-back',
      '   marketplace cutover. Changes are recorded in the programme change log and approved.',
      '6. **Reporting.** Programme status — audits completed, findings open, coverage achieved — is',
      '   a standing management review input under 27001 9.3.2.',
      '',
      '## Records',
      '',
      'The programme schedule, its change log and the coverage tracker, retained five years.',
      '',
      '## Review',
      '',
      'Each January, and whenever a certification or surveillance audit result suggests the',
      'weighting was wrong.',
    ].join('\n'),
  },

  {
    code: 'ISMS-POL-C9-3',
    title: 'ISMS Management Review Procedure',
    clause: '27001 9.3',
    crossRefs: ['27001 9.3.1', '27001 9.3.2', '27001 9.3.3', '27001 5.1', '9001 9.3'],
    version: 'v2.4',
    owner: 'Dhiaz Fathra',
    form: {
      code: 'FRM-ISMS-C9-3-01',
      name: 'Management review agenda, input pack and minute template',
    },
    revisions: [
      {
        version: 'v2.2',
        date: '2024-09-30',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Superseded',
        note: 'Quarterly cadence set; ISMS and QMS reviews still held separately and repeating the same content.',
      },
      {
        version: 'v2.3',
        date: '2025-09-15',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Superseded',
        note: 'Combined ISMS/QMS review adopted; input pack circulated five working days ahead.',
      },
      {
        version: 'v2.4',
        date: '2026-03-23',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Every decision must now carry an owner and a date in the minute, or it is not recorded as a decision.',
      },
    ],
    evidence: [
      {
        name: 'isms-c9-3-management-review-attendance-2026.md',
        fileType: 'MD',
        uploadedAt: '2026-07-14',
        expiryDate: '2027-07-14',
        uploader: 'Dhiaz Fathra',
        note: 'Attendance and quorum record for the four ISMS management reviews held under this procedure.',
        body: [
          '# Management review attendance — 2026 cycles',
          '',
          '| Review | Date | Chair | Present | Apologies | Quorum met |',
          '| --- | --- | --- | --- | --- | --- |',
          '| MR-2026-Q1 | 2026-01-26 | Aris Ihwan | Dhiaz Fathra, Tika, Agil, Pak Andre, Pak Chen, Rica | Pak Rila | Yes |',
          '| MR-2026-Q2 | 2026-04-20 | Aris Ihwan | Dhiaz Fathra, Tika, Agil, Andreas, Pak Andre, Pak Rila, Wiwin | Rica | Yes |',
          '| MR-2026-Q3 | 2026-07-13 | Aris Ihwan | Dhiaz Fathra, Tika, Agil, Andreas, Pak Andre, Pak Chen, Rica, Wiwin | none | Yes |',
          '| MR-2026-Q4 | scheduled 2026-10-19 | Aris Ihwan | — | — | — |',
          '',
          'Quorum rule: the chair, the management representative, the QA lead and at least three',
          'process owners. A review held without quorum is rescheduled, not minuted as held.',
          'Average duration 95 minutes. Input pack circulated 5 working days ahead in every case;',
          'the Q1 pack was late by one day and the delay is noted in the MR-2026-Q1 minute.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-C9-3 · ISMS Management Review Procedure',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v2.4 · **Review** annually',
      '**Requirement** ISO/IEC 27001:2022 9.3 · **Also satisfies** 27001 9.3.1, 27001 9.3.2, 27001 9.3.3, 27001 5.1, ISO 9001 9.3',
      '',
      '## Purpose',
      '',
      'To set out how top management of PT Cakrawala Bumi Estetika reviews the ISMS at planned',
      'intervals to ensure its continuing suitability, adequacy and effectiveness. The review is',
      'where security stops being an engineering concern and becomes a business decision with a',
      'budget attached.',
      '',
      '## Scope',
      '',
      'The whole ISMS, reviewed jointly with the QMS in a single combined session because the two',
      'systems share process owners, a scope and most of the audience. ISMS and QMS items are',
      'minuted under separate headings so each standard can be evidenced independently.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Aris Ihwan (Managing Director)** chairs the review and owns the decisions taken in it.',
      '- **Dhiaz Fathra** assembles the input pack, presents it and minutes the outputs.',
      '- **Tika** presents audit results and corrective action status.',
      '- **Agil** presents metrics, incidents and technical control performance.',
      '- **Process owners** — Pak Andre, Pak Chen, Pak Rila, Wiwin, Rica, Andreas — answer for',
      '  their areas and accept the actions assigned to them in the room.',
      '',
      '## Procedure',
      '',
      '1. **Cadence.** Quarterly, in the month following each quarter close. An additional review',
      '   is convened within ten working days of any major nonconformity or a confirmed incident',
      '   affecting patient data.',
      '2. **Quorum.** The chair, the management representative, the QA lead and at least three',
      '   process owners. Without quorum the session is rescheduled and nothing is minuted as',
      '   reviewed — attendance is the difference between a management review and a status meeting.',
      '3. **Input pack.** Circulated five working days ahead, containing the inputs required by',
      '   27001 9.3.2 and listed in ISMS-POL-C9-3-2. Members are expected to have read it; the',
      '   session is for decisions, not for reading numbers aloud.',
      '4. **Conduct.** Each agenda item ends with one of three outcomes: accepted as adequate, an',
      '   action with an owner and a date, or an escalation with a resource commitment.',
      '5. **Minute.** Dhiaz Fathra issues the minute within five working days. A decision recorded',
      '   without an owner and a date is not a decision and is returned to the chair.',
      '6. **Carry forward.** Open actions from the previous review are the first agenda item of the',
      '   next. An action open across three consecutive reviews is escalated as a resourcing issue,',
      '   not re-dated a third time.',
      '',
      '## Records',
      '',
      'Agendas, input packs, attendance sheets and signed minutes, retained five years in the',
      'compliance repository.',
      '',
      '## Review',
      '',
      'Annually, and whenever the composition of top management changes.',
    ].join('\n'),
  },

  {
    code: 'ISMS-POL-C9-3-1',
    title: 'Management Review — General Requirements and Planned Intervals',
    clause: '27001 9.3.1',
    crossRefs: ['27001 9.3', '27001 9.3.2', '27001 5.1', '27001 5.3', 'A.5.1'],
    version: 'v1.2',
    owner: 'Dhiaz Fathra',
    form: {
      code: 'FRM-ISMS-C9-3-1-01',
      name: 'Management review calendar and suitability assessment sheet',
    },
    revisions: [
      {
        version: 'v1.0',
        date: '2024-07-15',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Superseded',
        note: 'Annual review interval; too slow to react to the clinic expansion from 9 to 13 sites.',
      },
      {
        version: 'v1.2',
        date: '2026-02-09',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Quarterly interval fixed, with the suitability/adequacy/effectiveness judgement written as three separate statements.',
      },
    ],
    evidence: [
      {
        name: 'isms-c9-3-1-suitability-assessment-2026q2.md',
        fileType: 'MD',
        uploadedAt: '2026-07-13',
        expiryDate: '2027-07-13',
        uploader: 'Aris Ihwan',
        note: 'The chair written judgement on continuing suitability, adequacy and effectiveness for Q2 2026.',
        body: [
          '# Continuing suitability, adequacy and effectiveness — MR-2026-Q3 (Q2 data)',
          '',
          '**Chair** Aris Ihwan · **Date** 13 July 2026 · **Interval** quarterly, as planned',
          '',
          '## Suitability — does the ISMS still fit the business we are?',
          '',
          'Partly. The scope still describes 13 clinics and one ERP, which is accurate. It does not',
          'yet describe the marketplace business the group is migrating onto Express.js and Go, and',
          'the Q2 risk assessment carried R-052 specifically because of that gap. Action MR-Q3-01:',
          'Dhiaz Fathra to bring a revised scope statement to MR-2026-Q4 by 2026-10-19.',
          '',
          '## Adequacy — do we have enough of what the ISMS needs?',
          '',
          'No, in one respect. Two people (Agil, Andreas) carry every technical control and both',
          'were on the critical path of the June audit findings. Action MR-Q3-02: Pak Rila to fund',
          'one additional security engineer in the 2027 budget round, decision by 2026-11-30.',
          '',
          '## Effectiveness — is it working?',
          '',
          'Yes, on the evidence. Three minor nonconformities in H1, none major; leaver deprovisioning',
          'moved from 91% to 100% after CAR-2026-057; erasure runs with an unacknowledged service',
          'reached zero in August; no confirmed patient data breach in the period.',
          '',
          'Overall judgement: the ISMS is effective and adequate for current operations, and will',
          'not be suitable for the marketplace business without the scope revision above.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-C9-3-1 · Management Review — General Requirements and Planned Intervals',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v1.2 · **Review** annually',
      '**Requirement** ISO/IEC 27001:2022 9.3.1 · **Also satisfies** 27001 9.3, 27001 9.3.2, 27001 5.1, 27001 5.3, A.5.1',
      '',
      '## Purpose',
      '',
      'Clause 9.3.1 requires top management to review the ISMS at planned intervals to ensure its',
      'continuing suitability, adequacy and effectiveness. This document fixes what "planned',
      'intervals" means at Dermaster and forces the three words to be answered separately, because',
      'an ISMS can be effective at what it does and still be unsuitable for the business it now has.',
      '',
      '## Scope',
      '',
      'The review obligation of top management over the ISMS covering head office, the engineering',
      'team, the 13 clinic locations and the outsourced processes in the scope statement.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Aris Ihwan** personally makes and signs the suitability, adequacy and effectiveness',
      '  judgement. It may not be delegated to the management representative.',
      '- **Dhiaz Fathra** schedules the reviews and supplies the evidence behind the judgement.',
      '- **The board of PT Cakrawala Bumi Estetika** receives the annual consolidated judgement.',
      '',
      '## Requirements',
      '',
      '1. **Planned intervals.** Quarterly, scheduled in the calendar 12 months ahead on',
      '   `FRM-ISMS-C9-3-1-01`. The interval moved from annual to quarterly in 2026 because an',
      '   annual cycle could not keep up with an estate that grew from 9 to 13 clinics in 18 months.',
      '2. **Unplanned reviews.** Convened within ten working days of a major nonconformity, a',
      '   confirmed incident involving patient data, or a change of scope.',
      '3. **Three separate judgements.** Suitability asks whether the ISMS still fits the business,',
      '   its context and its interested parties. Adequacy asks whether it has the resources,',
      '   people and authority it needs. Effectiveness asks whether it achieves its objectives on',
      '   the evidence. Each is written as its own statement with its own reasoning; a single',
      '   sentence covering all three is rejected by the chair.',
      '4. **Evidence-bound.** Each judgement cites the specific inputs it rests on — audit results,',
      '   metric trends, incident counts, risk assessment output. An assertion without a cited',
      '   input is not minuted.',
      '5. **Signature.** The chair signs the assessment sheet. The signed sheet is the record that',
      '   satisfies 9.3.1 and is presented at certification and surveillance audits.',
      '6. **Escalation to the board.** The Q4 assessment is consolidated annually and tabled at the',
      '   board meeting, with any resourcing decision it depends on.',
      '',
      '## Records',
      '',
      'Review calendar and signed suitability assessment sheets, retained five years.',
      '',
      '## Review',
      '',
      'Annually, and whenever the interval proves too slow — evidenced by a decision that had to be',
      'taken outside a review because the next one was too far away.',
    ].join('\n'),
  },

  {
    code: 'ISMS-POL-C9-3-2',
    title: 'Management Review Inputs — Required Input Pack',
    clause: '27001 9.3.2',
    crossRefs: ['27001 9.3', '27001 9.1', '27001 9.2', '27001 6.1.2', '27001 4.2'],
    version: 'v2.1',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-ISMS-C9-3-2-01', name: 'Management review input pack checklist' },
    revisions: [
      {
        version: 'v2.0',
        date: '2025-04-14',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Superseded',
        note: 'Input list aligned item by item with 9.3.2 (a) to (f) after an auditor could not find the interested-party input.',
      },
      {
        version: 'v2.1',
        date: '2026-04-06',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Each input now names the person who supplies it and the source document, so a missing input has an owner.',
      },
    ],
    evidence: [
      {
        name: 'isms-c9-3-2-input-pack-2026q3.md',
        fileType: 'MD',
        uploadedAt: '2026-07-06',
        expiryDate: '2027-07-06',
        uploader: 'Dhiaz Fathra',
        note: 'The actual input pack circulated for MR-2026-Q3, mapped to 9.3.2 (a)-(f).',
        body: [
          '# Management review input pack — MR-2026-Q3 (circulated 6 July 2026)',
          '',
          '| 9.3.2 | Input | Supplied by | Source | Summary |',
          '| --- | --- | --- | --- | --- |',
          '| (a) | Status of actions from previous reviews | Dhiaz Fathra | Action register | 9 actions carried, 6 closed, 3 open, 1 open across 2 reviews (MR-Q1-04, MFA on legacy PMS) |',
          '| (b) | Changes in external and internal issues | Rica, Wiwin | Context register | PDP Law implementing regulation issued Mar 2026; marketplace migration; Medan clinic opening Q4 |',
          '| (c) | Needs and expectations of interested parties | Rica | Interested party register | Patients (erasure requests up 34%), BPOM, Zitadel, AWS, PT Mitra Sumber Daya, staff |',
          '| (d) | Feedback on information security performance | Agil | Monthly metric sheets | 11 metrics, 2 breaches in Q2, both closed; MTTD improved 6.1h to 3.4h |',
          '| (d) | Nonconformities and corrective actions | Tika | CAR register | 3 raised (CAR-2026-057/058/059), 2 closed, 1 in verification |',
          '| (d) | Monitoring and measurement results | Agil | FRM-ISMS-C9-1-01 | See metric sheet; clinic MDM non-compliance down from 14 to 9 devices |',
          '| (d) | Audit results | Tika | IA-2026-02 report | 3 minor NC, 2 observations, no major |',
          '| (d) | Fulfilment of security objectives | Dhiaz Fathra | Objectives sheet | 4 of 5 objectives on track; "zero unacknowledged erasure runs" missed in June, met in Jul-Aug |',
          '| (e) | Feedback from interested parties | Wiwin | Complaint register, patient queries | 6 patient security queries, 2 about photo storage; 1 corporate client security questionnaire |',
          '| (f) | Results of risk assessment and treatment plan status | Dhiaz Fathra | FRM-ISMS-C8-2-01, FRM-ISMS-C8-3-01 | 3 High risks, all under treatment; 7 of 11 treatment actions closed |',
          '| (g) | Opportunities for continual improvement | All owners | Improvement log | 5 proposals, 2 recommended for approval (SIEM correlation rules, MDM auto-remediation) |',
          '',
          'Pack circulated 5 working days ahead of the 13 July session. No input marked "not available".',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-C9-3-2 · Management Review Inputs — Required Input Pack',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v2.1 · **Review** annually',
      '**Requirement** ISO/IEC 27001:2022 9.3.2 · **Also satisfies** 27001 9.3, 27001 9.1, 27001 9.2, 27001 6.1.2, 27001 4.2',
      '',
      '## Purpose',
      '',
      'To define exactly what must be in front of top management before an ISMS review can be held,',
      'who supplies each item and from which source. The pack exists so that the review is a',
      'judgement on evidence rather than a conversation about impressions.',
      '',
      '## Scope',
      '',
      'Every quarterly and unplanned ISMS management review held under ISMS-POL-C9-3.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Dhiaz Fathra** assembles the pack and chases missing inputs.',
      '- **Named suppliers** — Agil (performance, metrics, incidents), Tika (audit and corrective',
      '  action), Rica (context, interested parties, legal change), Wiwin (customer feedback),',
      '  Pak Chen (supplier security), Andreas (technical control status) — each own their input.',
      '- **Aris Ihwan** may refuse to open a review whose pack is incomplete.',
      '',
      '## Required inputs',
      '',
      '1. **Status of actions from previous management reviews** — every open action with its',
      '   owner, original date and the number of reviews it has been carried across.',
      '2. **Changes in external and internal issues relevant to the ISMS** — regulatory change,',
      '   notably under UU No. 27/2022 and BPOM requirements, organisational change, new locations,',
      '   platform change.',
      '3. **Changes in the needs and expectations of interested parties** — patients, regulators,',
      '   corporate clients, staff, processors and cloud providers.',
      '4. **Feedback on information security performance** — nonconformities and corrective',
      '   actions; monitoring and measurement results; audit results; and fulfilment of the',
      '   information security objectives. These four are presented as four items, not merged.',
      '5. **Feedback from interested parties** — patient security queries, complaint themes with a',
      '   security element, and client security questionnaires received in the period.',
      '6. **Results of risk assessment and status of the risk treatment plan** — current risk',
      '   levels, movement since the last review, and per-action treatment progress.',
      '7. **Opportunities for continual improvement** — proposals from any owner, with an estimate',
      '   of the effort and the risk each would reduce.',
      '',
      '## Rules for the pack',
      '',
      'An input that cannot be supplied is listed as missing with a reason and an owner; it is',
      'never silently omitted. Data is shown against the previous two periods so a trend is visible.',
      'The pack is circulated five working days before the session.',
      '',
      '## Records',
      '',
      'Input pack checklists and the circulated packs themselves, retained five years alongside the',
      'minutes they informed.',
      '',
      '## Review',
      '',
      'Annually, and whenever an auditor cannot locate one of the required inputs in the pack.',
    ].join('\n'),
  },

  {
    code: 'ISMS-POL-C9-3-3',
    title: 'Management Review Results — Decisions, Actions and Change Needs',
    clause: '27001 9.3.3',
    crossRefs: ['27001 9.3', '27001 9.3.2', '27001 10.1', '27001 6.3', '9001 9.3.3'],
    version: 'v1.4',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-ISMS-C9-3-3-01', name: 'Management review decision and action record' },
    revisions: [
      {
        version: 'v1.2',
        date: '2025-05-19',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Superseded',
        note: 'Minutes recorded discussion but not decisions; the follow-up item could not be traced to a resolution.',
      },
      {
        version: 'v1.4',
        date: '2026-04-27',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Decisions classified as improvement, ISMS change or resource need, and each carries a funding note where money is involved.',
      },
    ],
    evidence: [
      {
        name: 'isms-c9-3-3-decision-record-2026q3.docx',
        fileType: 'DOCX',
        uploadedAt: '2026-07-17',
        expiryDate: '2027-07-17',
        uploader: 'Dhiaz Fathra',
        note: 'The decisions and actions minuted from MR-2026-Q3, issued four working days after the session.',
        body: [
          '# Management review decisions and actions — MR-2026-Q3',
          '',
          '**Session** 13 July 2026 · **Chair** Aris Ihwan · **Minuted by** Dhiaz Fathra · **Issued** 17 July 2026',
          '',
          '| Ref | Class | Decision | Owner | Due | Funding |',
          '| --- | --- | --- | --- | --- | --- |',
          '| MR-Q3-01 | ISMS change | Revise the scope statement to include the marketplace services and re-run the risk assessment for that scope | Dhiaz Fathra | 2026-10-19 | None required |',
          '| MR-Q3-02 | Resource need | Fund one additional security engineer in the 2027 budget; two people currently carry every technical control | Pak Rila | 2026-11-30 | IDR 420M annualised, 2027 opex |',
          '| MR-Q3-03 | Improvement | Deploy SIEM correlation rules for leaver-account activity so detection is automatic, not sampled at audit | Agil | 2026-09-30 | Within existing tooling spend |',
          '| MR-Q3-04 | Improvement | MDM auto-remediation for clinic devices out of compliance for more than 72 hours | Pak Andre | 2026-10-31 | IDR 38M one-off |',
          '| MR-Q3-05 | ISMS change | Add erasure acknowledgement completeness as a security objective for 2027 | Dhiaz Fathra | 2026-12-15 | None required |',
          '| MR-Q3-06 | Resource need | Approve external lead auditor for the pre-certification audit IA-2027-03 | Tika | 2027-06-30 | IDR 65M, 2027 opex |',
          '',
          'Carried from MR-2026-Q2: MR-Q1-04 (MFA on the legacy clinic PMS) open across two reviews;',
          'escalated by the chair as a resourcing issue rather than re-dated a third time, and',
          'absorbed into MR-Q3-02.',
          'Closed at this session: MR-Q2-02 (supplier attestation backlog), MR-Q2-03 (restore',
          'rehearsal evidence), MR-Q2-05 (payment callback verification).',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-C9-3-3 · Management Review Results — Decisions, Actions and Change Needs',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v1.4 · **Review** annually',
      '**Requirement** ISO/IEC 27001:2022 9.3.3 · **Also satisfies** 27001 9.3, 27001 9.3.2, 27001 10.1, 27001 6.3, ISO 9001 9.3.3',
      '',
      '## Purpose',
      '',
      'To define what a Dermaster management review must produce. Clause 9.3.3 requires the results',
      'to include decisions related to continual improvement opportunities and to any need for',
      'change in the ISMS. This document turns that requirement into a record format that survives',
      'contact with a busy quarter.',
      '',
      '## Scope',
      '',
      'The outputs of every ISMS management review, including combined sessions held jointly with',
      'the QMS review.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Aris Ihwan** takes the decisions; only the chair may commit resources.',
      '- **Dhiaz Fathra** records them, issues the minute and tracks the action register.',
      '- **Action owners** accept their actions in the room and report status at the next review.',
      '- **Pak Rila** attaches a funding position to any decision with a cost.',
      '',
      '## Required outputs',
      '',
      '1. **Every result is classified.** Each recorded result is one of: an improvement',
      '   opportunity, a needed change to the ISMS (scope, policy, objectives, controls,',
      '   resources), or a resource need. The classification determines where it is routed —',
      '   improvements to the improvement log under ISMS-POL-C10-1, ISMS changes to the change',
      '   process, resource needs to the budget cycle.',
      '2. **Every result has an owner and a date.** A result without both is not a decision and is',
      '   returned to the chair before the minute is issued. This rule was added in v1.4 after 2025',
      '   minutes recorded discussion that could not later be traced to any resolution.',
      '3. **Money is named.** Where a decision has a cost, the minute records the amount and the',
      '   budget line, so the decision is testable at the next review rather than aspirational.',
      '4. **Carried actions are escalated, not re-dated.** An action open across three consecutive',
      '   reviews is escalated as a resourcing or ownership problem and re-stated as a new decision',
      '   with a different approach.',
      '5. **Issue within five working days.** The minute is issued to all attendees and to the',
      '   affected owners, and stored in the compliance repository under version control.',
      '6. **Close the loop.** Closed decisions are listed in the following minute with the evidence',
      '   that closed them; closure is confirmed by Tika, not asserted by the owner.',
      '',
      '## Records',
      '',
      'Decision and action records, the running action register, and closure evidence, retained',
      'five years.',
      '',
      '## Review',
      '',
      'Annually, and whenever an action is found to have been closed without evidence.',
    ].join('\n'),
  },

  {
    code: 'ISMS-POL-C10-1',
    title: 'Continual Improvement of the ISMS',
    clause: '27001 10.1',
    crossRefs: ['27001 10.2', '27001 9.3.3', '27001 9.1', '27001 6.2', 'A.5.36'],
    version: 'v2.0',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-ISMS-C10-1-01', name: 'ISMS improvement log and benefit assessment' },
    revisions: [
      {
        version: 'v1.1',
        date: '2024-10-21',
        author: 'Tika',
        approval: 'Approved by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Improvement treated as whatever came out of corrective action; nothing proactive was ever proposed.',
      },
      {
        version: 'v2.0',
        date: '2026-06-08',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Improvement separated from correction: anyone may propose, and each proposal is scored against the risk it reduces.',
      },
    ],
    evidence: [
      {
        name: 'isms-c10-1-improvement-log-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-09-01',
        expiryDate: '2027-09-01',
        uploader: 'Dhiaz Fathra',
        note: 'The 2026 improvement log with proposal source, benefit assessment and outcome.',
        body: [
          'ISMS improvement log — 2026',
          '',
          'ID | Proposal | Proposed by | Source | Risk reduced | Effort | Decision | Outcome',
          'IMP-2026-03 | Trigger leaver deprovisioning from the HR event instead of a ticket | Agil | Audit finding F-2026-11 | R-012 | 6 days | Approved MR-Q2 | Live 2026-07-18; leaver metric 91% to 100%',
          'IMP-2026-05 | Terraform plan gate blocking public ACLs on media buckets | Andreas | Near miss in staging | R-023 | 3 days | Approved MR-Q2 | Live 2026-06-24; 2 unsafe plans blocked since',
          'IMP-2026-07 | Kiosk profile on clinic tablets, no local photo gallery | Pak Andre | Clinic staff suggestion, Kemang | R-017 | 11 days | Approved MR-Q2 | Rolled out 13 sites by 2026-08-22',
          'IMP-2026-09 | SIEM correlation rules for leaver-account activity | Agil | Metric analysis | R-012, R-063 | 8 days | Approved MR-Q3 | In progress, due 2026-09-30',
          'IMP-2026-10 | MDM auto-remediation after 72h non-compliance | Pak Andre | Metric trend | Clinic device risk | 5 days | Approved MR-Q3 | In progress, due 2026-10-31',
          'IMP-2026-11 | Phishing simulation moved from annual to quarterly | Rica | 12.4% June click rate | R-075 | 2 days/quarter | Approved MR-Q3 | First quarterly run Aug 2026, 7.6%',
          'IMP-2026-12 | Replace the quarterly access review spreadsheet with a generated report | Agil | Audit observation F-2026-14 | Review integrity | 4 days | Deferred to 2027 | Capacity, revisit MR-2027-Q1',
          'IMP-2026-14 | Single sign-on for the legacy clinic PMS | Wiwin | Reception staff feedback | R-012 | 30+ days | Escalated | Depends on vendor roadmap; tracked as MR-Q3-02',
          '',
          'Proposals received 14, approved 6, deferred 5, rejected 2, escalated 1.',
          'Two rejected: "block all USB storage group-wide" (no route for radiology media transfer',
          'yet, revisit after the courier change) and "annual pen test of the signage CMS"',
          '(disproportionate to a score-4 risk).',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-C10-1 · Continual Improvement of the ISMS',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v2.0 · **Review** annually',
      '**Requirement** ISO/IEC 27001:2022 10.1 · **Also satisfies** 27001 10.2, 27001 9.3.3, 27001 9.1, 27001 6.2, A.5.36',
      '',
      '## Purpose',
      '',
      'To continually improve the suitability, adequacy and effectiveness of the ISMS. The point of',
      'this document is to separate improvement from correction. Fixing what broke is clause 10.2;',
      'improvement is what the organisation does when nothing has broken, and at Dermaster it used',
      'to be nothing at all — before 2026 every "improvement" in the log was in fact a corrective',
      'action wearing a different label.',
      '',
      '## Scope',
      '',
      'The ISMS, its controls, its documentation and the processes that run it, across head office,',
      'engineering and the 13 clinic locations.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Any employee** may propose an improvement; the Kemang tablet kiosk profile came from a',
      '  clinic nurse, not from engineering.',
      '- **Dhiaz Fathra** maintains the improvement log and assesses each proposal.',
      '- **Aris Ihwan and the management review** approve, defer or reject proposals.',
      '- **The proposer or a named owner** implements an approved proposal.',
      '',
      '## Procedure',
      '',
      '1. **Propose.** Anyone may raise an improvement through the compliance mailbox, their line',
      '   manager, or directly at the ISMS operations meeting. A proposal states what is weak now',
      '   and what it would look like afterwards. No form-filling is required to get an idea heard.',
      '2. **Assess benefit.** Dhiaz Fathra records the proposal against the risk it would reduce or',
      '   the objective it would advance, with an effort estimate. A proposal that maps to no risk',
      '   and no objective is rejected with a reason recorded — as the annual signage CMS pen test',
      '   was, being disproportionate to a score-4 risk.',
      '3. **Decide.** Proposals are decided at the quarterly management review, or immediately by',
      '   Dhiaz Fathra where the effort is under two days and the change is reversible.',
      '4. **Implement and verify.** The owner implements; the effect is verified against the metric',
      '   or risk score the proposal claimed it would move. IMP-2026-03 is closed on evidence: the',
      '   leaver deprovisioning metric moved from 91% to 100% and held.',
      '5. **Feed the sources.** Improvement proposals are actively drawn from metric trends, audit',
      '   observations, incident reviews, near misses, staff feedback and the risk assessment — six',
      '   named sources, so the log does not depend on people volunteering ideas unprompted.',
      '6. **Report.** The log is a management review input and the approved items become review',
      '   decisions under 27001 9.3.3.',
      '',
      '## Records',
      '',
      'Improvement log with proposal, assessment, decision and verified outcome, retained five',
      'years.',
      '',
      '## Review',
      '',
      'Annually, and whenever a quarter passes with no improvement proposal from outside the',
      'engineering and QA teams — that silence is itself the finding.',
    ].join('\n'),
  },

  {
    code: 'ISMS-POL-C10-2',
    title: 'Nonconformity and Corrective Action Procedure (ISMS)',
    clause: '27001 10.2',
    crossRefs: ['27001 10.1', '27001 9.2', '27001 9.3.2', 'A.5.24', '9001 10.2'],
    version: 'v3.2',
    owner: 'Tika',
    form: { code: 'FRM-ISMS-C10-2-01', name: 'Corrective action request and root cause record' },
    revisions: [
      {
        version: 'v3.0',
        date: '2024-12-16',
        author: 'Tika',
        approval: 'Approved by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Root cause analysis made mandatory; "staff error" was being recorded as a root cause on a third of records.',
      },
      {
        version: 'v3.1',
        date: '2025-08-11',
        author: 'Tika',
        approval: 'Approved by Aris Ihwan',
        status: 'Superseded',
        note: 'Similar-nonconformity check added: every CAR asks where else the same weakness exists.',
      },
      {
        version: 'v3.2',
        date: '2026-05-04',
        author: 'Tika',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Effectiveness verification separated from closure; a CAR is closed only after the fix is observed working on real traffic.',
      },
    ],
    evidence: [
      {
        name: 'isms-c10-2-corrective-action-register-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-09-02',
        expiryDate: '2027-09-02',
        uploader: 'Tika',
        note: 'The 2026 ISMS corrective action register with root causes and verified closures.',
        body: [
          'ISMS corrective action register — 2026',
          '',
          'CAR | Source | Nonconformity | Root cause | Correction | Corrective action | Owner | Verified | Status',
          'CAR-2026-041 | Metric breach | Surabaya Pakuwon CSAT below threshold 2 quarters | Practitioner roster gap on Thursdays | Locum booked | Roster minimum staffing rule added to the scheduling system | Pak Andre | 2026-06-30 | Closed',
          'CAR-2026-052 | Change failure | Marketplace cutover rolled back, 4h degraded service | No production-like data volume in the staging environment | Rollback executed | Staging refreshed nightly from a masked production snapshot | Andreas | 2026-08-12 | Closed',
          'CAR-2026-057 | Audit F-2026-11 | 3 of 20 leavers kept an active session 2-6 days | Deprovisioning depended on HR raising a ticket, not on the leaver event | 3 accounts disabled same day | Zitadel deprovisioning triggered by the HR leaver event | Agil | 2026-08-04 | Closed',
          'CAR-2026-058 | Audit F-2026-12 | Restore rehearsal recorded with no evidence of restored record count | Rehearsal checklist had no output field | Rehearsal repeated with evidence | Checklist rewritten; the runbook prints a record count | Andreas | 2026-07-29 | Closed',
          'CAR-2026-059 | Audit F-2026-13 | 2 emergency changes without a consequence review | Procedure did not say who reviews an unplanned change | Reviews performed retrospectively | ISMS-POL-C8-1 v2.1 names the reviewer and a 5-day limit | Dhiaz Fathra | 2026-08-19 | Closed',
          'CAR-2026-061 | Metric breach | Privileged access review missed at Bandung Dago in July | Reviewer on leave with no delegate | Review completed 6 days late | Named delegate required on the recertification sheet | Agil | 2026-09-01 | Closed',
          'CAR-2026-064 | Incident | Phishing e-mail reached 41 finance mailboxes | Sender-domain rule not applied to the finance tenant | Rule applied, mails purged | Rule set unified across all tenants; quarterly simulation added | Rica | pending | In verification',
          '',
          'Similar-nonconformity check outcomes: CAR-2026-057 found the same ticket dependency in the',
          'contractor offboarding path, which was fixed under the same action. CAR-2026-058 found two',
          'other runbooks with no output field; both were corrected.',
          'Median days from raise to verified closure: 41. Target <= 60.',
        ].join('\n'),
      },
    ],
    body: [
      '# ISMS-POL-C10-2 · Nonconformity and Corrective Action Procedure (ISMS)',
      '',
      '**Owner** Tika (QA Lead) · **Approver** Aris Ihwan · **Version** v3.2 · **Review** annually',
      '**Requirement** ISO/IEC 27001:2022 10.2 · **Also satisfies** 27001 10.1, 27001 9.2, 27001 9.3.2, A.5.24, ISO 9001 10.2',
      '',
      '## Purpose',
      '',
      'To state what Dermaster does when the ISMS does not work as it should: how the nonconformity',
      'is contained, how its cause is found, how the cause is removed so it does not recur, and how',
      'the organisation confirms that removal actually worked. The procedure treats "staff error"',
      'as a symptom, never as a root cause — a system that depends on nobody making a mistake is',
      'the nonconformity.',
      '',
      '## Scope',
      '',
      'Nonconformities from any source: internal and external audit, metric breach, incident review,',
      'supplier failure, patient or staff complaint with a security element, and self-reported',
      'lapses. It covers head office, engineering, all 13 clinic locations and outsourced processes.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Anyone** may raise a nonconformity; self-reporting is explicitly protected and is never',
      '  a disciplinary matter on its own.',
      '- **Tika** owns the register, quality-checks every root cause and verifies effectiveness.',
      '- **Action owners** perform the correction and the corrective action.',
      '- **Dhiaz Fathra** escalates any CAR open beyond 60 days to Aris Ihwan.',
      '',
      '## Procedure',
      '',
      '1. **React.** Contain the nonconformity and deal with its consequences first: disable the',
      '   account, purge the mail, restore the record, notify the affected patient where PDP Law',
      '   requires it. Containment is recorded as the correction, distinct from corrective action.',
      '2. **Evaluate the need to eliminate the cause.** Ask whether it could recur or occur',
      '   elsewhere. A one-off with no plausible recurrence is closed as a correction with the',
      '   reasoning recorded — but that judgement is Tika, not the action owner.',
      '3. **Determine the root cause.** Five-whys or a cause-and-effect analysis, recorded on',
      '   `FRM-ISMS-C10-2-01`. "Staff error", "carelessness" and "one-off" are rejected as root',
      '   causes; the analysis must reach a decision, a design or a missing control.',
      '4. **Check for similar nonconformities.** Every CAR asks where else the same weakness exists',
      '   — which found the same ticket dependency in the contractor offboarding path under',
      '   CAR-2026-057. Findings from this check are fixed under the same action.',
      '5. **Implement.** The corrective action changes the system, not only the behaviour: a gate,',
      '   an event trigger, a generated report, a required field.',
      '6. **Verify effectiveness.** Tika verifies by observing the fix working on real traffic — a',
      '   real leaver deprovisioned, a real rehearsal producing a record count — at least 30 days',
      '   after implementation. Closure without observed effect is not permitted.',
      '7. **Update risks and documentation.** Where the cause changes the risk picture, the risk',
      '   assessment and the affected procedure are revised, as ISMS-POL-C8-1 was under CAR-2026-059.',
      '',
      '## Records',
      '',
      'Corrective action requests, root cause records, verification evidence and the register,',
      'retained five years. The register is a documented management review input.',
      '',
      '## Review',
      '',
      'Annually, and whenever a nonconformity recurs after a CAR was closed against it — a',
      'recurrence means the verification step, not only the fix, failed.',
    ].join('\n'),
  },
]
