import type { SeedDocument } from './types'

/** Measurement and management review documents. */
export const MEASUREMENT_DOCUMENTS: SeedDocument[] = [
  {
    code: 'ENG-MET-001',
    title: 'Engineering Measurement Framework (SPACE / DORA)',
    clause: '9.1.1',
    crossRefs: ['9.1.3', 'A.8.25', '9.3'],
    version: 'v1.1',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-MET-01', name: 'Quarterly delivery metrics workbook' },
    revisions: [
      {
        version: 'v1.0',
        date: '2026-01-13',
        author: 'Dhiaz Fathra',
        approval: 'Drafted',
        status: 'Superseded',
        note: 'Four DORA metrics defined against GitLab and deployment data.',
      },
      {
        version: 'v1.1',
        date: '2026-04-20',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'SPACE dimensions added so the measure is not delivery speed alone; explicit non-use for individual appraisal.',
      },
    ],
    evidence: [
      {
        name: 'delivery-metrics-2026Q2.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-07-08',
        expiryDate: '2027-07-08',
        uploader: 'Tika',
        note: 'Quarterly workbook as presented to the management review.',
        body: [
          'Delivery metrics — 2026 Q2 (PT Cakrawala Bumi Estetika, Engineering)',
          '',
          'Deployment frequency | 3.4 per week | 2.1 previous quarter | Elite band not claimed; measured on tagged deploys only',
          'Lead time for change | 2.6 days median | 4.1 days previous | Measured first commit to production tag',
          'Change failure rate | 11% | 16% previous | Deploys followed by a rollback or a hotfix within 24h',
          'Time to restore | 47 minutes median | 78 minutes previous | P1 and P2 incidents',
          'Satisfaction (SPACE S) | 3.9 of 5 | 3.6 previous | 12 of 13 responded',
          'Flow interruption (SPACE A) | 6.2 context switches per engineer per week | 7.8 previous | Self-reported',
          'Review wait time (SPACE C) | 5.1 hours median | 9.4 previous | First human review comment on a merge request',
          '',
          'Source: GitLab API export, deployment tags, quarterly survey. ETL by Tika; workbook is',
          'the record of the quarter and is not edited after presentation.',
        ].join('\n'),
      },
    ],
    body: [
      '# Engineering Measurement Framework (SPACE / DORA)',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v1.1',
      '**Requirement** ISO 9001 9.1.1 · **Also satisfies** 9.1.3, A.8.25, management review inputs',
      '',
      '## 1. Purpose',
      '',
      'ISO 9001 9.1.1 requires the organisation to determine what it monitors, how, and when the',
      'results are evaluated. For engineering, this document is that determination.',
      '',
      '## 2. What is measured',
      '',
      '### DORA — delivery performance',
      '',
      '- **Deployment frequency** — Definition: Tagged production deploys per week · Source: Deployment tags',
      '- **Lead time for change** — Definition: Median first commit to production tag · Source: GitLab API',
      '- **Change failure rate** — Definition: Deploys followed by rollback or hotfix within 24 hours · Source: Deployment log',
      '- **Time to restore** — Definition: Median P1/P2 incident duration · Source: Incident register',
      '',
      '### SPACE — the dimensions delivery speed hides',
      '',
      '- **Satisfaction** — Measure: Quarterly 5-point survey, whole team · Source: Survey',
      '- **Performance** — Measure: Change failure rate, escaped defects found by QA in production · Source: Incident register, QA log',
      '- **Activity** — Measure: Merge requests merged (context only, never a target) · Source: GitLab API',
      '- **Communication** — Measure: Median wait for the first human review comment · Source: GitLab API',
      '- **Efficiency** — Measure: Self-reported context switches per week · Source: Survey',
      '',
      '## 3. How it is collected',
      '',
      'A scheduled export pulls the GitLab and deployment data; Tika runs the ETL and lands it in',
      'the quarterly workbook. The workbook is deliberately a spreadsheet: it is read by people',
      'outside engineering, it is the artefact presented at the management review, and it is',
      'filed unchanged afterwards as the record of that quarter.',
      '',
      'The ETL handoff is documented in the workbook’s first sheet — source query, run date,',
      'operator — so a number in the record can be traced back to the export that produced it.',
      '',
      '## 4. How it is used',
      '',
      '1. Reported quarterly to the management review as a performance input (ISO 9001 9.3.2).',
      '2. A metric moving the wrong way for two consecutive quarters is raised as an improvement',
      '   opportunity with an owner, not as a target to be hit.',
      '3. **Not used to appraise individuals.** Activity counts are context. Anyone ranking',
      '   engineers by merge request count is misusing this document.',
      '',
      '## 5. Deliberate limits',
      '',
      'No metrics platform, no real-time dashboard, no per-engineer drill-down. A quarterly',
      'workbook answers the question the management review actually asks. Build a pipeline when',
      'the spreadsheet stops being able to hold the data, not before.',
      '',
      '## 6. Review',
      '',
      'Annually, and whenever a metric is found to be driving behaviour rather than describing it.',
    ].join('\n'),
  },

  {
    code: 'ISMS-PRO-093',
    title: 'Management Review Meeting — Procedure, Agenda and Minutes Template',
    clause: '9.3',
    crossRefs: ['9001 9.3', '9.1.1', 'A.5.1'],
    version: 'v2.1',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-MRM-01', name: 'Management review minutes' },
    revisions: [
      {
        version: 'v2.0',
        date: '2025-08-25',
        author: 'Dhiaz Fathra',
        approval: 'Drafted',
        status: 'Superseded',
        note: 'Combined the ISMS and QMS reviews into one meeting with one minute set.',
      },
      {
        version: 'v2.1',
        date: '2026-02-09',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Input list aligned to 9.3.2 item by item; decisions must name an owner and a date to be minuted.',
      },
    ],
    evidence: [
      {
        name: 'mrm-minutes-2026Q2-signed.docx',
        fileType: 'DOCX',
        uploadedAt: '2026-07-15',
        expiryDate: '2029-07-15',
        uploader: 'Dhiaz Fathra',
        note: 'Signed minutes of the Q2 2026 combined ISMS/QMS management review.',
        body: [
          '# Management Review Meeting — Minutes, 2026 Q2',
          '',
          '**Organisation** PT Cakrawala Bumi Estetika · **Date** 14 July 2026, 09:00–11:20 WIB',
          '**Chair** Aris Ihwan · **Secretary** Dhiaz Fathra (Management Representative)',
          '**Present** Aris Ihwan, Dhiaz Fathra, Pak Andre, Pak Chen, Pak Rila, Andreas, Rica',
          '**Apologies** none · **Scope** ISO/IEC 27001:2022 and ISO 9001:2015, combined review',
          '',
          '## 1. Status of actions from the previous review',
          '',
          '| Action | Owner | Status |',
          '| --- | --- | --- |',
          '| Close A.8.10 deletion policy gap | Dhiaz Fathra | Closed — policy v1.1 approved 7 April |',
          '| Quarterly rehearsal of Zitadel key rotation | Randy | Closed — first rehearsal 30 June |',
          '| Supplier review for the Nutanix migration partner | Pak Chen | Open — due 30 September |',
          '',
          '## 2. Changes in internal and external issues',
          '',
          'Two new clinic locations opened in the quarter, bringing the group to 13. PDP Law',
          'enforcement guidance was issued in May; TRD-SEC-002 was revised on 16 June in response.',
          'The Nutanix migration and the marketplace move from Strapi remain the two largest',
          'changes in flight.',
          '',
          '## 3. Performance of the ISMS and QMS',
          '',
          '- **Nonconformities and corrective action.** Three raised, three closed. None repeated.',
          '- **Monitoring and measurement.** Delivery metrics workbook 2026 Q2 presented: change',
          '  failure rate down to 11%, time to restore down to 47 minutes.',
          '- **Audit results.** Internal audit of Annex A.8 completed in May; two observations, no',
          '  major nonconformity.',
          '- **Interested parties.** No patient complaint escalated to the group in the quarter.',
          '- **Risk treatment.** Risk register reviewed; the erasure acknowledgement gap remains',
          '  the highest residual risk and stays under monthly review.',
          '',
          '## 4. Adequacy of resources',
          '',
          'The engineering team stands at 13. The chair noted that the ERP replatform, the Super',
          'App and the Nutanix migration are running concurrently against one team, and asked the',
          'Management Representative to bring a sequencing proposal to Q3 rather than add scope.',
          '',
          '## 5. Opportunities for improvement',
          '',
          '1. Automate the erasure acknowledgement reconciliation, currently a monthly manual check.',
          '2. Extend the internal review agent to check the data-map declaration on every service.',
          '3. Bring supplier reviews onto the same quarterly cycle as this meeting.',
          '',
          '## 6. Decisions',
          '',
          '| Decision | Owner | Due |',
          '| --- | --- | --- |',
          '| ISMS and QMS remain suitable, adequate and effective; scope unchanged | Aris Ihwan | — |',
          '| Sequencing proposal for the three concurrent programmes | Dhiaz Fathra | 2026-09-30 |',
          '| Erasure acknowledgement reconciliation automated | Randy | 2026-10-31 |',
          '| Supplier review cycle aligned to this meeting | Pak Chen | 2026-09-30 |',
          '',
          '## 7. Next review',
          '',
          '13 October 2026.',
          '',
          '_Signed_ Aris Ihwan, Director — 15 July 2026',
        ].join('\n'),
      },
    ],
    body: [
      '# Management Review Meeting — Procedure, Agenda and Minutes Template',
      '',
      '**Owner** Dhiaz Fathra (Management Representative) · **Approver** Aris Ihwan · **Version** v2.1',
      '**Requirement** ISO/IEC 27001:2022 9.3 · **Also satisfies** ISO 9001:2015 9.3, 9.1.1',
      '',
      '## 1. Purpose',
      '',
      'Top management reviews the ISMS and the QMS at planned intervals to confirm they remain',
      'suitable, adequate and effective. This procedure states who attends, what is put in front',
      'of them, and what the meeting must produce.',
      '',
      '## 2. Frequency and participants',
      '',
      'Quarterly, and additionally after any P1 incident involving personal data. Chaired by the',
      'Director (Aris Ihwan). Standing attendees: the Management Representative, department heads',
      '(Pak Andre, Pak Chen, Pak Rila), solutions architecture (Andreas) and the controller',
      'representative (Rica). The ISMS and QMS reviews are held as one meeting with one minute',
      'set — the inputs overlap and holding them apart produced two versions of the same facts.',
      '',
      '## 3. Inputs (27001 9.3.2 / 9001 9.3.2)',
      '',
      '1. Status of actions from previous reviews.',
      '2. Changes in internal and external issues relevant to the ISMS and QMS.',
      '3. Changes in the needs and expectations of interested parties.',
      '4. Feedback on performance: nonconformities and corrective actions, monitoring and',
      '   measurement results, audit results, fulfilment of objectives.',
      '5. Feedback from interested parties, including patient complaints.',
      '6. Results of risk assessment and the status of the risk treatment plan.',
      '7. Adequacy of resources.',
      '8. Opportunities for continual improvement.',
      '',
      'Each input has a named owner who brings it. An input arriving verbally without a document',
      'is minuted as not provided.',
      '',
      '## 4. Outputs (9.3.3)',
      '',
      'Decisions on continual improvement opportunities and on any change needed to the ISMS or',
      'QMS. **A decision is minuted only if it names an owner and a date.** Anything without both',
      'is a discussion, and is minuted as one.',
      '',
      '## 5. Minutes',
      '',
      'The Management Representative circulates minutes within five working days on FRM-MRM-01.',
      'The chair signs them. Signed minutes are retained for three years and filed against this',
      'procedure as the evidence that clause 9.3 is met.',
      '',
      '## 6. Agenda template',
      '',
      '```',
      '1. Attendance, apologies, scope of review',
      '2. Actions from the previous review',
      '3. Changes in internal/external issues and interested parties',
      '4. Performance: nonconformities, measurement, audit results, objectives',
      '5. Risk assessment and treatment status',
      '6. Adequacy of resources',
      '7. Opportunities for improvement',
      '8. Decisions (owner and date each)',
      '9. Date of next review',
      '```',
    ].join('\n'),
  },
]
