import type { SeedDocument } from './types'

/**
 * ISO 9001:2015 sub-clauses 8.2.1–8.2.4 and 8.3.1–8.3.6.
 *
 * The parent clauses 8.2 and 8.3 are already carried by QMS-SOP-8-2 and
 * QMS-SOP-8-3 in `qms-operation-a.ts`. These documents sit underneath those
 * two: each takes one sub-clause obligation and says how it is actually
 * discharged, rather than restating the parent procedure.
 */
export const QMS_SUBCLAUSES_8: SeedDocument[] = [
  {
    code: 'QMS-SOP-8-2-1',
    title: 'Customer Communication',
    clause: '8.2.1',
    crossRefs: ['9001 8.2', '9001 8.2.4', '9001 9.1.2', '9001 8.7', 'A.5.34'],
    version: 'v2.1',
    owner: 'Wiwin',
    form: { code: 'FRM-8-2-1-01', name: 'Customer communication and enquiry log' },
    revisions: [
      {
        version: 'v1.6',
        date: '2024-11-18',
        author: 'Wiwin',
        approval: 'Reviewed by Pak Andre',
        status: 'Superseded',
        note: 'Each clinic ran its own WhatsApp number; no single record of what a patient had been told before arrival.',
      },
      {
        version: 'v2.0',
        date: '2025-08-14',
        author: 'Wiwin',
        approval: 'Reviewed by Pak Andre',
        status: 'Superseded',
        note: 'Enquiries consolidated onto the group WhatsApp Business number and the Super App inbox; response targets set but not yet measured.',
      },
      {
        version: 'v2.1',
        date: '2026-03-09',
        author: 'Wiwin',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Response targets now measured per channel and reported monthly; added the contingency-communication rule for device downtime and the rule that clinical answers are never given by the front desk.',
      },
    ],
    evidence: [
      {
        name: 'qms-8-2-1-communication-log-2026-q2.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-07-06',
        expiryDate: '2027-07-06',
        uploader: 'Wiwin',
        note: 'Channel performance against target for the second quarter of 2026, with the two breached weeks explained.',
        body: [
          'Channel | Volume Q2 2026 | Target first response | Median | Within target | Breached weeks | Note',
          'WhatsApp Business (group number) | 14,382 | 15 minutes, 08:00–21:00 WIB | 6 min | 96.4% | W19, W23 | W19 Lebaran cover short by two agents; W23 outage of the inbox bridge for 4h',
          'Super App in-app inbox | 5,910 | 4 working hours | 51 min | 99.1% | none | Clinical questions auto-routed to a practitioner queue',
          'Instagram direct message | 3,144 | 4 working hours | 2h 10m | 92.8% | W19, W21 | Escalation to the clinic co-ordinator added 2026-06-01',
          'Telephone, per clinic | 8,207 | answered within 5 rings | n/a | 88.0% | W17–W23 | Rings-to-answer measured only at 9 of 13 clinics; instrumentation gap logged',
          'E-mail (info@) | 612 | 1 working day | 3h 40m | 99.5% | none | Mostly corporate and partner enquiries',
          'Aftercare follow-up outbound | 4,455 | H+1 and H+7 after session | H+1 | 97.2% | W22 | 124 missed at Bali Seminyak, all contacted by H+3',
        ].join('\n'),
      },
      {
        name: 'qms-8-2-1-downtime-notice-2026-06-11.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-06-12',
        uploader: 'Pak Andre',
        note: 'Notice issued to affected patients when the Kelapa Gading laser was withdrawn for unscheduled service.',
        body: [
          '# Notice to booked patients — Kelapa Gading, 11–14 June 2026',
          '',
          'Issued 11 June 2026, 07:40 WIB, by the clinic co-ordinator on the group WhatsApp number.',
          '',
          'The laser platform at Kelapa Gading is withdrawn from use pending a service visit after a',
          'calibration check on 10 June returned a fluence reading outside the vendor tolerance. No',
          'treatment has been given with the device since that reading.',
          '',
          '148 booked sessions between 11 and 14 June were affected. Each patient was contacted once by',
          'WhatsApp and, where no reply was received within four hours, once by telephone. Of those,',
          '111 rebooked at Kelapa Gading for the following week, 24 transferred to Pondok Indah, and',
          '13 asked for a refund, all paid within three working days.',
          '',
          'No patient was told a return date until the vendor confirmed one on 12 June. Practitioners,',
          'not the front desk, answered the eleven questions raised about whether previous sessions',
          'were affected; the calibration record for the preceding six weeks was reviewed and was',
          'within tolerance.',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-8-2-1 · Customer Communication',
      '',
      '**Owner** Wiwin · **Approver** Aris Ihwan · **Version** v2.1 · **Review** half-yearly',
      '**Requirement** ISO 9001 8.2.1 · **Also satisfies** 9001 8.2, 9001 8.2.4, 9001 9.1.2, 9001 8.7, A.5.34',
      '',
      '## Purpose',
      '',
      'Most of what a patient believes about their treatment was said to them before they sat in the',
      'chair — in a WhatsApp reply, an Instagram message, or a price quoted at the desk. This',
      'procedure states what the organisation communicates to patients and corporate customers, on',
      'which channels, how quickly, and who is allowed to answer what. It sits under QMS-SOP-8-2,',
      'which governs the agreement itself; this document governs everything said around it.',
      '',
      '## Scope',
      '',
      'All 13 clinics and every inbound and outbound channel the group operates: the group WhatsApp',
      'Business number, the Super App in-app inbox, Instagram direct messages, clinic telephone',
      'lines, info@ e-mail, and outbound aftercare follow-up. Marketing campaign content is out of',
      'scope until it makes a claim about an outcome, a price or a risk, at which point clause 4',
      'below applies. Clinical advice itself follows the treatment protocol.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Wiwin** owns this procedure, the channel list, the response targets and the monthly report.',
      '- **Pak Andre** owns what may be said about a treatment; any answer that touches',
      '  contraindications, expected outcome or adverse effects is answered by a practitioner.',
      '- The **clinic co-ordinator** at each location owns contingency communication when a device,',
      '  a practitioner or a room becomes unavailable.',
      '- **Rica** approves any change that alters what personal data is collected in a channel, and',
      '  holds the retention rule for message history.',
      '- **Dhiaz Fathra** owns the inbox bridge and the app messaging service and reports channel',
      '  availability alongside the rest of the platform.',
      '',
      '## Procedure',
      '',
      '1. **One record.** Every enquiry, whichever channel it arrives on, lands in the communication',
      '   log FRM-8-2-1-01 against the patient record where one exists. A conversation held on a',
      '   personal staff device is a nonconformity, not a shortcut.',
      '2. **Response targets.** First response within 15 minutes on WhatsApp between 08:00 and 21:00',
      '   WIB, four working hours on the app inbox and Instagram, one working day on e-mail, five',
      '   rings on a clinic telephone. Targets are measured per channel and reported monthly by',
      '   Wiwin; a channel missing target for two consecutive months goes to management review with a',
      '   named cause.',
      '3. **Who answers what.** Price, availability, location and booking are answered by the front',
      '   desk or the agent. Suitability, contraindications, expected results, side effects and',
      '   anything about a treatment already given are routed to the practitioner queue and answered',
      '   by a practitioner. Agents do not paraphrase a clinical answer.',
      '4. **Claims.** Any outcome, price or risk stated in a channel must match the current treatment',
      '   catalogue version and the protocol aftercare card. Wiwin publishes the approved wording;',
      '   nothing beyond it is offered, and a promotion is quoted with its expiry.',
      '5. **Contingency.** When a device, practitioner or room becomes unavailable, the clinic',
      '   co-ordinator contacts every affected booking within two hours by WhatsApp, and by telephone',
      '   where there is no reply within four hours. No return date is given until it is confirmed by',
      '   the party who controls it. Refunds requested are paid within three working days.',
      '6. **Feedback and complaints** are captured in the same log, tagged, and passed to the',
      '   satisfaction analysis under 9.1.2 and, where they concern a delivered treatment, to the',
      '   nonconformity register under 8.7.',
      '7. **Customer property.** Where a patient sends photographs or documents through a channel,',
      '   they are attached to the patient record and handled under the customer property register;',
      '   they are never retained in the channel alone.',
      '',
      '## Records',
      '',
      'The communication log is retained for six years. Message content that forms part of the',
      'clinical record is retained with that record for ten years after the last treatment. Channel',
      'performance is reported monthly and held for three years.',
      '',
      '## Review',
      '',
      'Half-yearly by Wiwin with Pak Andre, and immediately after any complaint whose cause is',
      'something a patient was told outside the agreement.',
    ].join('\n'),
  },
  {
    code: 'QMS-SOP-8-2-2',
    title: 'Determining the Requirements for Treatments and Platform Services',
    clause: '8.2.2',
    crossRefs: ['9001 8.2', '9001 8.2.3', '9001 8.3.3', '9001 7.1.5', 'A.5.31'],
    version: 'v1.5',
    owner: 'Pak Andre',
    form: {
      code: 'FRM-8-2-2-01',
      name: 'Service requirement definition sheet (statutory, clinical, stated)',
    },
    revisions: [
      {
        version: 'v1.3',
        date: '2025-02-24',
        author: 'Pak Andre',
        approval: 'Reviewed by Aris Ihwan',
        status: 'Superseded',
        note: 'Requirement definition existed only for new treatments; platform services were specified in tickets and nowhere else.',
      },
      {
        version: 'v1.5',
        date: '2026-02-16',
        author: 'Pak Andre',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'One definition sheet for treatments and platform services; added the explicit claim-capability test and the PDP Law and Kemenkes licensing rows.',
      },
    ],
    evidence: [
      {
        name: 'qms-8-2-2-requirement-definition-microneedling-2026.docx',
        fileType: 'DOCX',
        uploadedAt: '2026-02-20',
        expiryDate: '2027-02-20',
        uploader: 'Pak Andre',
        note: 'Completed definition sheet for the RF microneedling service before it entered design.',
        body: [
          '# Service requirement definition — radiofrequency microneedling',
          '',
          'Completed 12 February 2026 by Pak Andre with Wiwin and Tika. Reference FRM-8-2-2-01/2026-004.',
          '',
          'Requirement source | Requirement | Evidence it can be met | Verdict',
          'Statutory — Kemenkes | Performed by a licensed practitioner in a licensed facility | 11 of 13 clinics hold the class; Bintaro and Bali Seminyak do not | Launch limited to 11 clinics',
          'Statutory — device | Device registered with Kemenkes (AKL number held) | AKL 20401811234 on file, valid to 2029 | Met',
          'Statutory — PDP Law | Explicit consent for before/after photographs, separable from treatment consent | Consent service supports a separate purpose flag | Met, screen change required',
          'Clinical | Maximum needle depth 2.5 mm for facial use per vendor specification | Protocol drafted at 0.5–2.0 mm | Met',
          'Clinical | Practitioner completed vendor certification before first session | 24 practitioners certified; 9 outstanding | Met at launch clinics only',
          'Stated by patient | Visible texture improvement within 3 sessions | Vendor data and pilot to confirm; not to be promised in marketing | Claim restricted',
          'Stated by patient | Downtime under 48 hours | Typical 24–72 hours; stated as a range on the aftercare card | Claim corrected',
          'Organisational | Booked and recorded in the Super App like every other treatment | Catalogue entry and session template required | Met, backlog item DERM-4471',
          '',
          'Outcome: requirement set accepted as complete and non-contradictory; released to design under',
          'QMS-SOP-8-3-3 on 16 February 2026 with two constraints — 11 clinics only, and no',
          '"results in 3 sessions" claim in any channel.',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-8-2-2 · Determining the Requirements for Treatments and Platform Services',
      '',
      '**Owner** Pak Andre · **Approver** Aris Ihwan · **Version** v1.5 · **Review** annual',
      '**Requirement** ISO 9001 8.2.2 · **Also satisfies** 9001 8.2, 9001 8.2.3, 9001 8.3.3, 9001 7.1.5, A.5.31',
      '',
      '## Purpose',
      '',
      'Before the organisation offers anything to a patient it has to know what that offer actually',
      'commits it to: what the law requires, what the device vendor permits, what the patient will',
      'reasonably expect from the way it is described, and whether the group can do all three at',
      'every clinic where it is sold. This procedure produces that statement, in writing, before an',
      'offer exists. QMS-SOP-8-2-3 reviews it; this document creates it.',
      '',
      '## Scope',
      '',
      'Every new treatment, every material change to an existing treatment, every device introduced',
      'to a clinic, and every platform service offered to patients or corporate customers — booking,',
      'consent, the patient record, membership, billing and the partner marketplace. It does not',
      'cover internal engineering tooling that no customer relies on.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Pak Andre** owns this procedure and signs the definition sheet for clinical services.',
      '- **Wiwin** states the requirements implied by how the service will be sold and priced, and',
      '  is accountable for the claim wording that follows from clause 5.',
      '- **Dhiaz Fathra** signs the sheet for platform services and states the technical constraints.',
      '- **Rica** states the statutory data-protection requirement and whether consent as designed',
      '  satisfies the PDP Law.',
      '- **Tika** states how each requirement will be measured once the service is live.',
      '- **Pak Chen** confirms that consumables and device registration are obtainable and licensed.',
      '',
      '## Procedure',
      '',
      '1. **Open a definition sheet** FRM-8-2-2-01 before any design work begins. No sheet, no design',
      '   gate — QMS-SOP-8-3-3 will not accept inputs without one.',
      '2. **Record requirements by source**, each on its own row: statutory and regulatory (Kemenkes',
      '   facility class, device AKL registration, PDP Law, BPOM where a product is supplied),',
      '   clinical and vendor constraints, requirements stated by the patient or corporate customer,',
      '   requirements not stated but necessary for the intended use, and requirements the',
      '   organisation adds itself.',
      '3. **Test each requirement for capability.** Against each row, name the evidence that the group',
      '   can meet it — the licence held, the certification count, the device on site, the service',
      '   that already exists. A requirement with no evidence is either met before launch or the',
      '   offer is narrowed.',
      '4. **Narrow rather than promise.** Where capability exists at some clinics only, the service',
      '   launches at those clinics and the catalogue is restricted accordingly. The group does not',
      '   sell at a location it cannot deliver at.',
      '5. **Restrict claims to what can be demonstrated.** Any outcome the organisation cannot show',
      '   evidence for is struck from the sheet and may not appear in the catalogue, the consultation',
      '   flow or any channel governed by QMS-SOP-8-2-1. Ranges are stated as ranges.',
      '6. **State the measure.** Every accepted requirement carries the measure Tika will report',
      '   against once live, so that 9.1.1 monitoring is decided here and not invented afterwards.',
      '7. **Close the sheet** with a verdict per row and an overall outcome — accepted, accepted with',
      '   constraints, or rejected — signed by the owner and by Aris Ihwan where a constraint limits',
      '   where or how the service may be sold.',
      '',
      '## Records',
      '',
      'Definition sheets are held per service in the QMS library for the life of the service plus',
      'three years and are attached to the design input record at gate 1. Rejected sheets are kept;',
      'they are the record of what the organisation decided not to offer, and why.',
      '',
      '## Review',
      '',
      'Annually by Pak Andre with Wiwin and Rica, and whenever a regulator changes a licensing or',
      'data-protection obligation that appears as a row on a live sheet.',
    ].join('\n'),
  },
  {
    code: 'QMS-SOP-8-2-3',
    title: 'Review of Requirements Before Committing to Treat or to Deliver',
    clause: '8.2.3',
    crossRefs: ['9001 8.2.2', '9001 8.2.4', '9001 8.1', '9001 8.5.1', 'A.5.34'],
    version: 'v2.0',
    owner: 'Pak Andre',
    form: { code: 'FRM-8-2-3-01', name: 'Pre-commitment requirement review record' },
    revisions: [
      {
        version: 'v1.4',
        date: '2024-08-05',
        author: 'Wiwin',
        approval: 'Reviewed by Pak Andre',
        status: 'Superseded',
        note: 'Review was a verbal check at the desk; only the signed agreement survived, so a refusal left no record.',
      },
      {
        version: 'v1.9',
        date: '2025-11-27',
        author: 'Pak Andre',
        approval: 'Reviewed by Aris Ihwan',
        status: 'Superseded',
        note: 'Review record created in the Super App, but corporate and marketplace commitments still reviewed by e-mail.',
      },
      {
        version: 'v2.0',
        date: '2026-04-14',
        author: 'Pak Andre',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'One review record for clinic, app and corporate commitments; refusals and reductions now recorded with a reason code and reported monthly.',
      },
    ],
    evidence: [
      {
        name: 'qms-8-2-3-review-outcomes-2026-h1.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-07-08',
        expiryDate: '2027-07-08',
        uploader: 'Tika',
        note: 'Outcome of pre-commitment reviews for the first half of 2026, including every refusal and reduction.',
        body: [
          'Reason code | Meaning | Cases H1 2026 | Outcome | Owner',
          'R-01 | Contraindication found at screening | 412 | Treatment refused or deferred; alternative offered in 366 cases | Practitioner',
          'R-02 | Practitioner not certified for the protocol at that clinic | 87 | Rebooked at a clinic with a certified practitioner | Clinic co-ordinator',
          'R-03 | Device unavailable within the required session interval | 54 | Booked at another location or interval extended with patient agreement | Clinic co-ordinator',
          'R-04 | Consumable batch cover short for the full course | 19 | Course start deferred a median of 9 days | Pak Chen',
          'R-05 | Requested outcome not achievable by the requested treatment | 233 | Alternative plan proposed; 141 accepted, 92 declined | Practitioner',
          'R-06 | Price quoted differs from live catalogue | 26 | Quoted price honoured for 7 days; catalogue corrected in 6 cases | Wiwin',
          'R-07 | Corporate commitment exceeds clinic capacity in the requested window | 4 | Window renegotiated; 1 declined outright (PT Nusantara Sehat, 300 screenings in 5 days) | Pak Andre',
          'R-08 | Consent could not be taken lawfully (minor without guardian) | 11 | Treatment refused; guardian consent obtained later in 7 cases | Rica',
          'Total commitments reviewed | | 61,048 | 99.0% proceeded as requested | Tika',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-8-2-3 · Review of Requirements Before Committing to Treat or to Deliver',
      '',
      '**Owner** Pak Andre · **Approver** Aris Ihwan · **Version** v2.0 · **Review** half-yearly',
      '**Requirement** ISO 9001 8.2.3 · **Also satisfies** 9001 8.2.2, 9001 8.2.4, 9001 8.1, 9001 8.5.1, A.5.34',
      '',
      '## Purpose',
      '',
      'A commitment is made the moment a patient is told yes. This procedure is the check performed',
      'immediately before that word, at three levels: can this treatment do what this patient is',
      'asking for, can this clinic deliver it on the dates offered, and may the organisation lawfully',
      'agree to it. It applies to the individual booking, which is where QMS-SOP-8-2-2 stops.',
      '',
      '## Scope',
      '',
      'Every treatment agreement signed in a clinic or in the Super App, every course of sessions,',
      'every corporate or marketplace commitment, and every change to a live agreement referred here',
      'by QMS-SOP-8-2-4. It covers commitments only; delivery is governed under 8.5.1.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Pak Andre** owns this procedure and reviews corporate commitments above 50 bookings.',
      '- The **treating practitioner** performs the clinical part of the review and is the only person',
      '  who may say that a requested outcome is or is not achievable.',
      '- The **clinic co-ordinator** confirms capacity — room, device, certified practitioner and',
      '  consumable cover for the whole course, not only the first session.',
      '- **Wiwin** confirms the price against the pinned catalogue version and owns reason code R-06.',
      '- **Rica** is consulted where consent cannot be taken in the ordinary way.',
      '- **Tika** reports the review outcomes monthly and takes repeated codes to management review.',
      '',
      '## Procedure',
      '',
      '1. **Review before payment.** The review is completed and recorded on FRM-8-2-3-01 before any',
      '   payment is taken and before the agreement is signed. The app blocks signature until every',
      '   review question is answered.',
      '2. **Clinical fitness.** The practitioner screens against the protocol and states whether the',
      '   outcome the patient described is achievable by the proposed treatment in the proposed number',
      '   of sessions. Where it is not, an alternative is proposed in writing; the original request is',
      '   not quietly reinterpreted.',
      '3. **Capacity.** The co-ordinator confirms a certified practitioner, an available device and',
      '   room at the required interval, and consumable batch cover for the full course. A course is',
      '   not started when cover exists only for the first session.',
      '4. **Commercial.** Price is taken from the pinned catalogue version. Where a quote already',
      '   given differs, the quote is honoured for seven days and the discrepancy is raised with',
      '   Wiwin the same day.',
      '5. **Lawfulness.** Consent must be obtainable from the person who may give it. A minor is not',
      '   treated without a guardian present; where identity or capacity is in doubt the commitment is',
      '   refused pending Rica.',
      '6. **Record the answer, including no.** Every review closes with a reason code. Refusals and',
      '   reductions are recorded exactly as they happened; a refusal recorded as a cancellation is',
      '   treated as a falsified record.',
      '7. **Corporate commitments** above 50 bookings, or any commitment that fixes a delivery window',
      '   across more than one clinic, are reviewed by Pak Andre against the operational plan under',
      '   8.1 before acceptance, and the accepted window is written into the agreement.',
      '8. **Verbal enquiries** that end without an agreement still produce a record where a clinical',
      '   refusal was given, so that the same patient is not offered the treatment elsewhere in the',
      '   group the following week.',
      '',
      '## Records',
      '',
      'Review records are held with the patient record for ten years after the last treatment.',
      'Corporate review records are held with the contract for six years after it ends. The reason',
      'code summary is published monthly and retained for three years.',
      '',
      '## Review',
      '',
      'Half-yearly by Pak Andre with Tika, and immediately where any single reason code exceeds five',
      'per cent of commitments reviewed in a month.',
    ].join('\n'),
  },
  {
    code: 'QMS-SOP-8-2-4',
    title: 'Changes to Agreed Requirements for Treatments and Services',
    clause: '8.2.4',
    crossRefs: ['9001 8.2.3', '9001 8.2.1', '9001 8.5.6', '9001 8.7', 'A.5.34'],
    version: 'v1.3',
    owner: 'Wiwin',
    form: { code: 'FRM-8-2-4-01', name: 'Change of agreed requirement record' },
    revisions: [
      {
        version: 'v1.1',
        date: '2025-01-30',
        author: 'Wiwin',
        approval: 'Reviewed by Pak Andre',
        status: 'Superseded',
        note: 'Changes handled as an annotation on the original agreement; no re-signature and no record of who authorised the change.',
      },
      {
        version: 'v1.3',
        date: '2026-05-06',
        author: 'Wiwin',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Change record made a distinct document with re-signature, and the amended-information sweep added for catalogue, price and protocol changes affecting live courses.',
      },
    ],
    evidence: [
      {
        name: 'qms-8-2-4-change-record-2026-05-19.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-05-20',
        uploader: 'Pak Andre',
        note: 'Change record for the course reduction agreed with a patient at Pondok Indah after an unexpected skin response.',
        body: [
          '# Change of agreed requirement — agreement AGR-2026-018842',
          '',
          '**Clinic** Pondok Indah · **Original agreement** 2026-03-04 · **Change agreed** 2026-05-19',
          '',
          'Original commitment: laser hair removal, axilla, 6 sessions at 4-week intervals,',
          'IDR 7,200,000, catalogue version CAT-2026-03.',
          '',
          'Change: reduced to 4 sessions. Reason: hair reduction assessed at session 3 as already',
          'exceeding the target, and a grade-1 erythema at session 3 that resolved in 36 hours. The',
          'treating practitioner judged two further sessions unnecessary.',
          '',
          'Effect on price: IDR 2,400,000 refunded to the original payment method, paid 2026-05-21,',
          'reference REF-2026-00913.',
          '',
          'Amended information issued: revised aftercare card, revised session schedule in the Super',
          'App, and a WhatsApp confirmation of the refund. Patient re-signed the amended agreement in',
          'the app at 14:12 WIB on 2026-05-19 before leaving the clinic.',
          '',
          'Authorised by the treating practitioner; countersigned by Pak Andre because the change',
          'reduced a paid course. No further sessions were delivered between the decision and the',
          're-signature.',
        ].join('\n'),
      },
      {
        name: 'qms-8-2-4-amended-information-sweep-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-30',
        expiryDate: '2027-06-30',
        uploader: 'Wiwin',
        note: 'Sweeps run in 2026 where a catalogue, price or protocol change affected agreements already signed.',
        body: [
          'Date | Change | Live agreements affected | Action | Completed',
          '2026-02-09 | Price increase, hydrafacial course | 318 | Existing agreements honoured at the signed price to completion | 2026-02-09',
          '2026-04-02 | Catalogue version pinning released | 1,204 | No patient impact; historic quotes back-filled with the version in force | 2026-04-05',
          '2026-06-01 | Revised laser hair removal parameters | 962 | Aftercare card reissued to all in-course patients; 41 asked to re-consent, all completed | 2026-06-14',
          '2026-06-11 | Kelapa Gading device withdrawn | 148 | Schedules amended and re-signed, or refunded | 2026-06-16',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-8-2-4 · Changes to Agreed Requirements for Treatments and Services',
      '',
      '**Owner** Wiwin · **Approver** Aris Ihwan · **Version** v1.3 · **Review** half-yearly',
      '**Requirement** ISO 9001 8.2.4 · **Also satisfies** 9001 8.2.3, 9001 8.2.1, 9001 8.5.6, 9001 8.7, A.5.34',
      '',
      '## Purpose',
      '',
      'Agreements change. A course is shortened because the skin responded faster than expected, a',
      'device is withdrawn, a protocol is revised while 900 patients are mid-course. This procedure',
      'states how an agreed requirement is changed, who may authorise it, and how everyone who needs',
      'to know is told — including the people inside the organisation who are about to deliver',
      'against the old version.',
      '',
      '## Scope',
      '',
      'Any change to a signed treatment agreement — treatment, session count, interval, price,',
      'clinic or practitioner — and any organisational change (catalogue, price, protocol, device,',
      'platform behaviour) that affects agreements already signed. Changes to the delivery process',
      'that do not alter what was agreed follow 8.5.6 instead.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Wiwin** owns this procedure and runs the amended-information sweep for catalogue and price',
      '  changes.',
      '- The **treating practitioner** authorises any clinical change and is the only person who may',
      '  reduce or extend a course on clinical grounds.',
      '- **Pak Andre** countersigns any change that reduces a paid course or alters price after',
      '  payment, and authorises protocol-driven changes across live courses.',
      '- **Dhiaz Fathra** ensures the platform holds change as a distinct record rather than',
      '  overwriting the original agreement.',
      '- **Rica** decides whether a change requires fresh consent rather than notification.',
      '',
      '## Procedure',
      '',
      '1. **A change is a new record**, FRM-8-2-4-01, referencing the original agreement. The original',
      '   is never edited; the two are read together and both are retained.',
      '2. **Authorise before delivering.** No session is delivered under changed terms until the',
      '   change is authorised and re-signed. Where a patient is in the chair, the change is agreed',
      '   and signed in the app before treatment continues.',
      '3. **State the reason in the record** in plain language — clinical judgement, device',
      '   availability, patient request, protocol revision, pricing error — and name the person who',
      '   authorised it.',
      '4. **Money follows the same day it is decided.** A reduction refunds the unused balance within',
      '   three working days to the original payment method, with the reference recorded.',
      '5. **Amend the information the patient holds.** The revised schedule, aftercare card and price',
      '   are reissued through the channels in QMS-SOP-8-2-1, and the patient receives a copy of the',
      '   amended agreement within one hour of signature.',
      '6. **Organisational changes trigger a sweep.** When a catalogue, price, protocol or device',
      '   change affects live agreements, Wiwin identifies every affected agreement within one working',
      '   day and records the action taken for each. A price rise never applies to an agreement',
      '   already signed; that course completes at the price agreed.',
      '7. **Fresh consent, not just notice**, is required where a protocol change alters the risk',
      '   profile or the personal data used. Rica decides which applies, and the decision is recorded.',
      '8. **Changes forced by a failure** — a withdrawn device, a missed session, a practitioner',
      '   unavailable — are additionally logged as nonconformities under 8.7 so the cause is treated',
      '   and not only the appointment.',
      '',
      '## Records',
      '',
      'Change records are held with the original agreement for ten years after the last treatment.',
      'Sweep records are retained for six years and are a standing input to the half-yearly review of',
      'requirement handling.',
      '',
      '## Review',
      '',
      'Half-yearly by Wiwin with Pak Andre, and after any complaint about a change the patient says',
      'they did not agree to.',
    ].join('\n'),
  },
  {
    code: 'QMS-POL-8-3-1',
    title: 'Design and Development — General Provisions',
    clause: '8.3.1',
    crossRefs: ['9001 8.3', '9001 8.3.2', '9001 6.3', '9001 7.1.6', 'A.8.25'],
    version: 'v1.2',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-8-3-1-01', name: 'Design item register and applicability decision' },
    revisions: [
      {
        version: 'v1.0',
        date: '2025-03-11',
        author: 'Andreas',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Stated that design control applied to platform work; clinical protocol work was assumed to be covered elsewhere and was not.',
      },
      {
        version: 'v1.2',
        date: '2026-01-27',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Applicability test written down with worked examples, and the design item register made the single place where a decision to apply or not apply design control is recorded.',
      },
    ],
    evidence: [
      {
        name: 'qms-8-3-1-design-item-register-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-07-02',
        expiryDate: '2027-07-02',
        uploader: 'Andreas',
        note: 'Every candidate design item raised in 2026 with the applicability decision and who took it.',
        body: [
          'Item | Type | Design control applied | Reason | Decided by | Gate reached',
          'DI-2026-001 RF microneedling service | Clinical protocol | Yes | New treatment, new device class | Pak Andre | Gate 3 passed 2026-06-24',
          'DI-2026-002 Revised LHR parameters | Clinical protocol | Yes | Material change to an existing protocol | Pak Andre | Released 2026-06-01',
          'DI-2026-003 Consent service purpose flags | Platform | Yes | Changes how consent is captured and stored | Rica | Gate 3 passed 2026-03-27',
          'DI-2026-004 Catalogue version pinning | Platform | Yes | Alters what the patient is committed to | Dhiaz Fathra | Released 2026-04-02',
          'DI-2026-005 Super App visual refresh | Platform | No | Presentation only, no change to booking, consent or record | Dhiaz Fathra | n/a, ordinary change control',
          'DI-2026-006 Node runtime upgrade 20 to 22 | Platform | No | Dependency upgrade, no functional change | Andreas | n/a, ordinary change control',
          'DI-2026-007 New aftercare card wording | Clinical | Yes | Alters information the patient relies on after treatment | Pak Andre | Gate 2 open',
          'DI-2026-008 Partner marketplace payout schedule | Platform | Yes | New customer-facing commitment | Wiwin | Gate 1 closed 2026-08-11',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-POL-8-3-1 · Design and Development — General Provisions',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v1.2 · **Review** annual',
      '**Requirement** ISO 9001 8.3.1 · **Also satisfies** 9001 8.3, 9001 8.3.2, 9001 6.3, 9001 7.1.6, A.8.25',
      '',
      '## Purpose',
      '',
      'The most common design failure at Dermaster has never been a bad gate; it has been deciding,',
      'informally and after the fact, that a piece of work was not really design. This policy states',
      'when the design and development process in QMS-SOP-8-3 applies, when it does not, who decides,',
      'and where that decision is written down.',
      '',
      '## Scope',
      '',
      'All work that creates or materially changes something a patient or corporate customer relies',
      'on: treatment protocols, devices introduced to a clinic, aftercare information, and the',
      'platform services that book, consent, record, follow up and bill. It applies equally to',
      'clinical and engineering work; there is one process, not two.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Dhiaz Fathra** owns this policy and the design item register.',
      '- **Pak Andre** takes the applicability decision for clinical items.',
      '- **Andreas** maintains the register entries for platform items and links them to the ADRs.',
      '- **Rica** takes the decision where the item changes what personal data is collected or how',
      '  consent is obtained; her decision to apply design control cannot be overridden by a delivery',
      '  deadline.',
      '- **Aris Ihwan** is the only person who may record a decision not to apply design control to an',
      '  item that meets the test in clause 2.',
      '',
      '## Policy',
      '',
      '1. **Every candidate item is registered** on FRM-8-3-1-01 before work starts, whether or not',
      '   design control will apply. An item that never reached the register is treated as an',
      '   uncontrolled change at audit.',
      '2. **The applicability test.** Design control applies if the item does any of the following:',
      '   introduces or materially changes a treatment protocol or device; changes what the patient is',
      '   told, agrees to or consents to; changes how a clinical record is captured, stored or',
      '   retained; creates a new commitment to a customer; or alters a control relied on for patient',
      '   safety or data protection. If none apply, ordinary change control under 6.3 is enough.',
      '3. **Worked examples, so the test is not re-argued.** A visual refresh of the Super App is not',
      '   design. A runtime upgrade is not design. Changing the wording of an aftercare card is design,',
      '   because the patient acts on it. Adding a consent purpose flag is design. Pinning a quoted',
      '   price to a catalogue version is design, because it changes the commitment.',
      '4. **Extent proportionate to consequence.** The number of gates is fixed; the depth is not. A',
      '   protocol that touches skin at energy carries a full clinical review, a pilot at two clinics',
      '   and a quarter of outcome monitoring. A new booking screen carries a design review, automated',
      '   verification and one-clinic validation. Nothing skips a gate for being small.',
      '5. **Nature, duration and complexity are stated at registration** so the plan under 8.3.2 is',
      '   built against a declared expectation rather than an assumed one.',
      '6. **Ownership is a named person, not a team.** Every registered item has one owner accountable',
      '   for its gates from registration to post-release monitoring.',
      '7. **No parallel route.** Work that meets the test does not proceed under an engineering ticket',
      '   or a clinical trial-and-see; if it is in production and it met the test, it is a',
      '   nonconformity under 8.7 regardless of how well it turned out.',
      '',
      '## Records',
      '',
      'The design item register is held in the QMS library, retained for six years, and reviewed at',
      'every management review alongside the list of items where design control was not applied.',
      '',
      '## Review',
      '',
      'Annually by Dhiaz Fathra with Pak Andre, and whenever an item reaches production without a',
      'register entry.',
    ].join('\n'),
  },
  {
    code: 'QMS-SOP-8-3-2',
    title: 'Design and Development Planning',
    clause: '8.3.2',
    crossRefs: ['9001 8.3.1', '9001 8.3.4', '9001 7.1', '9001 8.4.1', 'A.8.25'],
    version: 'v1.4',
    owner: 'Andreas',
    form: { code: 'FRM-8-3-2-01', name: 'Design and development plan' },
    revisions: [
      {
        version: 'v1.2',
        date: '2025-06-19',
        author: 'Andreas',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Plans named stages and dates but not the people required at each gate, so gates were held with whoever was free.',
      },
      {
        version: 'v1.4',
        date: '2026-03-24',
        author: 'Andreas',
        approval: 'Approved by Dhiaz Fathra',
        status: 'Current',
        note: 'Plan now names required attendees per gate, the resources the item needs, the customer involvement point, and which external providers contribute.',
      },
    ],
    evidence: [
      {
        name: 'qms-8-3-2-plan-rf-microneedling-2026.docx',
        fileType: 'DOCX',
        uploadedAt: '2026-03-02',
        expiryDate: '2027-03-02',
        uploader: 'Andreas',
        note: 'Approved design and development plan for design item DI-2026-001.',
        body: [
          '# Design and development plan — DI-2026-001, RF microneedling service',
          '',
          '**Owner** Pak Andre · **Approved** 2 March 2026 by Dhiaz Fathra · Plan reference FRM-8-3-2-01/2026-007',
          '',
          'Stage | Dates | Required attendees | Output | Status',
          'Gate 1 inputs | 16–27 Feb 2026 | Pak Andre, Wiwin, Tika, Rica | Input record and definition sheet | Closed 27 Feb',
          'Protocol drafting | 2–27 Mar 2026 | Pak Andre, two lead practitioners | Draft parameter table and aftercare card | Closed 27 Mar',
          'Platform build (catalogue, session template, consent flag) | 9 Mar–17 Apr 2026 | Andreas, one backend engineer, Rica | Merged, tests green | Closed 15 Apr',
          'Gate 2 design review | 21 Apr 2026 | Dhiaz Fathra (chair), Pak Andre, Rica, 2 practitioners not on the drafting team | Review minute, dated actions | Closed 6 May, 4 actions',
          'Practitioner certification | 20 Apr–22 May 2026 | Vendor trainer, 24 practitioners | Certificates on file | Closed 22 May',
          'Pilot validation, Pondok Indah and Bandung Dago | 25 May–20 Jun 2026 | Tika, pilot practitioners | 80 sessions or 6 weeks, outcome and adverse-event data | Closed 20 Jun, 94 sessions',
          'Gate 3 verification and validation | 24 Jun 2026 | Aris Ihwan (chair), Pak Andre, Tika, Dhiaz Fathra | Release decision | Passed 24 Jun',
          'Post-release monitoring | Jul–Sep 2026 | Tika | Quarterly outcome report | Open',
          '',
          'Resources committed: vendor certification 42,000,000 IDR, two devices already on site at the',
          'pilot clinics, 0.6 FTE backend for six weeks, consumable stock for 120 pilot sessions.',
          '',
          'External providers contributing: device vendor (parameter specification and training) and',
          'the calibration vendor (pre-pilot verification of both devices). Both are on the approved',
          'provider register.',
          '',
          'Customer involvement: 18 existing patients recruited for the pilot with separate written',
          'consent, and patient-reported outcome collected at sessions 1, 3 and at H+30.',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-8-3-2 · Design and Development Planning',
      '',
      '**Owner** Andreas · **Approver** Dhiaz Fathra · **Version** v1.4 · **Review** annual',
      '**Requirement** ISO 9001 8.3.2 · **Also satisfies** 9001 8.3.1, 9001 8.3.4, 9001 7.1, 9001 8.4.1, A.8.25',
      '',
      '## Purpose',
      '',
      'A design plan at Dermaster exists to answer one question early: what has to be true, and who',
      'has to be in the room, for this item to reach patients safely. Gates without named attendees',
      'and committed resources are held with whoever is free that afternoon, which is how the 2025',
      'protocol work drifted. This procedure sets what a plan must state before work begins.',
      '',
      '## Scope',
      '',
      'Every item registered under QMS-POL-8-3-1 with design control applied, clinical and platform',
      'alike. A plan is required regardless of size; a small item has a short plan, not none.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Andreas** owns this procedure and the plan template.',
      '- The **design item owner** writes the plan and keeps it current.',
      '- **Dhiaz Fathra** approves plans for platform items and any plan committing engineering time.',
      '- **Pak Andre** approves plans for clinical items and nominates pilot clinics.',
      '- **Tika** states the validation measures and the sample size before the pilot is scheduled.',
      '- **Pak Rila** confirms budget where the plan commits spend above 25,000,000 IDR.',
      '',
      '## Procedure',
      '',
      '1. **Write the plan on FRM-8-3-2-01 before the first gate.** The gate-1 input record is not',
      '   accepted without an approved plan attached.',
      '2. **State the stages and the gates** with dates. The three gates in QMS-SOP-8-3 are fixed;',
      '   the plan adds the stages between them appropriate to the item.',
      '3. **Name the required attendees per gate**, by person, including the reviewers who are not',
      '   doing the work. A gate held without a required attendee is not held; it is rescheduled.',
      '4. **State the responsibilities and authorities**: who drafts, who reviews, who verifies, who',
      '   validates, who may approve release. One name each.',
      '5. **Commit the resources** the item needs — practitioner time for certification, engineering',
      '   FTE, device availability at the pilot clinics, consumable stock, vendor training cost — and',
      '   have them confirmed by the person who holds them before approval.',
      '6. **State how customers are involved.** For clinical items this is the pilot cohort and the',
      '   patient-reported outcome points; for platform items it is the clinic staff or corporate',
      '   customer who will use it. Involvement is scheduled, not improvised at the end.',
      '7. **Name the external providers** contributing to the design — device vendor, calibration',
      '   vendor, contract engineers — and confirm each is on the approved provider register under',
      '   8.4.1 before they contribute.',
      '8. **State the verification and validation activities** the item will need, so that gate 3 is',
      '   planned for rather than discovered. Where a pilot is required, state the clinics, the',
      '   duration and the minimum session count.',
      '9. **Keep the plan current.** A date, attendee or resource that changes is amended on the plan',
      '   with the reason; the plan at release must describe what actually happened.',
      '',
      '## Records',
      '',
      'Approved plans and their amendments are held per design item for the life of the item plus',
      'three years, alongside the gate records under QMS-SOP-8-3-4.',
      '',
      '## Review',
      '',
      'Annually by Andreas with Dhiaz Fathra, and after any item that missed a planned gate date by',
      'more than four weeks.',
    ].join('\n'),
  },
  {
    code: 'QMS-SOP-8-3-3',
    title: 'Design and Development Inputs',
    clause: '8.3.3',
    crossRefs: ['9001 8.3.2', '9001 8.2.2', '9001 8.3.5', '9001 8.7', 'A.5.31'],
    version: 'v2.0',
    owner: 'Pak Andre',
    form: { code: 'FRM-8-3-3-01', name: 'Design input record and contradiction resolution' },
    revisions: [
      {
        version: 'v1.5',
        date: '2024-10-22',
        author: 'Pak Andre',
        approval: 'Reviewed by Aris Ihwan',
        status: 'Superseded',
        note: 'Inputs captured as a paragraph of intent; failures from previous protocols were not required to be reviewed.',
      },
      {
        version: 'v2.0',
        date: '2026-02-16',
        author: 'Pak Andre',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Inputs itemised by source with a mandatory review of prior adverse events and incidents, and contradictions now resolved and recorded at gate 1 rather than during build.',
      },
    ],
    evidence: [
      {
        name: 'qms-8-3-3-input-record-rf-microneedling.md',
        fileType: 'MD',
        uploadedAt: '2026-02-27',
        expiryDate: '2027-02-27',
        uploader: 'Pak Andre',
        note: 'Gate 1 input record for DI-2026-001, including the two contradictions found and how they were resolved.',
        body: [
          '# Design input record — DI-2026-001, RF microneedling',
          '',
          'Closed at gate 1 on 27 February 2026. Present: Pak Andre, Wiwin, Tika, Rica, Andreas.',
          '',
          '## Functional and performance inputs',
          '',
          '- Needle depth 0.5–2.0 mm facial, 2.0–3.0 mm body; vendor ceiling 2.5 mm facial.',
          '- Energy level 1–5 on the vendor scale; level 5 restricted to Fitzpatrick I–III.',
          '- Session interval 4 weeks minimum; course of 3 to 4 sessions.',
          '- Booking, consent, session record and aftercare handled in the Super App as for other',
          '  treatments; no separate paper flow.',
          '',
          '## Statutory and regulatory inputs',
          '',
          '- Kemenkes facility class required; held at 11 of 13 clinics.',
          '- Device AKL 20401811234, valid to 2029.',
          '- PDP Law: photographic evidence requires separate explicit consent from treatment consent.',
          '',
          '## Inputs from previous experience',
          '',
          '- 2025 laser hair removal review: parameter tables transcribed by hand had two entries above',
          '  the vendor ceiling. Input added — parameter tables are imported from the vendor file and',
          '  checked line by line, never retyped.',
          '- 2025 Kelapa Gading calibration drift: input added — devices used for a new protocol are',
          '  verified within seven days before the pilot starts.',
          '',
          '## Contradictions found and resolved',
          '',
          '1. Marketing asked for a "results in 3 sessions" claim; the clinical input supports a range',
          '   of 3 to 4 with visible change typically after session 2. Resolved: the claim is struck,',
          '   the catalogue states a 3 to 4 session course. Decided by Pak Andre and Wiwin.',
          '2. The commercial input assumed launch at all 13 clinics; the statutory input restricts to',
          '   11. Resolved: launch at 11, with Bintaro and Bali Seminyak excluded from the catalogue',
          '   until the facility class is held. Decided by Aris Ihwan.',
          '',
          '## Out of scope',
          '',
          'Combination with laser in the same session; body treatment above 3.0 mm; sale through the',
          'partner marketplace. Each would re-enter design as a new item.',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-8-3-3 · Design and Development Inputs',
      '',
      '**Owner** Pak Andre · **Approver** Aris Ihwan · **Version** v2.0 · **Review** annual',
      '**Requirement** ISO 9001 8.3.3 · **Also satisfies** 9001 8.3.2, 9001 8.2.2, 9001 8.3.5, 9001 8.7, A.5.31',
      '',
      '## Purpose',
      '',
      'Every design failure the organisation has investigated since 2024 traces back to an input that',
      'was known to someone and written down by no one. This procedure sets what must be stated',
      'before work starts, in enough detail that the output can later be checked against it, and',
      'forces contradictions into the open at gate 1 rather than into a build argument in week six.',
      '',
      '## Scope',
      '',
      'Gate 1 of QMS-SOP-8-3 for every registered design item, clinical and platform. Inputs for a',
      'change to a released item are recorded against the original input record so a protocol has one',
      'continuous file.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Pak Andre** owns this procedure and chairs gate 1 for clinical items.',
      '- **Dhiaz Fathra** chairs gate 1 for platform items.',
      '- **Wiwin** supplies the commercial and catalogue inputs and the claim wording sought.',
      '- **Rica** supplies statutory data-protection inputs and may block closure of the gate where',
      '  consent as described would be unlawful.',
      '- **Tika** supplies the performance measures and the prior adverse-event and incident data.',
      '- **Pak Chen** supplies vendor specifications, device registration and consumable constraints.',
      '',
      '## Procedure',
      '',
      '1. **Record inputs on FRM-8-3-3-01 by source**, each itemised: functional and performance',
      '   requirements; statutory and regulatory requirements; applicable standards and vendor',
      "   specifications; the organisation's own codes of practice; and the potential consequences of",
      '   failure given the nature of the treatment or service.',
      '2. **Carry the definition sheet across.** The accepted rows of FRM-8-2-2-01 are attached and',
      '   become inputs; nothing agreed there is quietly dropped here.',
      '3. **Review previous experience — mandatory.** Tika presents adverse events, complaints and',
      '   incidents from comparable protocols or services over the preceding 24 months. Each one',
      '   either becomes an input or is recorded as considered and not applicable, with the reason.',
      '4. **State inputs so they can be verified.** "Safe for darker skin" is not an input; "energy',
      '   level 5 restricted to Fitzpatrick I–III" is. An input that cannot be checked at gate 3 is',
      '   rewritten until it can.',
      '5. **Resolve contradictions at the gate.** Conflicting inputs — commercial against clinical,',
      '   scope against licensing — are named in the record, resolved by the accountable person, and',
      '   the decision written down with who took it. The gate does not close while a contradiction',
      '   stands.',
      '6. **State what is out of scope**, explicitly. Anything listed there re-enters as a new design',
      '   item rather than arriving as a late addition.',
      '7. **Inputs are complete and unambiguous** before gate 1 closes. An input still marked "to be',
      '   confirmed" holds the gate open; work may not start against it.',
      '8. **Retain superseded inputs.** When an input changes after gate 1, the change is recorded',
      '   under QMS-SOP-8-3-6 and the original is kept, so the reason a parameter exists is still',
      '   readable three years later.',
      '',
      '## Records',
      '',
      'Input records are held per design item for the life of the protocol or service plus three',
      'years, and are attached to the gate 3 release decision.',
      '',
      '## Review',
      '',
      'Annually by Pak Andre with Tika, and after any adverse event traced to an input that was never',
      'stated.',
    ].join('\n'),
  },
  {
    code: 'QMS-SOP-8-3-4',
    title: 'Design and Development Controls — Review, Verification and Validation',
    clause: '8.3.4',
    crossRefs: ['9001 8.3.3', '9001 8.3.5', '9001 8.3.2', '9001 9.1.1', 'A.8.29'],
    version: 'v2.2',
    owner: 'Tika',
    form: { code: 'FRM-8-3-4-01', name: 'Design review, verification and validation record' },
    revisions: [
      {
        version: 'v2.0',
        date: '2025-04-15',
        author: 'Tika',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Verification and validation recorded on one sheet and often conflated; a passing test suite was accepted as validation.',
      },
      {
        version: 'v2.2',
        date: '2026-05-20',
        author: 'Tika',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Verification and validation separated with distinct acceptance criteria; pilot minimums set at two clinics and 80 sessions or six weeks, and reviewer independence made explicit.',
      },
    ],
    evidence: [
      {
        name: 'qms-8-3-4-verification-validation-di-2026-001.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-24',
        expiryDate: '2027-06-24',
        uploader: 'Tika',
        note: 'Gate 3 verification and validation evidence for the RF microneedling service.',
        body: [
          'Activity | Type | Criterion | Result | Verdict | Evidence',
          'Parameter table against vendor file | Verification | Every row within vendor ceiling | 41 rows checked, 1 corrected (body 3.2 mm to 3.0 mm) | Pass after correction | Diff attached, checked by 2nd practitioner',
          'Device calibration before pilot | Verification | Both pilot devices verified within 7 days of start | Pondok Indah 2026-05-21, Bandung Dago 2026-05-22 | Pass | Calibration register entries CR-2026-114/115',
          'Consent purpose flag | Verification | Photographic consent separable and revocable | 18 test cases, all pass | Pass | CI run 4471, Rica sign-off 2026-04-30',
          'Catalogue restriction to 11 clinics | Verification | Treatment not bookable at Bintaro or Bali Seminyak | 26 booking attempts, all blocked | Pass | Test evidence in DERM-4488',
          'Practitioner certification | Verification | 100% of pilot practitioners certified before first session | 6 of 6 | Pass | Certificates on file',
          'Pilot, 2 clinics | Validation | >= 80 sessions or 6 weeks | 94 sessions over 4 weeks | Pass | Session records 2026-05-25 to 2026-06-20',
          'Adverse events in pilot | Validation | No event above grade 1; grade 1 rate below 8% | 5 grade-1 erythema (5.3%), none above | Pass | Adverse event log AE-2026-06',
          'Patient-reported outcome at H+30 | Validation | Mean >= 4.0 of 5 | 4.3 of 5, n=71 | Pass | Outcome survey export',
          'Aftercare comprehension check | Validation | >= 90% of pilot patients recall the 48h rule | 88% at first pass | Fail, then pass | Card reworded 2026-06-15, re-checked 94%',
          'Booking to record round trip in the app | Validation | Completed by clinic staff without support ticket | 94 of 94 | Pass | Support queue nil for DI-2026-001',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-8-3-4 · Design and Development Controls — Review, Verification and Validation',
      '',
      '**Owner** Tika · **Approver** Aris Ihwan · **Version** v2.2 · **Review** annual',
      '**Requirement** ISO 9001 8.3.4 · **Also satisfies** 9001 8.3.3, 9001 8.3.5, 9001 8.3.2, 9001 9.1.1, A.8.29',
      '',
      '## Purpose',
      '',
      'Three different questions get asked about a design and they are routinely collapsed into one.',
      'Review asks whether the design will meet the inputs. Verification asks whether the output does',
      'meet the inputs. Validation asks whether it works for a real patient in a real clinic. A green',
      'test suite answers the second and says nothing about the third. This procedure keeps them',
      'apart, with separate criteria and separate records.',
      '',
      '## Scope',
      '',
      'Gates 2 and 3 of QMS-SOP-8-3 for every registered design item. Applies to clinical protocols',
      'and platform services, including changes to released items re-entering at gate 2.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Tika** owns this procedure, defines the validation criteria and reports the results.',
      '- **Dhiaz Fathra** chairs gate 2 for platform items; **Pak Andre** for clinical items.',
      '- **Reviewers must be independent of the work**: two lead practitioners who did not draft the',
      '  protocol, or a second engineer who did not write the change.',
      '- **Rica** is a required reviewer at gate 2 wherever personal data is involved.',
      '- **Aris Ihwan** approves release at gate 3 and is the only person who may accept a validation',
      '  result that missed a criterion.',
      '',
      '## Procedure',
      '',
      '1. **Design review at gate 2** examines the design against the gate 1 inputs, row by row.',
      '   Problems are recorded as dated, owned actions on FRM-8-3-4-01. The gate stays open until',
      '   every action is closed; an action cannot be closed by the person who raised it alone.',
      '2. **Verification at gate 3** shows the output meets each stated input. Clinical: parameter',
      '   tables imported from the vendor file and checked line by line by a second practitioner,',
      '   device calibration verified within seven days of the pilot start, certification counts',
      '   confirmed. Platform: automated tests and contract tests green, consent and accessibility',
      '   checks passed, restrictions demonstrated by attempted misuse rather than assumed.',
      '3. **Validation at gate 3** shows the output works in use. Every clinical protocol is piloted',
      '   at two clinics for at least six weeks or 80 sessions, whichever comes first. Every',
      '   clinic-facing platform change runs at one location before group rollout. Validation is done',
      '   with real patients under the real consent, never a simulation.',
      '4. **Acceptance criteria are set before the activity runs**, by Tika, and written into the plan.',
      '   A criterion invented after the result is a nonconformity.',
      '5. **A failed criterion is recorded as failed**, then corrected and re-run. The record keeps',
      '   both results; the aftercare comprehension failure on DI-2026-001 is the pattern.',
      '6. **Necessary actions are taken and closed before release.** Release with an open action',
      "   requires Aris Ihwan's written acceptance on the gate 3 minute, naming the residual risk and",
      '   the date the action will close.',
      '7. **Retain the evidence, not the conclusion.** The record holds the test output, the session',
      '   counts, the adverse-event log and the survey export — enough for an auditor to re-derive the',
      '   verdict without asking anyone.',
      '8. **Post-release, the same measures continue** for one full quarter under 9.1.1. A protocol',
      '   whose adverse-event rate exceeds the pilot rate is suspended by Pak Andre immediately.',
      '',
      '## Records',
      '',
      'Review, verification and validation records are held per design item for the life of the item',
      'plus three years, with the gate 3 minute and the release approval.',
      '',
      '## Review',
      '',
      'Annually by Tika with Dhiaz Fathra and Pak Andre, and after any release where a criterion was',
      'accepted as met on judgement rather than evidence.',
    ].join('\n'),
  },
  {
    code: 'QMS-SOP-8-3-5',
    title: 'Design and Development Outputs',
    clause: '8.3.5',
    crossRefs: ['9001 8.3.4', '9001 8.3.3', '9001 8.5.1', '9001 7.5.3', 'A.5.37'],
    version: 'v1.6',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-8-3-5-01', name: 'Design output pack and release checklist' },
    revisions: [
      {
        version: 'v1.4',
        date: '2025-09-30',
        author: 'Andreas',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Outputs listed for platform work only; a clinical protocol reached the clinics as a slide deck with no acceptance criteria attached.',
      },
      {
        version: 'v1.6',
        date: '2026-06-24',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'One output pack for both kinds of design item, with the monitoring and acceptance criteria and the aftercare information made mandatory contents before release.',
      },
    ],
    evidence: [
      {
        name: 'qms-8-3-5-output-pack-di-2026-001.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-06-26',
        expiryDate: '2027-06-26',
        uploader: 'Andreas',
        note: 'Signed output pack and release checklist issued to the 11 launch clinics.',
        body: [
          '# Design output pack — DI-2026-001, RF microneedling · released 24 June 2026',
          '',
          'Item | Reference | Issued to | Verified against input | Signed',
          'Treatment protocol, v1.0 | PROT-RFM-001 | 11 clinics, QMS library | Inputs 1–14 | Pak Andre',
          'Parameter table (imported from vendor file rev 4.2) | PROT-RFM-001-A | Practitioners | Vendor ceiling rows | Two practitioners, countersigned',
          'Contraindication screening set | PROT-RFM-001-B | Super App consultation flow | Statutory and clinical inputs | Pak Andre',
          'Aftercare card, ID and EN, v1.1 | AFT-RFM-001 | Clinics and patient app | Comprehension criterion 90%, achieved 94% | Pak Andre',
          'Catalogue entry, restricted to 11 clinics | CAT-2026-06 | Super App | Statutory input, licensing | Wiwin',
          'Session record template | APP-RFM-SESS | Super App | Record retention and traceability inputs | Dhiaz Fathra',
          'Consent text with separate photographic purpose | CON-RFM-001 | Consent service | PDP Law input | Rica',
          'Practitioner competence requirement and certificate list | TRN-RFM-001 | HR record, clinic managers | Certification input | Tika',
          'Monitoring and acceptance criteria for first quarter | MON-RFM-001 | Tika, management review | 9.1.1 measures | Tika',
          'Device verification requirement before first use at a new clinic | CAL-RFM-001 | Calibration register | Prior-experience input | Tika',
          '',
          'Release checklist: all ten outputs present, each traceable to a numbered gate 1 input; gate 3',
          'minute signed by Aris Ihwan 24 June 2026; no open actions at release. Outputs placed under',
          'document control the same day and indexed in the QMS library.',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-8-3-5 · Design and Development Outputs',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v1.6 · **Review** annual',
      '**Requirement** ISO 9001 8.3.5 · **Also satisfies** 9001 8.3.4, 9001 8.3.3, 9001 8.5.1, 9001 7.5.3, A.5.37',
      '',
      '## Purpose',
      '',
      'What leaves design is what the clinics will actually work from. If the output is a slide deck',
      'and a conversation, the protocol is delivered thirteen different ways within a month. This',
      'procedure states what a design output pack must contain, how each item is tied back to a',
      'stated input, and what has to be true before it is released.',
      '',
      '## Scope',
      '',
      'The outputs of every registered design item — treatment protocols, parameter tables,',
      'screening sets, aftercare information, catalogue entries, consent text, session record',
      'templates, competence requirements, monitoring criteria, and the software itself.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Dhiaz Fathra** owns this procedure and the output pack template.',
      '- The **design item owner** assembles the pack and signs that each output traces to an input.',
      '- **Pak Andre** signs clinical outputs; **Wiwin** signs the catalogue entry and any claim',
      '  wording; **Rica** signs consent text; **Tika** signs the monitoring and acceptance criteria.',
      '- **Aris Ihwan** approves release on the gate 3 minute.',
      '- **Andreas** places the pack under document control on the day of release.',
      '',
      '## Procedure',
      '',
      '1. **Assemble the pack on FRM-8-3-5-01** before gate 3. The release checklist is part of the',
      '   pack, not a separate ritual.',
      '2. **Every output traces to a numbered input.** The pack carries the mapping. An output with no',
      '   input behind it is either removed or an input was missed and gate 1 is reopened.',
      '3. **Mandatory contents, both kinds of item**: the thing itself; the acceptance criteria the',
      '   work must meet in use; the monitoring measures for the first quarter; the competence',
      '   required of whoever will perform it; and the information the patient receives, in Bahasa',
      '   Indonesia and English where it is patient-facing.',
      '4. **Outputs state characteristics essential for intended and safe use** — parameter ceilings,',
      '   contraindications, session intervals, storage conditions for consumables, and for platform',
      '   items the data retained and its retention period.',
      '5. **Reference the delivery requirement.** Each output names where it is used in the process:',
      '   which step of the treatment session record, which screen of the consultation flow, which',
      '   entry of the calibration register.',
      '6. **Adequate for the purpose means usable by the clinic.** A protocol issued without a',
      '   parameter table a practitioner can read at the device is not adequate, however complete it',
      '   is as a document.',
      '7. **Approval before release.** Each output is signed by the accountable person listed above,',
      '   and release is approved by Aris Ihwan. No output reaches a clinic ahead of that signature.',
      '8. **Place under document control the same day.** Outputs enter the QMS library with a code, a',
      '   version and a review date under 7.5.3; superseded versions are withdrawn from the clinics',
      '   rather than left in circulation.',
      '',
      '## Records',
      '',
      'Output packs and release checklists are held per design item for the life of the protocol or',
      'service plus three years. Superseded outputs are retained under document control and marked',
      'withdrawn.',
      '',
      '## Review',
      '',
      'Annually by Dhiaz Fathra with Pak Andre, and whenever a clinic reports working from a version',
      'that was superseded.',
    ].join('\n'),
  },
  {
    code: 'QMS-SOP-8-3-6',
    title: 'Design and Development Changes',
    clause: '8.3.6',
    crossRefs: ['9001 8.3.5', '9001 8.3.4', '9001 8.5.6', '9001 8.2.4', 'A.8.32'],
    version: 'v1.7',
    owner: 'Andreas',
    form: { code: 'FRM-8-3-6-01', name: 'Design change record and impact assessment' },
    revisions: [
      {
        version: 'v1.5',
        date: '2025-10-14',
        author: 'Andreas',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Post-release changes were raised as ordinary tickets; the link back to the original design file was lost after two revisions.',
      },
      {
        version: 'v1.7',
        date: '2026-06-01',
        author: 'Andreas',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Changes re-enter at gate 2 with the original input record attached, and the impact assessment now covers patients mid-course, stock in the field and superseded outputs.',
      },
    ],
    evidence: [
      {
        name: 'qms-8-3-6-change-record-lhr-parameters-2026.docx',
        fileType: 'DOCX',
        uploadedAt: '2026-06-03',
        expiryDate: '2027-06-03',
        uploader: 'Tika',
        note: 'Design change record for the revised laser hair removal parameters released on 1 June 2026.',
        body: [
          '# Design change record — PROT-LHR-004, parameter revision',
          '',
          '**Raised** 2026-03-18 by Pak Andre · **Released** 2026-06-01 · **Change reference** DC-2026-011',
          '',
          '## Change',
          '',
          'Fluence and pulse-width table revised for Fitzpatrick IV–VI following the vendor update of',
          'February 2026 and 18 months of adverse-event data. Two entries in the previous table',
          'exceeded the vendor ceiling for Fitzpatrick V and were corrected.',
          '',
          '## Re-entry point',
          '',
          'Gate 2, with the original gate 1 input record from PROT-LHR-004 attached. New input added:',
          'the Fitzpatrick V–VI gap raised in the 2025 internal audit.',
          '',
          '## Impact assessment',
          '',
          'Area | Impact | Action | Owner | Closed',
          'Patients mid-course | 962 in-course agreements across 13 clinics | Aftercare card reissued; 41 asked to re-consent | Wiwin | 2026-06-14',
          'Practitioner competence | All practitioners trained on the previous table | Refresher before first session under new parameters; 118 of 118 completed | Tika | 2026-05-29',
          'Superseded outputs | Old parameter table printed at 13 clinics | Withdrawn and destroyed, confirmed per clinic | Clinic co-ordinators | 2026-06-02',
          'Platform | Session record references parameter set version | Version field added, defaults to current | Andreas | 2026-05-27',
          'Stock in the field | No consumable change | None | Pak Chen | n/a',
          '',
          '## Authorisation',
          '',
          'Verification: parameter table imported from vendor file rev 4.2 and checked line by line by',
          'two practitioners. Validation: pilot at Pondok Indah and Bandung Dago, 96 sessions over',
          'eight weeks, two grade-1 erythema events, none above grade 1.',
          '',
          'Approved for group rollout by Aris Ihwan on 20 May 2026 subject to two conditions — bilingual',
          'aftercare card and refresher training. Both closed 29 May 2026; released 1 June 2026.',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-8-3-6 · Design and Development Changes',
      '',
      '**Owner** Andreas · **Approver** Aris Ihwan · **Version** v1.7 · **Review** annual',
      '**Requirement** ISO 9001 8.3.6 · **Also satisfies** 9001 8.3.5, 9001 8.3.4, 9001 8.5.6, 9001 8.2.4, A.8.32',
      '',
      '## Purpose',
      '',
      'A protocol changes several times over its life, and each change is where the reasoning gets',
      'lost. This procedure keeps a design item as one continuous file: every change re-enters the',
      'gates, carries the original inputs with it, and records what it did to the people already',
      'mid-course, the practitioners trained on the old version, and the printed material sitting in',
      'thirteen clinics.',
      '',
      '## Scope',
      '',
      'Any change to a released design output — a treatment protocol, parameter table, screening set,',
      'aftercare card, consent text, catalogue entry or platform service under design control — and',
      'any change made during design after gate 1 has closed. Changes to how the process is run',
      'without altering the output follow 8.5.6.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Andreas** owns this procedure and the change record.',
      '- The **design item owner** carries the change through the gates and owns the impact',
      '  assessment.',
      '- **Pak Andre** authorises clinical parameter changes and may suspend a protocol without',
      '  waiting for a review.',
      '- **Tika** confirms retraining and re-verification are complete before release.',
      '- **Rica** decides whether a change requires fresh consent from patients mid-course.',
      '- **Aris Ihwan** approves release and any condition attached to it.',
      '',
      '## Procedure',
      '',
      '1. **Raise the change on FRM-8-3-6-01**, referencing the design item and the output being',
      '   changed. The original gate 1 input record is attached; the change is not a new file.',
      '2. **Re-enter at gate 2.** Design review, verification and validation under QMS-SOP-8-3-4 apply',
      '   to the changed part and to anything it touches. A parameter revision is piloted like a new',
      '   protocol.',
      '3. **Record new or altered inputs** and keep the superseded ones, so that the reason a value',
      '   exists remains readable after several revisions.',
      '4. **Impact assessment, mandatory rows**: patients mid-course under the previous version;',
      '   practitioner competence and retraining; superseded outputs in circulation, printed and',
      '   digital; platform records that reference the old version; consumables and stock already in',
      '   the field; and any commitment already made to a customer, which is handled under 8.2.4.',
      '5. **Retraining before first use.** No practitioner performs a session under changed parameters',
      '   before completing the refresher; Tika confirms the count against the practitioner list.',
      '6. **Withdraw the old version.** Superseded printed material is withdrawn and destroyed,',
      '   confirmed per clinic in writing, and the digital version is marked withdrawn in the QMS',
      '   library the day the change is released.',
      '7. **Authorise and record.** The record holds the change, the results of the review, the person',
      '   who authorised it, and every action taken to prevent an adverse effect on conformity. A',
      '   release with conditions names them and the date each closed.',
      '8. **Urgent safety changes** may be issued by Pak Andre immediately, suspending the affected',
      '   protocol; the full record is completed within five working days and the suspension stands',
      '   until it is.',
      '',
      '## Records',
      '',
      'Change records are held with the design item file for the life of the item plus three years.',
      'Impact assessments are a standing input to management review where they show patients affected',
      'mid-course.',
      '',
      '## Review',
      '',
      'Annually by Andreas with Tika, and after any change that reached a clinic without a completed',
      'impact assessment.',
    ].join('\n'),
  },
]
