import type { SeedDocument } from './types'

/** QMS context, leadership and planning: ISO 9001 clauses 4, 5 and 6. */
export const QMS_CONTEXT_LEADERSHIP_PLANNING: SeedDocument[] = [
  {
    code: 'QMS-SOP-4-1',
    title: 'Context Analysis and Strategic Issue Review',
    clause: '4.1',
    crossRefs: ['4.2', '4.3', '6.1'],
    version: 'v2.0',
    owner: 'Aris Ihwan',
    form: { code: 'FRM-4-1-01', name: 'Internal and external issue register' },
    revisions: [
      {
        version: 'v1.2',
        date: '2024-08-19',
        author: 'Wiwin',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Issue register kept in a spreadsheet on the finance share; no fixed review cadence.',
      },
      {
        version: 'v2.0',
        date: '2026-02-11',
        author: 'Aris Ihwan',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Review moved into the half-yearly directors’ session and tied to the risk register; issue owners named individually.',
      },
    ],
    evidence: [
      {
        name: 'issue-register-2026H1.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-02-11',
        expiryDate: '2026-08-11',
        uploader: 'Wiwin',
        note: 'Issues carried into the 2026 first-half review, with owner and current direction of travel.',
        body: [
          'Ref | Type | Issue | Owner | Direction | Linked risk',
          'CTX-01 | External | BPOM device registration timelines lengthening for imported aesthetic devices | Pak Chen | Worsening | RSK-014',
          'CTX-02 | External | Price competition from single-branch clinics in Jakarta Selatan | Wiwin | Stable | RSK-021',
          'CTX-03 | External | UU 27/2022 PDP enforcement phase begins; patient consent evidence now examinable | Rica | Worsening | RSK-003',
          'CTX-04 | Internal | Practitioner turnover at two locations above 20 percent annualised | Pak Andre | Improving | RSK-009',
          'CTX-05 | Internal | ERP replatform runs alongside the legacy system until Q4 2026 | Dhiaz Fathra | Stable | RSK-011',
          'CTX-06 | Internal | Treatment catalogue maintained twice — clinic system and Super App | Wiwin | Improving | RSK-018',
          'CTX-07 | External | Single-supplier dependency for two injectable product lines | Pak Chen | Stable | RSK-006',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-4-1 · Context Analysis and Strategic Issue Review',
      '',
      '**Owner** Aris Ihwan · **Approver** Aris Ihwan · **Version** v2.0 · **Next review** August 2026',
      '',
      '## Purpose',
      '',
      'Dermaster Indonesia runs clinic operations across 13 locations and an in-house engineering',
      'group that builds the systems those clinics work in. The two halves are pulled by different',
      'forces — regulator and practitioner supply on one side, platform migration and data',
      'obligations on the other. This procedure is how the directors write down what is actually',
      'pushing on the business, so that the quality objectives and the risk register are answering',
      'something real rather than a list assembled the week before an audit.',
      '',
      '## Scope',
      '',
      'Covers every issue capable of changing the QMS outcome: regulatory, commercial, clinical,',
      'workforce and technology. It does not cover project-level problems — those belong in the',
      'delivery backlog — and it does not cover ISMS threat modelling, which is run separately',
      'under the Annex A controls and feeds this review only as a summary.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Aris Ihwan** chairs the review and owns the register.',
      '- **Wiwin** compiles market and commercial input, including competitor pricing.',
      '- **Pak Andre** brings clinic-floor and workforce issues from the 13 locations.',
      '- **Pak Chen** brings supplier, import and device-registration issues.',
      '- **Pak Rila** brings cost, margin and payer issues.',
      '- **Dhiaz Fathra** brings platform, data-protection and engineering-capacity issues.',
      '- **Tika** records the session and updates the register.',
      '',
      '## Procedure',
      '',
      '1. Six weeks before each review (February and August), Tika circulates the current register',
      '   and asks each contributor above for changes, additions and closures.',
      '2. Contributors reply within 10 working days. An addition must state the issue, why it',
      '   matters to quality outcomes, and evidence — a regulator notice, a churn figure, a',
      '   complaint trend — not an impression.',
      '3. Tika consolidates and classifies each entry as internal or external and marks the',
      '   direction of travel: improving, stable, or worsening against the previous review.',
      '4. The directors meet for half a day. Each issue is confirmed, reworded or closed, and',
      '   given a single named owner. An issue with no owner is closed, not carried.',
      '5. Every issue marked worsening must be linked to an entry in the risk register within',
      '   5 working days of the session, or the session minutes record why it needs no risk.',
      '6. Tika updates the register, publishes it in the compliance repository, and raises the',
      '   changes at the next management review as a context input.',
      '',
      '## Records',
      '',
      'The issue register and the session minutes are held in the compliance repository under the',
      'clause 4.1 folder. Both are retained for three review cycles — around three years — so that',
      'an auditor can see how an issue moved before it was closed.',
      '',
      '## Review',
      '',
      'Half-yearly by the directors, and out of cycle whenever a regulator publishes a change that',
      'affects clinic licensing, device registration or patient data handling.',
    ].join('\n'),
  },
  {
    code: 'QMS-SOP-4-2',
    title: 'Interested Parties and Requirements Determination',
    clause: '4.2',
    crossRefs: ['4.1', '4.3', '9.1.2'],
    version: 'v1.4',
    owner: 'Wiwin',
    form: { code: 'FRM-4-2-01', name: 'Interested party requirements register' },
    revisions: [
      {
        version: 'v1.1',
        date: '2024-11-05',
        author: 'Wiwin',
        approval: 'Reviewed by Aris Ihwan',
        status: 'Superseded',
        note: 'Listed parties but not their requirements; no monitoring method recorded against any entry.',
      },
      {
        version: 'v1.4',
        date: '2026-01-27',
        author: 'Wiwin',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Each requirement now carries how it is monitored and who answers for it; patients split from corporate payers.',
      },
    ],
    evidence: [
      {
        name: 'interested-party-register-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-01-27',
        expiryDate: '2027-01-27',
        uploader: 'Wiwin',
        note: 'Parties, their stated requirements, how each is monitored and who answers for it.',
        body: [
          'Party | Requirement they place on us | How we monitor it | Answerable',
          'Patients | Treatment outcome matches what was explained at consultation | Post-treatment survey at day 7 and day 30 | Pak Andre',
          'Patients | Personal and clinical data stays confidential | PDP consent audit, access log review | Rica',
          'Corporate payers | Invoices reconcile to treatments delivered, within terms | Monthly billing exception report | Pak Rila',
          'Kemenkes and local health office | Clinic licences and practitioner credentials current | Credential expiry tracker, monthly | Pak Andre',
          'BPOM | Devices and injectables registered and traceable to batch | Batch traceability check, quarterly | Pak Chen',
          'Practitioners | Equipment maintained and consumables in stock at point of use | Stockout count per location per week | Pak Andre',
          'Suppliers | Forecast shared and payment on agreed terms | Supplier scorecard, half-yearly | Pak Chen',
          'Engineering staff | Clear priorities and a change process that does not thrash | Quarterly SPACE survey | Dhiaz Fathra',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-4-2 · Interested Parties and Requirements Determination',
      '',
      '**Owner** Wiwin · **Approver** Aris Ihwan · **Version** v1.4 · **Next review** January 2027',
      '',
      '## Purpose',
      '',
      'A clinic group has more parties with a legitimate claim on its quality than most businesses:',
      'the patient in the chair, the practitioner holding the device, the health office that licences',
      'the room, BPOM for what is injected, the corporate payer settling the invoice. This procedure',
      'establishes who those parties are, what each of them actually requires of us, and — the part',
      'that was missing until v1.4 — how we would know if we stopped meeting it.',
      '',
      '## Scope',
      '',
      'Applies to all 13 clinic locations and to the engineering group. It covers parties whose',
      'requirements bear on conformity of service or on customer satisfaction. It deliberately',
      'excludes parties with only a general interest — trade press, industry associations — whose',
      'expectations we track commercially but do not manage as QMS requirements.',
      '',
      '## Roles and responsibilities',
      '',
      'Wiwin owns the register and runs the annual determination. Pak Andre speaks for patient and',
      'practitioner requirements, Pak Chen for supplier and regulator-of-product requirements,',
      'Pak Rila for payer requirements, Rica for personal data obligations under UU 27/2022, and',
      'Dhiaz Fathra for the internal engineering audience. Aris Ihwan approves the resulting set.',
      '',
      '## Procedure',
      '',
      '1. Annually in January, Wiwin issues the current register to the six contributors above.',
      '2. Each contributor confirms the requirements listed for their parties, deletes any that are',
      '   no longer real, and adds new ones. A new requirement is only accepted with a source: a',
      '   regulation, a contract clause, a survey result or a recorded complaint.',
      '3. For every requirement, the register must state a monitoring method and a frequency. A',
      '   requirement nobody measures is either given a measure or removed — it does not sit in the',
      '   register as an intention.',
      '4. Wiwin cross-checks the draft against the clause 4.1 issue register so that a worsening',
      '   external issue is reflected in the requirement it threatens.',
      '5. Aris Ihwan approves the register. Changes that alter what we promise a patient are also',
      '   pushed into the consultation script and the Super App consent copy within one month.',
      '6. Requirements that fail their monitoring measure twice in a row are raised as an',
      '   improvement item under clause 10.2, not simply noted.',
      '',
      '## Records',
      '',
      'Register, contributor responses and the approval note live in the compliance repository.',
      'Retained five years, matching the retention on patient satisfaction records so the two can',
      'be read together.',
      '',
      '## Review',
      '',
      'Annually by Wiwin, and immediately after any change to clinic licensing conditions, payer',
      'contract terms, or the personal data obligations Rica maintains.',
    ].join('\n'),
  },
  {
    code: 'QMS-POL-4-3',
    title: 'Scope of the Quality Management System',
    clause: '4.3',
    crossRefs: ['4.1', '4.2', '4.4'],
    version: 'v2.2',
    owner: 'Aris Ihwan',
    form: { code: 'FRM-4-3-01', name: 'Scope statement and exclusion justification' },
    revisions: [
      {
        version: 'v2.0',
        date: '2025-03-14',
        author: 'Aris Ihwan',
        approval: 'Approved by Aris Ihwan',
        status: 'Superseded',
        note: 'Scope covered clinic operations only; engineering was treated as an internal supplier outside the QMS.',
      },
      {
        version: 'v2.2',
        date: '2026-05-06',
        author: 'Aris Ihwan',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Engineering brought inside the scope boundary; design and development no longer excluded; franchise sites stated as out of scope.',
      },
    ],
    evidence: [
      {
        name: 'scope-approval-minute-2026-05.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-05-06',
        uploader: 'Aris Ihwan',
        note: 'Signed directors’ minute adopting the revised scope and removing the clause 8.3 exclusion.',
        body: [
          '# Directors’ minute — QMS scope revision',
          '',
          'Held 6 May 2026, Jakarta head office. Present: Aris Ihwan (chair), Pak Andre, Pak Chen,',
          'Pak Rila, Dhiaz Fathra, Wiwin. Tika recording.',
          '',
          '**Resolved 1.** The QMS scope is extended to the in-house engineering group. The board',
          'accepted that a team which specifies, builds and releases the systems clinics book and',
          'chart in cannot sensibly be treated as an external supplier to the QMS.',
          '',
          '**Resolved 2.** The exclusion of clause 8.3 is withdrawn. Design and development of the',
          'patient-facing Super App and the clinic platform is a real design activity and will be',
          'controlled under QMS-SOP-8-3 from the next release cycle.',
          '',
          '**Resolved 3.** Franchise-operated sites remain outside the scope boundary. They hold',
          'their own licences and employ their own practitioners; our control over them is',
          'contractual, not operational. Their brand-standard audits continue separately.',
          '',
          '**Action.** Dhiaz Fathra to publish the revised scope statement and reissue the QMS manual',
          'index by 20 May 2026. Carried unanimously.',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-POL-4-3 · Scope of the Quality Management System',
      '',
      '**Owner** Aris Ihwan · **Approver** Aris Ihwan · **Version** v2.2 · **Next review** May 2027',
      '',
      '## Purpose',
      '',
      'To state plainly what the quality management system covers, so that neither an auditor nor a',
      'department head has to infer the boundary. The scope changed materially in May 2026 and this',
      'document is the record of where the line now sits and why.',
      '',
      '## Scope statement',
      '',
      'The QMS covers the provision of aesthetic and dermatological clinical services at company-',
      'operated Dermaster Indonesia locations, together with the specification, development,',
      'release and support of the software platform those services run on — patient booking,',
      'clinical records, the treatment catalogue, billing and the patient Super App. It covers the',
      'supporting functions that determine service quality: procurement of devices and consumables,',
      'practitioner credentialling, and quality assurance.',
      '',
      '## Boundaries and exclusions',
      '',
      '1. **Franchise-operated sites are out of scope.** They are separately licensed, employ their',
      '   own practitioners and are governed by brand-standard contracts. We audit them against',
      '   those contracts; we do not manage their processes.',
      '2. **No clause of ISO 9001:2015 is claimed as not applicable.** The previous exclusion of',
      '   clause 8.3 was withdrawn in May 2026 once engineering came inside the boundary — the group',
      '   designs software, and calling that something other than design served no one.',
      '3. **Third-party laboratory analysis is outside the boundary as a process** but inside it as',
      '   an externally provided service, controlled under clause 8.4.',
      '4. Information security controls are managed by the ISMS under ISO/IEC 27001:2022. Where the',
      '   two systems touch — documented information, supplier control, internal audit — the two',
      '   scopes are deliberately aligned rather than duplicated.',
      '',
      '## Physical and organisational extent',
      '',
      'All company-operated clinic locations, the Jakarta head office, and the engineering group,',
      'including engineering staff working remotely and the AWS ap-southeast-1 environment the',
      'platform runs in.',
      '',
      '## Records',
      '',
      'This statement, the directors’ minute that adopted it, and the superseded versions are held',
      'in the compliance repository. Superseded scope statements are retained indefinitely — an',
      'auditor asking when engineering came into scope should get a dated answer.',
      '',
      '## Review',
      '',
      'Annually by the directors, and immediately on opening or closing a location, acquiring a',
      'business, or converting a franchise site to company operation.',
    ].join('\n'),
  },
  {
    code: 'QMS-SOP-4-4',
    title: 'Process Map, Interactions and Process Ownership',
    clause: '4.4',
    crossRefs: ['4.3', '6.3', '9.1.1'],
    version: 'v1.6',
    owner: 'Tika',
    form: { code: 'FRM-4-4-01', name: 'Process definition sheet' },
    revisions: [
      {
        version: 'v1.3',
        date: '2024-06-28',
        author: 'Tika',
        approval: 'Reviewed by Aris Ihwan',
        status: 'Superseded',
        note: 'Process map drawn as a diagram only; no inputs, outputs or performance indicator per process.',
      },
      {
        version: 'v1.6',
        date: '2026-03-30',
        author: 'Tika',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Every process now has a definition sheet with owner, inputs, outputs, indicator and handover point; software delivery added as a core process.',
      },
    ],
    evidence: [
      {
        name: 'process-inventory-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-03-30',
        expiryDate: '2027-03-30',
        uploader: 'Tika',
        note: 'The 11 defined processes with owner, type and the indicator each is judged on.',
        body: [
          'Process | Type | Owner | Primary input | Primary output | Indicator',
          'Enquiry and booking | Core | Wiwin | Enquiry via app, phone or walk-in | Confirmed appointment | Booking-to-arrival conversion',
          'Consultation and treatment planning | Core | Pak Andre | Patient history, clinical assessment | Signed treatment plan and consent | Plan-to-treatment variance',
          'Treatment delivery | Core | Pak Andre | Treatment plan, prepared room, consumables | Completed treatment, clinical note | Adverse event rate per 1000 treatments',
          'Aftercare and follow-up | Core | Pak Andre | Completed treatment | Day-7 and day-30 contact record | Follow-up completion rate',
          'Billing and settlement | Core | Pak Rila | Treatment record | Settled invoice | Billing exception rate',
          'Software delivery | Core | Dhiaz Fathra | Prioritised requirement | Released, verified change | Change failure rate',
          'Procurement and supply | Support | Pak Chen | Location forecast | Stocked consumables and devices | Stockout count per location',
          'Practitioner credentialling | Support | Pak Andre | Licence and training record | Approved scope of practice | Expired credential count (target zero)',
          'Equipment maintenance | Support | Agil | Service schedule | Serviced, calibrated device | Overdue service count',
          'Complaint and nonconformity handling | Support | Tika | Complaint or nonconformity | Closed corrective action | Median days to close',
          'Management review | Governing | Aris Ihwan | Performance inputs | Decisions and resource allocation | Actions closed by next review',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-4-4 · Process Map, Interactions and Process Ownership',
      '',
      '**Owner** Tika · **Approver** Aris Ihwan · **Version** v1.6 · **Next review** March 2027',
      '',
      '## Purpose',
      '',
      'Most of what goes wrong in this group goes wrong at a handover: consultation to treatment,',
      'treatment to billing, requirement to release. A diagram of boxes does not fix that. This',
      'procedure requires every process to be written down with its inputs, its outputs, the person',
      'who owns it and the number it is judged on, and it requires each handover to have a named',
      'receiver on the far side.',
      '',
      '## Scope',
      '',
      'All processes inside the QMS boundary defined in QMS-POL-4-3 — 11 at the time of writing,',
      'classified as core, support or governing. Team-internal working practices below the level of',
      'a defined process are not covered and are left to the process owner.',
      '',
      '## Roles and responsibilities',
      '',
      'Tika maintains the process inventory and the definition sheets, and is the only person who',
      'adds or retires a process. Each named process owner keeps their own sheet accurate and',
      'reports their indicator quarterly. Aris Ihwan approves the inventory and resolves disputes',
      'where two owners disagree about where a handover sits.',
      '',
      '## Procedure',
      '',
      '1. Every process has a definition sheet on FRM-4-4-01 recording: purpose, owner, inputs and',
      '   their source process, outputs and their receiving process, the system of record, the',
      '   performance indicator with its target, and known failure modes.',
      '2. A handover is only defined when both sides agree. The sending owner drafts it; the',
      '   receiving owner signs the sheet. An unsigned handover is escalated to Aris Ihwan within',
      '   10 working days rather than left ambiguous.',
      '3. Indicators are read from the measurement workbook maintained by QA, not gathered by hand',
      '   at reporting time. A process whose indicator cannot be sourced automatically is flagged in',
      '   the inventory as manually measured, and that is treated as a gap to close.',
      '4. Process owners report indicator, trend and any breach of target quarterly to the',
      '   management review.',
      '5. Adding, merging or retiring a process is a change under QMS-SOP-6-3 and needs the same',
      '   impact assessment as any other planned change.',
      '6. Tika reruns the full inventory against the organisation chart every March; a process whose',
      '   owner has left the company is reassigned before the review closes.',
      '',
      '## Records',
      '',
      'Definition sheets and the process inventory are held in the compliance repository. Retained',
      'for the life of the process plus three years, so a retired process can still be explained.',
      '',
      '## Review',
      '',
      'Annually by Tika, and whenever a location opens, a service line launches, or a reorganisation',
      'moves a process between department heads.',
    ].join('\n'),
  },
  {
    code: 'QMS-POL-5-1',
    title: 'Leadership and Commitment to the Quality Management System',
    clause: '5.1',
    crossRefs: ['5.2', '5.3', '9001 9.3'],
    version: 'v2.0',
    owner: 'Aris Ihwan',
    form: { code: 'FRM-5-1-01', name: 'Leadership commitment evidence log' },
    revisions: [
      {
        version: 'v1.5',
        date: '2024-10-02',
        author: 'Aris Ihwan',
        approval: 'Approved by Aris Ihwan',
        status: 'Superseded',
        note: 'Stated commitment in general terms; no scheduled leadership activity and no evidence log.',
      },
      {
        version: 'v2.0',
        date: '2026-04-15',
        author: 'Aris Ihwan',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Commitments turned into dated, checkable obligations — clinic walkrounds, review attendance, resource decisions minuted.',
      },
    ],
    evidence: [
      {
        name: 'leadership-commitment-log-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-01',
        expiryDate: '2027-06-01',
        uploader: 'Tika',
        note: 'What leadership actually did, with dates — the record an auditor asks for when commitment is claimed.',
        body: [
          'Date | Activity | Who | Outcome',
          '2026-01-22 | Management review Q4 2025 | Aris Ihwan, all department heads | Six actions raised; QA headcount approved',
          '2026-02-11 | Context and issue review, first half 2026 | Directors | Seven issues carried, two closed',
          '2026-02-19 | Clinic walkround, Kelapa Gading | Aris Ihwan, Pak Andre | Consumable stockout raised; procurement forecast changed',
          '2026-03-05 | Quality policy briefing to new practitioners | Pak Andre | 14 staff briefed and signed',
          '2026-04-15 | Quality policy reissued | Aris Ihwan | v2.0 approved and published',
          '2026-04-23 | Management review Q1 2026 | Aris Ihwan, all department heads | ERP dual-running risk escalated; deadline moved',
          '2026-05-06 | QMS scope extended to engineering | Directors | Clause 8.3 exclusion withdrawn',
          '2026-05-28 | Clinic walkround, Bandung | Aris Ihwan, Tika | Two aftercare records incomplete; retraining ordered',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-POL-5-1 · Leadership and Commitment to the Quality Management System',
      '',
      '**Owner** Aris Ihwan · **Approver** Aris Ihwan · **Version** v2.0 · **Next review** April 2027',
      '',
      '## Purpose',
      '',
      'Commitment stated in a policy is not evidence of commitment. This document converts what the',
      'directors of Dermaster Indonesia undertake to do into obligations that can be checked against',
      'a calendar and a log — because that is the only form of commitment an auditor, or a',
      'practitioner on the clinic floor, can actually verify.',
      '',
      '## Scope',
      '',
      'Binds the Director and the department heads for clinic operations, procurement, finance and',
      'engineering. It covers their obligations towards the QMS; their ISMS obligations sit under',
      'the corresponding Annex A controls and are not restated here.',
      '',
      '## Roles and responsibilities',
      '',
      'Aris Ihwan is accountable for the effectiveness of the QMS and does not delegate that',
      'accountability. Pak Andre, Pak Chen, Pak Rila and Dhiaz Fathra are accountable within their',
      'functions and attend the management review in person. Tika maintains the commitment evidence',
      'log and reports any missed obligation directly to Aris Ihwan.',
      '',
      '## Policy',
      '',
      '1. The Director chairs the management review quarterly. Delegation of the chair is permitted',
      '   at most once per year and is minuted with the reason.',
      '2. Department heads attend the management review in person. Two consecutive absences without',
      '   a delegate are treated as a nonconformity against this clause.',
      '3. The Director conducts at least six unannounced clinic walkrounds a year, covering all 13',
      '   locations across a rolling 24-month window. Each walkround produces a dated note and any',
      '   action it raises is tracked to closure.',
      '4. Resource decisions affecting quality — headcount, equipment replacement, training budget —',
      '   are recorded in the review minutes with the decision and the reason, including refusals.',
      '5. Quality objectives are set by the directors, not proposed upward and rubber-stamped, and',
      '   are published to all staff within 10 working days of approval.',
      '6. No revenue target may be pursued by suspending a control in this QMS. Where the two',
      '   conflict, the process owner escalates to the Director and the decision is minuted.',
      '7. Every new clinical or engineering hire is briefed on the quality policy within their first',
      '   month, by their department head rather than by a recording.',
      '',
      '## Records',
      '',
      'The commitment evidence log, walkround notes and management review minutes are held in the',
      'compliance repository. Retained five years.',
      '',
      '## Review',
      '',
      'Annually by the Director, and after any external audit finding raised against clause 5.',
    ].join('\n'),
  },
  {
    code: 'QMS-POL-5-2',
    title: 'Quality Policy',
    clause: '5.2',
    crossRefs: ['5.1', '6.2', '7.3'],
    version: 'v3.0',
    owner: 'Aris Ihwan',
    form: { code: 'FRM-5-2-01', name: 'Quality policy acknowledgement record' },
    revisions: [
      {
        version: 'v2.4',
        date: '2024-04-08',
        author: 'Aris Ihwan',
        approval: 'Approved by Aris Ihwan',
        status: 'Superseded',
        note: 'Aspirational wording that staff could not act on; no link to measurable objectives.',
      },
      {
        version: 'v3.0',
        date: '2026-04-15',
        author: 'Aris Ihwan',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Rewritten into five commitments a practitioner can apply at the chair; each tied to a quality objective and issued bilingually.',
      },
    ],
    evidence: [
      {
        name: 'quality-policy-acknowledgements-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-05-20',
        expiryDate: '2027-05-20',
        uploader: 'Tika',
        note: 'Acknowledgement coverage by location and function for the v3.0 policy.',
        body: [
          'Location or function | Headcount | Acknowledged | Coverage | Outstanding since',
          'Kelapa Gading | 24 | 24 | 100% | —',
          'Pondok Indah | 21 | 21 | 100% | —',
          'Bandung | 17 | 16 | 94% | 2026-05-02',
          'Surabaya | 19 | 19 | 100% | —',
          'Medan | 12 | 11 | 92% | 2026-05-11',
          'Head office | 15 | 15 | 100% | —',
          'Engineering | 18 | 17 | 94% | 2026-05-06',
          'Total | 126 | 123 | 98% | three outstanding, all chased by Pak Andre',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-POL-5-2 · Quality Policy',
      '',
      '**Owner** Aris Ihwan · **Approver** Aris Ihwan · **Version** v3.0 · **Next review** April 2027',
      '',
      '## Purpose',
      '',
      'The previous policy was a paragraph of aspiration that no one could act on at the chair or in',
      'a code review. This version states five commitments concrete enough that a practitioner or an',
      'engineer can tell whether they are keeping them, and each is tied to an objective that is',
      'actually measured.',
      '',
      '## Scope',
      '',
      'Applies to every person working at a company-operated Dermaster Indonesia location, at head',
      'office, or in the engineering group, including contractors and locum practitioners. It is',
      'issued in Bahasa Indonesia and English, and both versions are controlled.',
      '',
      '## The policy',
      '',
      '**One — the patient understands before they consent.** No treatment begins until the plan,',
      'the realistic outcome, the alternatives and the aftercare have been explained in the',
      'patient’s own language and the consent record is complete.',
      '',
      '**Two — clinical safety outranks throughput.** Any practitioner may stop or defer a treatment',
      'on safety grounds without seeking approval, and will not be questioned on utilisation for',
      'having done so.',
      '',
      '**Three — we say what we can deliver.** Marketing claims, catalogue descriptions and Super App',
      'copy must match what the clinical team can reproducibly deliver. Wiwin reviews commercial',
      'material against the clinical protocol before release.',
      '',
      '**Four — patient data is treated as the patient’s, not ours.** Access is by role and logged;',
      'retention follows the published schedule; a deletion request is honoured within the statutory',
      'window under UU 27/2022.',
      '',
      '**Five — we fix causes, not symptoms.** A complaint, adverse event or nonconformity is closed',
      'only when the cause is understood and the process changed. Repeat occurrences are treated as',
      'the failure of the earlier fix.',
      '',
      '## Communication and acknowledgement',
      '',
      'The policy is displayed in every staff area, forms part of induction in the first month, and',
      'is acknowledged individually on FRM-5-2-01. Coverage is reported to each management review;',
      'the standing target is 100 percent within 30 days of issue. It is available to patients,',
      'payers and regulators on request and published on the corporate site.',
      '',
      '## Records',
      '',
      'Signed acknowledgements are held by HR; the coverage summary and all superseded versions are',
      'held in the compliance repository. Acknowledgements are retained for employment plus two',
      'years; superseded policy versions indefinitely.',
      '',
      '## Review',
      '',
      'Annually by the Director alongside the quality objectives, and whenever the QMS scope changes.',
    ].join('\n'),
  },
  {
    code: 'QMS-POL-5-3',
    title: 'Organisational Roles, Responsibilities and Authorities',
    clause: '5.3',
    crossRefs: ['5.1', '4.4', '7.2'],
    version: 'v2.3',
    owner: 'Aris Ihwan',
    form: { code: 'FRM-5-3-01', name: 'Role and authority matrix' },
    revisions: [
      {
        version: 'v2.1',
        date: '2025-01-20',
        author: 'Dhiaz Fathra',
        approval: 'Reviewed by Aris Ihwan',
        status: 'Superseded',
        note: 'Responsibilities listed by job title; authority limits and escalation routes left unstated.',
      },
      {
        version: 'v2.3',
        date: '2026-05-19',
        author: 'Aris Ihwan',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Authority limits made explicit, deputies named for every critical role, and the engineering roles added after the scope extension.',
      },
    ],
    evidence: [
      {
        name: 'role-authority-matrix-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-05-19',
        expiryDate: '2027-05-19',
        uploader: 'Tika',
        note: 'Who decides what, up to what limit, and who acts when they are unavailable.',
        body: [
          'Role | Holder | Decides | Limit | Deputy',
          'Director | Aris Ihwan | QMS scope, policy, objectives, resource | Unlimited | Pak Rila (finance matters only)',
          'Head of Clinic Operations | Pak Andre | Scope of practice, treatment suspension, location standards | Any clinical stop | Location manager on duty',
          'Head of Procurement | Pak Chen | Supplier approval, batch quarantine and release | Contracts to IDR 500m | Pak Rila',
          'Head of Finance | Pak Rila | Credit notes, write-offs, payer terms | Write-offs to IDR 50m | Aris Ihwan',
          'Head of Engineering | Dhiaz Fathra | Release approval, architecture, platform incident command | Production rollback, any time | Andreas',
          'QA Lead | Tika | Audit findings, nonconformity classification, measurement definitions | Can halt a release | Randy',
          'Solutions Architect | Andreas | Contract and schema change approval | Additive changes without escalation | Dhiaz Fathra',
          'Controller representative | Rica | Personal data requests, retention exceptions | Deletion within statutory window | Dhiaz Fathra',
          'Infrastructure Engineer | Agil | Equipment service scheduling, environment change | Emergency change with post-hoc review | Randy',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-POL-5-3 · Organisational Roles, Responsibilities and Authorities',
      '',
      '**Owner** Aris Ihwan · **Approver** Aris Ihwan · **Version** v2.3 · **Next review** May 2027',
      '',
      '## Purpose',
      '',
      'The failure this document exists to prevent is the one where something needs to be stopped —',
      'a treatment, a batch, a release — and nobody present is sure they are allowed to stop it. It',
      'assigns responsibility, states authority limits in figures where money is involved, and names',
      'a deputy for every role whose absence would block a decision.',
      '',
      '## Scope',
      '',
      'Covers all roles with QMS responsibility across clinic operations, procurement, finance,',
      'quality assurance and engineering. Line-management structure is documented separately by HR',
      'and is deliberately not restated here; this document is about authority, not reporting lines.',
      '',
      '## Assignment of responsibilities',
      '',
      '- **Aris Ihwan (Director)** — accountable for the QMS as a whole, its scope, policy and',
      '  objectives, and for the resources it needs.',
      '- **Dhiaz Fathra (Head of Engineering)** — appointed management representative for the QMS as',
      '  well as the ISMS: reports QMS performance to the review, maintains the documented',
      '  information system, and is the contact point for external auditors.',
      '- **Tika (QA Lead)** — owns internal audit, nonconformity classification and the measurement',
      '  definitions the objectives are judged on. Holds independent authority to halt a release.',
      '- **Pak Andre** — clinical process conformity across the 13 locations and practitioner',
      '  credentialling; may suspend any treatment or practitioner on safety grounds.',
      '- **Pak Chen** — supplier approval, incoming inspection, batch quarantine and release.',
      '- **Pak Rila** — billing accuracy, payer terms and the financial controls behind them.',
      '- **Rica** — personal data obligations under UU 27/2022 for clinic and platform alike.',
      '- **Andreas, Randy, Agil** — design, delivery and infrastructure responsibilities as set out',
      '  in the authority matrix.',
      '',
      '## Authority rules',
      '',
      '1. Anyone may stop work they believe is unsafe or nonconforming. This authority is not',
      '   limited by grade and its use is never a disciplinary matter.',
      '2. Financial authority limits are as stated in FRM-5-3-01. A decision above a limit is',
      '   escalated to the Director; splitting a decision to stay under a limit is a nonconformity.',
      '3. Every critical role has a named deputy who holds the same authority when the holder is',
      '   unavailable. A role with a vacant deputy is reported at the next management review.',
      '4. Quality authority is not merged with commercial authority: the person who approves a',
      '   release or a batch is never the person carrying the revenue target for it.',
      '5. A change of role holder is reflected in the matrix within 5 working days, and system',
      '   access is realigned in the same window.',
      '',
      '## Records',
      '',
      'The authority matrix, deputy assignments and the change log are held in the compliance',
      'repository. Retained five years after a role holder changes.',
      '',
      '## Review',
      '',
      'Annually, and on any reorganisation, departure of a role holder, or extension of the QMS',
      'scope.',
    ].join('\n'),
  },
  {
    code: 'QMS-SOP-6-1',
    title: 'Risk and Opportunity Management for Quality',
    clause: '6.1',
    crossRefs: ['4.1', '6.2', '10.2'],
    version: 'v2.1',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-6-1-01', name: 'Quality risk and opportunity register' },
    revisions: [
      {
        version: 'v1.8',
        date: '2024-09-12',
        author: 'Tika',
        approval: 'Reviewed by Aris Ihwan',
        status: 'Superseded',
        note: 'Risks scored but actions were not tracked to closure; opportunities recorded nowhere.',
      },
      {
        version: 'v2.1',
        date: '2026-03-18',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Single register for both standards with a QMS view; treatment actions given owners and dates, and effectiveness checked at the following review.',
      },
    ],
    evidence: [
      {
        name: 'quality-risk-register-2026Q1.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-03-18',
        expiryDate: '2026-09-18',
        uploader: 'Tika',
        note: 'Open quality risks and opportunities at the Q1 2026 review, with residual score and treatment owner.',
        body: [
          'Ref | Type | Description | Inherent | Treatment | Owner | Residual | Due',
          'RSK-003 | Risk | Patient consent records incomplete for legacy treatments predating the app | High | Backfill audit, then block booking without consent record | Rica | Medium | 2026-07-31',
          'RSK-006 | Risk | Single supplier for two injectable lines | High | Qualify a second supplier per line | Pak Chen | High | 2026-10-31',
          'RSK-009 | Risk | Practitioner turnover above 20 percent at two locations | Medium | Retention review, cross-location cover roster | Pak Andre | Medium | 2026-08-15',
          'RSK-011 | Risk | Dual-running ERP causes divergent treatment catalogues | High | Single-writer rule, nightly reconciliation report | Andreas | Medium | 2026-06-30',
          'RSK-014 | Risk | Device registration lead time delays a service launch | Medium | Start registration at business-case stage, not launch | Pak Chen | Medium | 2026-09-30',
          'RSK-018 | Risk | Catalogue maintained twice, app and clinic system disagree | Medium | Retire the second catalogue | Wiwin | Low | 2026-05-30',
          'OPP-02 | Opportunity | Day-30 follow-up data can drive protocol refinement | — | Feed outcome data into clinical protocol review | Pak Andre | — | 2026-11-30',
          'OPP-05 | Opportunity | Booking funnel telemetry can cut no-shows | — | Reminder experiment in the Super App | Wiwin | — | 2026-08-31',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-6-1 · Risk and Opportunity Management for Quality',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v2.1 · **Next review** March 2027',
      '',
      '## Purpose',
      '',
      'To turn the issues and requirements found under clauses 4.1 and 4.2 into risks and',
      'opportunities that someone owns and acts on. The failure the previous version had was not',
      'scoring — it was that a scored risk sat in a spreadsheet for a year with nothing happening to',
      'it. This version makes the treatment action, not the score, the tracked object.',
      '',
      '## Scope',
      '',
      'All risks and opportunities affecting the QMS outcome: clinical, regulatory, supply,',
      'workforce, commercial and platform. Information security risks are assessed under the ISMS',
      'and enter this register only where they also threaten service conformity — patient data',
      'availability, for instance. Clinical risk assessment for an individual patient is a treatment',
      'process, not a QMS process, and is out of scope here.',
      '',
      '## Roles and responsibilities',
      '',
      'Dhiaz Fathra maintains the register and runs the quarterly cycle. Tika facilitates the',
      'assessment workshops and challenges scores that do not match the evidence. Each risk has one',
      'named treatment owner drawn from the department heads. Aris Ihwan accepts residual risk',
      'scored high; nobody else may.',
      '',
      '## Procedure',
      '',
      '1. Quarterly, Tika runs a one-hour assessment with the department heads, working from the',
      '   clause 4.1 issue register, open nonconformities, complaint trends and audit findings.',
      '2. Each risk is scored for likelihood and consequence on the shared 5x5 scale used by both',
      '   management systems, giving an inherent rating of low, medium or high.',
      '3. Every risk rated medium or high gets a treatment action with a single owner and a due',
      '   date. A risk without an action is either accepted in writing by Aris Ihwan or removed.',
      '4. Opportunities are recorded in the same register with an intended benefit and an owner.',
      '   They are not scored — an opportunity nobody is working on is closed rather than parked.',
      '5. Treatment actions overdue by more than 30 days are escalated to the Director in the',
      '   monthly operations report, not held until the next quarterly cycle.',
      '6. At the review following completion, the owner reports whether the treatment worked. If the',
      '   residual score did not move, the action is reopened with a different approach.',
      '7. Risks that materialise are cross-referenced to the nonconformity raised under clause 10.2,',
      '   so the register shows what it failed to prevent as well as what it prevented.',
      '',
      '## Records',
      '',
      'Register, workshop notes and residual risk acceptances are held in the compliance repository.',
      'Register versions are retained for five years; a closed risk remains visible in the archive',
      'with its closure reason.',
      '',
      '## Review',
      '',
      'The register quarterly; this procedure annually, or after any risk materialises that the',
      'register had rated low.',
    ].join('\n'),
  },
  {
    code: 'QMS-SOP-6-2',
    title: 'Quality Objectives and Achievement Planning',
    clause: '6.2',
    crossRefs: ['5.2', '6.1', '9.1.1'],
    version: 'v1.9',
    owner: 'Tika',
    form: { code: 'FRM-6-2-01', name: 'Quality objective plan' },
    revisions: [
      {
        version: 'v1.6',
        date: '2025-02-03',
        author: 'Tika',
        approval: 'Reviewed by Aris Ihwan',
        status: 'Superseded',
        note: 'Objectives set annually with targets but no plan stating resources, method or who checks progress.',
      },
      {
        version: 'v1.9',
        date: '2026-01-14',
        author: 'Tika',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Every objective now carries a plan sheet, a data source in the measurement workbook, and quarterly progress reporting.',
      },
    ],
    evidence: [
      {
        name: 'quality-objectives-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-01-14',
        expiryDate: '2027-01-14',
        uploader: 'Tika',
        note: 'The 2026 objective set with baseline, target, data source and owner.',
        body: [
          'Objective | Baseline 2025 | Target 2026 | Measured by | Owner | Q1 actual',
          'Adverse events per 1000 treatments | 2.4 | below 1.5 | Clinical incident log | Pak Andre | 1.9',
          'Day-30 follow-up completion | 71% | above 90% | Follow-up record in clinic system | Pak Andre | 82%',
          'Patient satisfaction, top-two box | 84% | above 90% | Post-treatment survey | Wiwin | 87%',
          'Complaints closed within 10 working days | 58% | above 85% | Complaint register | Tika | 74%',
          'Billing exception rate | 3.1% | below 1.0% | Monthly billing exception report | Pak Rila | 2.2%',
          'Consumable stockouts per location per month | 1.8 | below 0.5 | Stock system | Pak Chen | 1.1',
          'Change failure rate, platform releases | 18% | below 10% | Deployment records | Dhiaz Fathra | 12%',
          'Expired practitioner credentials at any time | 3 | 0 | Credential tracker | Pak Andre | 1',
        ].join('\n'),
      },
      {
        name: 'objective-plan-followup-completion.docx',
        fileType: 'DOCX',
        uploadedAt: '2026-01-14',
        expiryDate: '2027-01-14',
        uploader: 'Tika',
        note: 'Worked example of a completed plan sheet — the day-30 follow-up objective.',
        body: [
          '# Objective plan — day-30 follow-up completion',
          '',
          '**Objective** Raise day-30 follow-up completion from 71 percent to above 90 percent by',
          'December 2026. **Owner** Pak Andre. **Sponsor** Aris Ihwan.',
          '',
          '**Why this objective** Follow-up is where a poor outcome is caught early enough to correct.',
          'The 2025 complaint analysis found that 6 of 11 escalated complaints had no day-30 contact',
          'on record, and in four of those the patient had raised the issue only after the window in',
          'which a correction is straightforward.',
          '',
          '**What will be done** Automated day-30 prompt in the Super App and an SMS fallback for',
          'patients without the app, both built by the platform team in Q1. Follow-up ownership',
          'assigned to the treating practitioner rather than reception from February. Completion',
          'reported per location weekly rather than per group monthly.',
          '',
          '**Resources** Two engineering sprints in Q1, one QA week for the SMS gateway, no additional',
          'clinic headcount. Approved at the January review.',
          '',
          '**How it is measured** Count of treatments with a day-30 contact record divided by',
          'treatments eligible in the same window, read from the clinic system by the measurement',
          'ETL. No manual counting.',
          '',
          '**Checkpoints** Quarterly at the management review. Q1 actual 82 percent — ahead of the',
          'interim 78 percent checkpoint, driven mostly by the app prompt; SMS fallback slipped to Q2',
          'and is the main risk to the year-end target.',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-6-2 · Quality Objectives and Achievement Planning',
      '',
      '**Owner** Tika · **Approver** Aris Ihwan · **Version** v1.9 · **Next review** January 2027',
      '',
      '## Purpose',
      '',
      'Objectives are easy to set and easy to abandon quietly. This procedure requires each one to',
      'come with a plan that names what will be done, what it needs, how it is measured and when it',
      'is checked — and it requires the measure to come out of a system rather than out of someone’s',
      'recollection at the end of the year.',
      '',
      '## Scope',
      '',
      'The group-level quality objectives set annually by the directors, and any location- or',
      'function-level objective derived from them. Personal performance goals are an HR matter and',
      'are outside this procedure, even where they reference the same numbers.',
      '',
      '## Roles and responsibilities',
      '',
      'Tika drafts the objective set, maintains the plan sheets and reports progress. Each objective',
      'has one owner among the department heads, who is answerable for the plan and its checkpoints.',
      'Aris Ihwan approves the set and the targets. Randy maintains the measurement ETL that feeds',
      'the actuals, so no figure is keyed in by the person being measured.',
      '',
      '## Procedure',
      '',
      '1. Each December, Tika proposes the following year’s objective set from four inputs: the',
      '   quality policy commitments, the risk register, the previous year’s performance, and the',
      '   interested-party requirements register.',
      '2. Objectives must be measurable and consistent with the policy. A proposed objective with no',
      '   data source already in the measurement workbook is either given one before approval or not',
      '   set. Between six and ten group objectives is the working range.',
      '3. The directors approve the set in January, including the baseline and the target for each.',
      '4. Within 20 working days of approval, each owner completes a plan sheet on FRM-6-2-01: what',
      '   will be done, resources required, who is responsible, completion date, how results are',
      '   evaluated, and interim checkpoints.',
      '5. Resource requests in a plan sheet are decided at the January or April management review;',
      '   an objective whose resources are refused is retargeted rather than left to fail silently.',
      '6. Progress is reported quarterly with actual against interim checkpoint. An objective missing',
      '   two consecutive checkpoints is reviewed by the directors, who either change the plan,',
      '   change the target, or drop the objective and record why.',
      '7. Objectives are communicated to all staff within 10 working days of approval and displayed',
      '   per location with that location’s own figures, not only the group figure.',
      '',
      '## Records',
      '',
      'Objective set, plan sheets and quarterly progress reports are held in the compliance',
      'repository; actuals live in the measurement workbook. Retained five years so multi-year',
      'trends can be read.',
      '',
      '## Review',
      '',
      'Objectives quarterly at the management review and reset annually; this procedure annually by',
      'the QA Lead.',
    ].join('\n'),
  },
  {
    code: 'QMS-SOP-6-3',
    title: 'Planning and Control of Changes to the QMS',
    clause: '6.3',
    crossRefs: ['4.4', '6.1', '8.5.6'],
    version: 'v1.5',
    owner: 'Andreas',
    form: { code: 'FRM-6-3-01', name: 'QMS change request and impact assessment' },
    revisions: [
      {
        version: 'v1.2',
        date: '2024-12-09',
        author: 'Andreas',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Covered platform changes only; organisational and process changes went through no assessment at all.',
      },
      {
        version: 'v1.5',
        date: '2026-04-02',
        author: 'Andreas',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Extended to process, organisational and supplier changes; rollback position and resource availability now mandatory fields.',
      },
    ],
    evidence: [
      {
        name: 'change-log-2026Q1.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-04-02',
        expiryDate: '2026-10-02',
        uploader: 'Randy',
        note: 'QMS-affecting changes assessed in Q1 2026, with outcome and whether the rollback position was used.',
        body: [
          'Ref | Change | Type | Requester | Assessed | Decision | Outcome',
          'CHG-2026-004 | Retire the duplicate treatment catalogue in the clinic system | Process and platform | Wiwin | 2026-01-19 | Approved, phased by location | Complete, no rollback',
          'CHG-2026-007 | Move follow-up ownership from reception to treating practitioner | Process | Pak Andre | 2026-02-02 | Approved with training precondition | Complete',
          'CHG-2026-011 | Second supplier qualification for injectable line B | Supplier | Pak Chen | 2026-02-24 | Approved, first batch under enhanced inspection | In progress',
          'CHG-2026-013 | Billing service cutover to the new ERP | Platform | Agil | 2026-03-06 | Deferred — rollback position not demonstrable | Reworked, resubmitted Q2',
          'CHG-2026-016 | QA Lead given authority to halt a release | Organisational | Tika | 2026-03-17 | Approved, matrix updated | Complete',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-6-3 · Planning and Control of Changes to the QMS',
      '',
      '**Owner** Andreas · **Approver** Aris Ihwan · **Version** v1.5 · **Next review** April 2027',
      '',
      '## Purpose',
      '',
      'Changes to how this group works have historically arrived two ways: engineered ones with a',
      'design review, and organisational ones announced in a meeting. Only the first kind was ever',
      'assessed. This procedure applies one assessment to both, so that a change to who owns patient',
      'follow-up gets the same scrutiny as a change to the service that records it.',
      '',
      '## Scope',
      '',
      'Any deliberate change affecting a defined process, a documented procedure, a role or authority,',
      'an approved supplier, or a production system inside the QMS scope. Emergency corrective work',
      'to restore a failed service is out of scope while it is happening — it is handled as an',
      'incident and assessed retrospectively within 5 working days.',
      '',
      '## Roles and responsibilities',
      '',
      'Andreas owns this procedure and chairs the weekly change assessment. The requester is the',
      'process owner whose process changes, not the person implementing it. Tika assesses quality',
      'impact and may require a verification step. Dhiaz Fathra approves platform changes; Aris Ihwan',
      'approves organisational changes and anything affecting more than one department. Randy',
      'maintains the change log.',
      '',
      '## Procedure',
      '',
      '1. The requester raises FRM-6-3-01 stating the purpose of the change, the processes and roles',
      '   it touches, the consequences it could have — including the unintended ones — the resources',
      '   it needs and whether they are available, and the rollback position.',
      '2. A change with no credible rollback position is not approved. Where rollback is genuinely',
      '   impossible, the change is split into reversible stages or run in parallel with the existing',
      '   process until verified.',
      '3. Assessment happens at the Tuesday change meeting. Changes touching one process and one',
      '   department may be approved there; anything wider goes to the Director.',
      '4. The assessment records integrity of the QMS: which documents must be reissued, which',
      '   training must precede go-live, and which records or indicators change definition. A change',
      '   that alters an indicator definition must state how the historic series is handled.',
      '5. Approved changes name an implementation owner and a verification date. Verification is done',
      '   by someone other than the implementer, normally QA.',
      '6. Changes affecting clinic practice are rolled out location by location with at least one week',
      '   between the first location and the rest, unless a regulator requires otherwise.',
      '7. Randy closes the change in the log only after the verification result is recorded. Changes',
      '   verified as ineffective are reopened rather than closed with a note.',
      '',
      '## Records',
      '',
      'Change requests, assessments, approvals and verification results are held in the compliance',
      'repository and summarised in the quarterly change log. Retained three years; changes affecting',
      'clinical process are retained five.',
      '',
      '## Review',
      '',
      'Annually by the Solutions Architect, and after any change that required an unplanned rollback.',
    ].join('\n'),
  },
]
