import type { SeedDocument } from './types'

/** ISO 9001 clause 8 (earlier part): operational planning, customer requirements, design, supply. */
export const QMS_OPERATION_A: SeedDocument[] = [
  {
    code: 'QMS-SOP-8-1',
    title: 'Operational Planning and Control of Clinic and Platform Delivery',
    clause: '8.1',
    crossRefs: ['6.1', '6.3', '8.5', '9.1.1'],
    version: 'v2.0',
    owner: 'Pak Andre',
    form: { code: 'FRM-8-1-01', name: 'Operational plan and capacity sheet per clinic quarter' },
    revisions: [
      {
        version: 'v1.3',
        date: '2025-05-19',
        author: 'Pak Andre',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Capacity planning still done per clinic in spreadsheets; no link to the booking service.',
      },
      {
        version: 'v2.0',
        date: '2026-02-11',
        author: 'Pak Andre',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Quarterly operational plan now built from booking-service demand data; outsourced steps listed explicitly and pointed at QMS-POL-8-4.',
      },
    ],
    evidence: [
      {
        name: 'operational-plan-q2-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-03-27',
        expiryDate: '2026-07-01',
        uploader: 'Pak Andre',
        note: 'Approved capacity and staffing plan for the 13 locations, quarter starting April 2026.',
        body: [
          'Clinic | Rooms | Practitioner FTE | Planned treatments/week | Q1 actual | Acceptance criterion',
          'Kelapa Gading | 6 | 4.0 | 420 | 388 | >= 95% slots started within 15 min of booked time',
          'Pondok Indah | 8 | 5.5 | 560 | 571 | >= 95% slots started within 15 min of booked time',
          'Bandung Dago | 4 | 2.5 | 250 | 214 | >= 95% slots started within 15 min of booked time',
          'Surabaya Manyar | 5 | 3.0 | 300 | 297 | >= 95% slots started within 15 min of booked time',
          'Bali Seminyak | 4 | 2.0 | 210 | 233 | >= 95% slots started within 15 min of booked time',
          '',
          'Bandung Dago is 14% under plan for the second quarter running; a demand review was',
          'raised as an improvement action rather than a nonconformity.',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-8-1 · Operational Planning and Control of Clinic and Platform Delivery',
      '',
      '**Owner** Pak Andre (Head of Clinic Operations) · **Approver** Aris Ihwan · **Version** v2.0',
      '**Requirement** ISO 9001 8.1 · **Also satisfies** 6.1, 6.3, 8.5, 9.1.1 · **Review** quarterly',
      '',
      '## Purpose',
      '',
      'Dermaster Indonesia delivers two kinds of output from one quality system: aesthetic',
      'treatments given in 13 clinics, and the digital services the in-house engineering group',
      'builds around them. This procedure is how each quarter of that delivery is planned before',
      'it starts, so that capacity, competence and acceptance criteria are decided in advance',
      'rather than discovered at the treatment chair or in a production incident.',
      '',
      '## Scope',
      '',
      'Covers clinic treatment delivery, the booking and consultation flow in the Super App, and',
      'engineering release trains. Excludes design of new treatment protocols and new digital',
      'products, which is planned under QMS-SOP-8-3, and supplier-side planning, which sits with',
      'QMS-POL-8-4.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Pak Andre** owns the operational plan and signs it before the quarter opens.',
      '- **Dhiaz Fathra** contributes the engineering side: release capacity, planned changes and',
      '  any platform work that constrains clinic operations.',
      '- **Tika** supplies the previous quarter actuals from the measurement workbook.',
      '- **Pak Chen** confirms that consumables and outsourced processes in the plan are covered by',
      '  an approved provider before the plan is signed.',
      '- **Aris Ihwan** approves the plan and any in-quarter change above 10% of planned capacity.',
      '',
      '## Procedure',
      '',
      '1. **Six weeks before the quarter**, Tika exports demand and outcome data for the closing',
      '   quarter — bookings, completed treatments, no-shows, complaint volume — from the booking',
      '   service into the measurement workbook.',
      '2. **Five weeks before**, clinic managers submit room, device and practitioner availability',
      '   per location on FRM-8-1-01. Availability is stated in FTE, not headcount.',
      '3. **Four weeks before**, Pak Andre sets planned treatment volume per clinic and the',
      '   acceptance criteria that apply to it: slot punctuality, consent completeness, and the',
      '   post-treatment follow-up call within 72 hours.',
      '4. **Four weeks before**, Dhiaz Fathra states which platform changes land in the quarter and',
      '   which of them touch a clinic-facing flow. Anything touching booking, consent capture or',
      '   the patient record is planned as a change under 6.3, not as routine work.',
      '5. **Three weeks before**, Pak Chen confirms consumable lead times against the plan and flags',
      '   any item with less than four weeks of cover.',
      '6. **Two weeks before**, the plan is reviewed in the operations meeting and signed by Aris',
      '   Ihwan. An unsigned plan blocks the quarter opening; the previous quarter plan does not',
      '   roll over silently.',
      '7. **During the quarter**, deviation is controlled: a clinic may move up to 10% of planned',
      '   capacity between weeks on its own authority. Beyond that, or any change to an acceptance',
      '   criterion, needs Pak Andre and is recorded on the plan as a dated amendment.',
      '8. **Outsourced processes** — laboratory analysis, medical waste disposal, device calibration',
      '   — are listed in the plan by provider and control tier so that nothing outsourced is',
      '   invisible in the operational picture.',
      '',
      '## Records',
      '',
      'The signed plan and its amendments (FRM-8-1-01) live in the QMS document library, one entry',
      'per clinic per quarter, retained three years. Weekly actuals stay in the measurement',
      'workbook and are retained for the life of the certification cycle.',
      '',
      '## Review',
      '',
      'Reviewed at the close of every quarter by Pak Andre with Tika, and whenever a location opens',
      'or closes. Structural changes go to the management review.',
    ].join('\n'),
  },
  {
    code: 'QMS-SOP-8-2',
    title: 'Determining and Reviewing Requirements for Treatments and Digital Services',
    clause: '8.2',
    crossRefs: ['8.1', '8.3', '9.1.2', 'A.5.34'],
    version: 'v2.2',
    owner: 'Pak Andre',
    form: { code: 'FRM-8-2-01', name: 'Consultation and treatment agreement record' },
    revisions: [
      {
        version: 'v2.1',
        date: '2025-09-08',
        author: 'Wiwin',
        approval: 'Reviewed by Pak Andre',
        status: 'Superseded',
        note: 'Consultation record still paper at nine locations; price confirmation not tied to the quoted catalogue version.',
      },
      {
        version: 'v2.2',
        date: '2026-04-02',
        author: 'Pak Andre',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Consultation record moved into the Super App for all 13 clinics; quoted price now pinned to a catalogue version id, and contraindication screening made a blocking step.',
      },
    ],
    evidence: [
      {
        name: 'requirement-review-exceptions-2026-h1.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-05',
        uploader: 'Wiwin',
        note: 'Cases in the first half of 2026 where the treatment given differed from the agreement, and how each was resolved.',
        body: [
          'Date | Clinic | Difference from agreement | Cause | Resolution | Closed',
          '2026-01-22 | Pondok Indah | Session count reduced 6 to 4 | Practitioner judgement on skin response | Re-agreed and re-signed in app before session 4 | Yes',
          '2026-02-14 | Kelapa Gading | Price quoted below live catalogue | Promotion expired mid-consultation | Quoted price honoured; catalogue version pinning shipped 2026-04-02 | Yes',
          '2026-03-30 | Bali Seminyak | Add-on given, not on agreement | Verbal request not recorded | Charged as agreed, staff coached, add-on flow added to the app | Yes',
          '2026-05-11 | Surabaya Manyar | Treatment declined at screening | Contraindication found after payment | Refunded within 3 working days; screening moved before payment | Yes',
        ].join('\n'),
      },
      {
        name: 'consultation-agreement-template-v2.2.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-04-02',
        expiryDate: '2027-04-02',
        uploader: 'Pak Andre',
        note: 'Signed template of the consultation and treatment agreement as issued to the clinics.',
      },
    ],
    body: [
      '# QMS-SOP-8-2 · Determining and Reviewing Requirements for Treatments and Digital Services',
      '',
      '**Owner** Pak Andre · **Approver** Aris Ihwan · **Version** v2.2',
      '**Requirement** ISO 9001 8.2 · **Also satisfies** 8.1, 8.3, 9.1.2, A.5.34',
      '',
      '## Purpose',
      '',
      'A patient arrives with an outcome in mind, not a treatment code. This procedure sets out how',
      'the organisation turns that into an agreed, recorded and achievable commitment — what will be',
      'done, in how many sessions, at what price, with what risks stated — and how the commitment is',
      'reviewed before anything is delivered.',
      '',
      '## Scope',
      '',
      'Applies to every treatment agreement made in a clinic or through the Super App, and to',
      'requirements accepted from corporate customers for the marketplace and partner services. It',
      'does not cover the medical judgement itself, which follows the clinical protocol issued under',
      'QMS-SOP-8-3.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Pak Andre** owns the consultation flow and the agreement template.',
      '- **Wiwin** maintains the treatment catalogue, prices and promotion rules that the agreement',
      '  quotes from, and is the steward for the commercial data behind it.',
      '- The **treating practitioner** performs the contraindication screening and may refuse or',
      '  reduce a requested treatment; that refusal is recorded, not negotiated at the desk.',
      '- **Rica** confirms that consent captured in the flow meets the PDP Law obligations before any',
      '  change to the consultation screens goes live.',
      '- **Dhiaz Fathra** owns the booking and consent services that carry the record.',
      '',
      '## Procedure',
      '',
      '1. **Capture what the patient wants** in their own words in the consultation record, before a',
      '   treatment is named. Free text, and it stays in the record.',
      '2. **Screen for contraindications** against the protocol for the candidate treatment. This is',
      '   a blocking step in the app: no agreement can be signed while a screening question is',
      '   unanswered, and it is completed before payment is taken.',
      '3. **State what is being agreed** on FRM-8-2-01: treatment, number of sessions, interval,',
      '   expected outcome in plain language, known side effects, aftercare, and total price.',
      '4. **Pin the price** to a catalogue version id issued by Wiwin. A promotion that lapses during',
      '   the consultation does not change the quoted price; the quote is honoured for 7 days.',
      '5. **Confirm the organisation can meet it** — device availability at that location, a',
      '   practitioner competent for that protocol, and consumable cover within the session interval.',
      '   If any is missing, the agreement is not signed and the patient is offered a dated',
      '   alternative.',
      '6. **Sign in the app**; the patient receives a copy by e-mail or WhatsApp within one hour.',
      '7. **Changing an agreement** — any change to treatment, session count or price is re-agreed and',
      '   re-signed before the next session. Verbal add-ons are not billable.',
      '8. **Enquiries and complaints** about what was promised are logged in the same record so that',
      '   satisfaction analysis under 9.1.2 reads from the agreement, not from recollection.',
      '',
      '## Records',
      '',
      'Consultation and treatment agreements are held in the patient service and retained for ten',
      'years after the last treatment, matching the clinical retention rule. Exception cases are',
      'summarised half-yearly on the requirement review exception sheet and taken to management',
      'review.',
      '',
      '## Review',
      '',
      'Reviewed half-yearly by Pak Andre with Wiwin, and immediately after any complaint whose root',
      'cause is a difference between what was agreed and what was delivered.',
    ].join('\n'),
  },
  {
    code: 'QMS-SOP-8-3',
    title: 'Design and Development of Treatment Protocols and Digital Services',
    clause: '8.3',
    crossRefs: ['8.2', '8.5', '6.3', 'A.8.25'],
    version: 'v1.4',
    owner: 'Dhiaz Fathra',
    form: {
      code: 'FRM-8-3-01',
      name: 'Design stage-gate record (inputs, review, verification, validation)',
    },
    revisions: [
      {
        version: 'v1.2',
        date: '2025-07-30',
        author: 'Andreas',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Covered digital product design only; clinical protocol introduction was handled outside the QMS.',
      },
      {
        version: 'v1.4',
        date: '2026-05-20',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'One stage-gate for both clinical protocols and digital services; validation now requires a pilot at two clinics before group rollout.',
      },
    ],
    evidence: [
      {
        name: 'design-review-minute-lhr-protocol-2026-05.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-05-20',
        uploader: 'Aris Ihwan',
        note: 'Signed gate-3 design review minute for the revised laser hair removal protocol.',
        body: [
          '# Design review — revised laser hair removal protocol (gate 3)',
          '',
          '**Held** 15 May 2026 · **Chair** Aris Ihwan · **Present** Pak Andre, Dhiaz Fathra, Tika, two lead practitioners',
          '',
          '## Inputs restated',
          '',
          'Device vendor parameter update, 18 months of adverse-event data from the treatment service,',
          'and the Fitzpatrick V–VI gap raised in the 2025 internal audit.',
          '',
          '## Verification',
          '',
          'Parameter tables checked line by line against the vendor specification. Two entries for',
          'Fitzpatrick V exceeded the vendor ceiling and were corrected before this review.',
          '',
          '## Validation',
          '',
          'Pilot at Pondok Indah and Bandung Dago, 96 sessions over eight weeks. Two grade-1 erythema',
          'events, both resolved within 48 hours; none above grade 1. Patient-reported outcome at',
          'session 4 averaged 4.5 of 5.',
          '',
          '## Decision',
          '',
          'Approved for group rollout from 1 June 2026, conditional on the aftercare card being',
          'reissued in Bahasa Indonesia and English and on refresher training for all practitioners',
          'before their first session under the new parameters. Both conditions closed 29 May 2026.',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-8-3 · Design and Development of Treatment Protocols and Digital Services',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v1.4',
      '**Requirement** ISO 9001 8.3 · **Also satisfies** 8.2, 8.5, 6.3, A.8.25 · **Review** annual',
      '',
      '## Purpose',
      '',
      'Two things get designed here and both reach a patient: a clinical treatment protocol, and the',
      'software that books, records and follows up that treatment. They fail differently but they',
      'fail for the same reason — going live without stating up front what "working" means. This',
      'procedure puts one stage-gate across both so that inputs, verification and validation are',
      'recorded before anything is released.',
      '',
      '## Scope',
      '',
      'A new or materially changed treatment protocol; a new device introduced to the clinics; a new',
      'digital service or a change to booking, consent, the patient record or billing. Cosmetic',
      'copy changes, dependency upgrades and configuration are excluded and follow the ordinary',
      'change control in 6.3.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Dhiaz Fathra** owns this procedure and chairs gates for digital services.',
      '- **Pak Andre** owns clinical protocol design inputs and nominates the pilot clinics.',
      '- **Andreas** produces the technical design and the verification evidence for platform work.',
      '- **Tika** defines the validation measures and reports the pilot result.',
      '- **Rica** is a required reviewer at gate 2 wherever personal data is involved.',
      '- **Aris Ihwan** approves release at gate 3. No one else can waive a gate.',
      '',
      '## Procedure',
      '',
      '**Gate 1 — inputs (before work starts).** Record on FRM-8-3-01: the need and where it came',
      'from, regulatory and vendor constraints, prior adverse events or incidents, what success will',
      'be measured by, and what is explicitly out of scope. Inputs must be complete and',
      'non-contradictory; a contradiction is resolved at this gate, not during build.',
      '',
      '**Gate 2 — design review (mid-build).** The design is reviewed against the inputs by people',
      'not doing the work: for protocols, two lead practitioners; for platform work, a second',
      'engineer plus Rica where personal data is touched. Actions from the review are dated and',
      'owned, and the gate stays open until they are closed.',
      '',
      '**Gate 3 — verification and validation (before release).** Verification asks whether the',
      'output meets the stated inputs — parameter tables checked against vendor specification, test',
      'suites and contract tests green, accessibility and consent screens checked. Validation asks',
      'whether it works in use: every protocol is piloted at two clinics for at least six weeks or',
      '80 sessions, whichever comes first, and every clinic-facing platform change runs at one',
      'location before group rollout. Release is approved by Aris Ihwan on the minute.',
      '',
      '**Post-release.** Outcome measures are watched for the first full quarter. A protocol whose',
      'adverse-event rate exceeds the pilot rate is suspended by Pak Andre without waiting for a',
      'management review.',
      '',
      '**Design changes after release** re-enter at gate 2 with the original input record attached,',
      'so the history of a protocol is one continuous file rather than a series of unrelated ones.',
      '',
      '## Records',
      '',
      'Stage-gate records, review minutes, pilot results and release approvals are held per design',
      'item in the QMS library for the life of the protocol or service plus three years. Platform',
      'design decisions are additionally recorded as ADRs in the owning repository.',
      '',
      '## Review',
      '',
      'Annually by Dhiaz Fathra and Pak Andre together, and after any adverse event traced to a',
      'design input that was never stated.',
    ].join('\n'),
  },
  {
    code: 'QMS-POL-8-4',
    title: 'Control of Externally Provided Processes, Products and Services',
    clause: '8.4',
    crossRefs: ['8.4.1', '8.4.2', '8.4.3', 'A.5.19'],
    version: 'v2.0',
    owner: 'Pak Chen',
    form: { code: 'FRM-8-4-01', name: 'Approved external provider register' },
    revisions: [
      {
        version: 'v1.1',
        date: '2024-11-04',
        author: 'Pak Chen',
        approval: 'Reviewed by Pak Rila',
        status: 'Superseded',
        note: 'Single approval route for every provider regardless of what they supplied.',
      },
      {
        version: 'v2.0',
        date: '2026-01-15',
        author: 'Pak Chen',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Three control tiers introduced; cloud and software providers brought under the same register as clinical suppliers, with ISMS supplier controls referenced rather than duplicated.',
      },
    ],
    evidence: [
      {
        name: 'approved-provider-register-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-01-15',
        expiryDate: '2027-01-15',
        uploader: 'Pak Chen',
        note: 'Current approved providers with tier, what they supply and the date of last evaluation.',
        body: [
          'Provider | Supplies | Tier | Last evaluation | Next due | Status',
          'PT Estetika Medika | Injectables and dermal fillers | 1 | 2026-01-08 | 2027-01-08 | Approved',
          'Lumina Devices Asia | Laser devices, calibration service | 1 | 2025-12-02 | 2026-12-02 | Approved',
          'Klinik Patologi Nusantara | Laboratory analysis (outsourced process) | 1 | 2026-02-19 | 2027-02-19 | Approved',
          'PT Limbah Medis Sejahtera | Medical waste collection | 1 | 2025-11-27 | 2026-11-27 | Approved',
          'Amazon Web Services | Cloud hosting, ap-southeast-1 | 2 | 2026-03-10 | 2027-03-10 | Approved',
          'Zitadel | Identity and access management | 2 | 2026-03-10 | 2027-03-10 | Approved',
          'PT Sinar Kemasan | Retail packaging and printed aftercare cards | 3 | 2025-08-14 | 2027-08-14 | Approved',
          'Kurir Cepat Logistik | Inter-clinic consumable transfer | 3 | 2026-04-01 | 2028-04-01 | Approved, monitored',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-POL-8-4 · Control of Externally Provided Processes, Products and Services',
      '',
      '**Owner** Pak Chen (Head of Supplier and Procurement) · **Approver** Aris Ihwan · **Version** v2.0',
      '**Requirement** ISO 9001 8.4 · **Also satisfies** 8.4.1, 8.4.2, 8.4.3, A.5.19',
      '',
      '## Purpose',
      '',
      'Work the organisation does not do itself still reaches the patient — the filler injected, the',
      'laser calibrated by the vendor, the histology read by an outside laboratory, the cloud region',
      "the patient record lives in. This policy states the organisation's position on that work: it",
      'is controlled to the same standard as work done in-house, in proportion to what its failure',
      'would cost.',
      '',
      '## Scope',
      '',
      'Every externally provided product, service and outsourced process used in clinic delivery or',
      'in the platform, including cloud and SaaS providers. Excludes utilities, building services and',
      'professional advisers that do not touch product, service or patient data; those are managed',
      'as ordinary purchases by Pak Rila.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Pak Chen** owns the approved provider register and is the only person who may add to it.',
      '- **Pak Andre** states the clinical requirement for anything used in treatment.',
      '- **Dhiaz Fathra** states the technical and security requirement for platform providers and',
      '  is the ISMS counterpart for supplier security under A.5.19.',
      '- **Pak Rila** holds the commercial terms and will not release payment against an unregistered',
      '  provider.',
      '- **Aris Ihwan** approves tier 1 additions and any exception.',
      '',
      '## Policy',
      '',
      '1. **No unregistered provider.** Nothing that touches a patient, a treatment or production',
      '   data is bought from a provider absent from FRM-8-4-01. Finance enforces this at payment.',
      '2. **Control is tiered by consequence.** Tier 1 is anything whose failure could harm a patient',
      '   or halt treatment; tier 2 is anything holding or processing production data; tier 3 is',
      '   everything else. The tier decides the evidence required and the re-evaluation interval —',
      '   annual for tiers 1 and 2, biennial for tier 3. QMS-SOP-8-4-2 sets out what each tier means',
      '   in practice.',
      '3. **Outsourced processes stay ours.** Outsourcing a process does not outsource responsibility',
      '   for its output. Every outsourced process is named in the operational plan under QMS-SOP-8-1',
      '   with the control applied to it.',
      '4. **Requirements are written before the first order,** never after a dispute. QMS-SOP-8-4-3',
      '   governs what must be communicated to a provider.',
      '5. **Performance is measured, not felt.** Each tier 1 and tier 2 provider carries two measures',
      '   agreed at approval — typically on-time delivery and defect or incident rate — reported to',
      '   the management review.',
      '6. **A provider may be suspended immediately** by Pak Chen on a safety or data-breach finding,',
      '   without waiting for the evaluation cycle. Reinstatement needs Aris Ihwan.',
      '7. **Security requirements are not restated here.** For any provider handling production data,',
      '   the ISMS supplier controls apply as written; this policy adds the quality obligations and',
      '   defers to the ISMS on security.',
      '',
      '## Records',
      '',
      'The approved provider register, evaluation records, performance measures and suspension',
      'notices are held by procurement, retained five years after a provider leaves the register.',
      '',
      '## Review',
      '',
      'Annually by Pak Chen with Pak Rila, and whenever a tier 1 provider fails an evaluation.',
    ].join('\n'),
  },
  {
    code: 'QMS-SOP-8-4-1',
    title: 'External Provider Selection, Evaluation and Approval',
    clause: '8.4.1',
    crossRefs: ['8.4', '8.4.2', '10.2'],
    version: 'v1.3',
    owner: 'Pak Chen',
    form: { code: 'FRM-8-4-1-01', name: 'Provider evaluation and approval record' },
    revisions: [
      {
        version: 'v1.2',
        date: '2025-03-18',
        author: 'Pak Chen',
        approval: 'Reviewed by Pak Rila',
        status: 'Superseded',
        note: 'Evaluation criteria were qualitative; two providers approved with no documented basis.',
      },
      {
        version: 'v1.3',
        date: '2026-02-06',
        author: 'Pak Chen',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Scored criteria with a pass threshold added; trial-supply period made mandatory for tier 1 clinical consumables.',
      },
    ],
    evidence: [
      {
        name: 'provider-evaluation-klinik-patologi-nusantara-2026.docx',
        fileType: 'DOCX',
        uploadedAt: '2026-02-19',
        expiryDate: '2027-02-19',
        uploader: 'Pak Chen',
        note: 'Approval evaluation for the outsourced histology laboratory, including site visit notes.',
        body: [
          '# Provider evaluation — Klinik Patologi Nusantara',
          '',
          '**Evaluated** 19 February 2026 · **Evaluator** Pak Chen · **Clinical reviewer** Pak Andre · **Tier** 1',
          '',
          '## Basis of evaluation',
          '',
          'Site visit to the Jakarta Selatan laboratory, review of the KAN accreditation certificate',
          '(valid to March 2028), turnaround data for 240 specimens handled during the trial period,',
          'and a written statement of the reporting pathway for a critical result.',
          '',
          '## Scores',
          '',
          '| Criterion | Weight | Score | Weighted |',
          '| --- | --- | --- | --- |',
          '| Accreditation and licensing | 30 | 5 | 150 |',
          '| Turnaround against agreed 3 working days | 25 | 4 | 100 |',
          '| Result accuracy and re-read rate | 25 | 5 | 125 |',
          '| Communication of critical results | 10 | 4 | 40 |',
          '| Commercial terms | 10 | 3 | 30 |',
          '| **Total** | 100 | | **445 / 500 (89%)** |',
          '',
          'Pass threshold for tier 1 is 80%. Approved. One observation: 6 of 240 specimens exceeded',
          'the 3-day turnaround; the provider attributed this to courier collection and has moved to',
          'a fixed 16:00 pickup. To be checked at the next evaluation.',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-8-4-1 · External Provider Selection, Evaluation and Approval',
      '',
      '**Owner** Pak Chen · **Approver** Aris Ihwan · **Version** v1.3',
      '**Requirement** ISO 9001 8.4.1 · **Also satisfies** 8.4, 8.4.2, 10.2 · **Review** annual',
      '',
      '## Purpose',
      '',
      'To set out how a provider gets onto the approved register, how the decision is evidenced, and',
      'how it is revisited. The point of the procedure is that an approval can be explained a year',
      'later to someone who was not in the room.',
      '',
      '## Scope',
      '',
      'New providers, re-evaluation of existing ones, and removal. Applies to clinical consumables,',
      'devices and their calibration, outsourced clinical processes, waste handling, logistics, and',
      'cloud or software providers holding production data.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Pak Chen** runs the evaluation and holds the record.',
      '- **Pak Andre** scores the clinical criteria for anything used in treatment; **Dhiaz Fathra**',
      '  scores the technical and security criteria for platform providers.',
      '- **Pak Rila** scores commercial terms and confirms the provider is a legitimate registered',
      '  entity before any payment is set up.',
      '- **Aris Ihwan** approves tier 1 additions and every removal on a safety ground.',
      '',
      '## Procedure',
      '',
      '1. **State the need first.** The requesting department writes what is needed and to what',
      '   requirement, before any provider is contacted. A provider is never approved to fill a need',
      '   nobody wrote down.',
      '2. **Assign the tier** from QMS-POL-8-4 at the outset; the tier decides how much of the rest of',
      '   this procedure applies.',
      '3. **Collect the basis of evaluation.** For tier 1: licence and accreditation certificates,',
      '   product registration where BPOM registration applies, a site visit, and references from two',
      '   existing customers. For tier 2: current certification or audit report, data-residency',
      '   statement, incident history, and the ISMS supplier assessment. For tier 3: commercial terms',
      '   and a sample or trial delivery.',
      '4. **Score against weighted criteria** on FRM-8-4-1-01. Weights are set before scoring, not',
      '   after. The pass threshold is 80% for tier 1 and tier 2, 65% for tier 3; below threshold the',
      '   provider is not approved, and a score cannot be adjusted to reach it.',
      '5. **Trial supply for tier 1 clinical consumables** — at least one delivery cycle or 60 days,',
      '   used at two clinics, before full approval. Findings from the trial are attached to the',
      '   evaluation.',
      '6. **Approve and register.** Pak Chen adds the provider to FRM-8-4-01 with tier, scope of',
      '   supply, evaluation date and next due date. Approval is scoped: a provider approved for',
      '   consumables is not thereby approved to run an outsourced process.',
      '7. **Re-evaluate** on the cycle in QMS-POL-8-4, using performance data from the period rather',
      '   than repeating the initial paperwork. A provider that falls below threshold gets a',
      '   corrective action request under 10.2 with a 30-day response window before removal is',
      '   considered.',
      '8. **Remove** on failure to respond, on a repeat safety finding, or when the supply ends.',
      '   Removal is recorded with the reason; a removed provider re-enters at step 1.',
      '',
      '## Records',
      '',
      'Evaluation records, trial findings, corrective action requests and removal notices are held',
      'by procurement for five years after the provider leaves the register. The register itself is',
      'the index into them.',
      '',
      '## Review',
      '',
      'Annually by Pak Chen, and after any internal audit finding against clause 8.4.',
    ].join('\n'),
  },
  {
    code: 'QMS-SOP-8-4-2',
    title: 'Type and Extent of Control Applied to External Provision',
    clause: '8.4.2',
    crossRefs: ['8.4', '8.4.1', '8.6', 'A.5.22'],
    version: 'v1.2',
    owner: 'Pak Chen',
    form: {
      code: 'FRM-8-4-2-01',
      name: 'Incoming verification and outsourced process control log',
    },
    revisions: [
      {
        version: 'v1.1',
        date: '2025-06-25',
        author: 'Agil',
        approval: 'Reviewed by Pak Chen',
        status: 'Superseded',
        note: 'Incoming checks described for consumables only; no control statement for cloud providers.',
      },
      {
        version: 'v1.2',
        date: '2026-03-10',
        author: 'Pak Chen',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Control matrix by tier added; cold-chain verification made a reject-on-fail check, and cloud provider monitoring tied to the platform status review.',
      },
    ],
    evidence: [
      {
        name: 'incoming-verification-log-2026-q2.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-30',
        uploader: 'Agil',
        note: 'Incoming verification results for the quarter, including the two rejected deliveries.',
        body: [
          'Date | Provider | Item | Batch | Check | Result | Action',
          '2026-04-08 | PT Estetika Medika | Dermal filler 1ml | EM-24418 | Cold chain, seal, expiry, BPOM label | Pass | Released to Pondok Indah',
          '2026-04-22 | PT Estetika Medika | Injectable toxin | EM-24501 | Cold chain 2-8C | Fail, logger read 11.4C | Rejected, provider credited, root cause: courier box',
          '2026-05-06 | Lumina Devices Asia | Laser calibration service | CAL-0619 | Certificate, in-tolerance report | Pass | Device returned to service',
          '2026-05-19 | PT Sinar Kemasan | Aftercare cards | SK-3390 | Print proof, quantity | Fail, wrong language variant | Rejected, reprinted within 6 days',
          '2026-06-11 | Klinik Patologi Nusantara | Histology reports | n/a | Turnaround, completeness | Pass, 3 of 41 late | Logged, raised at evaluation',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-8-4-2 · Type and Extent of Control Applied to External Provision',
      '',
      '**Owner** Pak Chen · **Approver** Aris Ihwan · **Version** v1.2',
      '**Requirement** ISO 9001 8.4.2 · **Also satisfies** 8.4, 8.4.1, 8.6, A.5.22',
      '',
      '## Purpose',
      '',
      'Approving a provider says they can supply. This procedure is about what happens to each',
      'delivery after that, and how much of it is checked. Checking everything the same amount is',
      'both expensive and unsafe — it spends attention on printed cards that a cold-chain failure',
      'needed.',
      '',
      '## Scope',
      '',
      'Incoming products, outsourced processes and continuing services from every registered',
      'provider. Also covers the case where a provider subcontracts part of what it supplies.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Pak Chen** sets the control tier and owns this procedure.',
      '- **Agil** performs incoming verification for consumables and devices at the central store and',
      '  keeps FRM-8-4-2-01.',
      '- The **receiving clinic manager** repeats the seal and expiry check at the point of use.',
      '- **Dhiaz Fathra** owns monitoring of tier 2 platform providers.',
      '- **Tika** samples the log quarterly as part of the measurement pack.',
      '',
      '## Procedure',
      '',
      '**Control matrix.**',
      '',
      '| Tier | What it covers | Control applied | Frequency |',
      '| --- | --- | --- | --- |',
      '| 1 | Injectables, devices, outsourced clinical processes, waste | Documented incoming verification per delivery; annual site visit; batch traceability | Every delivery |',
      '| 2 | Cloud, identity, anything holding production data | Service-level and incident monitoring; annual assurance review; access review with the ISMS | Continuous plus annual |',
      '| 3 | Packaging, print, logistics, non-clinical goods | Quantity and specification check on receipt; performance reviewed at re-evaluation | Sampled, 1 in 5 deliveries |',
      '',
      '**Tier 1 incoming verification.** For every delivery: seal integrity, quantity against the',
      'order, batch number recorded, expiry at least 6 months out, BPOM registration label present,',
      'and for cold-chain items the shipper temperature logger read and recorded. Any failure is a',
      'reject — the delivery is quarantined in the red-labelled area of the central store and the',
      'provider notified the same working day. Nothing rejected is used "just this once"; that',
      'decision is not available to anyone at the store.',
      '',
      '**Outsourced clinical processes.** The output — a laboratory report, a calibration certificate',
      '— is verified against the agreed specification before it is used: completeness, in-tolerance',
      'result, and turnaround against the agreed window. Late or incomplete outputs are logged even',
      'when accepted, because the pattern is the evidence at re-evaluation.',
      '',
      '**Tier 2 continuing services.** Availability, incident count and time to notify are read from',
      'the provider status feeds into the platform status review. A provider incident that affected',
      'clinic operations is written up under 10.2 whether or not the provider issues its own report.',
      '',
      '**Subcontracting.** A provider must declare in writing before subcontracting any part of a',
      'tier 1 or tier 2 supply. An undeclared subcontractor is treated as a supply failure.',
      '',
      '## Records',
      '',
      'FRM-8-4-2-01 is kept per quarter with rejections, quarantine and disposition. Batch records',
      'for injectables are retained ten years to support traceability under 8.5.2. Calibration',
      'certificates are held with the device file.',
      '',
      '## Review',
      '',
      'Annually by Pak Chen with Agil, and after any rejected delivery that reached a clinic before',
      'it was caught.',
    ].join('\n'),
  },
  {
    code: 'QMS-SOP-8-4-3',
    title: 'Information Communicated to External Providers',
    clause: '8.4.3',
    crossRefs: ['8.4', '8.4.2', '7.4', 'A.5.20'],
    version: 'v1.1',
    owner: 'Pak Chen',
    form: { code: 'FRM-8-4-3-01', name: 'Purchase specification and provider acknowledgement' },
    revisions: [
      {
        version: 'v1.0',
        date: '2024-09-12',
        author: 'Pak Chen',
        approval: 'Approved by Aris Ihwan',
        status: 'Superseded',
        note: 'Purchase orders carried item and price only; specification lived in e-mail threads.',
      },
      {
        version: 'v1.1',
        date: '2026-02-27',
        author: 'Pak Chen',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Standing specification per item introduced with a provider acknowledgement signature; right of access and change-notice obligations added for tier 1 and tier 2.',
      },
    ],
    evidence: [
      {
        name: 'purchase-specification-injectables-2026.docx',
        fileType: 'DOCX',
        uploadedAt: '2026-02-27',
        expiryDate: '2027-02-27',
        uploader: 'Pak Chen',
        note: 'Standing specification issued to injectable providers, acknowledged in writing by both current providers.',
        body: [
          '# Purchase specification — injectable products',
          '',
          '**Issued** 27 February 2026 · **Issuer** Pak Chen · **Applies to** all tier 1 injectable supply',
          '',
          '## What is required with every delivery',
          '',
          '- Product name, strength, batch number and expiry printed on the primary packaging',
          '- Valid BPOM registration number for the exact presentation supplied',
          '- Certificate of analysis for the batch, sent electronically before the delivery arrives',
          '- Continuous temperature record for the whole shipment, 2-8C, readable on arrival',
          '- Minimum remaining shelf life of 6 months at the point of delivery',
          '',
          '## Obligations on the provider',
          '',
          '- Notify Pak Chen in writing at least 30 days before any change to formulation, presentation,',
          '  manufacturing site or subcontracted logistics',
          '- Notify within 24 hours of any recall, quality alert or regulatory action affecting a batch',
          '  supplied to Dermaster Indonesia',
          '- Permit a site visit by the organisation or its certification body with 10 working days notice',
          '',
          '## Acknowledgement',
          '',
          'Acknowledged by PT Estetika Medika, 3 March 2026, and by Lumina Devices Asia (device',
          'consumables), 5 March 2026. Both signatures held with this specification.',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-8-4-3 · Information Communicated to External Providers',
      '',
      '**Owner** Pak Chen · **Approver** Aris Ihwan · **Version** v1.1',
      '**Requirement** ISO 9001 8.4.3 · **Also satisfies** 8.4, 8.4.2, 7.4, A.5.20 · **Review** annual',
      '',
      '## Purpose',
      '',
      'Most supply disputes here have had the same shape: the organisation believed something was',
      'required and the provider had never been told it in writing. This procedure fixes what must',
      'be communicated to a provider, in what form, and how the organisation knows the provider',
      'received it.',
      '',
      '## Scope',
      '',
      'All communication that creates or changes an obligation on a registered provider: standing',
      'specifications, purchase orders, change notices, competence and qualification requirements,',
      'and rights of access. Day-to-day operational messages — a delivery time, a stock query — are',
      'out of scope.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Pak Chen** issues every standing specification and is the single channel for changing one.',
      '- **Pak Andre** writes the clinical content of a specification; **Dhiaz Fathra** writes the',
      '  technical and data-handling content for tier 2 providers.',
      '- **Pak Rila** issues purchase orders against an existing specification and no other way.',
      '- **Agil** confirms at incoming verification that what arrived matches the specification in',
      '  force on the order date.',
      '',
      '## Procedure',
      '',
      '1. **One standing specification per item or service,** on FRM-8-4-3-01, held by procurement and',
      '   version-numbered. A purchase order references the specification and its version rather than',
      '   restating it, so an order can never quietly contradict the specification.',
      '2. **Every specification states**: what is being supplied and to what standard; approval or',
      "   release requirements; competence or qualification required of the provider's personnel",
      '   where they perform work on our behalf; the records that must accompany a delivery; how',
      "   performance will be measured; and the organisation's right of access for verification.",
      '3. **For tier 2 providers add** where production data may be held and processed, the breach',
      '   notification window, and the deletion obligation at end of contract. These mirror the ISMS',
      '   supplier agreement clauses rather than competing with them.',
      '4. **Acknowledgement is required.** A new or changed specification for tier 1 or tier 2 is not',
      '   in force until the provider has acknowledged it in writing. Acknowledgement is filed with',
      '   the specification.',
      '5. **Change notice runs both ways.** The organisation gives 30 days notice of a change to a',
      '   specification where the provider must alter how it works, and requires 30 days notice from',
      '   the provider of any change to formulation, site, personnel performing work on our premises,',
      '   or subcontracting. Recalls and regulatory actions are notifiable within 24 hours.',
      '6. **Personnel working on our premises** — calibration engineers, waste handlers — are named in',
      '   advance and are given the site induction before their first visit; Pak Andre confirms the',
      '   induction happened.',
      '7. **Nothing binding by verbal agreement.** A commitment made in a meeting or a call is',
      '   confirmed by e-mail from Pak Chen the same day or it does not exist.',
      '',
      '## Records',
      '',
      'Specifications, their versions, acknowledgements, change notices and induction confirmations',
      'are held by procurement, retained five years after the supply ends. Purchase orders are held',
      'by finance on the same retention.',
      '',
      '## Review',
      '',
      'Annually by Pak Chen, and whenever a supply dispute turns on what the provider was told.',
    ].join('\n'),
  },
  {
    code: 'QMS-POL-8-5',
    title: 'Production and Service Provision in the Clinics and on the Platform',
    clause: '8.5',
    crossRefs: ['8.5.1', '8.5.2', '8.1', '8.6'],
    version: 'v2.1',
    owner: 'Pak Andre',
    form: { code: 'FRM-8-5-01', name: 'Treatment session record and post-treatment follow-up' },
    revisions: [
      {
        version: 'v2.0',
        date: '2025-10-21',
        author: 'Pak Andre',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Session record still allowed free-text device parameters; batch capture optional for injectables.',
      },
      {
        version: 'v2.1',
        date: '2026-05-28',
        author: 'Pak Andre',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Batch scan made mandatory at the point of use, device parameters constrained to the protocol range, and the 72-hour follow-up call made a recorded step.',
      },
    ],
    evidence: [
      {
        name: 'service-provision-conformity-check-2026-05.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-05-31',
        expiryDate: '2027-05-31',
        uploader: 'Tika',
        note: 'Sampled conformity check of treatment session records across five locations, signed off by QA.',
        body: [
          '# Service provision conformity check — May 2026',
          '',
          '**Sample** 150 completed session records, 30 per clinic, five locations · **Checker** Tika',
          '',
          '| Control checked | Conforming | Finding |',
          '| --- | --- | --- |',
          '| Practitioner competent for the protocol at the time of treatment | 150 / 150 | None |',
          '| Device parameters inside the protocol range | 149 / 150 | One record at Bandung Dago outside range, entered before the range constraint shipped |',
          '| Injectable batch scanned at point of use | 143 / 150 | Seven manual entries at Bali Seminyak during a scanner outage; batch still recorded |',
          '| Consent current for the treatment given | 150 / 150 | None |',
          '| 72-hour follow-up recorded | 138 / 150 | Twelve missed at Kelapa Gading over one week of understaffing |',
          '',
          'Two improvement actions raised: a spare scanner per location, and follow-up calls surfaced',
          'as an overdue queue in the clinic dashboard rather than a daily list.',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-POL-8-5 · Production and Service Provision in the Clinics and on the Platform',
      '',
      '**Owner** Pak Andre · **Approver** Aris Ihwan · **Version** v2.1',
      '**Requirement** ISO 9001 8.5 · **Also satisfies** 8.5.1, 8.5.2, 8.1, 8.6',
      '',
      '## Purpose',
      '',
      "This is the organisation's statement of how treatment is actually delivered under control:",
      'what must be true before a session starts, what is recorded while it runs, and what happens',
      'after the patient leaves. It is the umbrella for the detailed controls in the 8.5.x',
      'procedures and it applies equally to the digital service the patient experiences around the',
      'treatment.',
      '',
      '## Scope',
      '',
      'Every treatment session at all 13 locations, the Super App flows that book, record and follow',
      'up that session, and retail product sale at the clinics. Excludes the design of the protocol',
      'being delivered (QMS-SOP-8-3) and final release decisions on nonconforming work (8.6, 8.7).',
      '',
      '## Roles and responsibilities',
      '',
      '- **Pak Andre** owns service provision across the clinics.',
      '- The **treating practitioner** is accountable for the session and for its record; the record',
      '  is part of the treatment, not paperwork after it.',
      '- **Clinic managers** verify daily that devices in service hold a current calibration.',
      '- **Dhiaz Fathra** owns the availability of the systems the session depends on and the',
      '  documented fallback when they are down.',
      '- **Tika** samples session records monthly and reports conformity to the management review.',
      '',
      '## Policy',
      '',
      '1. **Five conditions before a session starts** — a signed agreement under QMS-SOP-8-2; consent',
      '   current for the treatment about to be given; a practitioner recorded as competent for that',
      '   protocol; a device with calibration in date; and consumables released by incoming',
      '   verification. Any one missing stops the session.',
      '2. **The protocol is the boundary.** Device parameters are constrained in the system to the',
      '   range published in the current protocol version. Treating outside the range requires the',
      '   practitioner to record a clinical justification, and it raises a review item automatically.',
      '3. **Batch at the point of use.** Every injectable and single-use consumable is scanned into',
      '   the session record as it is used, not reconciled at the end of the day. This is what makes',
      '   a recall executable within hours instead of days.',
      '4. **The record is contemporaneous.** The session record is completed before the practitioner',
      '   sees the next patient. Late completion is visible in the system and is a supervision issue',
      '   for the clinic manager.',
      '5. **Follow-up is part of the service.** A recorded contact within 72 hours of any injectable,',
      '   laser or energy-based treatment, capturing how the patient is and any adverse reaction.',
      '   Unreached patients are attempted twice more within a week before being closed as unreached.',
      '6. **When the system is down**, the paper fallback in the clinic folder is used and the records',
      '   are entered within 24 hours of service restoration. A session is never given with no record',
      '   at all.',
      '7. **Change during delivery** — a treatment that must be altered mid-course is re-agreed with',
      '   the patient under QMS-SOP-8-2 and the reason recorded against the original agreement.',
      '8. **Conformity is sampled, not assumed.** Tika samples 30 session records per location per',
      '   month against controls 1 to 5 and reports the result; a control below 95% conformity for two',
      '   consecutive months becomes a corrective action.',
      '',
      '## Records',
      '',
      'Session records, batch traceability, follow-up contacts and adverse events are held in the',
      'treatment service and retained ten years after the last treatment. Monthly conformity checks',
      'are retained for the certification cycle.',
      '',
      '## Review',
      '',
      'Quarterly by Pak Andre with Tika, alongside the operational plan review, and immediately after',
      'any adverse event or recall.',
    ].join('\n'),
  },
]
