import type { SeedDocument } from './types'

/** QMS operation, second half of clause 8: service provision, release, nonconformity. */
export const QMS_OPERATION_B: SeedDocument[] = [
  {
    code: 'QMS-SOP-8-5-1',
    title: 'Control of Clinic Treatment Delivery',
    clause: '8.5.1',
    crossRefs: ['8.5.2', '8.6', '8.7', '7.1.5'],
    version: 'v3.0',
    owner: 'Pak Andre',
    form: { code: 'FRM-8-5-1-01', name: 'Treatment room readiness checklist' },
    revisions: [
      {
        version: 'v2.4',
        date: '2024-09-12',
        author: 'Pak Andre',
        approval: 'Reviewed by Tika',
        status: 'Superseded',
        note: 'Paper room log replaced by the Super App practitioner checklist at the four Jakarta locations.',
      },
      {
        version: 'v3.0',
        date: '2025-11-03',
        author: 'Pak Andre',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Rolled out to all 13 locations; laser and injectable protocols split into separate step sets after the Bandung incident.',
      },
    ],
    evidence: [
      {
        name: 'room-readiness-log-q1-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-04-06',
        expiryDate: '2027-04-06',
        uploader: 'Pak Andre',
        note: 'One row per treatment room per opening shift, first quarter 2026.',
        body: [
          'Date | Location | Room | Opened by | Device check | Consumables in date | Deviation',
          '2026-01-04 | Kelapa Gading | LSR-1 | Nurse Dwi | Pass | Yes | none',
          '2026-01-04 | Kelapa Gading | INJ-2 | Nurse Sari | Pass | Yes | none',
          '2026-02-11 | Bandung | LSR-1 | Nurse Ayu | Fail — calibration overdue | Yes | Room closed, device recalled to vendor, reopened 2026-02-14',
          '2026-03-02 | Surabaya | INJ-1 | Nurse Rina | Pass | No — two vials expiring in 6 days | Vials quarantined under QMS-SOP-8-7',
          '2026-03-29 | Bali | LSR-2 | Nurse Made | Pass | Yes | none',
          '',
          'Deviations: 2 of 1,148 shifts. Both closed within the quarter.',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-8-5-1 · Control of Clinic Treatment Delivery',
      '',
      '**Owner** Pak Andre (Clinic Operations) · **Approver** Aris Ihwan · **Version** v3.0',
      '**Requirement** 8.5.1 · **Also satisfies** 8.5.2, 8.6, 8.7, 7.1.5 · **Review** annual',
      '',
      '## Purpose',
      '',
      'A treatment is produced once, on a person, and cannot be reworked. This procedure states',
      'the conditions that must hold before a practitioner starts, so that the outcome does not',
      'depend on which clinic the patient walked into or who happened to be on shift.',
      '',
      '## Scope',
      '',
      'All chargeable clinical services delivered at the 13 group locations: laser and energy',
      'device treatments, injectables, facials and post-procedure care. Retail product sales are',
      'excluded — they are covered by QMS-SOP-8-5-4. Software delivered by the engineering group',
      'is excluded; it is released under QMS-SOP-8-6.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Pak Andre** owns this procedure and the protocol set behind it.',
      '- **Clinic manager** confirms room readiness before the first appointment of each shift.',
      '- **Treating practitioner** performs the treatment and signs the record in the Super App.',
      '- **Tika (QA Lead)** samples completed records monthly and reports deviations to the',
      '  management review.',
      '',
      '## Procedure',
      '',
      '1. **Before the shift.** The clinic manager opens FRM-8-5-1-01 in the practitioner app and',
      '   confirms, per room: device self-test passed, calibration sticker in date, consumables',
      '   within expiry, and single-use stock sufficient for the booked list. A failed line closes',
      '   the room; the app will not accept a booking against a closed room.',
      '2. **Before the treatment.** The practitioner confirms patient identity against the record',
      '   (QMS-SOP-8-5-2), reviews contraindications, and captures written consent for the exact',
      '   protocol booked. A protocol change at the chair requires fresh consent, not a note.',
      '3. **During.** Device settings actually used are entered into the treatment record, not the',
      '   settings the protocol suggests. The app blocks a save where a setting is outside the',
      '   protocol range unless the practitioner records a reason.',
      '4. **After.** Post-procedure instructions are issued from the catalogue text for that',
      '   protocol, and the follow-up window opens automatically under QMS-SOP-8-5-5.',
      '5. **Deviation.** Anything that departs from the protocol — including an aborted treatment —',
      '   is raised as a nonconformity under QMS-SOP-8-7 the same day.',
      '',
      '## Competence and equipment',
      '',
      'A practitioner is authorised per protocol, not per grade. Authorisation is held in the staff',
      'service and enforced by the booking system: an unauthorised practitioner cannot be assigned.',
      'Energy devices are calibrated on the vendor cycle; an overdue calibration closes the room',
      'automatically at 00:00 on the due date.',
      '',
      '## Records',
      '',
      'Room readiness checklists and treatment records are held in the `treatment` service and',
      'retained for ten years after the last treatment, in line with the clinical retention rule in',
      'TRD-SEC-002. Deviation records follow the nonconformity register retention.',
      '',
      '## Review',
      '',
      'Annually by Pak Andre with Tika, and immediately after any deviation classified as harm.',
    ].join('\n'),
  },
  {
    code: 'QMS-SOP-8-5-2',
    title: 'Identification and Traceability of Treatments, Batches and Builds',
    clause: '8.5.2',
    crossRefs: ['8.5.1', '8.5.4', '8.7', '7.5.3'],
    version: 'v2.2',
    owner: 'Pak Andre',
    form: { code: 'FRM-8-5-2-01', name: 'Batch-to-patient traceability record' },
    revisions: [
      {
        version: 'v2.0',
        date: '2024-06-18',
        author: 'Tika',
        approval: 'Reviewed by Pak Andre',
        status: 'Superseded',
        note: 'Lot capture moved from the paper day-book to a barcode scan in the practitioner app.',
      },
      {
        version: 'v2.2',
        date: '2026-01-27',
        author: 'Pak Andre',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Reverse trace (lot to patient list) added after the supplier recall drill took nine hours.',
      },
    ],
    evidence: [
      {
        name: 'recall-drill-report-2026-01.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-01-27',
        uploader: 'Tika',
        note: 'Timed reverse-trace drill on a simulated filler lot recall, signed off by the Director.',
        body: [
          '# Traceability drill — simulated filler lot recall',
          '',
          '**Date** 21 January 2026 · **Run by** Tika · **Observed by** Pak Andre, Pak Chen',
          '',
          '## Scenario',
          '',
          'A supplier notifies that hyaluronic filler lot `HA-2409-118` may have been shipped',
          'outside its cold chain. Find every patient treated from that lot and every unit still',
          'in stock, group-wide.',
          '',
          '## Result',
          '',
          '| Step | Target | Actual |',
          '| --- | --- | --- |',
          '| Lot located in stock records | 30 min | 11 min |',
          '| Patient list produced from treatment records | 2 h | 1 h 40 min |',
          '| Remaining units quarantined at all locations | 4 h | 6 h 20 min |',
          '| Patient contact list handed to clinic managers | 4 h | 9 h 05 min |',
          '',
          '## Findings',
          '',
          '1. Two locations still recorded lots by typing the number; both had transposition errors',
          '   that hid four treatments from the first query. Barcode scan is now mandatory — the',
          '   free-text field was removed on 26 January.',
          '2. Quarantine depended on phoning each location. A quarantine flag pushed from the stock',
          '   service now closes the lot for booking within one minute.',
          '',
          'Re-drill scheduled for July 2026 with a four-hour end-to-end target.',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-8-5-2 · Identification and Traceability',
      '',
      '**Owner** Pak Andre · **Approver** Aris Ihwan · **Version** v2.2',
      '**Requirement** 8.5.2 · **Also satisfies** 8.5.1, 8.5.4, 8.7, 7.5.3',
      '',
      '## Purpose',
      '',
      'When a supplier recalls a lot, or a patient reports a reaction six weeks later, the group',
      'must be able to answer two questions quickly: what went into this patient, and where else',
      'did this lot go. This procedure defines the identifiers that make both answerable.',
      '',
      '## Scope',
      '',
      'Consumables with a lot or serial number (injectables, topicals, single-use tips), energy',
      'devices, treatment records, and software builds released to the Super App. Office supplies',
      'and non-clinical retail stock are out of scope.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Pak Andre** owns clinical traceability and the recall response.',
      '- **Pak Chen** provides the supplier lot data and drives the recall with the vendor.',
      '- **Randy** maintains the stock and treatment service queries that produce the trace.',
      '- **Tika** runs the traceability drill twice a year and reports the timings.',
      '',
      '## Identifiers',
      '',
      '| Object | Identifier | Assigned by |',
      '| --- | --- | --- |',
      '| Patient | `patient_id` from the patient service | System, at registration |',
      '| Treatment episode | `treatment_id`, references `patient_id` and practitioner | System, at booking |',
      '| Consumable unit | Supplier lot plus internal receipt id | Scanned at goods-in |',
      '| Energy device | Asset tag plus serial, tied to a location | Agil, at commissioning |',
      '| Software build | Git commit SHA plus semantic version | CI pipeline |',
      '',
      '## Procedure',
      '',
      '1. **Goods-in.** Every clinical consumable is scanned into the stock service against its',
      '   supplier lot on receipt. Unscanned stock is not available for booking.',
      '2. **At the chair.** The practitioner scans each unit used into the treatment record. Manual',
      '   entry of a lot number is not available — the drill in January 2026 showed why.',
      '3. **Forward trace.** From a `treatment_id`, the record lists every lot, device serial and',
      '   practitioner involved. Available to the practitioner and to Tika, logged on read.',
      '4. **Reverse trace.** From a lot, Randy runs the standing query in the stock service to list',
      '   affected treatments and remaining stock. Target: patient list within four hours of the',
      '   recall notice, quarantine within one hour.',
      '5. **Status identification.** Stock carries one of `available`, `quarantined`, `expired`,',
      '   `consumed`. Only `available` can be booked; QMS-SOP-8-7 sets who may change the status.',
      '',
      '## Records',
      '',
      'Traceability records live with the treatment record (ten years) and the stock ledger (five',
      'years after the lot is exhausted). Drill reports are retained for three cycles.',
      '',
      '## Review',
      '',
      'Twice yearly, after each drill, and on any change to the goods-in flow.',
    ].join('\n'),
  },
  {
    code: 'QMS-POL-8-5-3',
    title: 'Property Belonging to Patients and External Providers',
    clause: '8.5.3',
    crossRefs: ['8.5.4', '8.4.3', '8.7'],
    version: 'v1.3',
    owner: 'Pak Andre',
    form: { code: 'FRM-8-5-3-01', name: 'Customer and provider property register' },
    revisions: [
      {
        version: 'v1.1',
        date: '2024-11-05',
        author: 'Pak Andre',
        approval: 'Drafted',
        status: 'Superseded',
        note: 'Covered physical belongings only; written after two lost-item complaints at Kelapa Gading.',
      },
      {
        version: 'v1.3',
        date: '2026-02-19',
        author: 'Rica',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Patient photographs and provider-supplied demo devices brought into scope as customer property.',
      },
    ],
    evidence: [
      {
        name: 'customer-property-register-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-05-11',
        expiryDate: '2027-05-11',
        uploader: 'Pak Andre',
        note: 'Property held by the group at the May 2026 count, with condition and return status.',
        body: [
          'Item | Belongs to | Held at | Since | Condition | Status',
          'Clinical photograph set (patient records) | Patients | `media` object storage, ap-southeast-1 | ongoing | Intact | Held under consent',
          'Demo laser handpiece SN 44821 | Lutronic (provider) | Kelapa Gading | 2026-03-02 | Good | Return due 2026-06-30',
          'Consignment filler stock, 40 units | PT Medika Nusantara | Central store | 2026-04-15 | In date | Consumed on use, billed monthly',
          'Patient wedding ring, envelope 0142 | Patient (Bandung) | Clinic safe | 2026-05-04 | Good | Returned 2026-05-04, signed',
          'Marketing footage rushes | Dermalicious agency | `media` object storage | 2026-01-20 | Intact | Return/delete due 2026-07-20',
          '',
          'One item overdue at the count: demo handpiece return chased with Pak Chen on 11 May.',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-POL-8-5-3 · Property Belonging to Patients and External Providers',
      '',
      '**Owner** Pak Andre · **Contributor** Rica (personal data) · **Approver** Aris Ihwan',
      '**Version** v1.3 · **Requirement** 8.5.3 · **Also satisfies** 8.5.4, 8.4.3, 8.7',
      '',
      '## Purpose',
      '',
      'The group routinely holds things that are not its own: a patient’s belongings during a',
      'treatment, their clinical photographs, a supplier’s demo device, consignment stock. This',
      'policy states how that property is identified, protected and given back, and what happens',
      'when it is damaged or lost.',
      '',
      '## Scope',
      '',
      'Physical belongings taken into custody at a clinic, consignment and demo equipment from',
      'external providers, patient clinical images and records, and material supplied by marketing',
      'agencies. Staff personal effects are out of scope.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Pak Andre** owns the property register and the clinic-level custody rules.',
      '- **Pak Chen** owns provider-supplied equipment and consignment stock, including returns.',
      '- **Rica** owns patient images and records as controller representative under the PDP Law.',
      '- **Clinic manager** records custody and return at the location.',
      '',
      '## Policy',
      '',
      '1. **Nothing is held without a record.** Anything taken into custody is entered in',
      '   FRM-8-5-3-01 with owner, condition on receipt, and expected return date.',
      '2. **Belongings during treatment.** Valuables go into the room locker; the practitioner does',
      '   not hold them. Items in the clinic safe are logged and returned against a signature the',
      '   same day.',
      '3. **Patient images are patient property in substance.** They are captured only through the',
      '   practitioner app straight into object storage in AWS ap-southeast-1, never onto a device',
      '   gallery, and used outside the clinical record only where the marketing consent flag is',
      '   set on that patient.',
      '4. **Provider equipment.** Demo and loan devices are tagged, held under the same care as',
      '   owned assets, and returned by the agreed date. Pak Chen reviews open loans monthly.',
      '5. **Consignment stock** is scanned in like owned stock but flagged as consigned; it is',
      '   billed on consumption and counted at every stock take.',
      '6. **Loss or damage.** The owner is told the same working day, in writing, with what happened',
      '   and what the group proposes. A nonconformity is opened under QMS-SOP-8-7; the register',
      '   entry stays open until settlement.',
      '',
      '## Records',
      '',
      'The property register is held per location and consolidated at the quarterly stock take.',
      'Custody entries are retained for two years after return; loss and damage notifications are',
      'retained for six years with the complaint file.',
      '',
      '## Review',
      '',
      'Annually by Pak Andre with Pak Chen and Rica, and after any loss or damage event.',
    ].join('\n'),
  },
  {
    code: 'QMS-SOP-8-5-4',
    title: 'Preservation of Clinical Stock, Samples and Records',
    clause: '8.5.4',
    crossRefs: ['8.5.2', '8.5.1', '8.7', '7.5.3'],
    version: 'v2.0',
    owner: 'Pak Chen',
    form: { code: 'FRM-8-5-4-01', name: 'Cold chain and storage condition log' },
    revisions: [
      {
        version: 'v1.6',
        date: '2024-08-08',
        author: 'Pak Chen',
        approval: 'Reviewed by Pak Andre',
        status: 'Superseded',
        note: 'Twice-daily manual fridge readings; excursions found only at the next reading.',
      },
      {
        version: 'v2.0',
        date: '2025-12-15',
        author: 'Pak Chen',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Networked temperature loggers installed at all locations; alerting routed to the clinic manager and Agil.',
      },
    ],
    evidence: [
      {
        name: 'cold-chain-excursion-log-2026.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-01',
        expiryDate: '2027-06-01',
        uploader: 'Pak Chen',
        note: 'Every excursion alert raised by the loggers in 2026 to date, with disposition.',
        body: [
          'Date | Location | Unit | Peak temp | Duration | Disposition',
          '2026-01-19 | Surabaya | FR-2 | 11.4 C | 38 min | Door left ajar; stock assessed in date, released',
          '2026-02-27 | Bandung | FR-1 | 14.1 C | 3 h 12 min | Compressor failure overnight; 26 units scrapped under QMS-SOP-8-7',
          '2026-04-08 | Kelapa Gading | FR-3 | 9.2 C | 15 min | Within tolerance window, no action',
          '2026-05-22 | Bali | FR-1 | 10.8 C | 51 min | PLN outage, generator lag; supplier confirmed stock viable, released',
          '',
          'Scrap value 2026 to date: IDR 41.2m, all from the single Bandung compressor failure.',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-8-5-4 · Preservation of Clinical Stock, Samples and Records',
      '',
      '**Owner** Pak Chen (Supplier and Procurement) · **Approver** Aris Ihwan · **Version** v2.0',
      '**Requirement** 8.5.4 · **Also satisfies** 8.5.2, 8.5.1, 8.7, 7.5.3',
      '',
      '## Purpose',
      '',
      'Most of what the group buys degrades if it is stored wrong: fillers and toxins outside the',
      'cold chain, topicals in sunlight, sterile tips in a torn wrapper. This procedure sets the',
      'storage conditions, how they are monitored, and what to do when they are breached.',
      '',
      '## Scope',
      '',
      'Clinical consumables from goods-in to point of use at all 13 locations and the central',
      'store; patient samples awaiting external lab collection; and the digital preservation of',
      'treatment records and clinical images. Excludes retail packaged goods, which follow the',
      'manufacturer label only.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Pak Chen** owns storage standards and the supplier side of any excursion claim.',
      '- **Clinic manager** acts on excursion alerts and quarantines affected stock.',
      '- **Agil** maintains the temperature loggers, their network path and the alert routing.',
      '- **Tika** samples the excursion log quarterly against the loggers’ raw data.',
      '',
      '## Procedure',
      '',
      '1. **Storage classes.** Cold chain 2–8 °C (injectables, toxins), controlled ambient below',
      '   25 °C and out of direct light (topicals, anaesthetics), dry sterile (single-use tips and',
      '   needles), and secure ambient (controlled substances, in the locked cabinet).',
      '2. **Monitoring.** Every cold unit carries a networked logger reading every five minutes.',
      '   An excursion above 8 °C for more than 20 minutes raises an alert to the clinic manager',
      '   and to Agil. Manual readings are no longer taken; the logger record is the record.',
      '3. **On an excursion alert.** The clinic manager quarantines the unit’s contents in the',
      '   stock service — quarantined stock cannot be booked — and records peak temperature and',
      '   duration in FRM-8-5-4-01 within the same shift.',
      '4. **Disposition within 24 hours.** Pak Chen checks the supplier’s stability data for the',
      '   excursion profile. Stock is released only on written supplier confirmation; otherwise it',
      '   is scrapped and raised as a nonconformity with the scrap value.',
      '5. **FEFO.** Stock is picked first-expiry-first-out. The app flags any unit within 30 days of',
      '   expiry and blocks a unit past it.',
      '6. **Digital preservation.** Treatment records and clinical images are held in AWS',
      '   ap-southeast-1 with versioning on, backed up nightly, and a restore is exercised quarterly',
      '   by Randy against a randomly chosen record.',
      '',
      '## Records',
      '',
      'Logger data is retained for three years; the excursion log and disposition decisions for',
      'six years with the supplier file. Restore exercise results are attached to the quarterly',
      'operations report.',
      '',
      '## Review',
      '',
      'Annually, and after any excursion that results in scrapped stock.',
    ].join('\n'),
  },
  {
    code: 'QMS-SOP-8-5-5',
    title: 'Post-Treatment Follow-Up and Warranty Activities',
    clause: '8.5.5',
    crossRefs: ['8.5.1', '9.1.2', '10.2', '8.7'],
    version: 'v1.4',
    owner: 'Pak Andre',
    form: { code: 'FRM-8-5-5-01', name: 'Post-treatment follow-up and outcome record' },
    revisions: [
      {
        version: 'v1.2',
        date: '2024-12-02',
        author: 'Pak Andre',
        approval: 'Drafted',
        status: 'Superseded',
        note: 'Follow-up was a phone call at the receptionist’s discretion; completion was not measured.',
      },
      {
        version: 'v1.4',
        date: '2026-03-17',
        author: 'Pak Andre',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Follow-up windows fixed per protocol and pushed by the Super App; adverse-event escalation path added.',
      },
    ],
    evidence: [
      {
        name: 'follow-up-completion-q1-2026.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-04-14',
        uploader: 'Tika',
        note: 'Quarterly follow-up completion and adverse-event summary presented to the management review.',
        body: [
          '# Post-treatment follow-up — Q1 2026',
          '',
          '**Prepared by** Tika · **For** Pak Andre and the management review, 14 April 2026',
          '',
          '## Completion',
          '',
          '| Protocol family | Follow-ups due | Completed in window | Rate |',
          '| --- | --- | --- | --- |',
          '| Injectables (72 h) | 3,410 | 3,187 | 93.5% |',
          '| Laser and energy (7 d) | 2,206 | 1,908 | 86.5% |',
          '| Facial and peel (48 h) | 5,884 | 5,101 | 86.7% |',
          '',
          'Target is 90%. Laser follow-up misses cluster at two locations where the app push was',
          'being dismissed at reception rather than actioned by the practitioner; the task now',
          'routes to the treating practitioner only.',
          '',
          '## Adverse events',
          '',
          'Nine reported, all grade 1–2 (swelling, bruising, transient erythema). Median time from',
          'report to clinical contact was 4 h 10 min against a four-hour target. None required',
          'referral. All nine are linked to their nonconformity record.',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-8-5-5 · Post-Treatment Follow-Up and Warranty Activities',
      '',
      '**Owner** Pak Andre · **Approver** Aris Ihwan · **Version** v1.4 · **Review** annual',
      '**Requirement** 8.5.5 · **Also satisfies** 8.5.1, 9.1.2, 10.2, 8.7',
      '',
      '## Purpose',
      '',
      'For an aesthetic treatment, most of what the patient judges happens after they leave: how',
      'the result settles, whether swelling was expected, whether anyone checked. This procedure',
      'defines what the group owes a patient after the appointment ends, and how a touch-up is',
      'decided without an argument at the desk.',
      '',
      '## Scope',
      '',
      'Every chargeable clinical treatment, plus device and software services the engineering group',
      'operates for the clinics after go-live. It covers follow-up contact, adverse-event handling,',
      'touch-up entitlement and the end of the group’s obligation. It does not set clinical',
      'treatment protocols — those sit under QMS-SOP-8-5-1.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Pak Andre** owns the follow-up standard and the touch-up rules.',
      '- **Treating practitioner** owns the follow-up for their own patient; it does not transfer',
      '  to whoever is on the desk.',
      '- **Tika** reports completion rates and adverse events quarterly.',
      '- **Pak Rila** approves any goodwill credit above IDR 5,000,000.',
      '',
      '## Procedure',
      '',
      '1. **Window opens automatically.** On saving a treatment record the Super App schedules the',
      '   follow-up for that protocol family: 72 hours for injectables, 7 days for laser and energy,',
      '   48 hours for facials and peels. The task is assigned to the treating practitioner.',
      '2. **Contact and record.** The practitioner records the patient’s reported outcome, any',
      '   side effect, and whether a review appointment is needed, in FRM-8-5-5-01. No contact is',
      '   also an outcome and is recorded as such after two attempts.',
      '3. **Adverse event.** Anything beyond the expected reaction stated in the consent is escalated',
      '   to the clinic’s senior practitioner within four hours, opened as a nonconformity, and',
      '   reported to Pak Andre the same day. Grade 3 or above also goes to Aris Ihwan immediately.',
      '4. **Touch-up entitlement.** Where a protocol carries a stated settling period, one review and',
      '   one correction within that period are included in the original price. The entitlement is',
      '   held against the treatment record, not negotiated at the desk.',
      '5. **Beyond entitlement.** A goodwill credit is proposed by the clinic manager with a reason',
      '   and approved by Pak Andre; above IDR 5,000,000 it also needs Pak Rila.',
      '6. **Software and device services.** Defects found after release are handled on the incident',
      '   path owned by Randy, with the same requirement to close the record.',
      '',
      '## Records',
      '',
      'Follow-up records sit with the treatment record and share its ten-year retention. Adverse',
      'events are additionally held in the nonconformity register and reviewed at every management',
      'review. Goodwill credits are reconciled monthly with finance.',
      '',
      '## Review',
      '',
      'Annually by Pak Andre, and whenever completion falls below 90% for two consecutive quarters.',
    ].join('\n'),
  },
  {
    code: 'QMS-SOP-8-5-6',
    title: 'Control of Changes to Clinical and Platform Processes',
    clause: '8.5.6',
    crossRefs: ['6.3', '8.5.1', '8.6', '10.2'],
    version: 'v2.1',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-8-5-6-01', name: 'Process change control record' },
    revisions: [
      {
        version: 'v2.0',
        date: '2025-05-20',
        author: 'Dhiaz Fathra',
        approval: 'Reviewed by Pak Andre',
        status: 'Superseded',
        note: 'Merged the clinical change form and the engineering change ticket into one record type.',
      },
      {
        version: 'v2.1',
        date: '2026-05-06',
        author: 'Andreas',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Unplanned-change back-record rule added after two hotfixes were reconstructed from chat logs.',
      },
    ],
    evidence: [
      {
        name: 'change-control-register-2026-h1.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-01',
        expiryDate: '2027-06-01',
        uploader: 'Andreas',
        note: 'All controlled process changes in the first half of 2026, planned and unplanned.',
        body: [
          'Ref | Change | Type | Requested by | Authorised by | Verified | Outcome',
          'CHG-2026-014 | Move injectable follow-up from 5 d to 72 h | Clinical | Pak Andre | Aris Ihwan | 2026-03-17 | Adopted, completion +6pp',
          'CHG-2026-021 | Booking service split from monolith | Platform | Andreas | Dhiaz Fathra | 2026-04-02 | Adopted, no incident',
          'CHG-2026-026 | Supplier switch for lidocaine cream | Supply | Pak Chen | Aris Ihwan | 2026-04-29 | Adopted after 30-day trial at 3 locations',
          'CHG-2026-031 | Emergency rollback of pricing rounding | Unplanned | Randy | Dhiaz Fathra (retro, +6 h) | 2026-05-11 | Adopted, root cause in 10.2 register',
          'CHG-2026-038 | Room readiness checklist wording | Clinical | Tika | Pak Andre | 2026-05-25 | Adopted',
          '',
          '38 changes raised, 36 adopted, 1 withdrawn, 1 reverted. One unplanned change (CHG-2026-031).',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-8-5-6 · Control of Changes to Clinical and Platform Processes',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v2.1',
      '**Requirement** 8.5.6 · **Also satisfies** 6.3, 8.5.1, 8.6, 10.2',
      '',
      '## Purpose',
      '',
      'A change that improves one clinic and quietly breaks another is the most common way this',
      'organisation creates a nonconformity. This procedure makes a change to a delivery process',
      'visible, authorised by someone who can carry the consequence, and reversible.',
      '',
      '## Scope',
      '',
      'Changes to how a service is delivered: clinical protocols, room and consumable standards,',
      'booking and pricing rules, supplier substitutions, and platform changes that alter what a',
      'clinic user sees or does. Routine code deployments that change no process are released under',
      'QMS-SOP-8-6 and are not raised here. Organisational restructuring is out of scope.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Requester** — any staff member; writes what changes and why.',
      '- **Pak Andre** authorises clinical process changes; **Dhiaz Fathra** authorises platform',
      '  changes; **Pak Chen** authorises supplier substitutions; **Aris Ihwan** authorises anything',
      '  affecting price, safety or more than three locations at once.',
      '- **Tika** verifies the outcome and closes the record.',
      '',
      '## Procedure',
      '',
      '1. **Raise.** The requester opens FRM-8-5-6-01 with the current state, the proposed state,',
      '   the reason, the locations or services affected, and what would show the change had gone',
      '   wrong.',
      '2. **Assess.** The authoriser considers effect on patient safety, on the other locations, on',
      '   competence (does anyone need retraining), on stock, and on records already in flight.',
      '3. **Authorise or decline,** in the record, with a named person and a date. Silence is not',
      '   authorisation; an unauthorised change is a nonconformity.',
      '4. **Pilot where the change is clinical.** Default is 30 days at up to three locations with',
      '   the measure named at step 1 before group-wide adoption.',
      '5. **Roll out.** Update the affected controlled document in the same week; brief the staff',
      '   who perform the process before the change takes effect, not after.',
      '6. **Unplanned change.** Where a change had to be made immediately — an outage, a safety',
      '   issue — it is back-recorded within six hours by the person who made it, with the same',
      '   fields and a retrospective authorisation. Reconstructing it later from chat logs is not',
      '   acceptable.',
      '7. **Verify and close.** Tika checks the measure at the end of the pilot or 30 days after',
      '   adoption and records adopted, reverted or withdrawn.',
      '',
      '## Records',
      '',
      'The change control register is held in this repository and retained for six years. Every',
      'record links to the controlled documents it altered and to any nonconformity it caused.',
      '',
      '## Review',
      '',
      'Half-yearly by Dhiaz Fathra with Pak Andre, and at every management review as a standing',
      'input alongside the nonconformity trend.',
    ].join('\n'),
  },
  {
    code: 'QMS-SOP-8-6',
    title: 'Release of Treatments and Platform Releases',
    clause: '8.6',
    crossRefs: ['8.5.1', '8.7', '9.1.1', '8.5.6'],
    version: 'v2.3',
    owner: 'Tika',
    form: { code: 'FRM-8-6-01', name: 'Release authorisation record' },
    revisions: [
      {
        version: 'v2.1',
        date: '2024-10-30',
        author: 'Tika',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Release gate was a manual QA sign-off in the ticket; evidence was not retained after the sprint.',
      },
      {
        version: 'v2.3',
        date: '2026-04-21',
        author: 'Tika',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'CI evidence bundle made the release record; named release authority per stream.',
      },
    ],
    evidence: [
      {
        name: 'release-authorisation-2026-04-21.pdf',
        fileType: 'PDF',
        uploadedAt: '2026-04-21',
        uploader: 'Tika',
        note: 'Signed authorisation for the Super App 4.2 release, with the gate results attached.',
        body: [
          '# Release authorisation — Super App 4.2.0',
          '',
          '**Build** `4.2.0` · commit `9f31ac2` · **Authorised by** Tika, 21 April 2026, 16:40 WIB',
          '',
          '| Gate | Threshold | Result |',
          '| --- | --- | --- |',
          '| Unit and integration tests | 100% pass | 4,182 pass, 0 fail |',
          '| Coverage on changed lines | ≥ 85% | 91.4% |',
          '| Static analysis, high severity | 0 | 0 |',
          '| Dependency vulnerabilities, critical | 0 | 0 |',
          '| Booking regression suite | 100% pass | 214 pass |',
          '| Staging soak, 24 h error rate | < 0.1% | 0.04% |',
          '',
          '## Deviations',
          '',
          'None. One medium static-analysis finding in the loyalty module was accepted with a',
          'ticket (ETR-4471) and does not block release under the threshold above.',
          '',
          '## Rollback',
          '',
          'Previous build `4.1.6` kept warm; rollback exercised in staging on 20 April, 3 min 40 s.',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-8-6 · Release of Treatments and Platform Releases',
      '',
      '**Owner** Tika (QA Lead) · **Approver** Aris Ihwan · **Version** v2.3',
      '**Requirement** 8.6 · **Also satisfies** 8.5.1, 8.7, 9.1.1, 8.5.6',
      '',
      '## Purpose',
      '',
      'Nothing reaches a patient or a clinic user until someone with authority has confirmed the',
      'planned checks were done and passed. This procedure names those checks, the person who may',
      'release, and the evidence that has to survive the release.',
      '',
      '## Scope',
      '',
      'Two release streams. **Clinical**: the point at which a treatment is declared complete and',
      'the patient is discharged from the chair. **Platform**: any build of the Super App, the',
      'Eternesia services or the marketplace promoted to production. Marketing content and internal',
      'tooling with no clinic or patient user are excluded.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Tika** is the release authority for platform builds and owns the gate definitions.',
      '- **Treating practitioner** is the release authority for a clinical treatment.',
      '- **Randy** operates the deployment and the rollback.',
      '- **Dhiaz Fathra** is the only person who may waive a platform gate, in writing, per release.',
      '',
      '## Procedure — platform',
      '',
      '1. A build is a release candidate only when the CI pipeline has produced its evidence bundle:',
      '   test results, coverage on changed lines, static analysis, dependency scan, and the booking',
      '   regression suite.',
      '2. Gates: all tests pass; coverage on changed lines at or above 85%; zero high-severity static',
      '   findings; zero critical dependency vulnerabilities; 24-hour staging soak below 0.1% error',
      '   rate.',
      '3. Tika authorises in FRM-8-6-01, attaching the bundle. The pipeline will not promote a build',
      '   without a matching authorisation record for that commit.',
      '4. Randy deploys, watches for 30 minutes, and confirms the rollback path is warm.',
      '5. A failed gate stops the release. A waiver needs Dhiaz Fathra in writing, names the gate and',
      '   the reason, and expires with that release — it does not carry to the next build.',
      '',
      '## Procedure — clinical',
      '',
      'A treatment is released when the practitioner has confirmed the protocol steps were completed,',
      'the immediate outcome is as expected, the record is signed, and post-procedure instructions',
      'have been issued. Nothing is released on someone else’s behalf.',
      '',
      '## Records',
      '',
      'Release authorisation records and their evidence bundles are retained for three years for',
      'platform releases; clinical release is part of the treatment record and shares its ten-year',
      'retention. Waivers are reported to the management review individually.',
      '',
      '## Review',
      '',
      'Half-yearly by Tika, and after any production incident traced to a gate that did not catch it.',
    ].join('\n'),
  },
  {
    code: 'QMS-SOP-8-7',
    title: 'Control of Nonconforming Outputs',
    clause: '8.7',
    crossRefs: ['10.2', '8.6', '8.5.4', '9.1.3'],
    version: 'v3.1',
    owner: 'Tika',
    form: { code: 'FRM-8-7-01', name: 'Nonconformity and disposition register' },
    revisions: [
      {
        version: 'v3.0',
        date: '2025-02-10',
        author: 'Tika',
        approval: 'Reviewed by Pak Andre',
        status: 'Superseded',
        note: 'Introduced the four dispositions and the single register shared by clinic and engineering.',
      },
      {
        version: 'v3.1',
        date: '2026-05-29',
        author: 'Tika',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Concession authority limited to Aris Ihwan for anything patient-facing; closure now requires effectiveness evidence.',
      },
    ],
    evidence: [
      {
        name: 'nonconformity-register-2026-h1.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-06-02',
        expiryDate: '2027-06-02',
        uploader: 'Tika',
        note: 'Open and closed nonconformities for the first half of 2026 with disposition and age.',
        body: [
          'Ref | Raised | Source | Description | Disposition | Status | Age (days)',
          'NC-2026-007 | 2026-01-22 | Clinic | Consumable used past expiry, single unit | Scrap + retrain | Closed | 6',
          'NC-2026-013 | 2026-02-27 | Storage | Bandung compressor failure, 26 units | Scrap, supplier claim | Closed | 24',
          'NC-2026-019 | 2026-03-30 | Platform | Pricing rounding error on 41 invoices | Correct + reissue | Closed | 9',
          'NC-2026-024 | 2026-04-18 | Clinic | Grade 2 adverse reaction, injectable | Correct, protocol review | Closed | 31',
          'NC-2026-029 | 2026-05-14 | Supply | Off-spec label language on imported topical | Concession, Aris Ihwan | Open | 19',
          '',
          '29 raised, 26 closed, median age 11 days. One concession in the period, patient-facing,',
          'authorised by the Director with a corrective action open under 10.2.',
        ].join('\n'),
      },
    ],
    body: [
      '# QMS-SOP-8-7 · Control of Nonconforming Outputs',
      '',
      '**Owner** Tika · **Approver** Aris Ihwan · **Version** v3.1 · **Review** annual',
      '**Requirement** 8.7 · **Also satisfies** 10.2, 8.6, 8.5.4, 9.1.3',
      '',
      '## Purpose',
      '',
      'Something that does not meet its requirement must be stopped before it reaches the next',
      'step, and dealt with by a decision someone owns. This procedure says how a nonconforming',
      'output is identified, contained, dispositioned and closed, and who may let one through.',
      '',
      '## Scope',
      '',
      'Any output of a group process that fails its requirement: consumables out of specification',
      'or out of condition, treatments that departed from protocol, adverse reactions, invoices and',
      'pricing errors, and platform defects found after release. Supplier-side nonconformity is',
      'raised here and pursued with the vendor by Pak Chen. Staff conduct matters are out of scope.',
      '',
      '## Roles and responsibilities',
      '',
      '- **Anyone** may raise a nonconformity; nobody needs permission to stop an output.',
      '- **Tika** owns the register, classifies severity, and closes records.',
      '- **Pak Andre** dispositions clinical nonconformity; **Pak Chen** supplier and stock;',
      '  **Dhiaz Fathra** platform.',
      '- **Aris Ihwan** is the only concession authority for anything a patient sees or receives.',
      '',
      '## Procedure',
      '',
      '1. **Identify and contain, same shift.** Move the output out of use: quarantine the stock,',
      '   close the room, hold the invoice batch, or disable the feature flag. Containment happens',
      '   before the record is written, not after.',
      '2. **Record.** Raise FRM-8-7-01 with what was found, where, how much is affected, and whether',
      '   any of it already reached a patient or customer.',
      '3. **Classify.** Major where a patient was or could have been harmed, where a regulatory duty',
      '   is engaged, or where more than one location is affected; otherwise minor. Major goes to',
      '   Aris Ihwan the same day.',
      '4. **Disposition** — exactly one of: **correct** (fix and re-verify), **segregate or scrap**,',
      '   **return to supplier**, or **concession** (accept as is, with a stated reason). A',
      '   concession on anything patient-facing needs the Director, in the record, before the output',
      '   is used.',
      '5. **Notify.** Where the output already reached a patient or customer, they are told what',
      '   happened and what is being done, by the clinic manager, within one working day.',
      '6. **Re-verify.** A corrected output is checked against the requirement it failed, by someone',
      '   other than the person who corrected it.',
      '7. **Escalate to corrective action.** Any major nonconformity, or a minor one recurring three',
      '   times in a quarter, opens a corrective action under clause 10.2.',
      '8. **Close.** Tika closes only on evidence the disposition took effect — the scrap note, the',
      '   re-verified record, the supplier credit — not on an assurance that it was done.',
      '',
      '## Records',
      '',
      'The register is the single record for both clinic and engineering, retained for six years.',
      'Counts, median age and repeat rate are a standing management review input.',
      '',
      '## Review',
      '',
      'Annually by Tika with the three disposition owners, and after any major nonconformity.',
    ].join('\n'),
  },
]
