import type { SeedDocument } from './types'

/** Security and privacy documents: PDP Law, leakage prevention, deletion, data governance. */
export const SECURITY_DOCUMENTS: SeedDocument[] = [
  {
    code: 'TRD-SEC-002',
    title: 'Personal Data Handling (UU No. 27/2022 PDP)',
    clause: 'A.5.34',
    crossRefs: ['A.5.31', 'A.8.10', 'A.8.12', 'A.5.14'],
    version: 'v2.1',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-SEC-02', name: 'Personal data processing register (RoPA)' },
    revisions: [
      {
        version: 'v1.0',
        date: '2025-11-10',
        author: 'Andreas',
        approval: 'Drafted',
        status: 'Superseded',
        note: 'First technical requirement set for patient data in the Eternesia ERP replatform.',
      },
      {
        version: 'v2.0',
        date: '2026-03-04',
        author: 'Andreas',
        approval: 'Reviewed by Dhiaz Fathra',
        status: 'Superseded',
        note: 'Health data classified as specific personal data under Art. 4(2); consent capture moved into the Super App onboarding flow.',
      },
      {
        version: 'v2.1',
        date: '2026-06-16',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Retention table aligned with ENG-SOP-001 deletion job; Zitadel actor claim added to the access log requirement.',
      },
    ],
    evidence: [
      {
        name: 'trd-sec-002-pii-handling-v2.1.md',
        fileType: 'MD',
        uploadedAt: '2026-06-16',
        expiryDate: '2027-06-16',
        uploader: 'Dhiaz Fathra',
        note: 'Controlled technical requirement document, current revision.',
      },
      {
        name: 'dpia-eternesia-patient-service-2026.docx',
        fileType: 'DOCX',
        uploadedAt: '2026-06-30',
        expiryDate: '2027-06-30',
        uploader: 'Rica',
        note: 'Data protection impact assessment for the patient service, signed by the controller representative.',
        body: [
          '# Data Protection Impact Assessment — Eternesia Patient Service',
          '',
          '**Controller** PT Cakrawala Bumi Estetika · **Assessor** Rica · **Approved** Aris Ihwan, 30 June 2026',
          '',
          '## 1. Processing assessed',
          '',
          'Patient identity, contact details, treatment history, before/after photographs and',
          'payment records for 13 clinic locations across the Dermaster, Derma Express and',
          'Dermalicious brands, held in the `patient` and `treatment` services of the Eternesia',
          'ERP and surfaced through the Super App.',
          '',
          '## 2. Why an assessment is required',
          '',
          'Art. 34 UU No. 27/2022 requires an impact assessment where processing carries high',
          'risk. Two triggers apply: health data is specific personal data (Art. 4(2)(a)), and',
          'the processing is large scale — roughly 240,000 patient records across the group.',
          '',
          '## 3. Risks and treatment',
          '',
          '| Risk | Treatment | Residual |',
          '| --- | --- | --- |',
          '| Clinic staff browsing records of patients they are not treating | Location-scoped role in Zitadel; every read logged with the actor claim | Low |',
          '| Before/after photographs leaving the clinic device | Photos are uploaded straight to object storage from the Flutter app; no local gallery write | Low |',
          '| Marketing re-use of treatment history without consent | Consent purpose stored per record; marketing exports filter on `consent.marketing = true` | Low |',
          '| Erasure request not reaching every service | Deletion orchestrated over NATS with per-service acknowledgement (TRD-SEC-002 §6) | Medium — acknowledgement gaps are reviewed monthly |',
          '',
          '## 4. Conclusion',
          '',
          'The processing may proceed with the controls above in place. Reassessment is due',
          'before the marketplace migration exposes any patient-linked order data.',
        ].join('\n'),
      },
    ],
    body: [
      '# TRD-SEC-002 — Personal Data Handling (UU No. 27/2022)',
      '',
      '**Author** Andreas · **Owner** Dhiaz Fathra (Management Representative) · **Approver** Aris Ihwan',
      '**Version** v2.1 · **Requirement** A.5.34 · **Also satisfies** A.5.31, A.8.10, A.8.12, A.5.14',
      '',
      '## 1. Purpose',
      '',
      'This document states the technical requirements every service built by the engineering',
      'team must meet when it processes personal data of patients, staff or applicants of',
      'PT Cakrawala Bumi Estetika, so that the group discharges its obligations as a controller',
      'under Undang-Undang No. 27 Tahun 2022 tentang Pelindungan Data Pribadi (PDP Law).',
      '',
      'It is a technical requirement document, not the privacy notice. The notice published to',
      'patients is maintained by Legal; this document is what engineering is audited against.',
      '',
      '## 2. Scope',
      '',
      '- The Eternesia ERP (21 Go services), the Super App (Flutter), and the marketplace',
      '  services migrated from Strapi to Express.js and Go.',
      '- All environments that hold production data, including any restore taken for debugging.',
      '- Processors acting for the group, bound by written instructions under Art. 51.',
      '',
      '## 3. Data classification',
      '',
      '- **Specific personal data (Art. 4(2))** — Examples: Treatment history, diagnoses, before/after photographs, biometric login · Handling: Encrypted at rest, access location-scoped, every read logged',
      '- **General personal data (Art. 4(1))** — Examples: Name, phone, e-mail, address, NIK, membership tier · Handling: Encrypted at rest, access role-scoped',
      '- **Pseudonymised** — Examples: Analytics events keyed by `patient_ref` · Handling: Re-identification key held only by the patient service',
      '- **Non-personal** — Examples: Catalogue, pricing, clinic opening hours · Handling: No restriction',
      '',
      'The class of every column that holds personal data is declared in the service’s',
      '`data-map.yaml`; the code review agent fails a merge request that adds a column to a',
      'patient-owning table without one.',
      '',
      '## 4. Lawful basis and consent',
      '',
      '1. Treatment records are processed on the basis of the treatment contract (Art. 20(2)(b)).',
      '2. Marketing use requires explicit consent (Art. 20(2)(a)), captured in the Super App',
      '   onboarding flow with the purpose text shown at the moment of capture.',
      '3. Consent is stored as a record — purpose, text version, timestamp, channel — not as a',
      '   boolean. Withdrawal writes a new record; it never overwrites the old one.',
      '4. A purpose absent from the consent record is not a permitted purpose. Exports for',
      '   marketing filter on the stored purpose, not on an operator’s assertion.',
      '',
      '## 5. Storage, transfer and access',
      '',
      '- Personal data is held in PostgreSQL on Nutanix in Indonesia. Cross-border transfer',
      '  (Art. 56) requires a recorded adequacy or contractual basis before the first byte moves;',
      '  no such transfer is currently approved.',
      '- Secrets that unlock personal data — database credentials, object storage keys — live in',
      '  Infisical. No credential is read from an environment file baked into a Podman image.',
      '- Identity and session are handled by Zitadel. Every service reads the actor from the',
      '  validated token; no service accepts an actor id from the request body.',
      '- Service-to-service traffic is ConnectRPC over TLS. Watermill/NATS subjects carrying',
      '  personal data are named `pii.*` so that subscription grants are reviewable at a glance.',
      '- Redis holds no personal data beyond a session reference with a TTL of 24 hours.',
      '',
      '## 6. Retention and erasure',
      '',
      '- **Treatment record** — Retention: 10 years from last treatment · Trigger: Statutory medical record period',
      '- **Consent record** — Retention: 5 years from withdrawal · Trigger: Proof of lawful basis',
      '- **Marketing profile** — Retention: 24 months from last interaction · Trigger: Purpose exhausted',
      '- **Access log** — Retention: 3 years · Trigger: ISMS requirement',
      '- **Applicant CV** — Retention: 12 months from decision · Trigger: HR policy',
      '',
      'A data subject erasure request (Art. 8) is raised as a `pii.erasure.requested` event. Each',
      'owning service acknowledges with `pii.erasure.completed` carrying the record count it',
      'removed. The request is closed only when every registered owner has acknowledged; the',
      'unacknowledged list is reviewed monthly by the owner of this document. Deletion itself',
      'follows the ISMS Information Deletion Policy (A.8.10).',
      '',
      '## 7. Breach notification',
      '',
      'Art. 46 requires notification of the data subject and the supervisory authority within',
      '3 × 24 hours of becoming aware of a failure of protection. The on-call engineer who',
      'confirms one raises a P1 incident immediately and notifies the Management Representative',
      'in the same action — the clock starts at awareness, not at diagnosis. The postmortem',
      'follows the blameless RCA procedure in ENG-SOP-001 §5.',
      '',
      '## 8. Verification',
      '',
      '- The internal code review agent checks every GitLab merge request against §3 and §5.',
      '- The processing register (FRM-SEC-02) is reconciled against the deployed services each',
      '  quarter; a service in production and absent from the register is a finding.',
      '- The erasure path is tested end to end each quarter against a seeded test patient.',
      '',
      '## 9. Related documents',
      '',
      '- ENG-SOP-001 — Engineering Standard Operating Procedure',
      '- CBE/ISMS/SOP/19 — Data Security and Leakage Prevention',
      '- ISMS Information Deletion Policy (A.8.10)',
      '- DPIA — Eternesia Patient Service, 2026',
    ].join('\n'),
  },

  {
    code: 'CBE/ISMS/SOP/19',
    title: 'Data Security and Leakage Prevention',
    clause: 'A.8.12',
    crossRefs: ['A.5.14', 'A.8.10', 'A.5.34', 'A.5.12'],
    version: 'v1.3',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-DLP-01', name: 'Data egress exception request' },
    revisions: [
      {
        version: 'v1.0',
        date: '2025-09-08',
        author: 'Dhiaz Fathra',
        approval: 'Drafted',
        status: 'Superseded',
        note: 'Issued after the group-wide classification exercise.',
      },
      {
        version: 'v1.2',
        date: '2026-01-22',
        author: 'Wiwin',
        approval: 'Reviewed by Compliance',
        status: 'Superseded',
        note: 'Clinic front-desk export limits added; USB storage prohibition made explicit.',
      },
      {
        version: 'v1.3',
        date: '2026-05-11',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'AI coding assistant clause added: no production data in prompts, repository-level allowlist.',
      },
    ],
    evidence: [
      {
        name: 'cbe-isms-sop-19-data-leakage-prevention-v1.3.docx',
        fileType: 'DOCX',
        uploadedAt: '2026-05-11',
        expiryDate: '2027-05-11',
        uploader: 'Dhiaz Fathra',
        note: 'Signed procedure as issued to all department heads.',
      },
      {
        name: 'egress-exception-log-2026H1.xlsx',
        fileType: 'XLSX',
        uploadedAt: '2026-07-06',
        expiryDate: '2027-01-06',
        uploader: 'Tika',
        note: 'Half-year register of approved exports: 11 requests, 9 approved, 2 refused.',
        body: [
          'Data egress exception log — 2026 H1',
          '',
          'EXC-2026-004 | Marketing | Consented patient list, Dermalicious Q2 campaign | Approved by Aris Ihwan | 2026-04-02 | Purged 2026-05-02',
          'EXC-2026-007 | Finance | Revenue extract, no patient identifiers | Approved by Aris Ihwan | 2026-05-14 | Retained per finance policy',
          'EXC-2026-009 | Clinic ops (Dermaster PIK) | Full patient export requested for a local backup | REFUSED — no lawful basis, no controlled destination | 2026-06-03 | n/a',
          'EXC-2026-011 | Engineering | Anonymised load-test dataset from production shapes | Approved by Dhiaz Fathra | 2026-06-21 | Destroyed after test',
        ].join('\n'),
      },
    ],
    body: [
      '# CBE/ISMS/SOP/19 — Data Security and Leakage Prevention',
      '',
      '**Issued by** PT Cakrawala Bumi Estetika · **Owner** Dhiaz Fathra · **Approver** Aris Ihwan',
      '**Version** v1.3 · **Requirement** A.8.12 · **Also satisfies** A.5.14, A.8.10, A.5.34, A.5.12',
      '',
      '## 1. Purpose',
      '',
      'To prevent information classified as confidential or personal from leaving the group’s',
      'controlled systems without an approved purpose, destination and retention.',
      '',
      '## 2. Scope',
      '',
      'All staff and contractors of the group, all 13 clinic locations, and every system that',
      'holds patient, staff, financial or commercial data — including laptops, clinic',
      'workstations, the Super App, and any AI assistant used in the course of work.',
      '',
      '## 3. Controlled egress points',
      '',
      '- **Database export** — Control: Only through an approved reporting query; ad-hoc `pg_dump` of production requires FRM-DLP-01',
      '- **Object storage** — Control: Bucket policies deny public read; links are signed and expire in 15 minutes',
      '- **E-mail attachment** — Control: Files classified confidential are shared as an access-controlled link, never as an attachment to an external address',
      '- **Removable media** — Control: USB mass storage is denied on clinic workstations. No exception is granted for patient data',
      '- **Messaging (WhatsApp, Telegram)** — Control: Patient photographs and records must not be sent over consumer messaging, including between clinicians',
      '- **Source control** — Control: GitLab push rules reject files matching credential and dump patterns',
      '- **AI coding assistants** — Control: See §4',
      '',
      '## 4. AI assistants and code',
      '',
      'The engineering team uses Claude Code and OpenCode against the group’s repositories, and',
      'runs an internal Go review agent over GitLab merge requests. Three rules apply:',
      '',
      '1. Production data must never be pasted into a prompt. Reproduce with synthetic or',
      '   anonymised data; §5 of ENG-SOP-001 explains how to obtain it.',
      '2. Assistants are enabled per repository, not globally. Repositories holding key material',
      '   or patient exports are not on the allowlist.',
      '3. `CLAUDE.md` and `AGENTS.md` in each repository state the data rules for that repository.',
      '   They are reviewed with the repository, not separately.',
      '',
      '## 5. Detection',
      '',
      '- Egress volume per user per day is monitored on the reporting database; a query returning',
      '  more than 5,000 patient rows raises an alert to the Management Representative.',
      '- Signed-URL issuance for the photograph bucket is logged and reviewed weekly.',
      '- Secret scanning runs in GitLab CI on every branch. A hit fails the pipeline and rotates',
      '  the affected credential in Infisical before the branch may be re-run.',
      '',
      '## 6. Exceptions',
      '',
      'An export not covered above requires FRM-DLP-01, approved by the Management Representative',
      'and, where personal data is involved, by the controller representative. Every approved',
      'exception names a destination, a purpose and a destruction date, and is entered in the',
      'egress exception log.',
      '',
      '## 7. Breach of this procedure',
      '',
      'Suspected leakage is an incident. It is raised the same way as any P1 (ENG-SOP-001 §5),',
      'and where personal data is involved the 3 × 24 hour notification clock of TRD-SEC-002 §7',
      'starts at the moment of awareness.',
    ].join('\n'),
  },

  {
    code: 'ISMS-POL-A810',
    title: 'Information Deletion Policy (A.8.10)',
    clause: 'A.8.10',
    crossRefs: ['A.5.34', 'A.8.12', 'A.5.37'],
    version: 'v1.1',
    owner: 'Dhiaz Fathra',
    form: { code: 'FRM-DEL-01', name: 'Deletion and destruction certificate' },
    revisions: [
      {
        version: 'v1.0',
        date: '2026-01-19',
        author: 'Dhiaz Fathra',
        approval: 'Drafted',
        status: 'Superseded',
        note: 'Written to close the A.8.10 gap raised in the 2025 internal audit.',
      },
      {
        version: 'v1.1',
        date: '2026-04-07',
        author: 'Dhiaz Fathra',
        approval: 'Approved by Aris Ihwan',
        status: 'Current',
        note: 'Backup expiry treated as deferred deletion rather than an exception; soft-delete window fixed at 30 days.',
      },
    ],
    evidence: [
      {
        name: 'deletion-certificate-2026Q2-decommissioned-nodes.docx',
        fileType: 'DOCX',
        uploadedAt: '2026-07-01',
        expiryDate: '2029-07-01',
        uploader: 'Agil',
        note: 'Destruction record for four decommissioned clinic workstations and two Nutanix nodes.',
        body: [
          '# Deletion and Destruction Certificate — 2026 Q2',
          '',
          '**Performed by** Agil · **Witnessed by** Dhiaz Fathra · **Date** 1 July 2026',
          '',
          '| Asset | Identifier | Method | Verified |',
          '| --- | --- | --- | --- |',
          '| Clinic workstation, Dermaster Kelapa Gading | CBE-WS-0412 | NVMe secure erase, then physical destruction of the drive | Yes |',
          '| Clinic workstation, Derma Express Bintaro | CBE-WS-0433 | NVMe secure erase | Yes |',
          '| Clinic workstation, Dermalicious Bandung | CBE-WS-0451 | NVMe secure erase | Yes |',
          '| Clinic workstation, Dermaster PIK | CBE-WS-0460 | NVMe secure erase | Yes |',
          '| Nutanix node | CBE-NX-07 | Cluster-level secure wipe before RMA | Yes |',
          '| Nutanix node | CBE-NX-08 | Cluster-level secure wipe before RMA | Yes |',
          '',
          'No asset left the premises before the method above completed and was verified.',
        ].join('\n'),
      },
      {
        name: 'erasure-request-closure-log-2026.md',
        fileType: 'MD',
        uploadedAt: '2026-08-05',
        expiryDate: '2027-08-05',
        uploader: 'Randy',
        note: 'Running log of data subject erasure requests and per-service acknowledgements.',
        body: [
          '# Erasure request closure log — 2026',
          '',
          'One row per data subject request under Art. 8 UU No. 27/2022. A request closes only',
          'when every owning service has acknowledged `pii.erasure.completed`.',
          '',
          '| Request | Received | Services acknowledged | Closed | Notes |',
          '| --- | --- | --- | --- | --- |',
          '| ERQ-2026-014 | 2026-03-02 | 7 of 7 | 2026-03-05 | Marketing profile and treatment record removed; consent record retained 5 years as proof of basis |',
          '| ERQ-2026-019 | 2026-05-21 | 7 of 7 | 2026-05-23 | — |',
          '| ERQ-2026-022 | 2026-06-30 | 7 of 7 | 2026-07-04 | Loyalty service acknowledged late (3 days); retry backlog cleared |',
          '| ERQ-2026-026 | 2026-08-01 | 7 of 7 | 2026-08-04 | Backups holding the record expire 2026-09-12; deferred deletion recorded |',
          '',
          'Monthly review by the Management Representative: no request open beyond 30 days.',
        ].join('\n'),
      },
    ],
    body: [
      '# Information Deletion Policy',
      '',
      '**Owner** Dhiaz Fathra · **Approver** Aris Ihwan · **Version** v1.1',
      '**Requirement** ISO/IEC 27001:2022 Annex A.8.10 · **Also satisfies** A.5.34, A.8.12, A.5.37',
      '',
      '## 1. Purpose',
      '',
      'Information held longer than it is needed is exposure without benefit. This policy states',
      'when information is deleted, how deletion is performed so that it cannot be reconstructed,',
      'and what record proves it happened.',
      '',
      '## 2. Scope',
      '',
      'Production and non-production systems, backups, object storage, log stores, laptops and',
      'clinic workstations, and any medium leaving the group’s control by disposal or return.',
      '',
      '## 3. When information is deleted',
      '',
      'Deletion is driven by the retention table in TRD-SEC-002 §6 and by three events:',
      '',
      '1. Retention period expiry — a scheduled job per owning service.',
      '2. A data subject erasure request — orchestrated over NATS, closed only on full',
      '   acknowledgement.',
      '3. Decommissioning of an asset or a system.',
      '',
      '## 4. Method',
      '',
      '- **PostgreSQL row** — Method: Hard `DELETE` after the 30-day soft-delete window; the soft-delete flag is a recovery window, not deletion',
      '- **Object storage** — Method: Object delete plus version delete; versioning does not survive a deletion',
      '- **Backups** — Method: Not edited. The record is marked deleted, and the deletion completes when the backup set expires — a maximum of 35 days. This deferral is recorded on the request',
      '- **Log store** — Method: Time-based expiry only; personal data must not be written to logs in the first place (TRD-SEC-002 §5)',
      '- **SSD / NVMe** — Method: Secure erase; where erase cannot be verified, physical destruction',
      '- **Paper consent form** — Method: Cross-cut shredding at the clinic, recorded on the destruction certificate',
      '',
      '## 5. Evidence',
      '',
      'Every deletion under §3(3) produces a destruction certificate (FRM-DEL-01) naming the',
      'asset, the method, the operator and a witness. Deletions under §3(1) and §3(2) are',
      'evidenced by the job’s own record: request id, service, row count, timestamp.',
      '',
      '## 6. Third parties',
      '',
      'A processor that holds group data returns or deletes it on termination and provides a',
      'written confirmation within 30 days. The confirmation is filed against this policy.',
      '',
      '## 7. Review',
      '',
      'Annually by the owner, and after any incident in which data was found to have been',
      'retained past its period.',
    ].join('\n'),
  },
]
